### ISSUE TITLE
feature ideas for context menu 

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#101]
hello,

would it be possible to add multiple items for the sub items incase you have a long list and it goes off page? 

also would it be possible to add more sub menu, so at the moment you can only go 1 deep, but  could it be possible to go further? 

hope this makes sense, 
many thanks.

**Comment by Ni55aN** [comment]
I think this will make sense. Since this is planned as a separate plugin, it means there will be more freedom to add functionality and use some of your own solutions

**Comment by Ni55aN** [comment]
The conext menu is implemented in [plugin](https://github.com/retejs/context-menu-plugin) in the basic form. Anyone can make a pull requests thus help in the development of the functional

**Comment by Clasen00** [comment]
@Ni55aN hello! Can you suggest any example about how to avoid using context menu plugin and change this functionality to add new nodes by clicking buttons somewhere?

**Comment by Ni55aN** [comment]
@Clasen00 similar issue #38  (but for the old version)

Try this:

```js
   const node = await anyComponent.createNode();

  node.position[0] = x;
  node.position[1] = y;
  this.editor.addNode(node);
```

where `anyComponent` it is the instance of registered component in your editor

```js
const anyComponent = new AnyComponent();

editor.register(anyComponent);
```

**Comment by Ni55aN** [comment]
The [rete-context-menu-plugin](https://github.com/retejs/context-menu-plugin) has been updated.
alight had been replaced with Vue.js. Added support of submenus and other useful things
