### ISSUE TITLE
Feature: export to code

### ISSUE THREAD

**Issue by CheweyZ** [retejs/rete#104]
I'm not sure what this would mean at your end depending on how you have it setup but would it be possible to have a feature that exports your current setup of blocks into JS given the logic that it runs is already in the blocks?

Note if not intending to add would you have any standout features of what I should do to implement it my self? as currently having issues figuring out the call stack of passing info between nodes in terms of code almost calling functions

**Comment by Ni55aN** [comment]
You can try to write lines of code inside the workers into a common string/file.
I can not exactly guarantee the success of this method, since I have not yet tested

**Comment by Ni55aN** [comment]
Everythink works well for simple example:
https://jsfiddle.net/2ewmocdz/

**Comment by Ni55aN** [comment]
This functionality can be implemented in the form of a plugin https://github.com/retejs/rete/issues/80

**Comment by Clasen00** [comment]
@Ni55aN can you please explain a little how can I use source code of my node in 1.0.8 alpha version of Rete? Because in 1.0.2 I could use something like this  `worker(node, inputs, outputs, sourceCode) {}` so `sourceCode ` var was the exactly source code. But in the current version this variable returning 'undefined' value. What can I do with this?

**Comment by Ni55aN** [comment]
The major difference between alpha.2 and alpha.8 is inputs/outputs indexes #146

https://rete.readthedocs.io/en/latest/Components/

**Comment by Clasen00** [comment]
@Ni55aN so there is no any examples about how i can append some js to the specific node?

**Comment by Ni55aN** [comment]
@Clasen00 do you mean a visual elements or logic ?

**Comment by Clasen00** [comment]
@Ni55aN i mean how to add some custom elements to the specific node :) Like in that example https://codepen.io/hatead/pen/mjPmxV?editors=0010 there is "+" and "-" buttons, i need this in my project)

**Comment by Ni55aN** [comment]
@Clasen00 ok, let's start again from beginning

> But in the current version this variable returning 'undefined' value.

Did you pass the `sourceCode` variable to `engine.process()` ?

> there is "+" and "-" buttons, i need this in my project)

You need a ButtonControl from the example, but this component rendered with a `rete-alight-render-plugin`. Currently `rete-vue-render-plugin` is more preferable. 
In any case, you can use `alight-render` together with `vue-render` - just add `this.render = 'alight';` to constructor of exist ButtonControl and `node.addControl(new ButtonControl(this.editor, 'btn', "+" ))` inside `builder()`

**Comment by Clasen00** [comment]
@Ni55aN thank you! I will try!
