### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by Ni55aN** [retejs/rete#107]
With considering the further development and transition to an architecture with plugins, more than one repository (the main source, documentation, cli and official plug-ins) will be required. Seems like it makes sense to create a separate organization for this. 

If so then perhaps I need to change the name to an easier and more attractive. Moreover, there will be no dependence on D3.js

What do you think about it?

**Comment by trsh** [comment]
1) I totally agree with the renaming. As I wrote in https://github.com/Ni55aN/d3-node-editor/issues/98#issuecomment-387626133

2) Proposing a name is rather tricky :/. node.js is kind of taken :D

If we go for easy and pragmatic, I would say "Node Editor" or "Logic Node Editor". As those where key words when I searched for this thing. 

I dislike "Cool" names like "Awesome Node director", or "Ninja Node Editor", as that makes a Lib sound more like a joke.  In same time it gives a project some authenticy. So, anyway, its up to you @Ni55aN - I have given my 15 cents to this.

**Comment by Legiew** [comment]
Here is my input:

Simplest change would be to just Node Editor.

To use an abbreviation: Yane or YaneJs (Yet another node editor)

You probably should get rid of the word "node" to get a better differentiation towards nodejs.

In PLC programming this style of programming is called function block diagram (FBD). A name here could be FubloJs.

Also the word flow could be used: FlowBlockEditor or FlobloEditJs, FlobloJs

As you can see I like short names more than long one containing whole words. Good luck for finding the right name!

**Comment by trsh** [comment]
@Legiew 

Just "Node Editor" will clash with Node.js editors (IDE's) like hell - true. 

The "JavaScript" or "JS" key-word is a must be, as that what it is. Not for all languages orsmth.

Stuff like "FubloJs" will have like no hits for google, until the project-repo will get popular. Majority of people will search with words "Node", "Editor", "Javascript/js" and "Logic" or "Flow". Another bunch for "Visual programming". 

So for simple, I would choose: "NodeEditorJS" or "VisualNodeEditorJS"

**Comment by Legiew** [comment]
Yeah you're right. A readable name should be better for the start.
Because of the node naming issues I personally would totally get rid of the word in the name.
I also thought about the word editor and imho it isn't suitable here, too. It is an editor sure, but it is also en executing engine.
So I would choose then FlowBlockJs. I first thought it could be an issue because the lib is called node editor atm and people will struggle with a different new name, but it is possible to deprecate it on npm and display a message after installing. An a link in the current Readme to the new project/organisation will do the rest.

**Comment by trsh** [comment]
Actually it's not so bad with that "node" name. When I google now "node+editor+javascript", I do not get any Node.js stuff in first page. Even got something like this > https://www.reddit.com/r/javascript/comments/4y5q0n/neditorjs_node_editor_ui/.

**Comment by Ni55aN** [comment]
So far, picked up one of the unoccupied and more suitable names is easeflow.
Still I think over others

**Comment by Ni55aN** [comment]
`anynode`

**Comment by trsh** [comment]
I would suggest then easeflowJS or anynodeJs

**Comment by Ni55aN** [comment]
@trsh npm prefers packages without ending js (for instance, `three`, `vue`, `react`)

**Comment by omega-tree** [comment]
logic-flow, prog-flow (programmatic-flow chart), p-flow,

**Comment by Ni55aN** [comment]
As for me, among the latest samples, `rete` is more appropriate

1. easy to pronounce and remember
2. there are no similar names (also names in the network are unoccupied)
3. [close to the dataflow in meaning](https://www.google.com.ua/search?q=rete+node+editor&tbm=isch)

What do you think?

**Comment by Ni55aN** [comment]
since I have been looking for a short, unoccupied and suitable name for more than a day, I stopped on `rete`

`mone` - a modular node editor (npm busy)
`uni` - universal node editor (also)

**Comment by Ni55aN** [comment]
@trsh @Legiew @omega-tree thanks for your kind approach

**Comment by trsh** [comment]
@rete stands for what? :)

**Comment by Ni55aN** [comment]
network, system
