### ISSUE TITLE
User error

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#109]
Hi, 

I was wondering if anyone knew why i would get this error - 
`Error in directive: **al-connection Unable to set property 'inputNode' of undefined or null reference** [object Object] TypeError: Unable to set property 'inputNode' of undefined or null reference at setAttributes (Unknown script code:2032:5) at Connection$1 (Unknown script code:2054:5) at fn (Unknown script code:10:18218) at c (Unknown script code:10:17701) at e.$init (Unknown script code:10:17623) at Anonymous function (Unknown script code:10:24121) at D (Unknown script code:10:25202) at r.bind (Unknown script code:10:25894) at r.bind (Unknown script code:10:26701) at Anonymous function (Unknown script code:11:19763)`

its not a massive issue as my nodes still work regardless, but it just spams and freezes my log when the node is updated.

many thanks :)

**Comment by Ni55aN** [comment]
I propose to leave it as is, and later (in a week or two) I will release library on the new architecture and fix this defect

**Comment by JMidd91** [comment]
sounds good to me, thanks a lot!

**Comment by JMidd91** [comment]
Hello,

is there any way i can disable this error message for the moment? its making it really hard to debug my nodes as it freezes Edge / IE if too many appear

**Comment by JMidd91** [comment]
that didnt work, but removing this line stopped the errors from crashing the log - `m=g,r.exceptionHandler(m,"Error in directive: "+h.attrName,{value:V,env:v,cd:e,scope:e.scope,element:t})`

**Comment by Ni55aN** [comment]
Try this polyfill: https://gist.github.com/ShirtlessKirk/6cdc2c32ddd97dc9c706

The problem is that in Edge and IE there is no dataset property
