### ISSUE TITLE
Feature: ue4 style reroute pins

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#111]
Hello,

is it possible to currently / in the future, add reroute pins like in UE4? [here is an example.](https://forums.unrealengine.com/filedata/fetch?id=1132219&d=1502241807)

also to be able to color the node connections the same color as the sockets? 

just features that I thought would be nice to have! 

cheers 👍

**Comment by Ni55aN** [comment]
Yeah! I'm working on basic connections plugin now. This function can be added in the future without any problems.

Can you show an interactive example how you can interact with these reroute pins?

**Comment by JMidd91** [comment]
here is a video that seems to explain and show a nice example - [https://youtu.be/lrCfs2ZiG_I?t=156](https://youtu.be/lrCfs2ZiG_I?t=156)

**Comment by Ni55aN** [comment]
Ok, I got it

**Comment by Ni55aN** [comment]
https://github.com/retejs/connection-reroute-plugin

**Comment by Ni55aN** [comment]
[The last example ](http://localhost:8080/#/examples )

**Comment by JMidd91** [comment]
example links to localhost?  nice to see this plugin closed, will try it out asap 👍

**Comment by Ni55aN** [comment]
I'll provide example for local testing soon

**Comment by Ni55aN** [comment]
[The last example ](http://rete.js.org/#/examples )
