### ISSUE TITLE
How to make complex block properties?

### ISSUE THREAD

**Issue by simplelike** [retejs/rete#113]
In the project I need to make at least 2 different kinds of complex blocks properties:
1. input id = "123" type = "text" with the button, that shows popup with textarea, where user will paste a lot of text (xml in fact), that will insert into #123.
2. And another input id = "321" type = "text" with button that, that will launch js function, result of which must be returned to #321.

Is it possible to make?

**Comment by Ni55aN** [comment]
Use for this control, which will contain the fields you specify
