### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by Adolar13** [retejs/rete#115]
The documentation at https://d3-node-editor.readthedocs.io/en/latest/ linked in the readme does not exist anymore.

**Comment by Ni55aN** [comment]
In the near future I'll rewrite documentation for v1.0.0.
Now you can see the docs for the previous version http://d3-node-editor.readthedocs.io/en/v0.7.4/

**Comment by Ni55aN** [comment]
https://rete.readthedocs.io/en/latest/
