### ISSUE TITLE
How 'Task works' and is it possible to avoid recursion error ?

### ISSUE THREAD

**Issue by realTrueProger** [retejs/rete#116]
Hello again )

1) Can you please explain how the Tasks works in v. 0.7.4? In general.. i dont understand what is the difference between tasks and process().. all that task.option, task.output. I cant understand it from the docs or from examples...

```
var task = new D3NE.Task(inputs, function (inps, data) {  // how it works ?
            console.log('Keydown event', node.id, data);
            return [data]
        });

        eventHandlers.remove();
        eventHandlers.add('keydown', function (e) {
            task.run(e.keyCode);
            task.reset();  // why reset ?
        });

        outputs[0] = task.option(0);    // what is all this options and outputs?
        outputs[1] = task.output(0);
```

2) And is it possible to avoid 'recursion detected' error if i need to cycle the logic?

**Comment by Ni55aN** [comment]
1. The tasks are needed for deferred execution of instructions. At the time of processing, ordinary workers are running, which create a network of tasks that can be executed later at any time (for example, by an event)

Tasks are just superstructure over the `process()`.
process() - performs task initialization
task.run() - performs task worker (second parameter)

> 
```js
function (inps, data) {  // how it works ?
```

An instance of the task is created that accepts the same tasks (`inputs`) and defines the data handler that passes through these tasks (`inps` is a data from previous tasks)


>
```js
outputs[0] = task.option(0);    // what is all this options and outputs?
```

`option(index)/output(index)` determines type of task's sockets, where `option` is an "exciter" (starts the next task after it) and `output` transmits data

**Comment by Ni55aN** [comment]
2. 
At the moment, recurrent connections are forbidden, as this leads to hangup when processing nodes.
Probably, in the future the question with cyclic execution of the nodes will be solved

**Comment by realTrueProger** [comment]
Thx, got it with Tasks )

But second answer in not what i expected...) Looks like i need somehow to write my own engine for that )
