### ISSUE TITLE
Zoom Step

### ISSUE THREAD

**Issue by rookuu** [retejs/rete#117]
Hello,

Is it possible to change the amount the editor view zooms by when scrolling? i.e create more steps.

**Comment by Ni55aN** [comment]
v0.7.4 does not have this capability, but in v1.0.0 you could add a zoom event handler and change it to suit your needs.

Currently I am working on new documentation, which may be completed by the end of the week

**Comment by Ni55aN** [comment]
https://github.com/retejs/docs
