### ISSUE TITLE
Feature : onDelete

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#118]
Hi,

would it be possible to implement an onDelete function to the nodes? 

so any code we put into the onDelete part of a node, it executes before it gets removed from the screen when we hit the delete key.

kind of like a final update? incase we need any thing removing that our nodes added. 

hope that makes sense!

kind regards

**Comment by JMidd91** [comment]
Maybe an onInputChange may be a good shout also, or onInputRemoval

**Comment by Ni55aN** [comment]
onDelete must be called after or before deleting node?
Component's `destroyed()` provide such ability (calls after a node deleted)

If you want to execute some method before deleting or even prevent deletion, you can subscribe to the `noderemove` event

```js 
editor.on('noderemove', node => {
    return false; // false to prevent
});
// or editor.eventListener in v0.7.4 and earlier
```

**Comment by JMidd91** [comment]
oh ok i will give that a try!

**Comment by JMidd91** [comment]
could you give me a basic example of where destroyed() would go in a component ? im running v0.7.3 at the moment. I couldnt find it in the docs

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/72

```js
new D3NE.Component('mycomp', {
    builder(node){ },
    worker(node, inputs, outputs){ },
    created(node){ }.
    destroyed(node){ }
});
```

**Comment by JMidd91** [comment]
this works a charm! can be closed now 👍

**Comment by Ni55aN** [comment]
https://github.com/retejs/lifecycle-plugin
