### ISSUE TITLE
[FR] Advanced connection validation and handling on Node level

### ISSUE THREAD

**Issue by trsh** [retejs/rete#120]
I'm looking now at this code:

```
connect(output: Output, input: Input, data = {}) {
        if (!this.trigger('connectioncreate', { output, input })) return;
```
and it's kind of what I want. Despite the socket comp-ability, sometimes I want to cancel the connection. Still this is some-have on global level. If I want some rules for a concrete Node type, I have to check Id's and blah blah. In the end it can result in a large if/switch statement.

Instead I would like to process the connection by example some callback (besides build?). That could return false, or execute some command to cancel the connection. 

User cases:

1) Node is busy at moment fetching some data, and connection has to be cancelled.
2) Node hasn't processed previous connection.
3) I don't want to allow only one input, and I don't want more that 14. MIN and MAX.
4) I want max connection from that type of node, and max from other.

Have to limit the checks only to Connection counts and types, etc. So that what the callback should return as data.

**Comment by trsh** [comment]
Not sure if worker is right place. Maybe some other clbck besides build, etc.

**Comment by trsh** [comment]
Or mark the connection non-valid? Display red, and it's not giving data.

**Comment by trsh** [comment]
This would be kind of cool, but makes things complicated. If I have some conditions, on which I allow the nodes to connect. Then on every change, I have to re-check this condition, and mark the connection as invalid, if it doesn't match any more. And mark it valid if the connection fits the needs again. This is kind of new thing.

**Comment by Ni55aN** [comment]
Instead of writing 
```js
editor.on('connectioncreate', ({input, output}) => {
   if(input.node.name === 'Add' && input.node.meta.busy)
       return false
});
```

you want something like that?

```js
class AddComponent extends Component {
 // ...
  onconnect(node, input, output) {
   if(node.meta.busy)
     return false;
   }
// ....
}
```

**Comment by trsh** [comment]
@Ni55aN yes. But let's have both?

**Comment by Ni55aN** [comment]
@trsh  Ok, first one is available now, but for second one I'll add a method

**Comment by trsh** [comment]
@Ni55aN thanks. Feel free to close this when appropriate.

**Comment by Ni55aN** [comment]
This feature will be added to the [lifecycle-plugin](https://github.com/retejs/lifecycle-plugin/blob/master/src/index.js)

**Comment by Ni55aN** [comment]
[rete-lifecycle-plugin](https://www.npmjs.com/package/rete-lifecycle-plugin) v0.2.0 has been published. It support onconnect/ondisconnect hooks
