### ISSUE TITLE
[FR] Make nodes more dynamic

### ISSUE THREAD

**Issue by trsh** [retejs/rete#121]
Sometimes some nodes have such identical meaning that it's a shame to make more than one. Instead you have some drop-down, where you choose different type.

Example:

Node "Process File". In drop down "From Bytes", "From url". When you switch the types, different input sockets are shown "Bytes" (array) and "Url" (string).

All we need todo, is ad an option to remove / add sockets on run, to drop invalid connections, and it's up to programmer to handle the type, etc.

**Comment by trsh** [comment]
Another example:

Node "have a beer". Input "beer". If you check "with chips", you must input also chips (addition socket arrives). Than you have check "with salted nuts", if you check that, also "nuts" input appears. Without this I would have 4 node types "Have a beer with chips", "Have a beer with nuts", "Have a beer", "Have a beer with nuts and chips". If I always show nuts an chips inputs additionally, I can't make any as mandatory.

**Comment by Ni55aN** [comment]
Great example! I'll provite a solution soon

**Comment by Ni55aN** [comment]
http://jsfiddle.net/vmxdcLbq/27/

For convenience, I'll add methods to the library for correct removal of inputs and outputs

```js
node.removeInput(input);
```
instead of 
```js
 input.connections.map(c => input.removeConnection(c));
 node.inputs.splice(node.inputs.indexOf(input), 1);
 input.node = null;
```

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/commit/37feef16bf7f24156267645bb7ec1370f3a87b5a

**Comment by trsh** [comment]
In your example, when I check some box, nothing happens. It's WIP?

**Comment by Ni55aN** [comment]
@trsh not WIP. It's working for me in Opera 53. Do you have any errors in devtools' console?

**Comment by JMidd91** [comment]
it works for me  on chrome 66.0.3359.181 but NOT edge 41.16299.402.0. i dont get any errors in the log though

**Comment by trsh** [comment]
No errors, no change in inputs when checking. Browser Chromium > Version 65.0.3325.181 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)

**Comment by Ni55aN** [comment]
Hmm.. really :smile: 
input event for type="checkbox" working in Opera, but not working in other browsers

@JMidd91 @trsh fixed: http://jsfiddle.net/vmxdcLbq/43/

**Comment by trsh** [comment]
@Ni55aN confirming. Working. So we can close this?

**Comment by JMidd91** [comment]
@Ni55aN confirming its working also 👍

**Comment by Ni55aN** [comment]
@trsh yeah
