### ISSUE TITLE
convert v0.7.3 to v1

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#122]
Just wanted to ask how much of a task it would be to convert from v0.7.3 to v1? 

I prob should do this for my project next week but just trying to prepare myself for the task at hand! 

will it be straight forward or will i have to write most of it from scratch ? 

cheers!

**Comment by Ni55aN** [comment]
I will soon write a guide for upgrading to version 1. 
For now do not rush with this, since now its plugins do not support all the features of version 0.7.3

**Comment by JMidd91** [comment]
ah ok thanks for the heads up!

**Comment by Ni55aN** [comment]
I have prepared [docs](https://rete.readthedocs.io/en/latest/Migrate/), but at the moment the context menu in v1.0.0 differs from the previous version

**Comment by JMidd91** [comment]
awesome! ill check that out asap

**Comment by JMidd91** [comment]
cool so I have attempted to convert one of my files but am just awaiting documentation for the context menu in v1.0.0. 

also just curious on when/if you plan to convert any of your demos to version 1? 

really like how version 1 feels. seems to be a lot more straight forward now vs v0.7.x, awesome job!

**Comment by Ni55aN** [comment]
> also just curious on when/if you plan to convert any of your demos to version 1?
Do you mean [examples](https://github.com/retejs/examples) and demos on codepen? They have already been rewritten for the new version

> really like how version 1 feels. seems to be a lot more straight forward now vs v0.7.x, awesome job!
Thanks so much!

**Comment by JMidd91** [comment]
So they are, must be cached or something on my work pc, awesome!
