### ISSUE TITLE
[FR] Safer inputs for workers and other improvements

### ISSUE THREAD

**Issue by trsh** [retejs/rete#124]
For now it's like this:

```
.....
return node
         .addInput(inp1)
         .addInput(inp2)
         .addControl(numControl)
         .addOutput(out);
   },
   worker(node, inputs, outputs) {
      var sum = inputs[0][0] + inputs[1][0];
      editor.nodes.find(n => n.id == node.id).controls[0].setValue(sum);
      outputs[0] = sum;
   }
```

I suggest something like this

```
...
return node
         .addInput('kavabanga1', inp1)
         .addInput('kavabanga2', inp2)
         .addControl(numControl)
         .addOutput(out);
   },
   worker(node, inputs, outputs) {
      var sum = inputs['kavabanga1'][0] + inputs['kavabanga2'][0];
      editor.nodes.find(n => n.id == node.id).controls[0].setValue(sum);
      outputs[0] = sum;
   }
```

This way you don't care if the order you add inputs changes. In Bonus it will alarm you, if change the inputs and not worker with new stuff at some level.

`editor.nodes.find(n => n.id == node.id).controls[0].setValue(sum);`

AS for this. Any chance to get controls / real node without this full scan? Or at least do it on core code and push it under `node`? if I have 100 nodes, it would make ~100x100 loop in summ, that seems much :). Have no suggestions right now. The solution should not be over-complicated

**Comment by trsh** [comment]
Same for Outputs. .addOutput('kavabanga3', a). 

I think this overall is very trivial. Especially if play/change the IO on run.

**Comment by Ni55aN** [comment]
Yeah, it's make sense. I'll investigate it

**Comment by trsh** [comment]
Thanks

**Comment by trsh** [comment]
(clap) tnx
