### ISSUE TITLE
Prevent inputs jumping

### ISSUE THREAD

**Issue by CheweyZ** [retejs/rete#126]
If i had a node with 3 inputs and the user connected 2 if they connected input 2-3 but left 1 I can have a default setting for these values via checking if "inp[0][0]" exists, however, the 2 inputs move down so instead in code in[uts 1-2 are defined and input 3 is empty is there a way to set it so that un-connect inputs hand in maybe a blank array instead?

this becomes more of a problem when you have multiple inputs of same type trying to validate what is actually connected and what is not 
![image](https://user-images.githubusercontent.com/19643053/41268723-adfb35c8-6e55-11e8-8ac8-a58c2af8d528.png)
wherein this case it would say the first 5 are connected and should default the others

**Comment by Ni55aN** [comment]
You can use Input with enabled multiple connections
https://rete.readthedocs.io/en/latest/Nodes/

If you need inputs in the form of multiple sockets, then what are the problems when validating them using a loop?

**Comment by CheweyZ** [comment]
are you meaning if the inputs array is less than inputs of the component then loop over and validate the input connection of the node and check which ones are null?

**Comment by Ni55aN** [comment]
> check which ones are null

May be `inputs.filter(input => input.length > 0)`, but this is too complicated. 

Only one input with multiple connections can be used

![2018-06-17_133713](https://user-images.githubusercontent.com/8259641/41507075-94abec84-7233-11e8-9814-82e18031f341.png)
