### ISSUE TITLE
Error when creating nodes with v1

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#127]
Hi,

I am getting an error in Edge and Chrome  when i try to move the nodes and when i try to create a connection, these are the errors - 

edge (not very helpful) - `SVG4601: SVG Path data has incorrect format and could not be completely parsed.`

chrome -` Error: <path> attribute d: Expected number, "M 608 123 C NaN 123 NaN NaN …". `

edge doesnt point to any lines of code, chrome however does - 
```
renderConnection @ utils.js:15
editor.on.arg @ index.js:67
```
all I have done to get these errors is copy your modules demo from [codepen](https://codepen.io/Ni55aN/pen/QOEbEW?editors=1010)

so i am not sure if its to do with Rete or a Rete plugin or something I have done. however the only thing I have done differently when copying from your codepen is convert it from babel to JS, and named my html id's differently

**Comment by trsh** [comment]
Browser and version please

**Comment by JMidd91** [comment]
Microsoft Edge 41.16299.402.0
Microsoft EdgeHTML 16.16299

Chrome - Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by JMidd91** [comment]
has anyone been able to replicate this? I cant seem to figure out why im getting it, i have copied the codepen into a local setup and it still does it

**Comment by Ni55aN** [comment]
I also have 
```
Microsoft Edge 41.16299.371.0
Microsoft EdgeHTML 16.16299
```
but I can't reproduce the error on Codepen.

Probably, you do not import all the dependencies?

![2018-06-16_211512](https://user-images.githubusercontent.com/8259641/41501292-697c30e8-71aa-11e8-8b02-0c8a4486ae99.png)

**Comment by JMidd91** [comment]
I think I have them all, these are what I am using - 

![image](https://user-images.githubusercontent.com/38964969/41520358-29c00f62-72c5-11e8-8569-adb61a74989e.png)

so the only difference is that i dont have Module/data.js listed here as I have my own  listed as actionNodes.js

**Comment by JMidd91** [comment]
ok so from testing on a different machine, i am now getting two errors from the above cdn's both in the codepen and locally - 

![image](https://user-images.githubusercontent.com/38964969/41560319-a6749fb8-733e-11e8-9a7f-bc78554246fc.png)

error 1 - 
![image](https://user-images.githubusercontent.com/38964969/41560361-bc26a090-733e-11e8-9b2b-e85fc6ea3834.png)

error 2 - 
![image](https://user-images.githubusercontent.com/38964969/41560387-ca8424fa-733e-11e8-81e1-31e0d2b056dd.png)


maybe this is to do with my issues?

**Comment by Ni55aN** [comment]
Try to update EDGE to v 42
For me on EDGE there are no errors in an example https://codepen.io/Ni55aN/pen/QOEbEW

**Comment by Ni55aN** [comment]
I see that you have some warnings before of these errors in the console. Perhaps they will clarify something

**Comment by JMidd91** [comment]
> Try to update EDGE to v 42

unfortunately i have no control over this on this machine as its a work machine. my other work machine is up to date hence why i didnt get the errors on there.

the only other error on this page is a font face error, not sure why it had 6 in the other screenshot. - 
![image](https://user-images.githubusercontent.com/38964969/41562134-a7013f40-7343-11e8-8bb4-a33b02542473.png)

**Comment by JMidd91** [comment]
Hey, I have just updated to the most resent version of rete and i am still getting that weird error - 
`SVG4601: SVG Path data has incorrect format and could not be completely parsed.`

It stops me from being able to move my nodes and it doesnt create any connections between the nodes either. 

still using EDGE version Microsoft Edge 41.16299.402.0

**Comment by Ni55aN** [comment]
@JMidd91 
> Seems like this version of EDGE doesnt understand async keyword. I'll try to build plugins through a Babel with compatibility for old browsers

https://www.npmjs.com/package/rete-connection-plugin

**Comment by Ni55aN** [comment]
@JMidd91 my bad. Just didn't notice that Babel doesn't export named const/function for UMD

Exports in all plugins have been changed to default export
