### ISSUE TITLE
[FR] expand and collapse for node

### ISSUE THREAD

**Issue by trsh** [retejs/rete#131]
Sometimes the node is Huge and take all screen. Would be nice to have an arrow next to title, that can collapse and expand it. And of course this remembered/stored in json.

**Comment by Ni55aN** [comment]
Since the [vue-render-plugin](https://github.com/retejs/vue-render-plugin) is avaliable, you can create your own component based on [Node.vue](https://github.com/retejs/vue-render-plugin/blob/master/src/Node.vue)
