### ISSUE TITLE
[FR] Minimap

### ISSUE THREAD

**Issue by Flippo24** [retejs/rete#132]
If a node is outside of the view then scrollbars should be shown. So you can see that there are other nodes without zooming out.

**Comment by JMidd91** [comment]
But scrollbars are ugly! Haha perhaps a mini map? Pretty sure ue4 has one, I'll see if I can find some reference, brb

**Comment by Ni55aN** [comment]
Good, I think this can be implemented as a plugin.

Feel free to create your own plugins (Of course, the current documentation is not clear enough, but I will supplement it not earlier than a week)

**Comment by Ni55aN** [comment]
https://rete.readthedocs.io/en/latest/Plugins/#minimap
