### ISSUE TITLE
How to display retrieved/stored Node Json from database?

### ISSUE THREAD

**Issue by christian-alejandre-mllrdev** [retejs/rete#133]
However, I can retrieve the json file from database but i dont know how to display and restore the previous nodes.

**Comment by Ni55aN** [comment]
Do you mean an "import" of scheme with nodes?
Use it:

```js
editor.fromJSON(data)
```
https://rete.readthedocs.io/en/latest/Editor

**Comment by christian-alejandre-mllrdev** [comment]
the 'await' on doc. made me confused, thanks it's all good.

**Comment by Ni55aN** [comment]
'await' required for calling next function after completing from JSON() (because this is asynchronous)

**Comment by Githamza** [comment]
I'm trying to import a graph from json but I get this error

```
TypeError: Cannot read property 'socket' of undefined
```
components are drawn with inputs and outputs but connections are not done.

the error is happening here in debugging mode 

```
  key: "connectTo",
            value: function connectTo(input) {
                if (!this.socket.compatibleWith(input.socket))
                    throw new Error('Sockets not compatible');
                if (!input.multipleConnections && input.hasConnection())
                    throw new Error('Input already has one connection');
                if (!this.multipleConnections && this.hasConnection())
                    throw new Error('Output already has one connection');
                var connection = new Connection(this, input);
                this.connections.push(connection);
                return connection;
            }
```

input value is undefined.

@Ni55aN  did the json data format changes from the version 0.1.0 to 0.2.0 ?
should I add `socket` item in my json ?

**Comment by Ni55aN** [comment]
> version 0.1.0 to 0.2.0

what package?

> if (!this.socket.compatibleWith(input.socket))

this or input is `undefined`?

**Comment by dotesfera** [comment]
Hi, I'm doing  `await editor.fromJSON(this.props.EditorJson);` on async componentDidMount, the nodes load well, but CONNECTIONS are not showing/working. @Ni55aN can you guide me how to make this right?
