### ISSUE TITLE
how to view / read only in node editor?

### ISSUE THREAD

**Issue by christian-alejandre-mllrdev** [retejs/rete#134]
Need to assign an access to the user that value, if set to "1" user can update/edit a node and if the access value is "2" the node editor should be unable to modify or set a view only. is there a way I can do this to  node editor?

**Comment by Ni55aN** [comment]
Starting from v1.0.0 you can use the [Readonly plugin](https://github.com/retejs/readonly-plugin/blob/master/index.js)

```js
import * as ReadonlyPlugin from 'rete-readonly-plugin';

editor.use(ReadonlyPlugin, { enabled: true });
```

**Comment by Flippo24** [comment]
How can the plugin later be disabled?

**Comment by Ni55aN** [comment]
```js
const params =  { enabled: true };
editor.use(ReadonlyPlugin, params);
///
params.enabled = false;
```

**Comment by Flippo24** [comment]
That was too easy. Why can not I find that out myself? Thanks anyway.
