### ISSUE TITLE
Error with plugins on alpha.5

### ISSUE THREAD

**Issue by mikecowgill** [retejs/rete#136]
After updating to rete 1.0.0-alpha.5 and updating the connection plugin and alight plugins beyond 0.1.0, I am getting an error when trying to use any plugin.

The error happens when calling the use function:

> TypeError: plugin.install is not a function

```
editor = new Rete.NodeEditor('test@1.0.0', container);
editor.use(ConnectionPlugin, { curvature: 0.4 });
```

After downgrading the plugins back to 0.1.0 it worked again (even with the core rete version at 1.0.0-alpha.5

**Comment by Ni55aN** [comment]
What does it print to the console?

```js
console.log(ConnectionPlugin);
```

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/127#issuecomment-403441998

**Comment by Ni55aN** [comment]
Please update all plugins to latest version

**Comment by Ni55aN** [comment]
updated: https://rete.readthedocs.io/en/latest/#installing

**Comment by mikecowgill** [comment]
After updating the plugins to these versions, all is well and working again. Thanks for the quick replies.

> "rete-alight-render-plugin": "^0.1.4",
>    "rete-connection-plugin": "^0.1.2",
>    "rete-keyboard-plugin": "^0.1.2",
