### ISSUE TITLE
LOGO PROPOSAL for RETE

### ISSUE THREAD

**Issue by joshuacarlito** [retejs/rete#137]
Hi sir :) I have observed that Rete has no logo yet and lately I have been contributing on open source projects. I am a graphics designer and if you want a logo sir, I can make a logo for you or you can suggest anything about the logo and I will digitalize it. Thank you sir ! Have a nice day !!

**Comment by Ni55aN** [comment]
Hi! Thanks for suggestion, but Rete.js has logo :)

![Rete.js logo](https://mir-s3-cdn-cf.behance.net/project_modules/1400/7a52be67661391.5b420681cb7ad.png)

Moreover, it has animated logo (by hover)
[open image in new tab](https://github.com/retejs/docs/blob/master/docs/assets/animated-logo.svg)

**Comment by Ni55aN** [comment]
![](https://trello-attachments.s3.amazonaws.com/5988366ad0e9bb6511d462b9/59d15518c3ad39cc23cf8166/bb10f4e0fb55dff25f0d0d5100954def/Animated_rete.js_logo.svg)
