### ISSUE TITLE
Enhance editor - future roadmap ?

### ISSUE THREAD

**Issue by imvetri** [retejs/rete#138]
Hi,

I am playing around with the project and I was thinking may be there is a way to enhance the editor. Following is how I am imagining.

Lets take **Creating node** as an example.

<img width="720" alt="creating node" src="https://user-images.githubusercontent.com/6542274/42459206-ebd63e92-83b8-11e8-8f4d-0bf8e89cd6de.png">

Taking this piece of code as an example, how about having editor options to create a new node and user just configure the input and output types and forget about coding it?

Please note that I am taking this as an example to convey my ideas to enhance it not entirely as it is as described above.

**Comment by Ni55aN** [comment]
I plan to create a website for the project. It will contain live examples with the source code on one page

> how about having editor options to create a new node and user just configure the input and output types and forget about coding it?

Do you mean a constructor of nodes for development or learning? If for development, it may not suit in many cases due to the style of the code or or more complex logic of their building

**Comment by imvetri** [comment]
> Do you mean a constructor of nodes for development or learning? If for development, it may not suit in many cases due to the style of the code or or more complex logic of their building

I will see whether I share with a demo. < 2 weeks.

**Comment by imvetri** [comment]
Update. I misunderstood that editor is also part of the rete. Turns out, it was just an example!. Thanks.
