### ISSUE TITLE
Zoom not working in Firefox/IE

### ISSUE THREAD

**Issue by axelf4** [retejs/rete#139]
Scrolling somewhat much with the mouse scroll wheel over the container and proceeding to right click to open the context menu causes `uncaught exception: Infinity loop detected`. Zooming in general is also defunct. The expected behaviour is that scrolling would zoom in/out.

The aforementioned issue has successfully been replicated in Firefox 61.0.1 and Internet Explorer 11.0.9600.19035CO. Zooming was a non issue in Google Chrome 67.0.3396.99 (64-bit). All using Windows 7.

The following library builds where used, however the problem persisted with `rete@1.0.0-alpha.6` and `rete-connection-plugin@0.1.2`.
```html
 <script src="https://cdn.jsdelivr.net/npm/rete@1.0.0-alpha.5/build/rete.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/alight@0.14.1/alight.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/rete-alight-render-plugin@0.1.2/build/alight-render-plugin.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/rete-connection-plugin@0.1.1/build/connection-plugin.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/rete-context-menu-plugin@0.1.1/build/context-menu-plugin.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/rete-task-plugin@0.1.0/build/index.js"></script>
```
The ["Programming a Messenger Bot"](https://codepen.io/Ni55aN/pen/rpOKNb) example also exhibited the issue.

**Comment by Ni55aN** [comment]
1253c53481000c5c404fd757be47bc720806b868

Release coming Soon

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/releases/tag/v1.0.0-alpha.7
