### ISSUE TITLE
Zoom dosn't work

### ISSUE THREAD

**Issue by zaslavsky** [retejs/rete#140]
zoom (in/out) dosn't work. Mouse scrolling broke area movement

**Comment by Ni55aN** [comment]
Fixed, but not released yet

1253c53481000c5c404fd757be47bc720806b868

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/releases/tag/v1.0.0-alpha.7

**Comment by Yugloocamai** [comment]
zoom is still broken for me.

**Comment by Ni55aN** [comment]
@Yugloocamai are there any examples reproducing the bug?
