### ISSUE TITLE
Auto zoom or fit on screen

### ISSUE THREAD

**Issue by christian-alejandre-mllrdev** [retejs/rete#142]
Hi, @Ni55aN is it possible to auto-fit/auto-zoom on the screen when It's getting bigger and bigger every time when I add a node.

**Comment by Ni55aN** [comment]
On event nodecreated call AreaPlugin.zookAt(editor)

**Comment by christian-alejandre-mllrdev** [comment]
@Ni55aN is this compatible with version v0.7.4?

**Comment by christian-alejandre-mllrdev** [comment]
@Ni55aN  thank you again! task is done! i just inserted editor.view.zoomAt(editor.nodes); at editor.eventListener.on("change".... 🍡

**Comment by flobiber** [comment]
Is this still working?

**Comment by Ni55aN** [comment]
@flobiber [zoomAt](https://rete.js.org/#/docs/plugins/area#lang=en&tosearch=AreaPlugin.zoomAt%28editor%2C%20nodes%29%3B)

**Comment by flobiber** [comment]
@Ni55aN Hmm 

```
    this.editor.use(AreaPlugin, {
      background: false,
      snap: false,
      scaleExtent: { min: 0.01, max: 10 },
      translateExtent: { width: 5000, height: 4000 }
    });

    AreaPlugin.zoomAt(this.editor, this.editor.nodes);
```

This isn't working right... it isn't centering and adjust zooming.

**Comment by Ni55aN** [comment]
The graph should be initialized before calling zoomAt. Perhaps you missed `await` before `editor.fromJSON()`

**Comment by flobiber** [comment]
You're great! Thx!

**Comment by 3ankur** [comment]
> The graph should be initialized before calling zoomAt. Perhaps you missed `await` before `editor.fromJSON()`

Thanks it worked :)
