### ISSUE TITLE
Node controls

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#143]
Hey,

in version 0.7.3 etc when i wanted to edit a control i could just refer to "el" and it would only effect the div withing that node even though all other nodes had the same div id for the control.

however I cant quite find how to get the same effect in 1.0+... I create the first node with a drop down list, the list gets populated as expected, i create a second node and the list in the first node receives the options that are supposed to populate the second node etc.

now i know why this is happening... because i am using the drop down's id which is the same across all nodes... what i am asking is if there is a variable like before that refers to the nodes element locally so then i can get to the individual elements of each node without messing with the rest? 

hope that makes sense

**Comment by JMidd91** [comment]
never mind, fixed it, swapped out creating a select list with vanilla JS/HTML to creating a select list using alight with this [demo ]([url](http://jsfiddle.net/lega911/Dz5HA/)) for help :) 

i am still open to any improvements / advice though! 

just for clarification, this is the code for my DropDownControl - 

```javascript
   class DropDownControl extends Rete.Control {
        
        constructor(emitter, key, idName, listData) {
            super();
            this.emitter = emitter;
            this.key = key;
            this.idName = idName;
            this.listData = listData;
            this.template = `<select id="${idName}" al-value="selectedId"><option value="" selected>No selected</option><option al-repeat="item in listData" >{{item.name}}</option></select>`
            
            this.scope = {
                value: null,
                listData,
                change: this.change.bind(this)
            };
        }
        
        change(e) {
            console.log("THIS IS CHANGE", e);
            this.scope.value = +e.target.value;
            this.update();
        }
        
        update() {
            console.log("THIS IS UPDATE");      
            
            this.putData('num', this.scope.value);
            this.emitter.trigger('process');
            this._alight.scan();
        }
        
        mounted() {
            
            node.scope.value = this.getData('num') || 0;
            
            this.update();
        }
    }
```

**Comment by Ni55aN** [comment]
By the way, you can use vanilla JS controls. `JsRenderPlugin` from example 
https://codepen.io/Ni55aN/pen/rpOKNb

```js
const JsRenderPlugin = {
  install(editor, params = {}){
    editor.on('rendercontrol', ({el, control}) => {
      if(control.render && control.render !== 'js') return;
      
      control.handler(el, editor);
    });
  }
}

class InputControl extends Rete.Control {
  
  constructor(key){
    super();
    this.render = 'js';
    this.key = key;
  }
  
  handler(el, editor) {
    var input = document.createElement('input');
    el.appendChild(input);
    
    var text = this.getData(this.key) || "Some message..";
    
    input.value = text;
    this.putData(this.key, text);
    input.addEventListener("change", () => {
      this.putData(this.key, input.value);
    });
 }
}

```

**Comment by JMidd91** [comment]
brilliant! didnt notice this in the example, thanks for pointing it out

**Comment by JMidd91** [comment]
hey can we reopen this? i finally got some time to look at this again. i cant seem to get my canvas to attach? the answer is prob really obvious but its avoiding me haha. here is my code - 

```javascript 
class PreviewControl extends Rete.Control {
        
        constructor(key){
            super();
            this.render = 'js';
            this.key = key;
        }

        handler(el, editor) {
            var canvas = document.createElement('canvas');
            canvas.width = 256;
            canvas.height = 256;
            
            el.appendChild(canvas);
            
            var ctx = canvas.getContext('2d');
            ctx.textAlign = 'center';
            ctx.fillStyle = '#000';
            ctx.fillRect(0,0, canvas.width, canvas.height);
            ctx.fillStyle = '#fff';
            ctx.fillText("Loading...", canvas.width/2, canvas.height/2);
        }
    }

```

all i get is this - ```html<div class="control" al-control=""></div>```

so my canvas doesnt seem to get attached? even though i think im doing it the same way as your example?
