### ISSUE TITLE
Position snap

### ISSUE THREAD

**Issue by christian-alejandre-mllrdev** [retejs/rete#144]
Hi there @Ni55aN how is it possible to place a node into the nearest round of x and y position? to arrange the node so easily into a grid. like it snaps everytime I drag or create a node.
version use: v0.7.4
https://codepen.io/pierrebleroux/pen/gGpvxJ

**Comment by Ni55aN** [comment]
https://jsfiddle.net/Ni55aN/6fd7hy0v/

**Comment by christian-alejandre-mllrdev** [comment]
I tried changing in the library (v0.7.4), it works, but it doesn't work well when dragging the node and it left behind in a mouse pointer.

**Comment by christian-alejandre-mllrdev** [comment]
Still unresolved issue on v0.7.4.

**Comment by Ni55aN** [comment]
IMHO it makes sense after a while to go to version 1, since the previous one will not be supported

AreaPlugin for v1.0.0 has been updated
https://github.com/retejs/area-plugin/commit/b5892012152537bc63835ecc69024483c765f277

```js
editor.use(AreaPlugin, {snap: {size: 64. dynamic: true}});
```
