### ISSUE TITLE
Replacing indexes with keys causing error

### ISSUE THREAD

**Issue by aahladatparadigm** [retejs/rete#146]
[Release v1.0.0-alphs-7](https://github.com/retejs/docs/blob/master/docs/Changelog.md) is causing error while.

I have added **key** attribute in src/index.d.ts 

1)
In Input and Output classes I have changed the constructor
`constructor(title: string, socket: Socket, multiConns?: boolean);`
The above has been changed to 
`constructor(key: string, title: string, socket: Socket, multiConns?: boolean);`

2) 
In IO class added
key: string;

Then it worked.

**Comment by aahladatparadigm** [comment]
👍

**Comment by Ni55aN** [comment]
`v1.0.0-alpha.8` published
