### ISSUE TITLE
Right click on a node

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#147]
hey,

just updated to context menu plugin [0.1.3](https://cdn.jsdelivr.net/npm/rete-context-menu-plugin@0.1.3/build/context-menu-plugin.min.js)  from  [0.1.1](https://cdn.jsdelivr.net/npm/rete-context-menu-plugin@0.1.1/build/context-menu-plugin.min.js) and now i cant right click on my nodes to remove them, not sure if its something i have done / should do / or its a bug in the plugin? 

Chrome Version 67.0.3396.99 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/38964969/43203874-48a89114-9017-11e8-8358-8b19fae8487d.png)

**Comment by Ni55aN** [comment]
6b2aeec9dc06d5e01c0f085e721a62afdb8877fb

**Comment by Ni55aN** [comment]
Fixed
