### ISSUE TITLE
input receiving connection

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#148]
Hey,

i was trying to figure out if there is a way to detect if an input is receiving a connection? 

i know there is this - `connectioncreated` but i dont think its what i want as i cant tell which node is being connected to/from etc.

is this possible? basically i want something to happen on a specific node when it receives a connection rather than something happening when any node gets a connection.

hope that makes sense

**Comment by Ni55aN** [comment]
Do you mean event handlers in component? Such as `created()`/`destroyed()` ?

**Comment by JMidd91** [comment]
no not those, i meant if i connect node 1's output to node 2's input, i want to know which input on that node has had a connection created then to do something about it

**Comment by Ni55aN** [comment]
`input.key` / `output.key` ?

**Comment by JMidd91** [comment]
sorry youve lost me. where can i access those? doesnt seem to have anything in the worker?

**Comment by Ni55aN** [comment]
worker has inputs, outputs

For example. `inputs['key']`

Input/Output instances have a  property `key`

**Comment by JMidd91** [comment]
but what i mean is where is it that this goes in the structure? like this? 

```javascript
class MyComponent extends Rete.Component {
    constructor(){
    }

    builder(node){
    }

    worker(node, inputs, outputs){

    Input.key = variable
    }
}

```

sorry to be a pain, im just confused!

**Comment by Ni55aN** [comment]
> i was trying to figure out if there is a way to detect if an input is receiving a connection

```js
worker(node, inputs, outputs){
    Inputs['key'].length > 0 // has connections
 }

```

**Comment by JMidd91** [comment]
Aaah cheers! I don't know why I couldn't understand that, thanks !
