### ISSUE TITLE
Disconnecting two nodes

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#150]
hey,

so i was following this [demo](http://jsfiddle.net/vmxdcLbq/43/) that was made a while ago to disconnect two nodes.

it works for the node with an input but the connection is still visible for the node with an output ( see pic ), i am then unable to remove the connection from the output node. The actual data connection still seems to be linked also.

what am i doing wrong? i have copied the demo linked above

![image](https://user-images.githubusercontent.com/38964969/43259985-fa11abd0-90cf-11e8-97c1-492351d8abbb.png)

**Comment by Ni55aN** [comment]
Try `editor.view.updateConnections({node})`

**Comment by JMidd91** [comment]
this isnt working for me at the moment

**Comment by Ni55aN** [comment]
Found a problem. Connections must be deleted through the editor to interfere with the view

http://jsfiddle.net/Ni55aN/vmxdcLbq/61/

**Comment by JMidd91** [comment]
this is perfect, thank you
