### ISSUE TITLE
Infinite connections

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#152]
hey,

I had a random moment and tried this (see pic below) was wondering if this was intentionally allowed or if it should be prevented as it may cause issues? i guess its not really important as its obvious it would prob cause issues, just thought id highlight that you can link a nodes output into its own input at the moment 

![image](https://user-images.githubusercontent.com/38964969/43448131-026266fc-94a5-11e8-9485-d8409c9fc1ad.png)

**Comment by Ni55aN** [comment]
Ok, I'll take a look at this problem.

**Comment by Ni55aN** [comment]
I noticed the problem of recurrent nodes not so long ago. Perhaps we need the option to disable such connections but, also have to change Engine to allow it to process such nodes.

**Comment by Ni55aN** [comment]
Hey! As I see this problem does not really bother anybody :)

Anyway, there are solution with at least one disadvantage - performance.

1. Install `rete-lifecycle-plugin`
2. 
```js
editor.on('connectioncreated', (connection) => {
   var recurentNodes = engine.detectRecursions(editor.toJSON());
   
  if(recurentNodes.length > 0) editor.removeConnection(connection);
});
```
