### ISSUE TITLE
Button and node.addOutput

### ISSUE THREAD

**Issue by saalaus** [retejs/rete#155]
Hello! I want to make it so that when you click on the button , the selected node add output.

This function is called when the button is clicked

```
function add_choose(){ 
    var node = editor.selected.list[0] // get selected nodes
    console.log(editor.selected)
    if(node.name == "test"){
        node.addOutput(new Rete.Output('next', text, anyType, false)); // if node name = test add output
    }
}
```

but why it does not work the way I want it:  A dedicated node is displayed in the console, but the output itself appears only when you click the node again

I tried and through editor.on, the result is the same

[video](https://youtu.be/9Ekhxck-kFw)

**Comment by JMidd91** [comment]
Try adding `node._alight.scan()` after `node.addOutput`. I think that should work, cant test though as I am away from my pc

**Comment by saalaus** [comment]
Thanks! `node._alight.scan()` helped me!
