### ISSUE TITLE
Too many active WebGL contexts.

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#156]
Hey,

has anyone come across this before? 

![image](https://user-images.githubusercontent.com/38964969/43579079-c5f87724-9648-11e8-88ef-80ab388c388c.png)

if you have, how did you fix it? 

from googling the main solutions that show up are listed in [this](https://stackoverflow.com/questions/23598471/how-do-i-clean-up-and-unload-a-webgl-canvas-context-from-gpu-after-use), but so far havnt worked for me.

**Comment by JMidd91** [comment]
is there any documentation on this? cant see any on the github page

**Comment by Ni55aN** [comment]
no, it does not have full documentation

Just create one Canvas (`new Texturity.Canvas (w, h);`) and draw into canvas many times what you want and copying the resulting images into `src`

https://github.com/Ni55aN/allmatter/blob/e19182163e8874b1db4a149d3bd15d66320c4aa2/src/editor/utils.js

**Comment by JMidd91** [comment]
is there any way to access the 2d context from this canvas? 

I am using [this library](https://github.com/phoboslab/WebGLImageFilter) and it needs to access the 2d context to apply a filter? 

likewise I have some nodes where i edit each pixel in a loop and then apply the new data back to the 2d context via `putImageData`

**Comment by Ni55aN** [comment]
2d or webgl ? Texturity works with webgl/webgl2

```js

const texture = new Texturity.Cancas(w,h);
texture.getGL()
```

**Comment by JMidd91** [comment]
Hi, sorry for the late reply, ive been away.

2d i believe. 

I am unable to get to this stage as for some reason ( after having a break ) i am now getting this error - 
![image](https://user-images.githubusercontent.com/38964969/44528202-d9195000-a6e0-11e8-9085-f48944a0eff3.png)


from using this code (which i am pretty sure hasnt changed) but my mind is a bit slow from being in holiday mode haha - 

```javascript
input.addEventListener('change', function (e) {
                var file    = node.input.files[0];
                var reader  = new FileReader();
                
                reader.addEventListener("load", function () {
                    var img = new Image();
                    img.src = reader.result;
                    
                    img.onload = function() {
                        var outputImg = fastCanvas.drawTexture(img, 0, 0, img.width, img.height).toSrc();
                    }                   
                    
                    
                }, false);

                if (file) {
                    reader.readAsDataURL(file);
                }
                
            }, false);

```

**Comment by Ni55aN** [comment]
First parameter in drawTexture must be WebGLTexture https://github.com/Ni55aN/texturity.js/blob/master/src/index.js#L109

Try this:
```js
var texture = Texturity.loadTexture(img)
var outputImg = fastCanvas.drawTexture(texture, 0, 0, img.width, img.height).toSrc();
```

**Comment by Ni55aN** [comment]
For now, you can only explore the features by reading the library code, since the documentation is simply missing

**Comment by JMidd91** [comment]
thanks, and sorry to be a pain! 

but that now gives me this issue - 

![image](https://user-images.githubusercontent.com/38964969/45012797-a04a7680-b010-11e8-9c2b-ba148b722d25.png)


after googling i came across [this link](https://stackoverflow.com/questions/42219499/glsl-for-opengl-es-3-0-failed-to-compile-shaders-unsupported-shader-version) but it doesnt make much sense to me.

would the above error be something I have done wrong or? 

this is my line of code it points too - 

```javascript
var fastCanvas = new Texturity.Canvas(textureSize, textureSize);
```

**Comment by JMidd91** [comment]
awesome! youre a hero, I greatly appreciate your help :) 

seems to have fixed the webGL context issue so far so will close for now.

thank you very much again!
