### ISSUE TITLE
alpha.8 argument "title" error

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#157]
hey,

just updated to alpha 8 from 5 and i get this error when i try and add a node to the canvas from the context menu

`Uncaught (in promise) TypeError: Value of argument "title" violates contract.`

![image](https://user-images.githubusercontent.com/38964969/43589477-ba438cfc-9666-11e8-9740-2580d43acfbe.png)

is this a user error on my behalf or a bug with the latest update? 

this is the combination of plugins i am using, if that helps - 

```javascript
<script src="https://cdn.jsdelivr.net/npm/rete@1.0.0-alpha.8/build/rete.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/alight@0.14.1/alight.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/rete-alight-render-plugin@0.1.5/build/alight-render-plugin.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/rete-connection-plugin@0.1.1/build/connection-plugin.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/rete-context-menu-plugin@0.1.4/build/context-menu-plugin.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/rete-module-plugin@0.1.3/build/module-plugin.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/rete-area-plugin@0.1.4/build/area-plugin.min.js"></script>
```

**Comment by Ni55aN** [comment]
alpha.7 have major changes related to creation of Input/Output (look through [changelist](https://github.com/retejs/rete/releases/tag/v1.0.0-alpha.7)).

[Example](https://rete.readthedocs.io/en/latest/Migrate/#named-inputsoutputs)

**Comment by JMidd91** [comment]
ah ok definitely user error! will implement these changes before closing :)
