### ISSUE TITLE
Do not drag node while mouse pointer on input controls.

### ISSUE THREAD

**Issue by Hatead1** [retejs/rete#158]
Hi!

It'is impossible to select the text or a part of the text using a mouse in input field of node.

**Comment by Ni55aN** [comment]
You need `stopPropagation()` on the mousedown event in Control's element.

In case of `alight`it should be `@mousedown.stop`
```js
<input type="number" :readonly="readonly" :value="value" @input="change($event)" @mousedown.stop/>
```

**Comment by Hatead1** [comment]
I meant to block this function globally. I don't think that someone really needs such feature.

**Comment by Ni55aN** [comment]
Why not? Controls can contain not only input fields, therefore, in all situations they should not block the movement of the node

**Comment by Hatead** [comment]
Do you understand that such "standard behavior"? For input fields mouse + LMB always select content of  input. Not drag! For list (select) - drop list, no drag. 

Add dropdown list to node, click on it for option list and drag node without releasing LMB  :)

**Comment by Ni55aN** [comment]
The Cotrol with the image in general should not block the dragging of the node. This is one of the reasons why you can not block a mousemove node.

Solution: `stopPropagation()` on the element you need

**Comment by Hatead1** [comment]
Haven't convinced, but Ok.

**Comment by blauwepiet** [comment]
Somehow the stoppropagation doesn't work.. I tried to put it on all mouse events and they all trigger but the propagation is not prevented when using either the Vue @mousedown.stop or add a function @mousedown="stopPropagation" and then that function is:

function(e){
  e.stopPropagation()
}

None of it stops this behavior. Do you have any idea what could cause this? is the drag event above the input event drag or something?

**Comment by blauwepiet** [comment]
Found the solution in https://github.com/retejs/rete/issues/253#issuecomment-462756008 for anyone having the same problem and this is the first issue you come across.

**Comment by yoshivda** [comment]
I'm having the same issue and none of the aforementioned solutions seem to work. I'm using the angular renderer plugin. I tried adding `(mousedown)="stopPropagation"`, where `stopPropagation(event)` calls `event.stopPropagation()`, but this still allows dragging (as @blauwepiet also found). I also tried other mouse events, none seem to work. A solution would be greatly appreciated 🙂
