### ISSUE TITLE
AddInput in code bugs

### ISSUE THREAD

**Issue by saalaus** [retejs/rete#160]
Hi, I'm using addInput in my code when I need it, and here are 2 problems:

1.Problem with path
![default](https://user-images.githubusercontent.com/37474917/44000247-1df3fb34-9e36-11e8-9d2c-866da4421de8.png)

2.Promlem with editor.fromJSON()
![default](https://user-images.githubusercontent.com/37474917/44000266-46b8fe84-9e36-11e8-8bf2-9ce9ccff6145.png)

How can I fix this?

**Comment by saalaus** [comment]
Not working save(editor.toJSON()) and load(editor.fromJson()), at boot such nodes appear, as in the 2 screenshot

**Comment by Ni55aN** [comment]
There is not enough code to figure out the issue
