### ISSUE TITLE
Problem with bindSocket

### ISSUE THREAD

**Issue by MeloJR** [retejs/rete#161]
Hi, I'm building a plugin for use `lit-html` instead of `alight` for rendering nodes. I have a first version of the plugin working right now but I found an issue with the `bindSocket` function.

Here is my issue: I have some nodes that add/remove their inputs dynamically (e.g. a node with a combo that changes its inputs based on the combo's value). I found that if I invoke the bindSocket function twice (with the same parameters) the connection plugin does not work, however, the `connectioncreated` event is fired.

As far as I see in the code, the `bindSocket` sets a value in the `sockets` Map so it should overwrite the last value and everything should work, but it doesn't.

I can prevent the double call of the `bindSocket` for the same inputs but, when the inputs change, I have to update the inputs of the node and the socket DOM element will be the same because I reuse the DOM elements. If I could call some 'unbindSocket' function for previous inputs the issue should be solved.

**Comment by Ni55aN** [comment]
Can you share live example? (ex. codesandbox.io)
