### ISSUE TITLE
Problem with latest Prototype framework.

### ISSUE THREAD

**Issue by Hatead1** [retejs/rete#162]
Simple test: add library (https://cdnjs.cloudflare.com/ajax/libs/prototype/1.7.3/prototype.min.js)  to codepen example.

**Comment by Ni55aN** [comment]
Seems like that framework changes the native behavior of objects / methods.
`al-socket` directive just does not invoked, which should call bindSocket

**Comment by Hatead1** [comment]
Ok, thanks.
