### ISSUE TITLE
Bugs in Chatbot example

### ISSUE THREAD

**Issue by mrwhy-orig** [retejs/rete#163]
I'm new to rete.js and I had a look a the example to get a better understanding of it... I found a bug in the Chatbot example. If you disconnect the MessageNode (ッ) from the sendNode an type a message into the chat, the text from the MessageNode is displayed. Even in that case you've changed it. Another thing i discovered is on line 141. The InputControl is instantiated without a name.
` var ctrl = new InputControl();`
But then in line 148 "node.data.tex"t is undefined.
`var text = inputs[0] ? inputs[0][0] : node.data.text; //default text`

Am I wrong here? Do I miss something?

**Comment by Ni55aN** [comment]
Thanks, I fixed this bug https://codepen.io/Ni55aN/pen/rpOKNb
