### ISSUE TITLE
How to create a group?

### ISSUE THREAD

**Issue by bachirelkhoury** [retejs/rete#167]
I have seen in previous examples that you can right+click and create a group.
I can't seem to find in the docs how to do that. When righ+clicking a node, I can only see the "Remove" button.

**Comment by Ni55aN** [comment]
Groups were implemented in v0.7.4 and earlier, but in the new version v1.0.0 this feature has been removed. Can be added in the future in the form of a plugin

**Comment by bachirelkhoury** [comment]
Ah I see... that's an important one.. sad to see it been dropped. 
thanks for the clarification.
