### ISSUE TITLE
Global variables accessible in Components

### ISSUE THREAD

**Issue by telcy** [retejs/rete#168]
Is there any way to add global variables to the engine which can be accessed within the components?

**Comment by Ni55aN** [comment]
Data related to processing can be passed to `process()` and available inside `worker()`

```js
engine.process(data, null, arg1, arg2); 

/// inside component
worker(node, inputs, outputs, arg1, arg2){
     outputs[0] = node.data.num;
}
```
https://rete.readthedocs.io/en/latest/Engine/
