### ISSUE TITLE
task plugin

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#172]
Hi

I have started to try to implement the task plugin. I have started using your [example ](https://codepen.io/Ni55aN/pen/MOYPEz)as close as possible

but I am now getting this error - 
`jquery-3.3.1.min.js:2 Uncaught Task plugin requires a task property in component`

and my component doesnt appear in the context menu. 

This error is just confusing me a bit as it suggests I should have a property somewhere but I dont see anything obvious in the example above that I have missed out?

here is the code for my component - 

```javascript

        
    class OnClickComponent extends Rete.Component {
        
        constructor() {
            super("HTML5 Button");
            
            this.task = {
                outputs: {data: 'option', event: 'output'},
                init(task){
                    eventHandlers.remove();
                    eventHandlers.add('click', function (e) {
                          task.run(e);
                          task.reset();
                    });
                }
            }
        }
        
        builder(node) {
            var inp1 = new Rete.Input("btn", "Button Obj", html5buttonSocket);
            var out1 = new Rete.Output("data", "Option Data", taskOptionSocket);
            var out2 = new Rete.Output("event", "Click Event", clickEventSocket);
            
            return node.addInput(inp1).addOutput(out1).addOutput(out2);
        }
        
        worker(node, inputs, data) {
            
            return {event: data}
        }
    }  
```

this is my "engine" part of the code - 

```javascript

 var container = document.querySelector('#nodeEditor');
        var components = [new HTML5ButtonComponent, new OnClickComponent];

        var editor = new Rete.NodeEditor('demo@0.1.0', container);
        editor.use(ConnectionPlugin, { curvature: 0.4 });
        editor.use(AlightRenderPlugin);
        editor.use(ContextMenuPlugin);
        editor.use(AreaPlugin);
        editor.use(TaskPlugin);
        editor.use(JsRenderPlugin);

        var engine = new Rete.Engine('demo@0.1.0');

        components.map(c => {
            editor.register(c);
            engine.register(c);
        });

        editor.on("process connectioncreated connectionremoved", async function() {
            requestAnimationFrame(async () => {
                await engine.abort();
                await engine.process(editor.toJSON());
            });
            
            console.log("input is?", editor);
            
        });

        editor.trigger('process');
        editor.view.resize();

```

**Comment by Ni55aN** [comment]
Does `HTML5ButtonComponent` have the `this.task` ?

**Comment by JMidd91** [comment]
it does in the constructor but I havnt put anything in that yet as I havnt figured out what i need to happen there yet as I am converting this part of my project from v0.7

**Comment by Ni55aN** [comment]
Some explanations #170

**Comment by JMidd91** [comment]
yea ive read that didnt seem to help me, I will continue to dig around unless anyone has another idea of what ive done wrong :)

**Comment by Ni55aN** [comment]
I propose you to share a live example on [codesandbox.io](http://codesandbox.io)

**Comment by JMidd91** [comment]
ok so i put all my code into code sand box just like how it is in my actual files and it gives me all kinds of errors so im assuming it wants me to set up the project in a certain way that I have never learnt. 

I dont really have the time to fix something like this but im hoping it will be obvious / quick fix for someone who has way more experience than i do so here is the link to the editor anyways - [https://codesandbox.io/s/w7wqyp7868](https://codesandbox.io/s/w7wqyp7868) 

and also hopefully that link will help solve my original issue too.

many thanks!

**Comment by JMidd91** [comment]
> 1.
> this.task = { // should not be empty
> outputs: {} // required
> }

ah ok will sort that out.

> OnClickComponent duplicates the name of other component (super("HTML5 Button"))

its always the simple things that I overlook! 

thanks for your help!

**Comment by JMidd91** [comment]
> outputs: {} // required

if you have a component that doesnt have any outputs, do you - 

1. leave the `{}` empty
2. swap it for `inputs:{}`
3. do something else?

**Comment by JMidd91** [comment]
a quick question, 

why is this used 
```javascript
worker(node, inputs, data) {
    return {key: data}
  }
```
instead of this
```javascript
worker(node, inputs, data) {
    output["key"] = data;
  }
```

**Comment by Ni55aN** [comment]
The Task plugin was impelemented later and some shortcomings were taken into account.

We can assume that the first option is more clean (all you can write to the output can be found at the end of the method). But on the other hand, this difference allows us to understand that in the first case this is not an ordinary `worker()`

**Comment by JMidd91** [comment]
I cant quite figure  out how to access the info I need or if its even possible for the way tasks work in the newer versions. this is the component from v0.7  -

```javascript
    window.interEventHandlers = {
        list: [],
        remove(eventNumber, el) {
            el.removeEventListener('click', this.list[eventNumber], false);
            el.removeEventListener('keydown', this.list[eventNumber], false);
        },
        add(name, el, h) {
            el.addEventListener(name, h, false);
            this
                .list
                .push(h);
        }
    };



    var c_onClick = new D3NE.Component("onClick Event", {
        builder(node) {
            
            var inp1 = new D3NE.Input("Button Obj", s_html5button);
            var out1 = new D3NE.Output("Option Data", s_taskOption);
            var out2 = new D3NE.Output("Click Event", s_clickEvent);
            
         return node
            .addInput(inp1)
            .addOutput(out1)
            .addOutput(out2);
        },
        worker(node, inputs, outputs) {

            var task = new D3NE.Task(inputs, function (inps, data) {
                return [data];
            });

            //console.log("INPUT IS", inputs[0][0]);
            if(inputs[0][0] != null){
                //console.log("LIST LENGTH IS ", window.interEventHandlers.list.length);
                //console.log("EVENT NUMBER IS ", node.data.eventNumber);
                if(node.data.eventNumber != null){
                    //console.log("WE HAVE AN EVENT, WILL NOW REMOVE IT AT POSITION", node.data.eventNumber);
                    window.interEventHandlers.remove(node.data.eventNumber, inputs[0][0]);
                    node.data.eventNumber = null;
                }else{
                    //console.log("no events have been created");
                }
                node.data.eventNumber = window.interEventHandlers.list.length;
                node.data.input1Element = inputs[0][0];
                //console.log("WE HAVE ", node.data.eventNumber, " TOTAL EVENTS");
                window.interEventHandlers.add('click',  inputs[0][0], function (e) {
                    task.run(e);
                    task.reset();
                });
            }
            
            outputs[0] = task.option(0);
            outputs[1] = task.output(0);
        },
        created(node){
            console.log("CREATED", node);
        },
        destroyed(node, inputs, outputs){
            engine.abort();
            if(node.data.input1Element != null){
                console.log("deleting event for ", node.data.input1Element.id);
                interEventHandlers.remove(node.data.eventNumber, node.data.input1Element);
            }
        }
   });
```

so in v1 I cant seem to figure out how to access info on what inputs are plugged in and how to look at data vars stored in the component via the task in the constructor? or can i do all this task work in the worker like before instead of in the task in the constructor?

**Comment by Ni55aN** [comment]
"Option Data" is not an output for data, most likely for an action ('option' type)

```js
if(inputs[0][0] != null){
```

Why do you checking inputs ?

**Comment by JMidd91** [comment]
the input of this component is a html5 button / div info which i then apply the click event to

**Comment by Ni55aN** [comment]
You can not get input when initializing tasks (because when initialized, these are objects of the form {task, key} and {run, get}

https://github.com/retejs/task-plugin/blob/master/src/task.js#L61

Therefore, all of workers must return the tasks (in v0.7.4, outputs[0] = task.ouption(0) for example)

------

Should be:
```js
this.task = {
outputs: {0: 'option', 1: 'output'}
}
```
instead of
```js
   outputs[0] = task.option(0);
   outputs[1] = task.output(0);
```

---------

```js
worker(node, inputs, data) {
   return {key: data};
}
```
instead of
```js
worker(node, inputs, outputs) {
     var task = new D3NE.Task(inputs, function (inps, data) {
            return [data];
      });
}
```
-----

Other code in the middle of worker must be in `this.task.init()` or in `worker()`. I need to see a living example of how this works for you now.

**Comment by JMidd91** [comment]
hopefully [this ](https://codepen.io/anon/pen/zJWXzo?editors=0010)helps

here is the layout, create the nodes in order as i think in this version i had a few bugs still - 
![image](https://user-images.githubusercontent.com/38964969/45408348-00ba6300-b664-11e8-824d-05706ce78e60.png)

the button drop down is a bit buggy in this one, you have to re select it before the div gets added to the data. you can then type any string in the console.log node, it will then put that into the log when you click the big blue bar button along with what ever is plugged into the "log this" input.

hope this helps!

**Comment by JMidd91** [comment]
sorry im still really confused on how to convert my 0.7 code to 1.0.  i think its because i dont really  get the flow of the data / code from task to worker / between components. 

dont worry if youre busy, i will figure it out eventually, just gets a bit frustrating being stuck haha

**Comment by Ni55aN** [comment]
you can share example on codesandbox (or something else) and I'll try to migrate it to v1.0.0 in my free time

**Comment by JMidd91** [comment]
ah awesome, what a hero :D, ive thrown it together [here](https://codepen.io/anon/pen/yxEbyY?editors=0010)

**Comment by Ni55aN** [comment]
The problem is that at the time of the initialization of the tasks you can not hang the event on the button, since the data about it will only be at the moment of execution.

Solution: https://codepen.io/Ni55aN/pen/dqKZZy

We listening to the events of all the buttons. When executing the tasks, we transfer control to Console Log if clicked button match selected in HTML5 Button

**Comment by Ni55aN** [comment]
>  I just need to to figure out how to get it to work with multiple buttons / on click nodes

The 'On Click' node can accept multiple inputs in "Button obj"

**Comment by JMidd91** [comment]
ah maybe i phrased it wrong. i meant that if i create two on clicks for two buttons, only the second lot gets activated? ill try explain it better with pics - 

![image](https://user-images.githubusercontent.com/38964969/45544089-44e96700-b80e-11e8-9288-14d9ea6aac6c.png)

so i created the top row first for the first button, then the second row for the second button.

if i click the first button, i dont get any logs that say "CONSOLELOG1" but if i click second button i get "CONSOLE LOG 2.

also, if i click the first button, it returns info about the second button only? 

![image](https://user-images.githubusercontent.com/38964969/45544169-72361500-b80e-11e8-8851-4a65c03ebfc3.png)

**Comment by Ni55aN** [comment]
I have transfered `interEventHandlers.remove()` to section with all tasks initialization instead of initialization on every "On Click"

https://codepen.io/Ni55aN/pen/dqKZZy?editors=0010

**Comment by JMidd91** [comment]
this is perfect, thanks very much for your help on this! also i hope this thread helps someone else also!

**Comment by haris-75** [comment]
Can we add a custom button in the editor/engine?
