### ISSUE TITLE
The problem with the dynamic addition of sockets

### ISSUE THREAD

**Issue by Clasen00** [retejs/rete#174]
Hello! Thank you for your great job, it's very useful! I'm working with your framework and trying to make app where I can dynamically add sockets. Here is an [example](https://codepen.io/Clasen00/pen/mGaVge?editors=0010 ): 
In example you can see Radio Component where you can add sockets dynamically by following code: 
` outputs.set(this.scope.value_txt, new Rete.Output(this.keyz, this.scope.value_txt, stringSocket, true));`
That works, but then I can't connect these added nodes to others and getting a lot of errors in the console. 
There is something wrong with my code? Can you help me resolve the problem with connects?

**Comment by Ni55aN** [comment]
Seems like a bug. I'll try to fix it in about a couple of days

**Comment by Clasen00** [comment]
@Ni55aN thank you very much! Notice me, if you please, when you will fix it :+1:

**Comment by Ni55aN** [comment]
@Clasen00 the problem is that the added Output doesn't have reference to a node. I.e. 
```js // in the ButtonControl
const out = new Output(...
out.node = this.getNode()
```

But you don't need to define it manually, just add the output via `.addOutput()`

```js
 this.getNode().addOutput(
    new Rete.Output(this.keyz, this.scope.value_txt, stringSocket, true)
);
```

**Comment by Ni55aN** [comment]
https://codepen.io/Ni55aN/pen/WgmaoG?editors=0010

**Comment by Clasen00** [comment]
@Ni55aN the problem is solved, thank you! This issue can be close) (will be cool to put it  in official documentation, i think).

**Comment by Clasen00** [comment]
@Ni55aN exuse me, something happened with Rete and now it's doesn't working i don't know why) Your example doesn't working, controls are not adding anymore

**Comment by Ni55aN** [comment]
@Clasen00 now it working?

**Comment by Clasen00** [comment]
@Ni55aN no, look! I can't add more than one control
![image](https://user-images.githubusercontent.com/18239785/46668548-12196f80-cc10-11e8-8501-ef043b3e742a.png)

**Comment by Clasen00** [comment]
@Ni55aN yes thank you very much!)
