### ISSUE TITLE
Can't resolve 'vue'

### ISSUE THREAD

**Issue by hirokuni** [retejs/rete#175]
Hi

I am making  web app using react and retejs. When I tried to start the app, then I got a following error.
(I also used [create-react-app](https://github.com/facebook/create-react-app) to make basic setup)

**Failed to compile
./node_modules/rete-vue-render-plugin/build/vue-render-plugin.min.js
Module not found: Can't resolve 'vue' in '/Users/hirokuni/work_team1/PlumConnectMobile/test/react-app-test-with-retejs/node_modules/rete-vue-render-plugin/build'**

Could you advise me how to solve it?

[Code.](https://github.com/hirokuni/react-app-test-with-retejs) It is a minimum test application.

**Comment by Ni55aN** [comment]
So far you can install vue.js separately, since I forgot to add it to `dependencies`. I'll do it in the next version

**Comment by hirokuni** [comment]
Thank you for your reply. I solved it!
