### ISSUE TITLE
How do you use this framework ?

### ISSUE THREAD

**Issue by Ni55aN** [retejs/rete#176]
I am working on the master's thesis and I would like to write about the projects which use this framework and what tasks are being solved with its help.

Please, write about your product and what tasks it solves. If you don't mind, I would like to describe your experience in my thesis.

**Comment by JMidd91** [comment]
I am using Rete to removing the coding aspect from people building WebGL scenes, and building interactions for said scenes so more people can get to use the fun side of the web without having to know JavaScript

**Comment by Clasen00** [comment]
Im using Rete to develop a platform to visual programming chat bots . That will be comercial project, but now it open source. [Link:)](https://github.com/Clasen00/bot-layout)

**Comment by jerosoler** [comment]
I'm using rete for the IoT [Link](https://github.com/jerosoler/IoTFlow)

**Comment by jtwnel** [comment]
Can this framework be used with ReactJs and Redux?

**Comment by Linkupdated** [comment]
I use Rete for my game, used to desing npc behaviors that players will be able to code themselves via visual programming. [Link](https://citywars.ca)

**Comment by designbyadrian** [comment]
@jtwnel Redux has nothing to do with rendering - it only supplies props to the component. It's also not the only state-management framework you can use with React.

**Comment by dgsunesen** [comment]
@juliandavidmr are you the create of UserSync? If so, I would like to talk with you about how that project is structured and what you have used to build it :)

**Comment by juliandavidmr** [comment]
Hello @dgsunesen, I built UserSync together with the collaboration of other colleagues. It is a public project, developed by the Bizagi company. It was built with Angular 7, while the Rete nodes use the Vue render plugin.

**Comment by Githamza** [comment]
@juliandavidmr  , do you mean that you have an angular plugin rederer or you use VueJs plugin inside Angular project ?

**Comment by juliandavidmr** [comment]
@Githamza You can inspect the website and you note that the nodes disferent internally to Angular components. Finally, I created a custom nodes with Vue, it's integrated inside Angular project.

**Comment by iKlsR** [comment]
@Ni55aN I think you should reopen and possibly pin this similar to [what imgui does](https://github.com/ocornut/imgui#gallery). It's very interesting to see how people take advantage of the framework and also can be a showcase of sorts.

**Comment by Ni55aN** [comment]
@iKlsR maybe I'll create new Issue with a example template (description, image, link)
