### ISSUE TITLE
task

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#179]
hey,

so I am fiddling with tasks again, I have some components that i want to connect with tasks, but I also have some that plug in that i want to work outside of tasks.

currently it seems that I am only able to create one or the other.

here is a [codepen](https://codepen.io/anon/pen/jvjGYP?editors=0010)

so a rough scenario - 

I have a button that i want to click that performs a console log of a number I have added together, this works. 

the part that doesn't work, is in the add component, the preview no longer updates since I have added tasks.

is there a way to accommodate both? 

p.s. sorry about the messy code, just thrown it together in my spare time by combining [this](https://codepen.io/Ni55aN/pen/dqKZZy?editors=0010) and [this](https://codepen.io/Ni55aN/pen/QOEbEW?editors=1000)

**Comment by Ni55aN** [comment]
1. The last parameter { silent } = {} doesn't make sense cause it only used in pure workers (they are not like that since you use in the Task plugin). Task plugin's workers have a follows parameters: `node, inputs, data`
2. `this` inside of worker (in case of used Task plugin) points to Task (in the pure worker `this` points to component instance). You need to get a component's instance using `this.component`

**Comment by Ni55aN** [comment]
```js
this.component.editor.nodes.find(n => n.id == node.id).controls.get('preview').setValue(sum);
```
instead of 
```js
 if (!silent)
     this.editor.nodes.find(n => n.id == node.id).controls.get('preview').setValue(sum);
```

**Comment by Ni55aN** [comment]
> so i should remove the silent code now?

yes

> so ive updated the link, seems to still only update when a task is performed?

exactly. It is the essence of the tasks - they are executed on demand

**Comment by JMidd91** [comment]
> exactly. It is the essence of the tasks - they are executed on demand

yea i get that, but would it not be possible to run it both ways? if not now, in the future as a feature? :)

**Comment by Ni55aN** [comment]
Is it make sense? It can only complicate the processing of nodes

**Comment by JMidd91** [comment]
hmm fair enough, maybe i need to re think how i set this up then

**Comment by Ni55aN** [comment]
> if you click either button, they execute both tasks.

the node can not know in advance which button it is bound to, since this data only comes when executing

> as you can see below, i have them separate but in the logs, theyre both executing at once

Trigger Task haven't to propagate execution. It should be closed, because pressed Button and Button Obj don't match

**Comment by JMidd91** [comment]
thanks for pointing that out. another user error from me haha

`this.closed = !isTargetButton?['task']:[];`

this had wrong output name, whoops!
