### ISSUE TITLE
angular 6 install

### ISSUE THREAD

**Issue by valefix80** [retejs/rete#180]
Hi,

I am trying to migrate from your D3NE library to Rate.

I followed the instruction in your doc but I am not able to install the library in angular 6.

I did:

npm install rete rete-vue-render-plugin rete-connection-plugin

added the following in angular.json

"scripts": [
           { "input": "./node_modules/rete/build/rete.min.js", "bundleName": "rete"},
              { "input": "./node_modules/rete-vue-render-plugin/build/vue-render-plugin.min.js", "bundleName": "rete-vue-render-plugin"},
              { "input": "./node_modules/rete-connection-plugin/build/connection-plugin.min.js", "bundleName": "rete-connection-plugin"}
            ]

this in app.module.ts

import Rete from "rete";
import ConnecionPlugin from 'rete-connection-plugin';
import VueRenderPlugin from 'rete-vue-render-plugin';

this in my component

///  reference path="../../../../../node_modules/rete/src/index.d.ts"/

I got these errors:

in the import:

/node_modules/rete/src/index"' has no default export

in the component when I try using Rete

[ts] Cannot find namespace 'Rete'.
any

any suggestions?

thank you in advance!

**Comment by Ni55aN** [comment]
Hi! Have you seen the [example](https://github.com/retejs/examples/tree/master/Angular)? What version are you installing?

**Comment by valefix80** [comment]
Hi!

I went back trying to install again the 0.7.4 as for in my previous project with angular 5 where it worked fine.

Following the same installing procedure I am getting a very strange error that I do not understand at all...

d3_node_editor__WEBPACK_IMPORTED_MODULE_4__.Socket is not a constructor

this happens when I try to create a Socket object. At build time there is no error... it only happens when the app is loaded..

any idea?

thanks!

**Comment by Ni55aN** [comment]
How do you import the library?
It should be 
```js
import * as D3NE from 'd3-node-editor';
```

**Comment by valefix80** [comment]
Yes, I import it in that way.

Could be a problem of angular 6? Because in another project with angular 5 I use the library with no problem..

**Comment by valefix80** [comment]
I could not try it with Angular 6... so cannot say if it works... sorry

**Comment by Ni55aN** [comment]
Rete.js doesn't require "scripts" property in the config.

[This example](https://github.com/retejs/examples/tree/master/Angular) works correctly
