### ISSUE TITLE
[q] Component with specified template

### ISSUE THREAD

**Issue by Radaana** [retejs/rete#181]
Good day
I'm using rete to build my own nodes with specified template. According to docs I declare MyComponent extending Rete.Component . In constructor I assign this.template  to my template, but unfortunately it doesn't work.

In rete-alight-render-plugin  rendernode event receives empty argument named "component "

How could I fix this problem?

**Comment by Ni55aN** [comment]
The doc has an inaccuracy in code: https://rete.readthedocs.io/en/latest/Plugins/#alight-render

It should look like:
```js
class MyComponent extends Component {
    constructor(){
        // ...
        this.data = {
           render = 'alight', // required if used more than one render plugin
            template = '<div ...>' // component specific template
        }
    }
}
```

On the other hand, `rete-alight-render-plugin` no longer in priority after the `rete-vue-render-plugin` release: https://rete.readthedocs.io/en/latest/Plugins/#vue-render

**Comment by Radaana** [comment]
Thank you for quick answer. If I use 

`class MyComponent extends Component { `

I have an error -> Uncaught ReferenceError: Component is not defined

Which library should I use to obtain Component to extend?

**Comment by Ni55aN** [comment]
`Component` is a class under namespace Rete

**Comment by Radaana** [comment]
Thank you for your help,  JMidd91 and Ni55aN , this worked for me

```
class MyComponent extends Rete.Component {
    constructor(){
        super('MyComponent');
        this.data = {
            render : "alight", 
            template : my-template 
        }
    }
}
```

**Comment by JMidd91** [comment]
> Thank you for your help, JMidd91 and Ni55aN , this worked for me

ah! i was right, i deleted my answer as I re read Ni55aN's original post and thought I was wrong haha. glad it worked
