### ISSUE TITLE
Alight plugin

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#182]
Hi,

hopefully someone can answer this - 

as in [this demo](https://codepen.io/Ni55aN/pen/dqKZZy?editors=0010) we have 2 buttons and a node that lists them, if you go into the console (after having created a node first so it lists both buttons in the drop down) and then delete one of the buttons, i cant seem for the life of me, to be able to refresh the list unless i delete that node and create a new one.

this is the line of code I have tried / would have assumed works - 

```javascript

this.component.editor.nodes.find(n => n.id == node.id).controls.get("button")._alight.scan();

```

but it doesnt seem to have any effect. even though it clearly has called the right function as if you dig in and look at the node, its internal list has been updated, its just the visual drop down list created by alight isnt updating...

hope that makes sense? 

also on a side note, would it be better to change this from using alight to vue? 
I am just a bit cautious of doing this as I have even less knowledge of vue 

many thanks.

**Comment by Ni55aN** [comment]
>  then delete one of the buttons

How do you delete a button?

**Comment by JMidd91** [comment]
oh i just select it in the dev tools and hit delete - 

![image](https://user-images.githubusercontent.com/38964969/46392872-d3992780-c6da-11e8-889f-a6417c39820a.png)


it simulates what i am doing in my actual project close enough :)

**Comment by Ni55aN** [comment]
JS doesn't observer a changes in DOM

**Comment by JMidd91** [comment]
i dont understand? when i delete a div, the array is adjusted to show this, its just that i cant get alight to update based on my array?

**Comment by Ni55aN** [comment]
but JS doesn't know about this. So you need to update info about buttons manually

**Comment by JMidd91** [comment]
yea thats what i dont understand, because calling 

```javascript```
_alight.scan()
```
should then make this template create a new list right?

```javascript

`<select al-value="selectedId" @click="change($event)"><option al-repeat="item in list" >{{item}}</option></select>`

```

**Comment by Ni55aN** [comment]
`var ctrl = new DropDownControl(this.editor, "button", Array.from(buttonsElement).map(b => b.innerText), () => {});` does not receive updated list (the third argument)

**Comment by JMidd91** [comment]
aaah ok, thanks for pointing that out will try to figure it out from here :)
