### ISSUE TITLE
Question regarding dinamically added controls

### ISSUE THREAD

**Issue by jprustv** [retejs/rete#183]
Hello,

I'm trying to create a component with a dynamic list of TextControl. 

To give you a context..

`var ctrl = new ButtonControl(this.editor, 'btnAddTextControl', 'Add TextControl', handleAddClick);`
This creates a button passing a callback function that will actually add the Controls.

This is the function called when I click the button:

```
function handleAddClick(emitter, key){
      var dynctrl = new TextControl(emitter, 'txtcontrol_' + key, '');
      node.addControl(dynctrl);
}
```

So basically, when I load the editor I have this:
![image](https://user-images.githubusercontent.com/11440704/46558254-dd7d7f00-c8c2-11e8-8873-0f0457d96d8a.png)

If I click the button, new controls are created:
![image](https://user-images.githubusercontent.com/11440704/46558555-d86cff80-c8c3-11e8-8a22-bd5574887044.png)

Then I save the editor.toJSON() so I can load it when I refresh the page.

The problem is: When I refresh the page, the dynamically added controls are not loaded (the node appears like in the first screenshot), even though they are in the **editor.nodes.[*nodeNumber*].data** (checked on console).

Is there something I'm missing or.. how would you do that?

**Comment by Ni55aN** [comment]
> When I refresh the page, the dynamically added controls are not loaded

you need to save all persistent data to `node.data`, and restore controls in `builder()`. (`toJSON()` doesn't save such information about the node, it must be in the builder, or saved manually in the node)

**Comment by jprustv** [comment]
Yea, that makes sense. Thanks for the answer.

**Comment by Ni55aN** [comment]
With one amendment: it is better to save such data to `node.meta`
