### ISSUE TITLE
[q][old library with d3] How to add submenu to context menu?

### ISSUE THREAD

**Issue by trsh** [retejs/rete#184]
Cant figure out looking at defs:

```
export class ContextMenu {
  visible : number;
  x : number;
  y : number;

  constructor(items : any, searchBar?: boolean)

  private bindTemplate(t);

  private searchItems(filter?: string);
  haveSubitems(item);
  isVisible();
  show(x : number, y : number, items?: any, searchBar?: boolean, onClick?: () => {});
  hide();
}
```

**Comment by trsh** [comment]
Ahh it can go only 2 levels?

**Comment by Ni55aN** [comment]
Do you use a 0.7.4? 
Context menu for previous versions allows a nested items on 2 level. In v1.0.0 the `context-menu-plugin` is quite simple and had only 1 level, but will be modified in future (I'm going to replace alight with vue.js)

**Comment by trsh** [comment]
0.7.4 yes. Rete must go at least Beta x
