### ISSUE TITLE
Is there a Vue example with components?

### ISSUE THREAD

**Issue by biapar** [retejs/rete#187]
Is there a Vue example with components?

**Comment by Ni55aN** [comment]
Yes, one of them: [rete.js.org/ecosystem/package](https://github.com/retejs/rete.js.org/tree/master/src/rete/components/ecosystem/package)

**Comment by biapar** [comment]
Thanks.

**Comment by iKlsR** [comment]
If I try to use `document.querySelector("#rete")` from inside `<script>` to grab the div from `<template>` it causes issues and I have to use `mounted()` to wait for the element to become available. Probably me doing something wrong but a barebones sample using a project generated with vue cli would be appreciated.
