### ISSUE TITLE
How to elaborate and execute data flow on server side and as background process?

### ISSUE THREAD

**Issue by biapar** [retejs/rete#188]
How to elaborate and execute data flow on server side and as background process?

**Comment by Ni55aN** [comment]
```js
const { Engine, Component } = require('rete/build/rete-engine.min');

var engine = new Engine('name@0.0.0');
engine.register(new YourComponent());

engine.process({
    id: 'name@0.0.0',
    nodes: {
        1: {
            name: 'component1',
            id: 1,
            inputs: [],
            outputs: []
        }
    }
}).then(console.log)
```

> as background process

You can run node.js using `forever` or `pm2`

**Comment by biapar** [comment]
Thanks. Is there a "name@0.0.0" for each flow? how to do with node?

**Comment by Ni55aN** [comment]
The ID is needed for consistency of the data and your editor.
For example, data from the previous version of your editor may be incompatible and will be processed incorrectly. Therefore, it is necessary to know the data versions and carry out the appropriate migrations

**Comment by biapar** [comment]
And in the case I've two different people ? They cannot share anything because they see only their data.
