### ISSUE TITLE
Group plugin

### ISSUE THREAD

**Issue by Linkupdated** [retejs/rete#189]
First of all, I love this plugin and been using it since d3-node-editor.

Just upgraded to the new architecture. Many hours of converting my existing 80 components and converting the json saved.

I was wondering about the group feature and if there was something possible and or making a plugins since now its more modular. Maybe even folder.

Also the main reason I upgraded is the new version feature fixed backgrounds and illimited space. The old translate functions were limited for size.

Thanks!

**Comment by Ni55aN** [comment]
Yes, I was thinking about Group feature, but I do not have time to implement this.

Advantageously, it should be named as Frames (since they should not affect the processing of nodes), and probably it should be combined with the [comment-plugin](https://github.com/retejs/comment-plugin)

**Comment by Ni55aN** [comment]
This feature was implemented in [comment-plugin](https://rete.readthedocs.io/en/latest/Plugins/#comment).

![](https://rete.readthedocs.io/en/latest/assets/comment.png)

I have investigated exist solutions (UE4, Substance designer) and found that similar feature represented in form of a comment. The main reasons: it shouldn't affect the processing of the scheme, it only helps the creator of this scheme
