### ISSUE TITLE
Any way to just use the views and ignore the engine?

### ISSUE THREAD

**Issue by rszemplinski** [retejs/rete#191]
Hi @Ni55aN ,

I just stumbled across this tool and would love to use this in my project. The only problem being that I have my own engine that is run elsewhere and would really only like to use the UI you've constructed. Would I be able to just install the package and use the graph and nodes or is the engine somehow tightly integrated into it? Or, would it just be easier to just fork the project and extract out the engine from the rest of the tool?

Thanks and great work!

**Comment by Ni55aN** [comment]
Yes, Engine and Editor are independent of each other
