### ISSUE TITLE
Moving Multiple Nodes

### ISSUE THREAD

**Issue by Linkupdated** [retejs/rete#192]
I was wondering if it was still possible to move multiple node, like before in 0.7.4. 

You can still select multiple nodes so that's perfect but how would I add the feature like holding SHIFT after having selected the nodes. Thanks.

**Comment by Linkupdated** [comment]
Cool, if I can do anything to help ask me!

**Comment by Ni55aN** [comment]
This feature is available in `v1.0.0-beta.1`

**Comment by Ni55aN** [comment]
Updated example: https://codepen.io/Ni55aN/pen/xzgQYq
