### ISSUE TITLE
Creating node at the center position in my view ...

### ISSUE THREAD

**Issue by teratux** [retejs/rete#193]
Hello ... tremendous job on ReteJS, I've managed to create a mathematical formula editor for my clients.  Reading through the history I found some interesting improvement points I'm going to include like comments, and snapping the components in place.  I'm also going to try to change the styling of my components later on, so any help in this direction is also welcome.

One thing I didn't manage to find was how to include components in the center position of the current viewing position of my editor.  I have a component palette in my editor view, as you can see [here](https://snag.gy/gVLOo0.jpg), and all components get added in the same fixed position no matter where the user is centered.  When the design gets too big it's a hassle the need to return to that fixed position and drag the component to it's place.  From the attached image you can see what an issue it is.  This is the code:

```
    n1 = await components[global_formula_component_index['getarrayval']].createNode();

//    n1.position = [80, 200];

    editor.addNode(n1);
    editor.view.resize();
    editor.trigger('process');
```
as you can see I tried also with a position of 80,200 to see if it was the relative position in the viewport but I didn't manage to get the expected behavior.

The closest issue I managed to find was #38 but it didn't refer to the result I'm trying to achieve.

Thanks in advance ...

**Comment by Ni55aN** [comment]
Have you tried a Drag & Drop?
You could take mouse coordinates from `editor.view.area.mouse`

**Comment by teratux** [comment]
The component palette for the moment has only buttons.  The screenshot is a bit misleading because a more natural behavior would be to drag n' drop the elements onto the canvas, maybe in an improved later version.  For the moment, every time the user clicks a button representing the desired component, internally I add it to the editor without specifying a position.  Ideally I would like it to appear centered.

**Comment by teratux** [comment]
It totally works !!! ... Thanks, great job

**Comment by teratux** [comment]
I guess it's no longer an issue ...

**Comment by teratux** [comment]
Check Stoliarov's second answer. That's what I used and adapted

**Comment by maya-gawinowski** [comment]
Hey,
@Ni55aN 

What would be an updated version of this with Rete.js V2 ?

**Comment by Ni55aN** [comment]
@maya-gawinowski https://retejs.org/docs/faq#viewport-center
