### ISSUE TITLE
update control of particular node

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#194]
Hi,

I am struggling to find a way to updated a canvas that is within a control of a node when either process is triggered, or a connection is created or removed.

now obviously i can do this - 

editor.on("process connectioncreated connectionremoved", async () => {
    //DO MY UPDATES TO MY NODE CONTROL
});

but this happens to every node, is there a way to find which node this happened to and trigger that nodes control to update? 

i feel that i have read a similar question to this before but i cant find it! 

many thanks!

**Comment by Ni55aN** [comment]
What render plugin do you using?

**Comment by Ni55aN** [comment]
You can update controls of the current processed node inside `worker()`

```js
worker(node, inputs, outputs) {
  this.editor.nodes.find(n => n.id === node.id).controls.get('canvas').doSmth();
}
```

**Comment by JMidd91** [comment]
> What render plugin do you using?

mostly alight, a couple use js

**Comment by Ni55aN** [comment]
Any success? Did you get an instance of Control class using `node.controls.get()` and call any method?

**Comment by JMidd91** [comment]
sorry forgot to reply to this! yes this worked a charm :)
