### ISSUE TITLE
Initial values on node creation

### ISSUE THREAD

**Issue by axvm** [retejs/rete#195]
Hi,
I can't to figure out how to assign initial values to node on creation in editor. Is it possible to assign initial values to node in `rete.js` out of box or I need to implement it by myself i.e. on `nodecreated` event or something like this?

**Comment by Ni55aN** [comment]
Hi, you can assign data before mounting of particular node

```js
builder(node) {
 node.data = {};
}
```

or before/after creation of any  node
```js
editor.on('nodecreate', node => node.data)
// or
editor.on('nodecreated', node => node.data)
// but you also need to update view manually (depends of your control implementation)
```

**Comment by Ni55aN** [comment]
Входные и выходные сокеты можно менять динамически, но их порядок будет согласно времени добавления.

Можно внутри builder'а добавить что-то подобное для проверки:
```js
      
        setTimeout(() => {
          inp2.connections.map(c => this.editor.removeConnection(c));
          node.removeInput(inp2);
          setTimeout(() => {
            node.addInput(inp2);
            node.update();
          },2000);
          node.update();
        }, 2000);
```

но пока что это не работает корректно, позже попробую выяснить причину 

> Ты сделал отличную работу, библиотечка огонь и код чистый. Спасибо за труд.

Спасибо, очень приятно!
