### ISSUE TITLE
Prevent drag

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#196]
Hey

I remember in the D3NE codepen examples you had a `preventDefault` or something similar preventing the node from being dragged when you were in an input field for example, but i cant find any sign of that in your new code examples and wondered if that was possible? everything i try from the internet doesnt work so far so I assume the fix is more specific to how you have built things. I am assuming the fix wont be that different from how it was in D3NE but i cant find the old examples any more.

many thanks 

EDIT: 

ok found the fix in an old backup i forgot about, it is this right? -  

```javascript
el.addEventListener("mousedown", function(e){
    e.stopPropagation()
});

```

if so i cant figure out where to put it in the component / control, especially when the control is built with alight. works perfect for a JS rendered node

**Comment by Ni55aN** [comment]
In alight you can [stop an event propagation](https://angular-light.readthedocs.io/en/latest/events.html?highlight=stop%20propagation)

```html
<input @mousedown.stop="">
```

In vue-render-plugin there is a same "stopPropagation"

**Comment by JMidd91** [comment]
awesome thanks
