### ISSUE TITLE
Add key to Constructor in 

### ISSUE THREAD

**Issue by mikecowgill** [retejs/rete#197]
In the last update there is a check for the key in the constructor of a Control but the index.d.ts doesn't have the key in the constructor. I adjusted it locally but can you update it like below?

```typescript
export abstract class Control {

  parent: Input | Node;
  constructor(key: string);

  getNode();
  getData(key: string);

  putData(key: string, data: any);
}
```

**Comment by Ni55aN** [comment]
Ok, I'll fix it.

By the way, feel free to make a Pull Request

**Comment by mikecowgill** [comment]
PR created. Thanks for creating this great library!

**Comment by Ni55aN** [comment]
Thanks!
