### ISSUE TITLE
Rete.js + Electron

### ISSUE THREAD

**Issue by soloroman** [retejs/rete#198]
Does Electron supports Rete.js?
How could i run rete without errors?
Electron console:
`Uncaught TypeError: Cannot read property 'makeInstance' of undefined
    at Object.install (index.js:11)
    at e.value (context.js:16)
    at scheme.js:142`
scheme.js is fully copied from [here](https://codepen.io/Ni55aN/pen/MOYPEz) (just tried to run it in electron)
and i don't know where does it found index.js...
Can anyone help to solve it? (i am a bit newbie)

**Comment by Ni55aN** [comment]
Please use the latest example with `vue-render-plugin`: https://codepen.io/Ni55aN/pen/xzgQYq
Just replace `alight render plugin`

**Comment by soloroman** [comment]
@Ni55aN 
Now another error. I could share the code if needed.
`Uncaught (in promise) TypeError: Cannot read property 'makeInstance' of undefined
    at t.value (context-menu.js:33)
    at new t (context-menu.js:25)
    at Object.install (index.js:38)
    at NodeEditor.use (context.js:19)
    at index.js:94
    at index.js:130`

**Comment by Ni55aN** [comment]
Have you removed AlightRenderPlugin?

**Comment by soloroman** [comment]
@Ni55aN
Yes, but nothing changed(

**Comment by Ni55aN** [comment]
I got it. Seems like you included context-menu-plugin via <script> and forgot a `alight` library.
Anyway, the latest version of context menu use a Vue.js, but you still need to include dependencies correctly (like ES6 modules using WebPack, Parcel, etc)

**Comment by soloroman** [comment]
@Ni55aN 
Oh, thx a lot!
Solved it.
That's how to include dependencies:
`
<script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>


<script src='https://cdn.jsdelivr.net/npm/rete@1.0.0-beta.3/build/rete.debug.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/rete-vue-render-plugin@0.2.1/build/vue-render-plugin.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/rete-connection-plugin@0.2.2/build/connection-plugin.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/alight@0.14.1/alight.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/rete-context-menu-plugin@0.2.1/build/context-menu-plugin.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/rete-area-plugin@0.1.5/build/area-plugin.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/rete-comment-plugin@0.2.0/build/comment-plugin.min.js'></script>


<script>if (window.module) module = window.module;</script>`
