### ISSUE TITLE
Halt the processing in engine (pending state)

### ISSUE THREAD

**Issue by kaz138** [retejs/rete#200]
Is it possible to use a pending state in engine when processing the flow (for use cases when I want to delay certain amount of time, or indefinitely i.e. for implementing a state machine)? Mainly try to understand the implication of this pending execution at runtime.

**Comment by Ni55aN** [comment]
> for use cases when I want to delay certain amount of time

The Engine can process async workers, but it should not keep state. Moreover, the nodes are processed from left to right.

You can create special nodes that will store your states outside the nodes.
