### ISSUE TITLE
Context menu 2.0 

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#202]
just implemented the new context menu, its awesome! 

seems to work as intended but i get an error when ever i interact with it - 

![image](https://user-images.githubusercontent.com/38964969/47480866-b06d1e00-d829-11e8-9019-11a1c264a602.png)

just thought id let you know, although you may already have known, unless its me with a user error again lol

**Comment by Ni55aN** [comment]
You need to insert lodash to your html page

**Comment by JMidd91** [comment]
core or full build?

**Comment by Ni55aN** [comment]
What build system do you use?

**Comment by JMidd91** [comment]
not sure what you mean? i was just looking on [here ](https://lodash.com/)and it had two versions? 

unless you mean how do i make my app, just via a normal editor including scripts etc. no npm or anything
