### ISSUE TITLE
[question] What are the reasons rete isn't written in typescript?

### ISSUE THREAD

**Issue by dkipp** [retejs/rete#203]
I'm excited about rete, I was looking every once in a while for something like it.
While I was searching, I somehow assumed that a library like this will be written in typescript.

The code looks great, you obviously know what you are doing, so what are your reasons for plain javascript?

I searched, but couldn't find a place where you already wrote about your decision.

Thanks for sharing your work

**Comment by Ni55aN** [comment]
> so what are your reasons for plain javascript?

JavaScript allows to code faster than TypeScript. Moreover, the code base does not increase so much, so static typing is not really needed

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/260
