### ISSUE TITLE
Context menu 2.0 

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#206]
having trouble understanding how to put components into different branches of the menu.

so far, my menu looks like this 🤣 

![image](https://user-images.githubusercontent.com/38964969/47701998-8e054700-dc13-11e8-9188-0762dff88d04.png)

by doing this - 

```javascript
matEditor.use(ContextMenuPlugin, {
    searchBar: true,
    allocate(component) { return ["thing","thing2", "thing3", "thing4"]}
});
```

am i missing something blindingly obvious? 

many thanks as usual!

**Comment by Ni55aN** [comment]
You can allocate different paths according to the component name or other props.

Example:

https://github.com/Ni55aN/allmatter/blob/dev/src/components/editor/NodeEditor.vue#L100
https://github.com/Ni55aN/allmatter/blob/dev/src/editor/components/math/add.js#L8

**Comment by JMidd91** [comment]
oooh its assigned in the component itself. ok thats great!

**Comment by JMidd91** [comment]
Perfect. thanks!

**Comment by Ni55aN** [comment]
> oooh its assigned in the component itself.

In this case, but not necessarily

`allocate` allows to generate path more flexible. For example, based on component's name

```js
allocate(component) { return component.name.startsWith('Input') ? ['Input'] : [] }
```

**Comment by JMidd91** [comment]
aah ok so this way you could programmatically do an alphabetical menu / submenu's
