### ISSUE TITLE
context menu 2.0

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#207]
so ive noticed there is more of a delay on how long it takes for the menu to disappear when you mouse off, can we/you expose a variable for the time this takes? so if we want to speed this up / slow it down?

so it could appear here maybe - 

```javascript
matEditor.use(ContextMenuPlugin, {
    searchBar: true,
    hideTime: 1000,
    allocate(component) { 
        return component.allocation || [];
    }
});
```

**Comment by JMidd91** [comment]
id submit it myself but i cant get my head around the way you code. im still basic haha

**Comment by Ni55aN** [comment]
Done [v0.2.3](https://www.npmjs.com/package/rete-context-menu-plugin/v/0.2.3)

**Comment by JMidd91** [comment]
badass, thank you!
