### ISSUE TITLE
[question] touch event of smartphone

### ISSUE THREAD

**Issue by hirokuni** [retejs/rete#208]
Hi

When  I tried that sample program [Flow-based programming](https://codepen.io/Ni55aN/pen/xzgQYq) on an android smartphone, I could't do some actions on node with touch on a screen. Touch event seems not to be handled well. I could do them with mouse connected to the mobile phone via USB.

Is there any way to control node (following actions) with touch on a screen?

I can't following actions with touch
- Delete node
- Connect sockets with line
- Can't delete Context Menu when it is appeared once

**Comment by Ni55aN** [comment]
> - Delete node
> - Connect sockets with line

This features are working on touch screen (just tested on my Android).

> - Can't delete Context Menu when it is appeared once

It'll be fixed (temporary solution - click on any item in menu)

**Comment by Ni55aN** [comment]
Fixed in context-menu-plugin@0.2.4

**Comment by hirokuni** [comment]
@Ni55aN 

> Delete node

Could you tell me the step how I can delete node with touch? 
In mouse control, the deletion can be done with menu on a node (The menu is shown with mouse click).


> Connect sockets with line

No problem. I confirmed that touching each socket between nodes can make a line.

**Comment by Ni55aN** [comment]
According to the standard, the context menu on the touch screens is called up by an  long tap

**Comment by hirokuni** [comment]
Thank you. I could delete node.
