### ISSUE TITLE
HTML tags in name input, output and node name?

### ISSUE THREAD

**Issue by saalaus** [retejs/rete#209]
Hello, how do I use HTML tags in name input, output and node name? If you just paste HTML tags, then they are inserted simply as plain text

Example: I want to make the text using HTML

![default](https://user-images.githubusercontent.com/37474917/47718073-44474b80-dc69-11e8-8617-86cece7bf4e9.png)

**Comment by Ni55aN** [comment]
Hello, you need a custom node (if you are using vue-render-plugin)

1. Copy and modify [default Node.vue](https://github.com/retejs/vue-render-plugin/blob/master/src/Node.vue) 

2. Define property in Rete.Component

```js
import Node from './Node.vue';

////
constructor() {
  super("Comp");
  this.data.component = Node;
}
```

3. Setup vue-loader
