### ISSUE TITLE
code plugin

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#210]
Hey,

in the code plugin, I noticed it makes the const name from the node name. but if the node name has a space in it, till break the const name in the source code, could you replace spaces with underscores when creating the source code? or even just remove the spaces

**Comment by Ni55aN** [comment]
Please create issues in the related repo https://github.com/retejs/code-plugin/issues

**Comment by Ni55aN** [comment]
https://github.com/retejs/code-plugin/issues/2

**Comment by Ni55aN** [comment]
By the way, that plugin is not stable yet and have some other issues

**Comment by JMidd91** [comment]
Yea I figured so, just thought I'd check it out :)

**Comment by Ni55aN** [comment]
v0.1.1 with the fix is available
