### ISSUE TITLE
Editable node name

### ISSUE THREAD

**Issue by jtwnel** [retejs/rete#211]
Hi, 

Is there a way to make a nodes name editable? or to insert another field on the node?

Thanks!

**Comment by Ni55aN** [comment]
"Editable" by user (who create schemes) or developer (who develop the editor)?

Maybe you need a custom[ node.vue](https://github.com/retejs/rete/issues/209#issuecomment-434406096)

**Comment by jtwnel** [comment]
"Editable by user", I tried to make a custom node.vue but I dont understand the template, where are the html tags? all I saw where css classes inside it.

**Comment by Ni55aN** [comment]
> where are the html tags?

This is an ordinary Vue.js template, not html page. All you need is a some knowledge of html/pug and Vue.js

Example:

```pug
 .title(v-if="!editTitle") {{node.name}}
input.title(v-else, :value="node.name", @change="setName")
```
