### ISSUE TITLE
minimize nodes

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#212]
I seem to remember this being asked but cant find the post - 

on each node there would be an arrow or something in the top right that you click and it merges all inputs/outputs into one / ontop of each other so the node can reduce in size whilst retaining the connections. and then if you click the arrow it would restore to full size.

was this suggested as a feature or was the post about a user going to build it themselves? this would be a pretty dope thing to have as I have some nodes with 17 inputs.

**Comment by Ni55aN** [comment]
[Custom node](https://github.com/retejs/rete/issues/209#issuecomment-434406096).

You can add button (arrow) after `.title` and wrap other tags to a container and hide/show it by clicking on the arrow

**Comment by JMidd91** [comment]
nice thanks
