### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by HamedFathi** [retejs/rete#213]
I should say thanks for your awesome work.

Is it possible to change the UI? Is it fully themeable?

**Comment by JMidd91** [comment]
Hey, 

yup its fully customisable via css, check out [this](https://rete.js.org/#/examples/customization)

hope that helps!

**Comment by Ni55aN** [comment]
The view contains nodes, connections, and a region. All of them are controlled separately by plugins and fully customized

**Comment by Githamza** [comment]
a code example to do this ?

**Comment by Ni55aN** [comment]
@Githamza 
- [vue render plugin](https://codepen.io/Ni55aN/pen/GGrzYE?editors=0010)
- [react render plugin](https://codesandbox.io/s/retejs-react-render-t899c)
- [area plugin (background cutmization)](https://github.com/retejs/rete.js.org/blob/master/src/components/Examples/list/customization/index.js#L47)
- [connections styles](https://github.com/retejs/rete.js.org/blob/master/src/components/Examples/list/customization/style.sass#L23)

**Comment by Githamza** [comment]
Can you give an example with an angular app ?
https://stackblitz.com/edit/github-rete

**Comment by fdfdsfdshfds** [comment]
Hello @Ni55aN how can I customise when using browser environment? I know it's better to import but my situation I can't.
