### ISSUE TITLE
Hi, what could this function do?

### ISSUE THREAD

**Issue by juliandavidmr** [retejs/rete#214]
https://github.com/retejs/rete/blob/54af9dbbf63d32fd66df45a4e8f52810a626f1c9/src/component.js#L14

**Comment by Ni55aN** [comment]
This function must create and add inputs/controls/outputs to the Node instance

**Comment by juliandavidmr** [comment]
I guess it's similar to `build(node: Node)` function. right?

**Comment by Ni55aN** [comment]
The `build()` is a decorator over `builder()`
