### ISSUE TITLE
I have a connection problem

### ISSUE THREAD

**Issue by saalaus** [retejs/rete#216]
I have a connection problem. What caused this to happen?

I noticed that everything is fine in the browser Firefox, and in a browser Google Chrome like this:
![image](https://user-images.githubusercontent.com/37474917/47961455-209b5100-e02d-11e8-8bef-d7152401eb38.png)

**Comment by Ni55aN** [comment]
What versions of rete and rete-connection-plugin are you using?

**Comment by saalaus** [comment]
Final version

**Comment by Ni55aN** [comment]
Cannot reproduce on https://codepen.io/Ni55aN/pen/xzgQYq
Can you share an example on codesandbox/jsfiddle?

**Comment by saalaus** [comment]
if i use 0.2.1 version connection plugin,then everything is fine

**Comment by Ni55aN** [comment]
Does the
```css
.connection {
 width: auto;
 height: auto;
}
```

fix it?

**Comment by saalaus** [comment]
yes, thanks

**Comment by Ni55aN** [comment]
It's quite strange behavior. The SVG container for each connection takes up some space and interferes with a click on comments (comment-plugin). 

The solution was to reduce its sizes to 1px, but then on the webkit the internal paths were displayed incorrectly. 
The next solution is to increase the size to 12px, and then everything was displayed correctly. 

Can you show what styles svg accepts for connections in devtools?

**Comment by saalaus** [comment]
![image](https://user-images.githubusercontent.com/37474917/47985960-19437880-e0fd-11e8-9eea-c9ecac357476.png)
![image](https://user-images.githubusercontent.com/37474917/47985975-252f3a80-e0fd-11e8-8d4b-117095f495ce.png)

**Comment by Ni55aN** [comment]
Is there the same issue at https://codepen.io/Ni55aN/pen/xzgQYq from your side?

**Comment by saalaus** [comment]
No

**Comment by Ni55aN** [comment]
> The next solution is to increase the size to 12px, and then everything was displayed correctly.

https://github.com/retejs/connection-plugin/commit/ce25976913c9fec679403cace4fddf6730f08cab
