### ISSUE TITLE
Force view update

### ISSUE THREAD

**Issue by SkinyMonkey** [retejs/rete#217]
Hi,

I'm working on a project where I have to be able to add inputs and outputs on the fly for some nodes.
The problem is : when I dynamically add an output or an input on a node, it does not appear until I click on a node.

How would one force the update of the editor to avoid that behaviour?

Thank you.

**Comment by Ni55aN** [comment]
`node.update()` (when using a `rete-vue-render-plugin`)

**Comment by SkinyMonkey** [comment]
Damn, seems pretty obvious now that you've said it.

I'll try, thank you!
