### ISSUE TITLE
Performance issues for large nets

### ISSUE THREAD

**Issue by LorenzoBernaschina** [retejs/rete#221]
When I have around 40-50 nodes on the screen the editor becomes very slow (for example it takes 30 seconds to do a simple copy-paste) and sometimes it crashes.

**Comment by Ni55aN** [comment]
Is the example on codesandbox/jsfiddle? What the time and functions a profiler shows?

**Comment by Ni55aN** [comment]
I have no any problems with performance in example https://codepen.io/Ni55aN/pen/xzgQYq with such number of nodes

**Comment by LorenzoBernaschina** [comment]
I am working with Angular, so it's not exactly the same example. The problems are related to the Events keypress and keydown. 
![screen shot 2018-11-13 at 11 05 42 2](https://user-images.githubusercontent.com/26749313/48406185-23d0c400-e734-11e8-9271-4466fa32f462.png)

**Comment by Ni55aN** [comment]
I had the same issue in Angular. Try this encapsulation strategy.

I think Angular's ChangeDetector goes through all the elements in the Rete.js area and spends resources on it, although he shouldn’t go there

**Comment by LorenzoBernaschina** [comment]
The side effect is that doing this way worker() doesn't work anymore (I don't need it).
Maybe the worker() call on so many nodes and performances issues are related.

**Comment by trsh** [comment]
@LorenzoBernaschina 

You have to put the listener in the right angular even, so the event attach is fired only Once. And possible detach onDestroy (not sure). Also check where you emit 'process'. It should not be a problem.

**Comment by Ni55aN** [comment]
Is the issue solved?

**Comment by testermax** [comment]
I did some test and disabled everything that triggered process event, commented out everything that had to do with the processing engine, all events, changedetection strategy onpush  on all visible components, and on the component that hosts the editor.
When I reached more or less 50 nodes, things started to get slower...and by the number of 70, it was to slow to use in my opinion. When I was dragging the nodes around, I got this stuttering effect, in addition to the context menu started to lag.
![image](https://user-images.githubusercontent.com/15218290/67676733-75dd1a80-f982-11e9-961a-a67ca0eda343.png)

Is it possible to fine tune anything else in my case? Or is there a limitation on how many nodes you can use, like I have reached the limit of max 70?

**Comment by Ni55aN** [comment]
> First Issue:
When I try to load a large network (100 nodes) from a JSON file from disk with this method:

I guess you call `engine.process()` on `nodecreated` or another event. You can prevent it by checking `editor.silent`. When `silent` is true, an event triggered while calling `fromJSON()`
```js
editor.on('connectioncreate connectionremove nodecreate noderemove', ()=>{
  if(editor.silent) return;
     
  engine.process(data);
});
```

**Comment by Ni55aN** [comment]
> Most of the time when I load this big JSON file with 100 nodes, it is being displayed reversed. I have to load it a couple of times, and then it shows correctly in the editor.

Can you provide an example on jsfiddle/codesandbox/etc?

**Comment by Ni55aN** [comment]
> Could the issue be in the angular renderer plugin?

I think the problem is in Angular itself :) When I used the vue-render plugin inside an Angular application, I had the same problem until I made the editor initializing inside `runOutsideAngular`.

Technically, you can define a custom component, detach the change detector and run it on demand.

**Comment by testermax** [comment]
@Ni55aN I didnt know about the `editor.silent` flag, and it is exactly what I wanted. 
I have implemented ` if(editor.silent) return;` in the eventhandler, and I can not reproduce the reversed displayed nodes anymore. I have not understood why this happened, and I think I will just let that go.

> Technically, you can define a custom component, detach the change detector and run it on demand.

I did create a custom node (just as the "Add" node in  the examples) and detached  the change detector, in addition to clearing out the worker logic, and this seems to be able to work more fluent with +50 in the editor than e.x the "Number" node, from the example code, which is not using a custom node. 
But there is still some stuttering when moving the nodes around, but a lot better.

**Comment by Ni55aN** [comment]
> Except from not fireing the process event, is there any other ways of slimming down?

If we are talking about FPS (transition of particular node or whole scheme), the events `updateconnection`, `nodedraged`, `nodetranslated`, etc are triggered. You can profiling it and analyze call tree. 

The main thing is that Angular is not fast itself , so it may make sense to use `runOutsideAngular` and another render plugin

**Comment by mikecowgill** [comment]
@Ni55aN Do you happen to have any examples using runOutsideAngular with the vue.js renderer? Is the idea to wrap the editor creation with runOutsideAngular, or the engine as well?

**Comment by Ni55aN** [comment]
@mikecowgill it should be enough to create NodeEditor instance inside the callback in `runOutsideAngular`

```js
this.ngZone.runOutsideAngular(() => {
    ... = new Rete.NodeEditor(...
});
```

**Comment by pwichmann** [comment]
Can someone explain to me **when exactly the flag editor.silent is true**?

I am trying to improve the performance of a large model. And this flag has the desired effect (especially when loading a model from json or loading a module) but I do not know what risks are associated with using: `if(editor.silent) return;`
I obviously need to avoid that things are not calculated correctly.

**Comment by creadicted** [comment]
I tested around with a lot of nodes. 
Setting -> changeDetection: ChangeDetectionStrategy.OnPush, on the node worked. 

```
import { Component, ChangeDetectorRef, ChangeDetectionStrategy } from '@angular/core';
import { NodeComponent, NodeService } from 'rete-angular-render-plugin';

@Component({
  templateUrl: './node.component.html',
  styleUrls: ['./node.component.sass'],
  providers: [NodeService],
  changeDetection: ChangeDetectionStrategy.OnPush,

})
export class MyNodeComponent extends NodeComponent {
  constructor(protected service: NodeService, protected cdr: ChangeDetectorRef) {
    super(service, cdr);
  }
}

```

**Comment by bennettluo** [comment]
@Ni55aN  Hi, I try to use **editor.silent** to determine whether it should be prevented in the listener callback, however it still outputs the warning (on attachment) when nodes hanged at the first render. 

![use-abort-to-force-it-to-complete](https://user-images.githubusercontent.com/14840837/99023925-8fa6cb00-25a0-11eb-88fb-61078e14eda7.png)

Is there any workaround to avoid causing some performance issue?

**Comment by bennettluo** [comment]
@Ni55aN Hi, I try to use editor.silent to determine whether it should be prevented in the listener callback, however it still outputs the warning (on attachment) when nodes hanged at the first render.

`vendors~rete.31fc3529.js:2 The process is busy and has not been restarted.
                Use abort() to force it to complete`

Is there any workaround to avoid causing some performance issue?

**Comment by bennettluo** [comment]
@Ni55aN Hi, I try to use `editor.silent` to determine whether it should be prevented in the listener callback, however it still outputs the warning (on attachment) when nodes hanged at the first render.

vendors~rete.31fc3529.js:2 The process is busy and has not been restarted. Use abort() to force it to complete

Is there any workaround to avoid causing some performance issue?

**Comment by bennettluo** [comment]
@Ni55aN Hi, I try to use `editor.silent` to determine whether it should be prevented in the listener callback, however it still outputs the warning (on attachment) when nodes hanged at the first render.

`vendors~rete.31fc3529.js:2 The process is busy and has not been restarted. Use abort() to force it to complete`

Is there any workaround to avoid causing some performance issue?

**Comment by bennettluo** [comment]
@Ni55aN Hi, I try to use `editor.silent` to determine whether it should be prevented in the listener callback, however it still outputs the warning when nodes hanged at the first render.

`vendors~rete.31fc3529.js:2 The process is busy and has not been restarted. Use abort() to force it to complete`

Is there any workaround to avoid causing some performance issues?

**Comment by unclexo** [comment]
If you call `abort()` and `process()` methods synchronously then, the error saying `process is busy` goes away but keep in mind it loses the asynchronicity. 
  
```
  // Aborts and proceses data
  editor.on(
    'process nodecreated noderemoved connectioncreated connectionremoved', 
    () => {
      if(editor.silent) {
        return false
      }

      compile()
    }
  )

function compile() {
    engine.abort()
    engine.process(editor.toJSON())
  }
```

**Comment by barnesew** [comment]
I had a very similar performance issue running Rete and Angular together. I attempted the fixes suggested here including changing the detection strategy to `OnPush` as well as trying `runOutsideAngular` but I could get neither one to work.

After running the JavaScript profiler, I discovered the problem was coming from the "pointermove" event triggering change detection at a high rate. Zonejs watches all the events and triggers the change detector anyway, even if you run it outside of Angular (As far as I could tell).

My solution was to do what it says to do in the polyfills.ts file about disabling zonejs patching for specific events. Here is the code I used:
```typescript
(window as any).__zone_symbol__UNPATCHED_EVENTS = [
  'pointermove',
  'pointerover',
  'pointerout'
];
```

It's important to note, this code must come BEFORE your import zonejs usually in the line `import 'zone.js/dist/zone';`.

Hope this helps anyone who comes after me! Tested against Angular v13.

**Comment by SvetlanaIo** [comment]
@barnesew, you're wonderful!
I think I should make one clarification.
In my case, it was required to move this code to a separate file `rete-unpatched-events.ts` and include this file to `polyfills.ts`.

```
// rete-unpatched-events.ts
(window as any).__zone_symbol__UNPATCHED_EVENTS = [
  'pointermove',
  'pointerover',
  'pointerout'
];
```
```
// polyfills.ts
import "./rete-unpatched-events";
import 'zone.js/dist/zone'; 
```

**Comment by Ni55aN** [comment]
If anyone is wondering how to display thousands of nodes, check out this example: https://retejs.org/examples/lod-gpu/
