### ISSUE TITLE
Unable to remove connections on removing socket

### ISSUE THREAD

**Issue by atifmustaffa** [retejs/rete#222]
Hi,
I have an issue on removing socket dynamically when the socket's multiConns is set to true for multiple connections.

I'm not sure if the issue is on my side or it's a bug. But when I tried this example: http://jsfiddle.net/Ni55aN/vmxdcLbq/61/ and recreate the problem I get the same error. It similar to [#150](https://github.com/retejs/rete/issues/150)

What I did:
Enable multiConn:
`var inp2 = new Rete.Input("Chips", chipsSocket, true);`

Connect multi connections on 'Chips' socket:
![image](https://user-images.githubusercontent.com/26905983/48386266-4d85ed00-e72c-11e8-8af0-32722d3f897a.png)

Uncheck 'Chips' socket:
![image](https://user-images.githubusercontent.com/26905983/48386371-b40b0b00-e72c-11e8-9029-e58c186cf5b6.png)

and when I console log the connections, I noticed that all connections are not removed
```
console.log('conns before', input.connections);
input.connections.map(editor.removeConnection.bind(editor));
console.log('conns after', input.connections);
node.removeInput(input);
```
![image](https://user-images.githubusercontent.com/26905983/48386489-1e23b000-e72d-11e8-9213-518ddbcccb12.png)

I used the same method on my code, and this error is thrown
![image](https://user-images.githubusercontent.com/26905983/48386858-65f70700-e72e-11e8-8181-76f1a472dc3a.png)

Am I missing something?

**Comment by JMidd91** [comment]
hey try adding this just after `removeInput` - 

```javascript 
node._alight.scan();
```

**Comment by atifmustaffa** [comment]
I've tried that and I think that does not solve the issue. Also, if you look at the example I mentioned `node._alight.scan()` is already called after `node.removeInput(input)`

**Comment by JMidd91** [comment]
yea and it works in that example for me using chrome

**Comment by atifmustaffa** [comment]
Same, Chrome Version 70.0.3538.102 (Official Build)

**Comment by Ni55aN** [comment]
Hi! I found the issue. `.map` refers to the particular array `input.connections` in memory, therefore after removing of first element `.length` == 1 and `.map` doesn't go to the second iteration.

Solution - copy array

```js
input.connections.slice()
```

**Comment by atifmustaffa** [comment]
Great! It works now. Thank you
