### ISSUE TITLE
Wrong definition of callback in Selected class

### ISSUE THREAD

**Issue by marchycat** [retejs/rete#223]
I want to remove selected nodes but only if they names aren't specific ones.
When I try to call
```
this.editor.selected.each((x)=>{
      if(x.name != "Start" && x.name != "Finish"){this.editor.removeNode(x);}
    });
```
I am receiving this: error TS2345: Argument of type '(x: any) => void' is not assignable to parameter of type '() => {}'.

each definition must be something like `each(callback: (node) => {});` or `each(callback: (node) => void);`

**Comment by juliandavidmr** [comment]
Updated, See [255](https://github.com/retejs/rete/pull/225)
