### ISSUE TITLE
createNode()

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#224]
hey

just looking at [this example](https://codepen.io/Ni55aN/pen/xzgQYq?editors=0010) and the createNode() function.

so in this - 

```javascript
var n1 = await components[0].createNode({num: 2});
```

the part that is {num: 2} 

is that num from data, or for component? 

when I am trying to replicate into my own project, i get this error - 

![image](https://user-images.githubusercontent.com/38964969/48401902-24605f00-e722-11e8-8d58-1f892607c882.png)

cant seem to get rid of it at the moment.

**Comment by JMidd91** [comment]
nvm... dumb moment...

`components is not defined` .... forgot i named it something else!

**Comment by JMidd91** [comment]
ok so now my question is back to the first part, what is the createNode() talking to ? as num is referenced in multiple places in the example. 

is it talking to node.data.num or the control key labeled num? (which are sort of the same thing i guess)

**Comment by Ni55aN** [comment]
> is it talking to node.data.num or the control key labeled num

The first one

**Comment by JMidd91** [comment]
thanks!
