### ISSUE TITLE
[FR] Smoother moving nodes improvements

### ISSUE THREAD

**Issue by trsh** [retejs/rete#227]
Whenever moving html objects should use translate3d instead of translate, because it automatically uses GPU power if available. The z coordinate can just be always 0.

Another trick is adding translateZ(0)! 

This can be checked in development rendering tab. The moved node is being repainted on every move.

**Comment by trsh** [comment]
Did and experiment, and replaced moving with:

`this.el.style.transform = `translate3d(${this.node.position[0]}px, ${this.node.position[1]}px, 0px)`;`

The problem is that it gets blurry, and ideally on move it should be `translate3d` and when stops, back to `translate`. Then is is some crap that happens with svg connection goes out of some mystical gpu layer. So not as an easy job as I thought :(

![qqqqqqqqqqqqqqqqqqqqqqqqqqqqq](https://user-images.githubusercontent.com/3727523/49157042-8d9dc000-f327-11e8-9168-9545696db423.png)

But I believe sooner or later, someone who will create a node with A LOTS of controls will complain about performance.

**Comment by Ni55aN** [comment]
Is there any progress?

**Comment by trsh** [comment]
No. Not working on this
