### ISSUE TITLE
Force connection path update

### ISSUE THREAD

**Issue by nadilas** [retejs/rete#230]
Hello guys,

based on #217 I can't get to update the connection paths. The idea is that the node i/Os are grouped and can be collapsed. 
When the collapse happens, I'd like to trigger an update of the paths so they are redrawn adjusted to the new "collapsed" state. Note: this happens if I drag the node, the paths are redrawn, but I can't find which method (in which plugin) does the trick or how to call to it.

**Comment by Ni55aN** [comment]
Hello @nadilas!
Can you share a live example ?

**Comment by nadilas** [comment]
Hi @Ni55aN, here's a quick video with a drag at the end (which triggers the update). Sorry for no code, but I wouldn't get a stripped down version this quickly onto codepen.

![path_update](https://user-images.githubusercontent.com/5324856/48952399-55bb0500-ef42-11e8-970e-1bff345fa71a.gif)

**Comment by Ni55aN** [comment]
Try this
```js
editor.view.updateConnections()
```

**Comment by nadilas** [comment]
@Ni55aN  awesome! thanks :)
