### ISSUE TITLE
Support sequential pins like UE4

### ISSUE THREAD

**Issue by quangIO** [retejs/rete#231]
Something like this would be helpful for making complicated logic (sync/async...).
![Sample Image](https://screenshotscdn.firefoxusercontent.com/images/ffcc8aa8-0da4-4753-9f37-18961b8f7f84.png)

**Comment by Ni55aN** [comment]
Do you mean visual presentation or behavior?

**Comment by quangIO** [comment]
Oop, sorry, just checked out the Messenger example. Creating a dummy socket + using event work for my use case now. Thanks for creating an awesome library!
