### ISSUE TITLE
[q?bug?] Zoom fires when not asked

### ISSUE THREAD

**Issue by trsh** [retejs/rete#233]
When clicking fast on number input up/down, scene starts to zoom. I tried to suppress different evens with `e.stopPropagation()` but that doesn't work or messed up other stuff.

**Comment by Ni55aN** [comment]
https://codepen.io/Ni55aN/pen/xzgQYq

`stopPropagation` is working on `dblclick` for input

**Comment by trsh** [comment]
Ok. Another mystery solved by @Ni55aN  :D

**Comment by Ni55aN** [comment]
Why mystery ? :D It's just JS API specification

**Comment by trsh** [comment]
@Ni55aN joke! :))))
