### ISSUE TITLE
readonly 

### ISSUE THREAD

**Issue by LorenzoBernaschina** [retejs/rete#235]
When I set readonly: true I get the connections and nodes locked but the text inside the nodes is still editable.

**Comment by Ni55aN** [comment]
Node's controls are independent of Editor. I think there is a good solution to check whether the read-only mode is turned on inside the control. I will write you later

**Comment by Ni55aN** [comment]
readonly plugin is updated

**Comment by Ni55aN** [comment]
Inside control:

```
if(this.emitter.exist('isreadonly') && editor.trigger('isreadonly')) return;
this.putData(key, value); // change value if not readonly
```
