### ISSUE TITLE
Temporary disable event handlers

### ISSUE THREAD

**Issue by dalduba** [retejs/rete#236]
I'm trying to implement undo/redo stack and found an issue. I'm using events (**editor.on()**), and in handler function I'm doing serialization with editor.toJSON(), putting this data into the history stack. But when  I'm trying to undo the data I'm using editor.fromJSON and this action spawn events which which causes pushing to the history stack again.

Is there a way to disable event handling temporary?

**Comment by Ni55aN** [comment]
Сheck the `silent` property of NodeEditor
```js
editor.on('nodecreated', node => {
  if(editor.silent) {
    // `nodecreated` was triggered while import (fromJSON())
  }
});
```

**Comment by Ni55aN** [comment]
On the other hand, are you sure that toJSON()/fromJSON() is a good way? Will the editor not slow down, as it will be re-created during each action?

**Comment by dalduba** [comment]
Putting full dump into the history stack is a simplest and most stable way. The optimizations will be later.

**Comment by Ni55aN** [comment]
The issue is solved?
