### ISSUE TITLE
es6 target

### ISSUE THREAD

**Issue by mikecowgill** [retejs/rete#237]
I have a problem using the 1.0.0 release with my angular project. Once I updated to 1.0.0 and error showed up on the constructor when calling `super('component')` for a custom component. The error is:
Class constructor Component$1 cannot be invoked without 'new'

After some research it seems to be due to rete targeting es6 now. While I tried also updating my angular project to target es6, there are some dependencies preventing me. I'm only able to target es5.

Is there a necessity to target es6 with rete? Or if you know of any other ways to resolve this, help is much appreciated.

If I revert to 1.0.0-beta.5 everything works fine.

**Comment by Ni55aN** [comment]
I found solution:

Add this to `tsconfig.json`
```json
 "include": [
    "src/**/*.ts",
    "node_modules/rete/build/*.js"
  ]
```

**Comment by Ni55aN** [comment]
There is problem when transpile to es5. 

`[...his.inputs.values(), ...this.outputs.values()]  must be `[].concat(g(this.inputs.values()),g(this.outputs.values()))`, but TS give the `this.inputs.values().concat(this.outputs.values());`. So the error `this.inputs.values(...).concat is not a function` appears

**Comment by mikecowgill** [comment]
I haven't been able to get retejs running with es5 now either. Instead I've updated my project to transpile to es6 and found a workaround for the other dependency. 
FYI the other dependecy is angular flex-layout which has an issue targeting es6 currently: https://github.com/angular/flex-layout/issues/950

**Comment by Ni55aN** [comment]
Another solution can be: import the bundle by "main" property of package.json instead of "module". Honestly I dont know if it is possible without interfering with dependency itself.

**Comment by mrwhy-orig** [comment]
Same problem here, with a fresh vue.js project. I tried to use the rete.js.org site as a guide. But when it comes to the render process, i get the same error with rete 1.0.0. With a rollback to Beta.5 it works like a charm...

**Comment by davidgraeff** [comment]
Actually I like to ask if not just es6 features but also es6 modules could be used.
Redux for example (see https://www.jsdelivr.com/package/npm/redux) exposes commonjs and also ES builds.

**Comment by d-led** [comment]
the [rete.js.org](https://github.com/retejs/rete.js.org) repo doesn't work either when upgraded to the latest version

**Comment by Ni55aN** [comment]
@d-led what exactly not working?

**Comment by d-led** [comment]
I've downloaded the repo source, then `npm i -U rete`, then `npm run serve`:

![image](https://user-images.githubusercontent.com/1716584/51692858-11a9b680-1ffe-11e9-81b8-7280fb52da85.png)

**Comment by Ni55aN** [comment]
@d-led thanks for the found issue. Now I understand the cause of the problem (this happens not only in Angular)

**Comment by d-led** [comment]
@Ni55aN superb! Glad to have helped

**Comment by Ni55aN** [comment]
@d-led you can try again with latest version. I have modified CLI to build ES modules using `preset-env`

**Comment by Ni55aN** [comment]
Related problem: https://github.com/retejs/rete-cli/issues/2 (seems to be solved)

**Comment by d-led** [comment]
the next challenge is testing. With 1.0.2 when tests are run the following can be seen:

```
    TypeError: _rete.Socket is not a constructor

      2 |
      3 | export default {
    > 4 |     num: new Socket('Number value'),
        |          ^
      5 |     action: new Socket('Action'),
      6 |     data: new Socket('Data'),
      7 |     package: new Socket('Package')

      at Object.<anonymous> (src/rete/sockets.js:4:10)
```

the file is unmodified. `import { Socket } from 'rete';` is still there

**Comment by Ni55aN** [comment]
just cloned `rete.js.org` repo, installed dependencies and have build the project without any errors

**Comment by d-led** [comment]
yes, it builds without errors. This is a test. Will write up how to reproduce

**Comment by d-led** [comment]
in fact, the statement in the test is not necessary to reproduce. This is just the unmodified rete.js.org code. Just importing it in the test is sufficient to reproduce: https://github.com/d-led/rete.js.org/commit/694f2f40b3d5fd10856a49f4ed0c7ebecf54f88b

it's the same import as in [add-component.js](https://github.com/retejs/rete.js.org/blob/master/src/rete/components/add-component.js#L3)

**Comment by Ni55aN** [comment]
I see, I'll check it

**Comment by Ni55aN** [comment]
It looks like a problem in Jest, since it does not see the export of ES modules in node_modules

**Comment by Ni55aN** [comment]
Not it should works (v1.0.3). The issue was in the module that was imported from Node.js as a UMD module (main field in package.json) instead of CommonJS
