### ISSUE TITLE
create an image URL input control; and display the image above that input

### ISSUE THREAD

**Issue by gordielachance** [retejs/rete#241]
Hi!
I'm trying to build something with your awesome plugin.

I was wondering if it was possible to have an URL input, and to display the image above the input field (if possible).
I did some tests but I cannot get it to work.
Here is what I have for now.  I know it is frankenstein-ish but that's a start.
Can someone help ?

Thanks a lot !

    function loadImage(url) {
        return new Promise((resolve, reject) => {
          let img = new Image();
          img.addEventListener('load', e => resolve(img));
          img.addEventListener('error', () => {
            reject(new Error(`Failed to load image's URL: ${url}`));
          });
          img.src = url;
        });
    }

    class QuestionImageUrlControl extends Rete.Control {

        constructor(emitter, key, readonly) {
            super(key);
            this.emitter = emitter;
            this.key = key;
            this.template = `<img src=""/><input type="url" :readonly="readonly" :value="value" @input="change($event)" placeholder="Enter Image URL"/>`;

            this.scope = {
                value: null,
                readonly,
                change: this.change.bind(this)
            };
        }

        onChange() {
            console.log("changed URL");
            var url = this.scope.value;
            console.log(this);
            /*
            loadImage(url).then(img => document.getElementById('image-holder').appendChild(img))
        .catch(error => console.error(error));
            */
        }

        change(e) {
            this.scope.value = e.target.value;
            this.update();
            this.onChange();
        }

        update() {
            if (this.key)
                this.putData(this.key, this.scope.value)
            this.emitter.trigger('process');
            this._alight.scan();
        }

        mounted() {
            this.scope.value = this.getData(this.key);
            this.update();
        }

        setValue(val) {
            this.scope.value = val;
            this._alight.scan()
        }
    }

**Comment by Ni55aN** [comment]
https://jsfiddle.net/Ni55aN/mj786hLw/28

Image will be loaded on each input change, so you need to use a debounce

**Comment by gordielachance** [comment]
Thanks you so much :)

**Comment by hasanaydemir** [comment]
Hi @Ni55aN, could you share jsfiddle again? I have trouble about show image like this. But jsfiddle URL get 404 error. Thanks.

**Comment by quicksilver32** [comment]
@Ni55aN  привет, присоединяюсь к просьбе выше, на той странице ошибка 404
