### ISSUE TITLE
[bug] Examples shows some graphical fragments

### ISSUE THREAD

**Issue by Mokkapps** [retejs/rete#242]
# Steps to reproduce

* Use [example](https://rete.js.org/#/examples/basic)
* Click on number output of bottom left node
* Click again on the same output (or alternative somewhere near the output in the editor area)

# Expected Behavior

There are no graphical fragments shown in the editor

# Observed Behavior

<img width="558" alt="screenshot 2019-01-23 at 21 54 21" src="https://user-images.githubusercontent.com/3127210/51636746-48c68c00-1f5a-11e9-8aab-b308314acf69.png">

Tested on MacbookPro with Firefox 64.0.2, but I could also reproduce it on a Windows machine using Chrome

**Comment by Ni55aN** [comment]
Thanks for notice! It's known bug that was fixed in `rete-connection-plugin` v0.3.3, but not updated on rete.js.org

**Comment by Ni55aN** [comment]
Check it now please

**Comment by Mokkapps** [comment]
Cool, now it works. Thanks for your fast response!
