### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by alemoreau** [retejs/rete#247]
When creating an app using vue cli 3, the line `import Rete from "rete";` crashes with 
`Uncaught ReferenceError: regeneratorRuntime is not defined`

Do you know how to fix this ?

### Steps to reproduce
> vue create app
> cd app
> yarn add rete rete-vue-render-plugin rete-connection-plugin
[ add `import Rete from "rete";` in src/main.js for instance ]
> yarn && yarn run serve

Thanks for this awesome framework !

**Comment by Ni55aN** [comment]
@alemoreau how do you build your app?

CommonJS and ES modules don't have polyfills (not to duplicate them in many plugins) You can import a polyfill from your code or install the babel plugin https://babeljs.io/docs/en/babel-plugin-transform-runtime#regenerator-aliasing

**Comment by alemoreau** [comment]
Thank you for leading me to a solution @Ni55aN .
Adding `
"@babel/preset-env",
      {
        "useBuiltIns": "entry"
      }
` in `babel.config.js` and `import '@babel/polyfill'` in main.js solved it.
For reference https://cli.vuejs.org/guide/browser-compatibility.html#polyfills

**Comment by shabbir847** [comment]
> Thank you for leading me to a solution @Ni55aN .
> **babel.config.js**
> `module.exports = { presets: [ ['@vue/app', { "useBuiltIns": "entry" } ] ] }`
> **main.js**
> `import '@babel/polyfill'`
> 
> For reference https://cli.vuejs.org/guide/browser-compatibility.html#polyfills

i am not getting how to do it.
plz you can explain me step by step

**Comment by MeloJR** [comment]
I don't know why it is mandatory to import polyfills in order to use this library. There is something that I don't understand. The point of polyfills is to include them if you need to support some kind of browser/features. Why does rete need polyfills in order to work in a browser (even in Chrome)?

**Comment by Ni55aN** [comment]
@MeloJR Rollup transpiles the source code to previous versions of ES where async/await is not supported (async/await transpiled to runtimeRegenerator). The runtimeRegenerator implementation is not included in the code and plugins bundles due to packet size optimization, thats why you need to include polyfill (or at least runtimeRegenerator).

**Comment by Felixclement** [comment]
just a side note on this issue,
since @babel/polyfill is deprecate is solved this issue using

[regenerator-runtime](https://www.npmjs.com/package/regenerator-runtime)

**Comment by syshex** [comment]
> just a side note on this issue,
> since @babel/polyfill is deprecate I solved this issue using
> 
> [regenerator-runtime](https://www.npmjs.com/package/regenerator-runtime)

How ? Any details on how you got it fixed ?

**Comment by ghostandthemachine** [comment]
This worked for me even though I'm using clojurescript. Much appreciated
