### ISSUE TITLE
[question] execution only mode?

### ISSUE THREAD

**Issue by dkipp** [retejs/rete#248]
is a developer able to design complex pipeline and workflows - and the final app just executes thees?

If yes, a example would help - The retejs description on the homepage and the examples are tightly coupled to the editor. I'm even unsure if thats in the project scope.

**Comment by Ni55aN** [comment]
Do you mean an examples such as [Events (tasks)](https://codepen.io/Ni55aN/pen/MOYPEz) and [Programming a Messenger Bot](https://codepen.io/Ni55aN/pen/rpOKNb)? They use the `rete-task-plugin`. 

It can works with `Editor` or `Engine`  (yeah, its not documented)

```js
import TaskPlugin from 'rete-task-plugin';

engine.use(TaskPlugin);
```

You can use `Engine` separately from `Editor`.
