### ISSUE TITLE
Connection Plugin Error

### ISSUE THREAD

**Issue by limuyao** [retejs/rete#250]
**Hi man! Thank you for an awesome lib!**
Just trying to use the first example (Flow-based programming) https://codepen.io/Ni55aN/pen/xzgQYq
and have an error.
When i try to drag a node over the border of view container it performs an error (Uncaught TypeError: Cannot read property 'input' of null)
![pic1](https://user-images.githubusercontent.com/11609827/52513006-edc3b300-2c42-11e9-8300-4b9615619e63.png)

**the error in https://cdn.jsdelivr.net/npm/rete-connection-plugin@0.4.1/src/index.js**
_at string num 11 and 59_
![2](https://user-images.githubusercontent.com/11609827/52513191-26b05780-2c44-11e9-99d3-d26f57f47494.png)

![2 5](https://user-images.githubusercontent.com/11609827/52513315-f87f4780-2c44-11e9-9cd5-14c55fca5b7f.png)

and when i drag other nodes over the borders i get the same problem:
![pic3](https://user-images.githubusercontent.com/11609827/52513016-fae0a200-2c42-11e9-9b6f-f9f045fd2b7c.png)

The same issue if i just scroll down the window a little bit:
![4](https://user-images.githubusercontent.com/11609827/52513037-1ea3e800-2c43-11e9-8783-dc2336daa82f.png)
**Chrome 71.0.3578.98 x64**

What's wrong with it? How to solve the problem? Thank you for help

**Comment by Ni55aN** [comment]
Fixed in v0.4.2
