### ISSUE TITLE
rete.js.org website is blank on Firefox

### ISSUE THREAD

**Issue by Dtatoo** [retejs/rete#252]
Website displays blank page when using Firefox(65) and IE11 https://rete.js.org on firefox. When I take a look at the Firefox console I am seeing the following error:
```
SyntaxError: invalid regular expression flag s
```

Website works as expected on Chrome.
On IE I don't see any error messages on console.

It seems like error is coming from 
*!
* rete-connection-reroute-plugin v0.1.2 
* (c) 2018  
* Released under the ISC license.
*/

**Comment by Ni55aN** [comment]
Fxed!
