### ISSUE TITLE
@mousedown.stop="" Doesn't work with vue-render-plugin

### ISSUE THREAD

**Issue by limuyao** [retejs/rete#253]
**Hi to all!** Still study using Rete.js and return to the old question about prevent drag event: https://github.com/retejs/rete/issues/196
> 
> 
> In alight you can [stop an event propagation](https://angular-light.readthedocs.io/en/latest/events.html?highlight=stop%20propagation)
> 
> ```
> <input @mousedown.stop="">
> ```
> 
> In vue-render-plugin there is the same "stopPropagation"

The solution doesn't work with **vue-render-plugin**. I use `<input @mousedown.stop="">` but still can drag a node

**Comment by Ni55aN** [comment]
Since v1.1.0 a mouse events was changed with pointer events.
Solution:
```js
 @pointermove.stop=""
```

**Comment by limuyao** [comment]
Thank you **Ni55aN**!
The `@pointerdown.stop` is working for me
