### ISSUE TITLE
New versions problem..

### ISSUE THREAD

**Issue by Hatead1** [retejs/rete#254]
Latest rete(110)+vrp(030)+conn-plug(042)+cont-menu-plug(034) don't work!
Rete(110)+vrp(026)+conn-plug(042)+cont-menu-plug(032) work!

Error
context.js:19 Uncaught (in promise) TypeError: t.install is not a function
    at n.value (context.js:19)
    at test.html:105 ( editor.use(VueRenderPlugin); )
    at test.html:141

Tested local and on codepen

**Comment by Ni55aN** [comment]
Since rete-cli@0.5.0 all three plugins (latest version) have a UMD, CommonJS and ES module.

a. In browser (include .min.js - UMD with default and named exports)
```js
editor.use(Plugin.default)
```
b. via Webpack, etc. (main or module from package.json will be imported, CommonJs for old version and ES module for latest)

```js
import Plugin from 'rete-vue-render-plugin';
// before it was
// import * as Plugin fr...

editor.use(Plugin)
```

**Comment by Ni55aN** [comment]
In your case you must to get 'default' property of plugin

**Comment by Ni55aN** [comment]
https://rete.js.org/#/docs -> Installation without bundlers (Webpack, Rollup, etc.)

**Comment by Hatead1** [comment]
Ok, thanks

However corrert 
  editor.use(ConnectionPlugin)
  editor.use(VueRenderPlugin)
on rete.js.org/#/docs (at the end of the page)

**Comment by Ni55aN** [comment]
Depends on your environment

**Comment by Hatead1** [comment]
На странице документации в разделе "Установка без сборщиков" в примере компоненты вызываются без .default, как раз мой case (даже не мой, а ваш, я на оригинальном codepen примере код меняю).

**Comment by Ni55aN** [comment]
Ниже строки `и подключить UMD модули:` идёт пример с default, дальше идут примеры без него при сборке через Webpack и т.п.

**Comment by Hatead1** [comment]
Меня или заклинило или? 
На странице примера codepen (https://codepen.io/Ni55aN/pen/xzgQYq) какой тип сборки? Там ведь стоит .default у трех компонентов. И именно этот пример при замене некоторых компонентов на более свежую версию не заработал.

В доках, в окне после фразы "Инициализируйте редактор, подключите минимально необходимые плагины" описан, как я понимаю, именно этот случай, но там нет .default у use().

**Comment by Ni55aN** [comment]
На Codepen подключены UMD модули, поэтому при их подключении нужно дописать `.default`. Так же для всех модулей, которые собраны через rete cli версии 0.5.0 и больше

> компонентов на более свежую версию

там стоят самые последние версии

> в окне после фразы "Инициализируйте редактор, подключите минимально необходимые плагины" описан, как я понимаю, именно этот случай, но там нет .default у use().

нет, это в случае сборки через webpack и подобные сборщики, не напрямую подключенные в HTML страницу

**Comment by Hatead1** [comment]
> там стоят самые последние версии
Когда я проверял, там стояли те версии, которые были в самом первом сообщении (в работающем варианте). Я их заменил на ваши же новые и ничего не заработало без .default

Что делаю я: 
1. скачиваю отсюда все необходимые компоненты и rete (git clone, npm i и т.д. ) 
2. Вношу свои изменения в код
3. Добавляю свои плагины
4. npm run build везде
5. Использование - обычная html страничка с загрузкой необходимых *.min.js (не common и не ES), остальное как в примере на cоdepen, только у меня все компоненты и их кишочки в отдельном плагине.

Что это получается за тип сборки и почему в этом случае мне нужно добавлять .default?

**Comment by Ni55aN** [comment]
> Я их заменил на ваши же новые и ничего не заработало без .default

Это предсказуемо, так как начиная с context-menu-plugin@0.3.4, vue-render-plugin@0.3.0 и connection-plugin@0.4.0 их бандлы собираются в *.min.js в том же формате UMD, только с поддержкой именованных экспортов (это полезно для ES модулей), поэтому энтрипоинты одни для всех, но UMD будет возвращать дефолтный экспорт под свойством default

Было в *.min.js
```js
export default {
  name,
  install,
  Something
}
// получаем
editor.use(Plugin);
Plugin.Something
```
Стало
```js
export default {
  name,
  install,
  Something
}
// получаем только при использовании *.min.js
editor.use(Plugin.default);
Plugin.Somehting
```

В первую очередь изменения в сборщик (rete-cli) были внесены для поддержки разных форматов модулей, и параллельно включена поддержка именованых экспортов для поддержки Tree Shaking 

> 2\. Вношу свои изменения в код 

С какой целью?

**Comment by Hatead1** [comment]
Я понял, спасибо. 
> С какой целью?
Стили, в основном. Ну и поскольку мне обычно нужно что-то странное, приходится добавлять. Вот, к примеру, нужно контекст-меню, но "main" д.б. фиксировано в своем диве слева, никогда не гаснуть и иметь items-ы, которые не гаснут при использовании search,, поэтому корежим cont.-menu-plugin :)

**Comment by Ni55aN** [comment]
В крайнем случае лучше использовать `!important`, чем пересобирать и переписывать стили при каждом обновлении зависимостей. К тому же, vue render и context-menu можно кастомизировать, переопределяя компоненты со своими стилями.

> Вот, к примеру, нужно контекст-меню, н..

не совсем понял о чем речь, но в любом случае лучше искать компромисы при расширении функционала в issues соответсвующего репозитория, чтобы не приходилось переписывать свои изменения при каждом обновлении зависимости

**Comment by Hatead1** [comment]
Компромиссы возможны, хотя мнение разработчика и пожелания пользователя редко когда совпадают :) Сейчас FR в контекст-меню напишу.
А ковыряния в компонентах - это еще и просто интересно :)
