### ISSUE TITLE
select list for node makes node selected when clicked to open options

### ISSUE THREAD

**Issue by akshayred** [retejs/rete#257]
When adding a select dropdown using Vuejs controller, the select field shows correctly. But when try to select an option from the dropdown, the whole node gets selected and when you move the cursor, the node moves with it and there is no way to unselect it with left click.

**Comment by Ni55aN** [comment]
Try to stop propagation of `pointerup` event

**Comment by akshayred** [comment]
Thank you for your help.
I would like to support your project via patreon. Can you please confirm if this patreon is correct.
https://www.patreon.com/join/ni55an/signup

Thank you!

**Comment by Ni55aN** [comment]
Yes, this is correct (nickname: ni55an)
