### ISSUE TITLE
Giving connection an onclick handler

### ISSUE THREAD

**Issue by prog-r-amer** [retejs/rete#258]
Hello,
is there an easy way to give a connection between 2 Nodes an onclick handler?

**Comment by Ni55aN** [comment]
```js
editor.connect(node1.outputs.get('out-key'), node2.inputs.get('in-key'));
```
where `out-key` and `in-key` are keys specified in Component's builder

**Comment by prog-r-amer** [comment]
I don't want to connect 2 nodes, I want something to happen when I click on the connection already existing. Like, for example remove the connection when I click on it.

**Comment by Ni55aN** [comment]
There is `connectionremoved` event

**Comment by Hatead1** [comment]
He wants 'pathclicked' or 'pathselect' event..

**Comment by Ni55aN** [comment]
```js
editor.on('renderconnection', ({ el }) => {
    el.addEventListener(...
});
```

**Comment by prog-r-amer** [comment]
Thanks a lot :)
