### ISSUE TITLE
Seamless TypeScript integration

### ISSUE THREAD

**Issue by Ni55aN** [retejs/rete#260]

**Comment by juliandavidmr** [comment]
Hello, I converted all the source code from Rete to Typescript, including several improvements in type recognition ... All the changes are here: https://github.com/juliandavidmr/rete

**Comment by juliandavidmr** [comment]
Also, I started to test the use of Rete from decorators to create components, events and controls.

**Comment by Ni55aN** [comment]
I have added `@babel/preset-typescript` and build a code as before via `rete-cli` without tons of dependencies
in each package. For type checking and generating .d.ts I'm using pure `tsc`.
FYI, JS code also replaced with TS

**Comment by juliandavidmr** [comment]
What do you think about of incorporating decorators into this project? *(Same as Angular or NestJS)*

i.e:

```ts
@Component()
export class ComponentA { /* ... */ }
```

```ts
@Control()
export class ControlX { /* ... */ }
```

With functions:

```ts
@Event('nodecreated')
OnCreateNode(node: Node) {
    console.log('Node created:', node)
}
```

> It might be good to separate this new feature into a new repository (for maintainability reasons).

**Comment by Githamza** [comment]
@juliandavidmr Thank you for your efforts .
I would like to start a projet using Angular + Rete, I would like to know if it's better to use the official JS version or your version.

You think that you will be able to update your version every official Rete new release.

I would ask your for a demo ( in stackblitz ) using Rete TS if it's possible ? 👍

**Comment by Ni55aN** [comment]
> What do you think about of incorporating decorators into this project?

What is the advantage of decorators over inheritance in this case? What are the alternatives for JS?

**Comment by Ni55aN** [comment]
@juliandavidmr events are well typed at the previous form

![Screenshot from 2019-03-23 21-29-35](https://user-images.githubusercontent.com/8259641/54870707-c704aa80-4db2-11e9-862c-c60ee65c1a36.png)

IMHO decorators in this case are not needed, moreover there is the issue of compatibility with JS

**Comment by Ni55aN** [comment]
`rete-cli@v0.6.0` supports additional babel presets and extensions, which allows to add TS support for plugins on demand


https://rete.js.org/#/cli
