### ISSUE TITLE
Allow deleting connection on mouseup after being detached

### ISSUE THREAD

**Issue by iKlsR** [retejs/rete#261]
<strike>The only way at the moment to detach noodles from nodes is to drag from the socket. An alternative would be to say hold <kbd>Ctrl </kbd> and drag over noodles or click to remove them or allow selecting the noodle itself and using some event to remove it, keypress or double click etc.</strike>

Also is it possible to immediately remove a connection the moment it is detached? Having it float around ready to be parented again seems a bit wonky.

**Comment by Ni55aN** [comment]
You can click a RMB (call a context menu) on connection (noodle :smiley:). It will be disconnected and attached to a pointer.

> An alternative would be to say hold Ctrl  and drag over noodles or click to remove them or allow selecting the noodle itself and using some event to remove it, keypress or double click etc.

By the way, this is a good suggestion

> Also is it possible to immediately remove a connection the moment it is detached? Having it float around ready to be parented again seems a bit wonky.

A click on empty area will hide a "phantom" connection. But you can "mousedown" on socket, move mouse out of socket, and "mouseup"

**Comment by iKlsR** [comment]
Ok I'm seeing these behaviors now and have renamed the issue accordingly. Thanks.

**Comment by Ni55aN** [comment]
I think a more interactive ways to manage connections can be implemented in a separated plugin

Need to come up with a name:
`*-connection-plugin`

**Comment by iKlsR** [comment]
`connection-behaviour-plugin`? 😁

**Comment by Ni55aN** [comment]
https://github.com/retejs/connection-mastery-plugin

**Comment by iKlsR** [comment]
Thanks @Ni55aN, I'll give it a look when I get the time.

**Comment by Ni55aN** [comment]
@iKlsR this feature is not implemented yet

**Comment by Ni55aN** [comment]
Have added `Delete connection by picking` feature https://github.com/retejs/connection-mastery-plugin

**Comment by iKlsR** [comment]
Thanks, I'll check it out.
