### ISSUE TITLE
ESlint for .ts

### ISSUE THREAD

**Issue by Ni55aN** [retejs/rete#262]
https://github.com/typescript-eslint/typescript-eslint

**Comment by dkipp** [comment]
For Typescript, TSLint might fit better
https://palantir.github.io/tslint/

**Comment by Ni55aN** [comment]
@dkipp does it validate a pure js correctly?

**Comment by renjfk** [comment]
I would also vote for tslint. We have been using it for a while and working perfectly fine.

**Comment by dkipp** [comment]
> @dkipp does it validate a pure js correctly?
What´s the need for pure js in a ts file?

I'm not aware of a typescript project using eslint over tslint.

**Comment by Ni55aN** [comment]
@dkipp I have my eslint rules and I would like to apply it for .js/.ts files without TSLint which has some differences

By the way, @typescript-eslint/parser and @typescript-eslint/plugin working good for .ts and .js files
