### ISSUE TITLE
Explanation about node and socket function attributes

### ISSUE THREAD

**Issue by akshayred** [retejs/rete#263]
Hi,

Can you please help me understanding what each attribute of following functions supposed to be and it will be nice if I could get some documentation for the same so that it can help others too.

new Rete.Output('num', "Number", numSocket);
node.addControl(new NumControl(this.editor, 'num')).addOutput(out1);
editor.connect(n1.outputs.get('num'), add.inputs.get('num1'));
await components[0].createNode({num: 10});
new Rete.Socket('Number value');

**Comment by Ni55aN** [comment]
Input/Output accept the follow arguments:
[key, name, socket, multiConns](https://github.com/retejs/rete/blob/master/src/io.ts#L15)

key - identifier of input or output (unique on its list)
name - any text
socket - https://rete.js.org/#/docs/sockets
multiConns - specify ability to add multiple connections (by default for Input = false, for Output = true)

Node has methods `addControl/addOutput/addInput` and `removeControl/removeOutput/removeInput`. 
Their names speak for themselves, they take 1 parameter

editor.connect - connect output with input programmatically (node.inputs / node.outputs - Map object)

await components[0].createNode({num: 10}); - create instance of node based on component (component must be registered - editor.register)

new Rete.Socket('Number value'); - socket (aka port) specify type or nature of data

**Comment by akshayred** [comment]
Thanks for your help and support.

**Comment by haris-75** [comment]
Can we make Dynamic Sockets, When we try to make connections between two nodes.
