### ISSUE TITLE
node.data value aren't cleaned after control deletion.

### ISSUE THREAD

**Issue by Hatead1** [retejs/rete#264]
If remove created control with value, the following created control with the same key will get old value.

May be add to "remove" function something like 
`						node.data.key = undefined; 
					      	delete(node.data.key);
`

**Comment by Ni55aN** [comment]
You must manage all the node data management yourself. This is not the responsibility of the framework.

**Comment by Hatead1** [comment]
I didn't create this variable! Why I must think about it and remember it? 

Эта переменная создается фреймворком во время создания инпута и должна удаляться при удалении инпута, ну это же очевидно! Как очевидно и ожидаемо всё остальное:  при удалении чего-либо должны вычищаться все останки во всех объектах и обновляться все отображения. И не должен пользователь вводить "волшебные строчки", затерянные глубинах issues, чтобы избавится от глюков фреймворка.

**Comment by Ni55aN** [comment]
В каком это месте создается фреймворком? Контрол создается вами - и putData вызывается в нем тоже вами

**Comment by Ni55aN** [comment]
> при удалении чего-либо должны вычищаться все останки во всех объектах и обновляться все отображения.

компонент контрола ничего не знает о том, удален ли он, все это выполняется локально, иначе это приведет к утрате слабой связности

> вводить "волшебные строчки", затерянные глубинах issues, чтобы избавится от глюков фреймворка.

все написание логики - ваша ответственность, и фреймворк не отвечает за ваши "волшебные строчки"

**Comment by Hatead1** [comment]
Беда слабой связанности в том, что у нас всегда будут разные взгляды на то, когда надо остановиться и перестать мельчить.
