### ISSUE TITLE
Cannot read property 'style' of null

### ISSUE THREAD

**Issue by Armaldio** [retejs/rete#265]
I'm using vue cli 3 to generate the project.

Then my component: 

```vue
<template>
  <div id="rete" class="node-editor"></div>
</template>

<script>
import Rete from 'rete';
// import ConnectionPlugin from 'rete-connection-plugin';
import VueRenderPlugin from 'rete-vue-render-plugin';

import CustomNodeComponent from './CustomNodeComponent.vue';
import CustomControlComponent from './CustomControlComponent.vue';

const container = document.querySelector('#rete');
const editor = new Rete.NodeEditor('demo@0.1.0', container);
editor.use(VueRenderPlugin);

class MyComponent extends Rete.Component {
  constructor() {
    super();
    this.data.render = 'vue';
    this.data.component = CustomNodeComponent;
    this.data.props = {};
  }
}

class MyControl extends Rete.Control {
  constructor() {
    super();
    this.data.render = 'vue';
    this.data.component = CustomControlComponent;
    this.data.props = {};
  }
}

const myComponent = new MyComponent();
editor.register(myComponent);
const myControl = new MyControl();
editor.register(myControl);

export default {
  name: 'Flow',
  mounted() {
  },
};
</script>

<style scoped lang="scss">
</style>
```

On launch, I'm not getting anything rendered, and get

![image](https://user-images.githubusercontent.com/3089715/53362671-b1fa4000-3908-11e9-92e7-7f17503108dc.png)

The error appear to be at line 15 of my code 
```js
L15         -> const editor = new Rete.NodeEditor('demo@0.1.0', container);
rete.esm.js -> _this.view = new EditorView(container, _this.components, _assertThisInitialized(_this));
rete.esm.js -> _this.container.style.overflow = 'hidden';
```

**Comment by iKlsR** [comment]
I had this exact issue Saturday when I picked up this library since it's been a minute since I have used Vue and also first time using the cli (`vue ui` is super cool as well). The issue is that the element isn't ready when the script runs that portion of code. My solution might not be the best or correct but what worked for me is to your functionality into either an `await` call somewhere or perform this somewhere inside `mounted() {}`

My setup currently looks like this

```
export default {
    methods: {
        async init() {
            // perform all initialization here (ie the document.querySelector)
        }

        mounted() {
            this.init();
        }
    }
}
```

Note that I put `async init`, this is to make sure you can make `await` calls inside the function as you might need to do so when creating components.

This is just one part however and you will probably run into https://github.com/retejs/rete/issues/247 right after. 

To fix that as well add `@babel/plugin-transform-regenerator": "^7.0.0"` and `babel-polyfill": "^6.26.0"` to your dependencies and follow the instructions in this comment https://github.com/retejs/rete/issues/247#issuecomment-459411540. Cheers.

**Comment by Ni55aN** [comment]
#rete element doesn't exist when the `querySelector` calling. All initial operations with HTML elements in template must by performed in `mounted()`. Moreover, querySelector is a bad practive for Vue.js - use a [$refs](https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements)

**Comment by iKlsR** [comment]
@Ni55aN I was going to suggest the refs method but I'm still reading up on it. Also it's a bit hard for a newbie like me to grok the layout of the examples in the retejs repo. Could you make a *simple* barebones example based on a new vue cli project with the best practices? The example on codesandbox is also a bit heavy I fear.

**Comment by Armaldio** [comment]
Thanks @iKlsR and @Ni55aN for this great explanation!

Moved all my stuff to mounted, but now facing

![image](https://user-images.githubusercontent.com/3089715/53367578-8da46080-3914-11e9-8f57-129c0333e50d.png)

Also, already fixed the #247

**Comment by iKlsR** [comment]
Seems to me that would be on your end in your custom component, maybe try commenting out lines/chunks until you see what's not getting set.

**Comment by Armaldio** [comment]
The custom component is really minimal so I doubt that

```vue
<template>
  <p>control</p>
</template>

<script>
export default {
  name: 'control',
};
</script>
```

**Comment by iKlsR** [comment]
Ok would be hard to say without seeing your code.

**Comment by Armaldio** [comment]
Here is the repo: https://github.com/Armaldio/flow

**Comment by iKlsR** [comment]
@Armaldio You needed a `super("component_name")` call in your custom component. Not sure how that trickled down to vue stuff. I'm also new to this :). I would also suggest maybe having an explicit `data() {}` in your `export` function.

I would recommend looking through the rete repositories when using stuff to see what the author does, the documentation is pretty sparse but the code is super readable.

**Comment by Ni55aN** [comment]
`eslint-disable-next-line` is evil :) It hints that you missed `super(name)`. The parameters `emitter`, `key` is redundant, super class require `name` only

**Comment by Ni55aN** [comment]
class MyComponent extends Rete.Component {
  constructor() {
    super("My component");
    this.data.render = 'vue';
    this.data.component = CustomNodeComponent;
    this.data.props = {};
  }
}

**Comment by Armaldio** [comment]
@iKlsR 
Yeah, it's in the snippet but did't worked (at least empty). I've also tried adding something to it, because I saw it took a string but that didn't made it.

Also, I'm mostly following the doc but it seems vue integration is missing infos and switching between native and vue render confuse me: https://rete.js.org/#/docs/plugins/vue-render

@Ni55aN I know ^^' just trying to setup my thing with different tries.

Everything finnaly work without any errors, but nothing is renderer. I hope to sort this out quickly

**Comment by Ni55aN** [comment]
Parent of #rete element should have a sizes (and `editor.view.resize()` of course)

**Comment by Ni55aN** [comment]
https://rete.js.org/#/docs/components

**Comment by Armaldio** [comment]
All parent have fixed size as well as #rete but no luck
https://github.com/Armaldio/flow/blob/master/src/components/Flow.vue

**Comment by Ni55aN** [comment]
obviously, since you have no nodes

**Comment by Armaldio** [comment]
Wonderfull that worked!

Thank you all for the quick support, really appreciate 🙏 

On a side note, while well made, the docs seems to miss some infos. I think it culd be really usefull to like, show the code, on the example (https://rete.js.org/#/examples/basic) page

Issue can be closed, thank again
