### ISSUE TITLE
fields of node gets hidden when connection is made with another node

### ISSUE THREAD

**Issue by akshayred** [retejs/rete#266]
I created 2 nodes, both of them have separate fields and controls. When I connect both the nodes, fields in second node becomes display none and when I remove the connection, the fields starts to show again.
Please check my code here

https://codepen.io/akshaykelotra/pen/PLwoMK

**Comment by Ni55aN** [comment]
You have added control to input
```js
  input1.addControl(new FieldsControl(this.editor, 'fieldscon'));
```

Input control serves as a replacement for connections, so control is hidden when the input is connected
