### ISSUE TITLE
Issue with Connection Bounding Box

### ISSUE THREAD

**Issue by prog-r-amer** [retejs/rete#267]
Hi,

I have an issue with giving the connections hover elements, because of the bounding box of the svg.

`.main-path:hover
{
	stroke: green !important;
}`

This doesn't work everywhere. If I give svg an absolute size like 10000px it works in a bigger area, but not when you translate the area. Can you give the svg the width and height properties according do the path inside it, so hover / onclick works everywhere?

**Comment by Ni55aN** [comment]
As I remember, SVG with large sizes will be overlayed on frames (from comment-plugin)

![screenshot from 2019-02-26 19-47-31](https://user-images.githubusercontent.com/8259641/53434496-6d050500-39ff-11e9-9193-1c61955d1126.png)

It seems that this is a bug with SVG, since the hover zone does not correspond to the actual size of the SVG

**Comment by prog-r-amer** [comment]
It goes a bit outside of the size of the svg, but it always works when the svg is bigger than the path. I would still appreciate an option to make the svg size bigger, since I don't use the comment plugin myself.

**Comment by prog-r-amer** [comment]
You were right, even if I set the svg size to the same size as the node editor hover doesn't always work. Do you have any suggestions how I get the hover to work 100% of the time?

**Comment by Ni55aN** [comment]
I don't. Seems like a bug in SVG, since I have not found a logical explanation for this behavior. Moreover, if the SVG size is too small, the coordinates of a connections may offset. This happens on all WebKit browsers.

**Comment by Ni55aN** [comment]
I will be grateful if someone finds examples with the reproduction of such behavior on a regular SVG (outside the framework)

**Comment by prog-r-amer** [comment]
I don't believe it's a bug in svg, I only get it within rete.
Could it be something with drag or onclick events not propagating correctly and because of that the element doesn't get the mouseover event?

**Comment by Ni55aN** [comment]
@prog-r-amer I have reproduced the bug: https://codepen.io/Ni55aN/pen/jJGVYe

Anyway, starting from rete-connetion-plugin@0.5.0-rc.1 it was fixed

**Comment by prog-r-amer** [comment]
wow, thanks mate.
I only have 1 issue now after upgrading:
without 

`.connection {width: auto; height: auto}`

it looks like this:
https://imgur.com/a/mkHsqgY

I don't get the hover bug anymore though and this css fixes it for me. Just wanted to report it.

**Comment by prog-r-amer** [comment]
Ok, very rarely I still manage to not get hover working right, but it's far better than before.

**Comment by prog-r-amer** [comment]
By the way, with

`pointer-events: all;` your codepen works bugfree for both paths.

**Comment by prog-r-amer** [comment]
No, it's with the 1px width and height, that it doesn't work.

**Comment by Ni55aN** [comment]
Is the [example](https://codepen.io/Ni55aN/pen/xzgQYq) have any issues?

**Comment by prog-r-amer** [comment]
On my mobile phone it looks the same as the example I sent you.
On my desktop pc it works.

**Comment by Ni55aN** [comment]
What is mobile OS?

**Comment by prog-r-amer** [comment]
Android with Chrome

**Comment by Ni55aN** [comment]
It's strange. I don't have any issues on Android 7.0 with Chrome 72

**Comment by prog-r-amer** [comment]
For Reference:
https://imgur.com/a/3zuY7Bx

Chrome Version is 72 too.

**Comment by prog-r-amer** [comment]
Why do you set the width and height for the svg?
It sets the ratio of the svg, and I think this is what causes the bug in some browsers.

I think you should set the width and height of the absolute positioned container, and give the svg no width and height attributes. This might also solve the still sometimes occuring hover bug, if you set the container to the actual dimensions of the svg, although I am not sure about that.

**Comment by Ni55aN** [comment]
> Why do you set the width and height for the svg?

in some cases SVG may overlap other elements

> I think you should set the width and height of the absolute positioned container, and give the svg no width and height attributes.

This doesn't work. SVG will still overlap
![Screenshot from 2019-03-15 11-46-14](https://user-images.githubusercontent.com/8259641/54422818-f57de800-4717-11e9-8283-2b5835cb1a34.png)

**Comment by prog-r-amer** [comment]
Why is it not allowed to overlap?

**Comment by Ni55aN** [comment]
> Why is it not allowed to overlap?

it will blocks a mouse events

> And in the Image you posted the width and height are still 1px.

with of div, not SVG

**Comment by prog-r-amer** [comment]
You can control the mouse events with pointer-events property of elements.

**Comment by Ni55aN** [comment]
pointer-events none doesn't working with root SVG

**Comment by prog-r-amer** [comment]
Today I learned...

**Comment by bfritscher** [comment]
I also have the bug on my desktop. The svg element bounding box is fine but the coordinates are wrong due to scaling factor of the HDPI display 150%.

![connector bug](https://user-images.githubusercontent.com/338973/54788236-9d227b00-4c2e-11e9-92ae-83c7bf4dda95.jpg)

On the other hand the 3D car configurator example works

**Comment by Ni55aN** [comment]
I can not give an explanation for this, since it looks like a bug at the level of the webkit engine

**Comment by Ni55aN** [comment]
The temporary solution is adding `width: auto;` `height: auto` to SVG, but it may lead to overlaying of other elements

**Comment by Ni55aN** [comment]
The same issue on Win10 with an interface scale of 125% (the browser has 100%)

![Opera Снимок_2019-03-31_102309_codepen io](https://user-images.githubusercontent.com/8259641/55287309-e9e51f00-53af-11e9-8d7e-9ab2a9a63e75.png)

**Comment by Ni55aN** [comment]
I deleted width and height constraints on SVG (which leads to a strange problem with a scaling)
I hope that `position: absolute` and `pointer-events: none` will solve the issue of clicking on comment/frame in all major browsers  

rete-connection-plugin@0.6.4 published
https://github.com/retejs/connection-plugin/commit/39c55569fcefeedf134aa7e2017908c0a14d2d62

**Comment by Ni55aN** [comment]
The most interesting thing is that `pointer-events` does not work without `position: absolute`

**Comment by Ni55aN** [comment]
https://github.com/retejs/connection-plugin/issues/12
