### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by shift-reality** [retejs/rete#270]
Hi
I want to change Node by manual described in this topis: https://github.com/retejs/rete/issues/209#issuecomment-434406096 ...
There is my webpack config:
{ test: /\.pug$/, loader: "pug?pretty=true" }, { test: /\.vue$/, loader: 'vue-loader' }
There output:
https://pastebin.com/W6tEsi0p
Can you help, please? I don't known why this error happens...

**Comment by Ni55aN** [comment]
You need the sass-loader

**Comment by shift-reality** [comment]
да все, просто там какие-то нюансы были sass/scss... (добавил {} и ;) все заработало..
Другой вопрос, я хочу сделать кастомную ноду, вот ее код вуа: https://pastebin.com/sF1VUvHp
Импорт: `import MyNode from './MyNode.vue';`
использование(в конструкторе): `this.data.component = MyNode;`
в консоле куча ошибок:
` Property or method "node" is not defined on the instance but referenced during render.`
Как мне правильно сделать это?
----
А еще спросить хотел, можно ли как-то изменить формат JSON, который выдается движком?

**Comment by Ni55aN** [comment]
уточните call stack, по которому возникла ошибка.

Эта проблема может быть в импортах
```
import mixin from 'rete-vue-render-plugin';
import Socket from 'rete-vue-render-plugin';
```
По дефолту возвращается только сам плагин для use(), а mixin и Socket - именованные 

Смотрите пример: https://github.com/retejs/rete.js.org/blob/master/src/rete/components/ecosystem/package/Component.vue#L24

**Comment by shift-reality** [comment]
Действительно, затупил...
Спасибо
