### ISSUE TITLE
Connection isn't updated when node is resized dynamically 

### ISSUE THREAD

**Issue by iKlsR** [retejs/rete#274]
If a node is resized because of its control updating *its* size, neither the connection point nor the curvature of the connection gets updated. See the gif for an example. It's somewhat subtle here. In one case the curve tip was moved from the socket.

![](https://i.imgur.com/pZD3SDJ.png)

It does however update if I move the offending node afterwards manually.

![](https://thumbs.gfycat.com/UnhealthyMisguidedAmericanwigeon-size_restricted.gif)

Poked around the issues and https://github.com/retejs/rete/issues/230 doesn't seem to help. Not sure if this is connection behaviour specific so putting it here.

**Comment by Ni55aN** [comment]
`editor.view.updateConnections({ node })` must be called after DOM is updated.
Try `setTimeout` to verify this

**Comment by iKlsR** [comment]
I'm doing this in the worker and getting no updates, also tried in a `connectioncreate(d)` event with timeout as well. Can you share an example?

**Comment by Ni55aN** [comment]
I need to see your code

**Comment by iKlsR** [comment]
I'm trying to do it like this

```
this.editor.on("connectioncreate", output => {
    let targetNode = output.node;
    this.editor.view.updateConnections({ targetNode });
    engine.process(this.editor.toJSON());
});
```

It seems to be the only way I can get the node but if I try to access it I get `Uncaught TypeError: Cannot read property 'getConnections' of undefined`.  I was getting similar errors in my workers because it seems this node object is not valid?

**Comment by Ni55aN** [comment]
`{ targetNode }` - property is `targetNode`
required property name is `node`. In other words, you set a wrong property name in the object being passed.


https://github.com/retejs/rete/blob/1477652eda47a67372a493ea9b03e3293288940c/src/view/index.ts#L78

**Comment by iKlsR** [comment]
Ok great, a bit more help and I've got it. The following now works for testing but obviously not ideal. Is there a way to know when the dom has been updated from Rete or do you use some language feature. Thanks!

```
this.editor.on("connectioncreate", output => {
    setInterval(() => {
        let node = output.output.node;
        this.editor.view.updateConnections({ node });
    }, 1000);
});
```

**Comment by Ni55aN** [comment]
`connectioncreate` triggered before a connection created,
`connectioncreated` - after a connection created. That's what you need

**Comment by iKlsR** [comment]
Ok, I tried that and same issue as my prior comment. I'm poking more around the source now. What seems to work for some weird reason is this at about the 200th repeat but by itself does not work.

I'm working on creating a fiddle.

```
this.editor.on("connectioncreated", connection => {
    setInterval(() => {
        let node = connection.output.node;
        this.editor.view.updateConnections({ node });
    }, 1);
});
```

**Comment by iKlsR** [comment]
@Ni55aN Here is an example. https://jsfiddle.net/iKlsR/cwyo5e24/. Connect the first node to the second and the control changes the overall size of the node but the connection doesn't get updated despite the node passed being valid.

**Comment by Ni55aN** [comment]
Oh, I see. Current sequence is as follows: 
`connection created -> update connections -> control added`

You need:
`connection created -> control added -> update connections`

How to achieve this: since the control affects the size of the node, it must update the connection itself

```js
class NumControl extends Rete.Control {

	// MODIFIED
  constructor(editor, key, readonly, show) {
    super(key);
    this.editor = editor;
   // ...
}
  // MODIFIED
  showControl(val) {
  	this.vueContext.show = val
    if(this.parent instanceof Rete.Node){
    	this.vueContext.$nextTick(() => this.editor.view.updateConnections({ node: this.parent }))
    }
  }
}
```

**Comment by iKlsR** [comment]
Perfect! Thanks.
