### ISSUE TITLE
file d.ts

### ISSUE THREAD

**Issue by francescoagati** [retejs/rete#275]
Hello,
i want generate file extern for language haxe for this library but i need the file .d.ts. where can i find this or how can i generate this from typescript code?

**Comment by Ni55aN** [comment]
Hello

https://github.com/retejs/rete/blob/master/package.json#L15
or
take a `.d.ts`'s `in node_modules/rete/types`

**Comment by francescoagati** [comment]
Ok thanks :-)

Il dom 10 mar 2019, 18:18 Vitaliy Stoliarov <notifications@github.com> ha
scritto:
