### ISSUE TITLE
Проблема с подключениями и ПКМ

### ISSUE THREAD

**Issue by shift-reality** [retejs/rete#276]
Здравствуйте!
Подскажите, в чем может быть проблема?
Воспроизводиться так: нужно сначала открыть контекстное меню, затем нажимать ПКМ
Результат: все связи начинают пропадать, по очереди...
Браузер: firefox 60.5.1esr (64-bit)
Снимок:
![Peek 2019-03-11 09-41](https://user-images.githubusercontent.com/29734946/54107633-63f23b80-43e2-11e9-87d7-d9d23f0c7d5a.gif)

**Comment by shift-reality** [comment]
В г.хроме все ОК, система Debian 9.9 64bit

**Comment by Ni55aN** [comment]
Какие плагины установлены?

**Comment by shift-reality** [comment]
`editor.use(VueRenderPlugin);
editor.use(ConnectionPlugin);
editor.use(ContextMenuPlugin);
editor.use(JsRenderPlugin);`

**Comment by Ni55aN** [comment]
Действительно, вопроизводится такой баг. Причем не только на firefox, на chrome тоже. Контекстное меню здесь не при чем. Все дело в SVG области, в которой отрисовывается path. 

Сама фича, из-за которой это проиходит, работает следующим образом: при клике на path нужно отсоединить соединение. 

По умолчанию SVG имеет размеры где-то 300x100 px, но остается прозрачной и кликабельной.

Решением могло бы быть обнулить размеры SVG, но тогда по какой-то причине пути внутри смещаются. Похоже на баг на уровне движка для рендеринга в браузере

**Comment by shift-reality** [comment]
Можно как-то заменить это поведение? т.е. убрать удаление связи по ПКМ

**Comment by Ni55aN** [comment]
Можно уменьшить размеры svg
 
```css
svg.connection { // dirty fix, path coordinates are incorrect with default 1px for some reason
  width: 12px;
  height: 12px;
}
```

в общем в комментарии изложена суть. И блокировать события на самом SVG не получается без ущерба для path

**Comment by shift-reality** [comment]
работает костыль выше, **спасибо**

**Comment by Ni55aN** [comment]
пока закрывать нет смысла, все же проблема с svg с единичными размерами или игнорированием событий (pointer-event: none) не работает для SVG

https://stackoverflow.com/a/13977580/3853903

**Comment by Ni55aN** [comment]
https://github.com/retejs/connection-plugin/issues/5
https://github.com/retejs/rete/issues/261#issuecomment-467164852

С выходом этого плагина можно будет удалить `el.addEventListener('contextmenu'` из rete-connection-plugin

UPD: удалил в 0.4.4
