### ISSUE TITLE
Need guidance: Trying to understand the code. Unable to find a starting point.

### ISSUE THREAD

**Issue by goodmite** [retejs/rete#279]
I spent hours trying to go through the code of this library, but no success.
I can't find the code which does DOM manipulation (Node creation, path creation updation). Where are all SCSS/CSS files? In this repo, I can't find any.

Can you give a very basic walkthrough of how a node is created on the editor? I will pick up from there.

Again, thanks for this great library!

**Comment by Hatead1** [comment]
search it in plugin's.. vue-render-plugin, connection-plugin.

**Comment by Ni55aN** [comment]
![photo_2019-03-17_20-59-59](https://user-images.githubusercontent.com/8259641/54496410-a5f61280-48f7-11e9-9905-3b9b2e850bd1.jpg)
