### ISSUE TITLE
Как добавить новый Output из Vue-компонента?

### ISSUE THREAD

**Issue by shift-reality** [retejs/rete#280]
Можно ли это реализовать?
Нужно сделать такой блок для ветвления, чтобы на него добавлять варианты, а выходы добавлялись по мере добавления новых вариантов..
Вот мой код: https://pastebin.com/ywCtpj1b
Но я застрял дальше на этапе связи с rete... не получается достучатся к node...
Помогите, плиз

**Comment by Ni55aN** [comment]
нудно внутри builder подписаться на событие, которое будет эмитить контрол, и по нему уже менять что-то в ноде

**Comment by shift-reality** [comment]
а метод builder не исполняется если использовать render=vue

**Comment by shift-reality** [comment]
а в конструкторе еще нет контекста вуа

**Comment by shift-reality** [comment]
а стоп, туплю
Подписку нужно внутри ноды делать а не контрола...

**Comment by shift-reality** [comment]
ну в любом случае:
`var cases = new MenuItemsMngControl(this.editor, "cases");
        node.addInput(inp1).addOutput(outm)
                .addControl(cases);
        cases.vueContext.$on('taskAdded', () => {            console.log('works!!');        })`
не сработало (нет контекста)

**Comment by Ni55aN** [comment]
скиньте живой пример

**Comment by shift-reality** [comment]
а у вас нет шаблона для пустой сценки с vue?

**Comment by Ni55aN** [comment]
на codepen есть демки

**Comment by shift-reality** [comment]
https://codepen.io/shift-reality/pen/wOmyMV там где HERE
но код не мой, просто для примера нашел
Вот вопрос, как из VUE-rete-контрола выбросить событие аж в Rete-компонент ?

**Comment by shift-reality** [comment]
ну или вопрос : как из КОМПОНЕНТА получить контекст КОНТРОЛА ?

**Comment by shift-reality** [comment]
не создавать же третий вуе исключительно для событий...

**Comment by Hatead1** [comment]
https://codepen.io/hatead1/pen/KEpmYz - я тут меняю тип входов/выходов на лету, может подойдет

**Comment by Ni55aN** [comment]
> ну или вопрос : как из КОМПОНЕНТА получить контекст КОНТРОЛА ?

нежелательно так делать, это приведет к сильной связности. Тем более, сразу после addControl контекст не будет создан, так как это проходит асинхронно.

В примере выше как раз правильно сделано.

В контрол нужно передать коллбэк (если достаточно подписываться только один раз)

```js
var VueNumControl = {
  props: [ ...., 'onChange'],


class NumControl extends Rete.Control {
  constructor(emitter, key, readonly, onChange) {
  .....
  this.props = { ...., onChange };


var nc = new NumControl(this.editor, 'num', false, () => console.log('Its alive!!!!'))
```

**Comment by shift-reality** [comment]
Действительно, я что-то не подумал о таком варианте
Спасибо всем!

**Comment by shift-reality** [comment]
А можете еще подсказать, как выключить зум по dblclick на редакторе ?
Раздражает, когда просто дважды кликнул, а оно приближает
Есть же колесико, его достаточно

**Comment by Ni55aN** [comment]
не ленитесь искать в issues

https://github.com/retejs/rete/issues/204#issuecomment-434440051

**Comment by shift-reality** [comment]
Спасибо!!

**Comment by shift-reality** [comment]
:)

**Comment by shift-reality** [comment]
Наверное поспешил закрывать
А как сделать, чтобы Выходы справа были на уровне пунктов меню ?
![Untitled](https://user-images.githubusercontent.com/29734946/54451194-f5eba280-475a-11e9-9015-c57523666f8f.png)
Зеленым отметил выходы, красным контрол (каждый пункт это элемент Li+input внутри общего контрола), контрол имеет ключ "items"..
___
- Есть идея добавлять множество rete-контролов (например, MenuItemControl, получится 1 пункт = 1 рете контрол на ноде) , и изменить шаблон ноды, чтобы он выводил Выходы в шаблоне согласно порядку пунктов меню..
___
-Или оставить как есть (1 контрол на все пункты) а выводы как-то стилями подвинуть, чтобы просто визуально подходило (мне не нравится этот вариант)
___
-Как сделать правильно?

**Comment by Ni55aN** [comment]
Это уже общий вопрос по поводу верстки. 

Сейчас сделано все блоками. Список output, control и input.  Можно обернуть .output в блоки и назначить его родителю display: flex, таким образом сделать такие блоки в ряд

**Comment by shift-reality** [comment]
нет, вопрос ### архитектуры, а потом верстки в конце

**Comment by Ni55aN** [comment]
> А как сделать, чтобы Выходы справа были на уровне пунктов меню ?

это не об архитектуре

**Comment by shift-reality** [comment]
1) вопрос в том делать ли 1 контрол для каждого пункта меню или сделать 1 общий для всех, а в его состоянии хранить пункты ?
2) Предложенный вариант с колбеком при горячей замене почему-то перестает работать...

**Comment by Ni55aN** [comment]
1. как вам угодно
2. только живой пример поможет разобраться
