### ISSUE TITLE
Task Delay Component 

### ISSUE THREAD

**Issue by zellb** [retejs/rete#281]
Im stuck while trying to create a task based component which basically pass its input to output by delaying the execution of the next block based on rx pipe of distinctUntilChanged and debounceTime.

    constructor() {
        super('Delay');
        this.task = {
            outputs: {result: 'output', action: 'option'},
            init(task) {

                task.closed = ['action'];

                task.component.subscription = task.component.subject.pipe(distinctUntilChanged(), debounceTime(10000)).subscribe( async data => {
                    task.closed = [];
                    await task.reset();
                    await task.run(data);
                    task.closed = ['action'];

                });

            }
        };
    }

    worker(node, inputs, data) {

        if (inputs['input'] && inputs['input'].length > 0) {

            const res = inputs['input'][0];

            if (this.closed.includes('action')) {
                this.component.subject.next(res);
            }

            return {result: res};
        }
    }

As you can see here Im closing the action output till the delay condition is met. This is working as expecting but things got complicated if I connect to delay blocks in a series since the same component instance is used for different nodes resulting in multiple next call on my delay subject. Any help would be appreciated

**Comment by Ni55aN** [comment]
`worker` may be async, so you can pause execution for a while.

async worker(node, inputs, data) {
    const res = inputs['input'][0];
 
   await delay(1000);

   return {result: res};

**Comment by zellb** [comment]
I don't need to pause execution because previous block (BLOCK A) which is a task based component should still be able to send data to delay component (BLOCK B) and delay component should gather these data and only return if the continuous data sent from BLOCK A doesn't change for a given amount of time. 

BLOCK A (trigger task from web socket) ---> continuous stream ----> Block B (check if data hasn't changed for specific amount of time) ---> return value or reset timer

**Comment by Ni55aN** [comment]
I got your thought.  I'll see what we can do with it.

**Comment by Ni55aN** [comment]
I guess `task.component.subscription` will not working with a multiple Delay nodes

There is a solution without RxJS, but it is also complicated
https://codepen.io/Ni55aN/pen/XGyqvY

By the way, Rx.js can be useful in some cases using Rete.js and I had an idea for another plugin (or task-plugin modification)

**Comment by zellb** [comment]
Absolutely would love to see RxJS on task plugin

**Comment by zellb** [comment]
I was able to solve this issue by getting rid of task plugin and use observables as input/output for each of my components and observers on each control. This way Rete is used only to link and apply different operations on observers from the controls (once only in process event) ,while Rxjs is used for sending/receiving data. Example : 

```
export class NumControl extends Control {
    component: any;
    props: any;
    vueContext: any;
    subject = new BehaviorSubject(this.value);


    constructor(public emitter, public key, map: Map<TemplateControl, any>, public value: number,removable = false, readonly = false) {
        super(key);

        this.component = map.get(TemplateControl.NumControl);
        this.component.bind(this);
        this.props = { emitter, ikey: key, readonly, removable , removeInput: this.removeInput.bind(this)};
    }

    putData(key: string, data: any) {
        super.putData(key, data);
        this.subject.next(data);
    }

    setValue(val) {
        this.vueContext.value = val;
    }
}
```

```
export class NumberComponent extends Component {

    templates: Map<TemplateControl, any>;

    constructor(templates: Map<TemplateControl, any>) {
        super('Number');
        this.templates = templates;
    }

    builder(node) {

        node.data.num = node.data.num  || 0;

        const out1 = new Output('num', 'Number', numSocket);
        node.addControl(new NumControl(this.editor, 'num', this.templates, node.data.num)).addOutput(out1);

        return node;
    }

    worker(node, inputs, outputs) {
        outputs['num'] = <NumControl> this.editor.nodes.find(n => n.id === node.id).controls.get('num').subject;
    }
}
```

```
export class DelayComponent extends Component {
    templates: Map<TemplateControl, any>;

    constructor(templates: Map<TemplateControl, any>) {
        super('Delay');
        this.templates = templates
    }

    async builder(node) {

        node.data.delay = node.data.delay || 10;

        const inp1 = new Input('input', 'Input', anySocket);
        const inp2 = new Input('delay', 'Delay (s)', numSocket);

        node.addInput(inp2);
        node.addInput(inp1);
        inp2.addControl(new NumControl(this.editor, 'delay', this.templates, node.data.delay, false));

        this.editor.on('connectioncreated', async (conn: Connection) => {

            if (conn.input.node === node && conn.input.key === 'input') {

                node.outputs.forEach(output => node.removeOutput(output));
                const output = new Output('output', 'Output', conn.output.socket);
                await node.addOutput(output);
                await node.update();
                this.editor.trigger('nodetranslated', {node});
            }

        });

        this.editor.on('connectionremoved', (conn: Connection) => {

            if (conn.input.node === node && conn.input.key === 'input') {
                node.outputs.forEach(output => node.removeOutput(output));
                node.update();
            }
        });
    }

    worker(node, inputs, outputs) {

        console.log('DELAY WORKER');


        const n1: Observable<any> = inputs['input'].length ? inputs['input'][0] : of(null);
        const n2: Observable<number> = inputs['delay'].length ? inputs['delay'][0] : <NumControl>this.editor.nodes.find(n => n.id === node.id).inputs.get('delay').control.subject;

        outputs['output'] = combineLatest(n1, n2).pipe(distinctUntilChanged((lhs, rhs) => {
            return lhs[0] === rhs[0] && lhs[1] === rhs[1];
        }), debounce(val => {
            return timer(val[1] * 1000)
        }), map(res => res[0]));

    }
}
```
