### ISSUE TITLE
Not Found: *.vue.map error when serving rete

### ISSUE THREAD

**Issue by blauwepiet** [retejs/rete#283]
When serving Rete through Django with a webpack build it says for every component of rete that uses Vue that it can not be found.

What are these *.vue.map files? And where/how can I find them or compile them?

**Comment by blauwepiet** [comment]
Are these like source maps and do they need to be compiled with webpack?

**Comment by iKlsR** [comment]
@blauwepiet I would think so, so not a rete issue, for laravel mix I have to enable these, this might be of some help https://stackoverflow.com/a/31101665.

**Comment by blauwepiet** [comment]
I forgot to close this issue after your comment, but I already had the source-map option on, eventually it resolved itself by tweaking the webpack config but due to further developement and this issue being 2 months old I forgot what it was that solved it...

If anyone manage to have this same issue, please contact me and we can compare our webpack configs to see where the potential problem lays.
