### ISSUE TITLE
Adding jumpers to sockets

### ISSUE THREAD

**Issue by pswin** [retejs/rete#286]
Well In a complex scenario. The diagram becomes a complete mess. It gets to look like spaghetti with a lot of connections which are crossed the components. So it becomes really hard to work. 

It would be a good idea if you add some jumpers with a name that connect to the node to each other without drawing connections. look at the picture:

https://i.stack.imgur.com/HqxdM.jpg

in the picture (from Altium designer). the users are able to specify names to pins (socket in our context). then by defining the same name somewhere else the connection is made between two nodes.

**Comment by Ni55aN** [comment]
> It gets to look like spaghetti with a lot of connections which are crossed the components.

You can reduce number of nodes using `rete-module-plugin` and  make connections more readable with `rete-connection-reroute-plugin`

The proposed solution with jumpers looks rather complicated, until I can confirm that it is worth implementing.
We'll take into account the opinions of others users
