### ISSUE TITLE
Connections not connecting to sockets

### ISSUE THREAD

**Issue by vandenesseml** [retejs/rete#288]
I have not been able to track this down, but mid development the connections connecting the nodes became separated from the sockets. I am expecting the connections to directly and seamlessly connect to the sockets to which they are connected. Is this a known issue and what should be the course of action to resolve this?
![image](https://user-images.githubusercontent.com/33128710/55885441-ed2e9680-5b77-11e9-9d89-b0c0a25d5f9d.png)

**Comment by Ni55aN** [comment]
This issue had been fixed in last version of `rete-connection-plugin`.

https://github.com/retejs/rete/issues/267

Please ensure that SVGs has `width: auto` and `height: auto`
