### ISSUE TITLE
Event listener subscribing multiple events

### ISSUE THREAD

**Issue by renjfk** [retejs/rete#290]
Subscribing multiple events no longer seems to be possible after typescript code migration due to type restrictions. I would suggest turning it into a string like it was before typescript migration which sounds kinda ugly or supporting array along with single event type something like...

```typescript
// emitter.ts
...
on<K extends keyof EventTypes>(names: K | K[], handler: (args: EventTypes[K]) => any) {
    (names instanceof Array ? names : (names as string).split(' ')).forEach(name => {
        if (!this.events[name])
            throw new Error(`The event ${name} does not exist`);
        this.events[name].push(handler);
    });

    return this;
}
...
```

![Screen Shot 2019-04-11 at 22 28 19](https://user-images.githubusercontent.com/15015690/55987197-a476fa80-5ca9-11e9-8067-16b8ef990991.png)

**Comment by Ni55aN** [comment]
How it would recognize type of `(args: EventTypes[K]) => any`?

**Comment by Ni55aN** [comment]
I've checked this. It should working now

**Comment by renjfk** [comment]
Cool, thanks for quick fix (;
