### ISSUE TITLE
rete-react-render-plugin [help wanted]

### ISSUE THREAD

**Issue by amazing-space-invader** [retejs/rete#291]
Hey. I'm trying to create render plugin for react, but I have problems with controls.

rendercontrol event
https://github.com/amazing-space-invader/rete-react-render/blob/master/src/react-renderer/index.js#L23

Rete.Control
https://github.com/amazing-space-invader/rete-react-render/blob/master/src/FieldControl.js#L21

In Vue render I seen AddComponent fires setValue into control and I'm don't know how to set it inside react component. I do not quite understand how to implement control with React and would be grateful for any help

**Comment by Ni55aN** [comment]
I'm working on React render plugin right now too :(

I'll give a feedback in about 2 hours

**Comment by amazing-space-invader** [comment]
@Ni55aN it's cool! I will wait your plugin

**Comment by Ni55aN** [comment]
https://www.npmjs.com/package/rete-react-render-plugin
v0.1.2 may has a bugs. It will be good if someone will test it

**Comment by Ni55aN** [comment]
Example: https://codesandbox.io/embed/72mjq7y0x0

**Comment by amazing-space-invader** [comment]
Awesome, thank you!
