### ISSUE TITLE
Store data globally

### ISSUE THREAD

**Issue by amazing-space-invader** [retejs/rete#293]
Hey! It is possible to save some data in global store, which provide that data to each other node without connection?

UserInput:
```
worker() {
  store.set('name', node.data.text);
}
```

TextNode:
```
worker() {
  return `Hello, ${store.get('name')}`;
}
```

![image](https://user-images.githubusercontent.com/12794753/56123740-be506000-5f7d-11e9-9f0e-625cd071d324.png)

**Comment by Ni55aN** [comment]
There are many methods. A few of them:

Access store in any component method
```js
const components = [new MyComp(store)];

class MyComp extends Rete.Component {
  constructor(store) {
    this.store = store;
  }
}

////

worker() {
  this.store.set('name', node.data.text);
}
```

or pass store to a workers only

```js
worker(node, inputs, outputs, { store }) {
}
////
engine.process
```
