### ISSUE TITLE
trigger process outside of vuecontrol component

### ISSUE THREAD

**Issue by akshayred** [retejs/rete#294]
I am trying to generate the form fields dynamically in a node using dynamic component. That I am able to achieve. But now I want to trigger the emitter process on change of value in that dynamically added field.
Please see the code I have written and search for @ todo want to trigger the process

https://codepen.io/akshaykelotra/pen/VNMNWa

Ajax calls written here are giving back values from drupal end.

**Comment by Ni55aN** [comment]
I guess you must to pass the emitter property to selectInput. As you have a nested components, you can use DI way

```js
var VueFieldDefaultValueControl = {
  props: ['getData', 'putData', 'emitter'],
  provide() {
      return {
        emitter: this.emitter
      }
....

const selectInput = {
   inject: ['emitter']
```

**Comment by jc-anguiano** [comment]
mmm... yesterday i "solved" a similar issue using trigger('process') from window.editor, it is a bad practice?

**Comment by Ni55aN** [comment]
> it is a bad practice

yes, because you cannot use several editors on the same page and in the SPA this leads to a memory leak when you go to another route/component

**Comment by Ni55aN** [comment]
@jc-anguiano https://github.com/retejs/rete/issues/293#issuecomment-483245667

**Comment by akshayred** [comment]
Thanks @Ni55aN , it worked for me.
