### ISSUE TITLE
Hover on socket shows socket name and undefined.

### ISSUE THREAD

**Issue by akshayred** [retejs/rete#297]
When hovering over socket, it shows the socket name passed to it's constructor and in next line it shows undefined. Can we add some description for socket so that in tooltip it shows name as well as description about the socket?

**Comment by Ni55aN** [comment]
This was fixed in rete-vue-render-plugin@0.3.3

What render plugin are you using?

**Comment by akshayred** [comment]
@Ni55aN 
I am using 0.2.6 render plugin. 
I updated it to 0.3.3 but than the whole graph stopped working. I might have to update other libraries too. So can you please help me and let me know which all libraries I should update. Below I am giving a list of libraries I am using.
One thing is that I can't use a NodeJS based application as I am using retejs in a drupal 8 module and it has to work standalone without any dependency on NodeJS.
With below combination rete is working fine.
https://cdn.jsdelivr.net/npm/rete@1.1.0/build/rete.min.js: {type: external, minified: true}
    https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js : {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-vue-render-plugin@0.2.6/build/vue-render-plugin.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-connection-plugin@0.4.1/build/connection-plugin.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/alight@0.14.1/alight.min.js: {type: external, minified: true}
    https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-context-menu-plugin@0.3.2/build/context-menu-plugin.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-area-plugin@0.2.0/build/area-plugin.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-comment-plugin@0.2.0/build/comment-plugin.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-history-plugin@0.1.0/build/history-plugin.min.js: {type: external, minified: true}
    https://cdnjs.cloudflare.com/ajax/libs/vue-resource/1.5.1/vue-resource.min.js: {type: external, minified: true}
    https://unpkg.com/vue-multiselect@2.1.0: {type: external}

**Comment by Ni55aN** [comment]
> I updated it to 0.3.3 but than the whole graph stopped working.

Are the any errors in console?

rete@1.1.0, rete-connection-plugin@0.4.1, etc is not a latest versions

![Opera Snapshot_2019-04-30_224236_rete js org](https://user-images.githubusercontent.com/8259641/56988677-4c8d2e80-6b99-11e9-8b3d-ceb7f9430d57.png)

**Comment by akshayred** [comment]
Thanks for the updates. I used all latest libraries. So below is what I am using now. And I am getting attached errors.

https://cdn.jsdelivr.net/npm/rete@1.3.0/build/rete.min.js: {type: external, minified: true}
    https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.min.js : {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-vue-render-plugin@0.3.5/build/vue-render-plugin.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-connection-plugin@0.7.2/build/connection-plugin.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/alight@0.14.1/alight.min.js: {type: external, minified: true}
    https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-context-menu-plugin@0.3.7/build/context-menu-plugin.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-area-plugin@0.2.1/build/area-plugin.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-comment-plugin@0.5.1/build/comment-plugin.min.js: {type: external, minified: true}
    https://cdn.jsdelivr.net/npm/rete-history-plugin@0.2.1/build/history-plugin.min.js: {type: external, minified: true}
    https://cdnjs.cloudflare.com/ajax/libs/vue-resource/1.5.1/vue-resource.min.js: {type: external, minified: true}
    https://unpkg.com/vue-multiselect@2.1.0: {type: external}
![rete_error](https://user-images.githubusercontent.com/43290688/57017511-28832900-6c3d-11e9-8493-83bf488f60ac.PNG)

**Comment by Ni55aN** [comment]
@akshayred https://rete.js.org/#/docs

When you are using UMD modules (.min.js), you have to pass `default` property to `use()` (for plugins that using rete-cli@v0.5.0 and later)
```js
editor.use(ConnectionPlugin.default)
```

Also use a console.log to figure out what value contains in VueRenderPlugin, ConnectionsPlugin, etc

**Comment by akshayred** [comment]
Thanks @Ni55aN  
After updating plugins to latest this issue got resolved.
