### ISSUE TITLE
Connection line offset

### ISSUE THREAD

**Issue by fleskovar** [retejs/rete#298]
When clicking and dragging from a socket to an input, the connection svg line gets drawn in the wrong position, always with an offset in the x axis of the screen.

Using code from the dataflow example (https://codepen.io/Ni55aN/pen/xzgQYq) and the following dependencies:

"dependencies": {
    "core-js": "^2.6.5",
    "rete": "^1.3.0",
    "rete-area-plugin": "^0.2.1",
    "rete-comment-plugin": "^0.5.1",
    "rete-connection-mastery-plugin": "^0.1.0",
    "rete-connection-plugin": "^0.7.2",
    "rete-context-menu-plugin": "^0.3.7",
    "rete-history-plugin": "^0.2.1",
    "rete-vue-render-plugin": "^0.3.5",
    "vue": "^2.6.10"
  },

 Image example: https://imgur.com/a/9w0eano

**Comment by Ni55aN** [comment]
I need a live example or at least static .html to figure out what the problem is

**Comment by fleskovar** [comment]
I have just figured out the problem! My <div id="rete"> was a child of a <div> that had "style='text-align: center;'"

Once I removed the style of the parent div, the problem got solved.

**Comment by makeitrein** [comment]
Thx @fleskovar for reporting and thx @Ni55aN for making this wonderful library. I just ran into the same issue after downloading and running locally the React Rete example found at: https://codesandbox.io/s/retejs-react-render-t899c

<img width="1440" alt="Screen Shot 2019-06-03 at 1 22 45 PM" src="https://user-images.githubusercontent.com/2068463/58832025-e023a600-8602-11e9-81f3-2de6a645f691.png">


While it works fine in CodeSandbox, having text-align: center makes the line appear at the far right of the screen in my local environment.

**Comment by Ni55aN** [comment]
@makeitrein I cannot reproduce based on exported ZIP. Check the styles of parent elements

**Comment by makeitrein** [comment]
> @makeitrein I cannot reproduce based on exported ZIP. Check the styles of parent elements

Thx for checking - it was a combo of text-align center and some position absolute I added to help test. Subscribed to your Patreon!

**Comment by Ni55aN** [comment]
@makeitrein thanks!
