### ISSUE TITLE
Scrolling on Multiselect zooms the editor.

### ISSUE THREAD

**Issue by akshayred** [retejs/rete#300]
I have added a multiselect (vue component) field. When I try to scroll using mouse wheel through the options, it triggers the zoom and don't scroll it.
Also if I try to scroll it using the mouse pointer, it do scroll but also shifts the position of node up and down.

**Comment by Ni55aN** [comment]
Can you share it on codepen/jsfiddle?

**Comment by akshayred** [comment]
@Ni55aN 
Here is a codepen which have multiselect component added to a node.
https://codepen.io/akshaykelotra/pen/VNMNWa

**Comment by Ni55aN** [comment]
@akshayred VueMultiselect dependency is missed

**Comment by akshayred** [comment]
@Ni55aN Multiselect seems to work fine at my end. But can you let me know which dependency is missing?

**Comment by Ni55aN** [comment]
https://codepen.io/akshaykelotra/pen/VNMNWa doesn't working from my side

**Comment by akshayred** [comment]
Yes, because that Multiselect is being fed with options coming from drupal database. I can write a working codepen and give you a link.

**Comment by akshayred** [comment]
@Ni55aN Here is the updated code pen with a multiselect example. when you will open the select dropdown and try to scroll through the options it will zoom and not scroll it.

https://codepen.io/akshaykelotra/pen/VNMNWa

**Comment by akshayred** [comment]
@Ni55aN 
I added the eventListener but still it is not working. I have updated the same codepen. Can you please review and let me know how to fix it?

https://codepen.io/akshaykelotra/pen/VNMNWa

**Comment by Ni55aN** [comment]
Its working for me.

`document.querySelector` is an example and you should to set event on `multiselect`

```html
<multiselect v-model="value" @mousewheel.native.stop=""
```
But this will prevent scroll on all select control, not a dropdown list

**Comment by Ni55aN** [comment]
Is the problem still actual?

**Comment by akshayred** [comment]
@Ni55aN 
Sorry for not updating but yes that issue is still there. I tried what you suggested but still it gives that issue.

**Comment by Ni55aN** [comment]
Can not reproduce. After I open the dropdown and scroll the list, the scene not zooming

**Comment by akshayred** [comment]
Can you please put a codepen example of it working for you?

**Comment by akshayred** [comment]
BTW, we are using Retejs for one of Drupal module project which we are contributing to the community. You can find that module here. https://www.drupal.org/project/if_then_else/

**Comment by Ni55aN** [comment]
@akshayred this one https://codepen.io/akshaykelotra/pen/VNMNWa

**Comment by Ni55aN** [comment]
What scroll behaviour do you expecting?

**Comment by akshayred** [comment]
@Ni55aN 
I checked the example you created. So what I am expecting is that when I click open the select option and scroll on it, it should scroll the options and not zoom in, zoom out the whole editor. And I tested on your example, it is not working there too.

**Comment by Ni55aN** [comment]
@akshayred I can't figure out why this not working for you

![ezgif-4-e8690e6397a6](https://user-images.githubusercontent.com/8259641/60497584-cdfa5d80-9cbd-11e9-86d5-f46db215261b.gif)

**Comment by metareason** [comment]
@Ni55aN I can also reproduce the issue, it zooms when the mouse is over the 'Select fields' area, not the dropdown with testx items:

* Click 'Select Fields'
* **Don't** move the mouse (in your video you move the mouse downwards into the testx items)
* Scroll with mouse wheel
* The whole page zooms

![rete-scroll-zoom](https://user-images.githubusercontent.com/480747/60498179-b5536d00-9ce8-11e9-97bd-2287bbabbcd5.gif)

Thanks for your work on Rete - I am trying it out at the moment!

**Comment by Ni55aN** [comment]
>  I can also reproduce the issue, it zooms when the mouse is over the 'Select fields' area, not the dropdown with testx items:

this is expected behavior, because any closed <select> doesn't prevent scrolling 

https://www.w3schools.com/code/tryit.asp?filename=G5LLJ28FICUD

https://vue-multiselect.js.org/#sub-getting-started (Option groups)

**Comment by Ni55aN** [comment]
Anyway, you can add mousewheel.stop attribute, as I mentioned above
```html
<multiselect v-model="value" @mousewheel.native.stop=""
```

But it's not UX friendly

**Comment by drupalchamp** [comment]
It's working when i add this line in chrome browser. But it doesn't work in Mozilla.

**Comment by akshayred** [comment]
@Ni55aN Can you please suggest some solution to this issue for Mozilla?

**Comment by Ni55aN** [comment]
@akshayred @drupalchamp `@wheel.native.stop="wheel"`
