### ISSUE TITLE
Uncaught Error: Node view not found

### ISSUE THREAD

**Issue by aj-ee** [retejs/rete#301]
I am getting the following error in a vuejs based app with multiple pages.

```
Uncaught Error: Node view not found
    at PickerView.getPoints (connection-plugin.esm.js?1be2:183)
    at PickerView.renderConnection$1 (connection-plugin.esm.js?1be2:205)
    at PickerView.updatePseudoConnection (connection-plugin.esm.js?1be2:172)
    at Picker.set (connection-plugin.esm.js?1be2:304)
    at Picker.pickInput (connection-plugin.esm.js?1be2:266)
    at Flow.act (connection-plugin.esm.js?1be2:333)
    at pointerUp (connection-plugin.esm.js?1be2:381)
```

When I first load the page with a rete editor everything works as expected, but if I navigate to another page & then back to the rete page I get the error above.

I have created a project using to demonstrate the issue:

https://github.com/aj-ee/rete-bug

```
git clone
npm install
npm run serve 
```

1. Navigate directly to page two: rete editor works fine with no errors
2. Navigate to page one and back to page two: you will see the error above appear in your logs.

Not sure if I'm missing something or if this is an actual bug but any help would be greatly appreciated!

**Comment by Ni55aN** [comment]
You should to `destroy()` editor before leaving the page
It is necessary to prevent a memory leak (for example, remove event listener on window in plugins). 

This is exactly what happens in the `rete-connection-plugin` that listen to the window event. It has not been removed, so when you re-enter the page, the second handler is added and they conflict

https://github.com/retejs/rete.js.org/blob/91f941a77a055169c174edc8542acdcf19429c57/src/components/Examples/Example.vue#L21

**Comment by aj-ee** [comment]
Excellent.

I had to add the following:

```
beforeDestroy() {
  this.editor.destroy();
}
```

working fine now, thanks!
