### ISSUE TITLE
Grouping nodes

### ISSUE THREAD

**Issue by rdinnik** [retejs/rete#302]
Enhancement request:
I need to group nodes when I work on a large diagram. The grouping functionality should provide capability either for collapsing and expanding of a group or for opening a sub-flow(group) in a new diagram. When user groups several nodes the group node should be created and inherited (creates proxies for) in-sockets of start nodes and out-sockets for end-nodes involved in sub-flow.

**Comment by Ni55aN** [comment]
Try the comment plugin

**Comment by rdinnik** [comment]
Can't find that plugin (comment) here: https://rete.js.org/#/docs/plugins/
The functionality is very similar to "module" plugin but should provide the drill-down and automatic creating of ports(in- out- sockets proxies).

**Comment by Ni55aN** [comment]
https://rete.js.org/#/docs/plugins/comment

This plugin doesn't support a collapsing group of nodes. It's a bit complicates an editor

**Comment by mick-d** [comment]
Hi, I am not sure this is the best place to ask this question @Ni55aN but:
- how complicated would it be to modify the code to group nodes (recursively, with groups possibly themselves inside a subflow)?
- can Rete be used to generate any kind of code dynamically as the general flow is built ("this action" --> "this code is generated in language X") ?
Rete looks amazing but these two features would be essential in my case before using it.

**Comment by Ni55aN** [comment]
Hi @mick-d 

> how complicated would it be to modify the code to group nodes (recursively, with groups possibly themselves inside a subflow)?

You can create an issue in the related repo (comment plugin). I'll be able to impelemt this asap.

> can Rete be used to generate any kind of code dynamically as the general flow is built

Yes, you can generate [JSON scheme](https://rete.js.org/#/docs/editor#lang=en&tosearch=The%20data%20has%20the%20following%20structure%3A)

**Comment by mick-d** [comment]
@Ni55aN , many thanks for the fast reply!

Just to clarify to make sure the subflow issue is best adapted to the comment plugin: what would be amazing to do with Rete.js is:
- to be able to group nodes to create a single node with the inputs and outputs inferred from the underlying node, and to be able to do that in a hierarchically (i.e. a subflow can also contain a node which is a subflow)
- to expand and collapse this node-subflows at will in the GUI (the general flow will expand or shrink on the canvas as a result)
- to be able to put any of this node-subflow in a menu of nodes (when the user put a node-subflow on the canvas he can then expand it as describe above)

Should i put all these in the command plugin repo as an issue?

**Comment by mick-d** [comment]
@Ni55aN  regarding the modification of code to group nodes, the objective is to create a master script in a custom workflow engine (written in python) which would match the visual flow, so that:
- each time the user create a node, the associated workflow engine python code to create that node would be automatically written in the master script
- each time the user create a connection, the associated workflow engine python code to generate that connection between two nodes would be automatically written in the master script

In the end the user may not even have to run anything, just to have access the the master script generated this way. Would that be possible?

**Comment by haris-75** [comment]
Can we make Collapse-able Nodes in reteJS like this in the provided Link: 
https://files.gitter.im/5b0f369ed73408ce4f9b523e/foRC/collapser.gif

**Comment by Ni55aN** [comment]
@haris-75 you can customize nodes

Angular render plugin: https://github.com/retejs/angular-render-plugin#custom-node, https://github.com/retejs/rete/issues/318
Vue render plugin: https://github.com/retejs/vue-render-plugin#react-render
React render plugin: https://github.com/retejs/react-render-plugin#react-render

**Comment by haris-75** [comment]
Thanks man
