### ISSUE TITLE
Renaming a node label breaks the graph

### ISSUE THREAD

**Issue by akshayred** [retejs/rete#304]
To reproduce this issue. Create a rete graph and save it's JSON output.

Now in your js rename one of the node's label and try to regenerate the graph using JSON save earlier. The node whose label we renamed don't load plus the connections are also removed. Let me know if it is clear enough to reproduce the issue.

**Comment by Ni55aN** [comment]
The node name is an identifier, not a label. That is, you should not change it, without performing the migration. If you just want to change the displayed text, use custom components and i18n

**Comment by akshayred** [comment]
@Ni55aN  What do you mean by using custom component to show the node name? How can I do that?

**Comment by Hatead1** [comment]
My decision
Clone vue-render-plugin, edit Node.vue, change 
```
<template lang="pug">
.node(:class="[selected(), node.name] | kebab")
  **.title {{node.name}}**
```
to 
```
<template lang="pug">
.node(:class="[selected(), node.name] | kebab")
  **.title {{node.meta.title}}**
```
Add to builder() function of your component:
`node.meta.title="New name";`

**Comment by Hatead1** [comment]
If U need access to title via JSON, use node.data object (node.data.title).

**Comment by Ni55aN** [comment]
./Node.vue
```js
<template lang="pug">
.node(:class="[selected(), node.name] | kebab")
  .title {{i18n(node.name)}}

  // Outputs
  .output(v-for='output in outputs()' :key="output.key")
    .output-title {{i18n(output.name)}}
    Socket(v-socket:output="output", type="output", :socket="output.socket")

  // Controls
  .control(
    v-for='control in controls()',
    v-control="control"
  )

  // Inputs
  .input(v-for='input in inputs()' :key="input.key")
    Socket(v-socket:input="input", type="input", :socket="input.socket")
    .input-title(v-show='!input.showControl()') {{i18n(input.name)}}
    .input-control(
      v-show='input.showControl()'
      v-control="input.control"
    )
</template>

<script>
import VueRenderPlugin from 'vue-render-plugin';
import i18n from 'i18n'; // function to translate text

export default {
  extends: VueRenderPlugin.Node,
  methods: {
    i18n(text) { return i18n(text) }
  }
}
</script>
```

```js
import CustomNodeComponent from './Node.vue';

class MyComponent extends Rete.Component {
    constructor(){
        // ...
        this.data.render = 'vue';
        this.data.component = CustomNodeComponent; // Vue.js component, not required
        this.data.props = {}; // props for the component above, not required
    }
}
```

**Comment by azakero** [comment]
@Ni55aN @Hatead1  Hi. I'm trying to achieve this but in my case it should be like the user can change the node name and also save it in localstorage as json. Right now if I follow what @Hatead1 mentioned to change the name via node.meta.title, the name disappears on page refresh as it is not being saved via json into localstorage. 

So my question is how can I add this in json so that I can save it in localstorage?

Here's how my event listener looks like :

```
async saveToLocalStorage( editor: NodeEditor, engine: Engine ) = {
    
    const editorData = editor.toJSON();

    console.log('editor from change listener: ', editor);
    console.log('editorData from change listener: ', editorData);

    this.localStorage.set(
      `editorData`,
      JSON.stringify(editorData)
    );

}
```
The first log shows meta as a property with the updated title. But the second one does not have meta property. 

How can I add meta property with the title in the json?
