### ISSUE TITLE
How is it possible to make an editor.clear without removing the position of the nodes?

### ISSUE THREAD

**Issue by gonzajet** [retejs/rete#305]
Hello, I tell you my situation, I have several nodes divided on the screen were to resolve the Responsive problem with the nodes, I perform a function where I re-draw all the nodes in a specific position. The fact is that I need to make an editor.clear to avoid duplicates, but I need to converse the position and then use it in my function. 

Is there any way to make an editor.clear and converse the position of all the nodes?

**Comment by Ni55aN** [comment]
How do you re-draw nodes? 
You can just change a nodes position: 

```js
const node = editor.nodes[0];
editor.view.nodes.get(node).translate(newX, newY)
```
