### ISSUE TITLE
Singleton Node

### ISSUE THREAD

**Issue by flobiber** [retejs/rete#308]
Is there a way to generate nodes that are unique (singleton) per editor? 
Like a start (entry-point) & end (end-point).

**Comment by Ni55aN** [comment]
Yes, you can prevent adding node
```js
editor.on('nodecreate', node => {
    const names = ['Entry', 'End'];

    if (names.includes(node.name) && editor.nodes.find(n => names.includes(n.name))) {
        alert(node.name + ' node already exist');
        return false;
    }
})
```

**Comment by flobiber** [comment]
Good solution! Is it also possible to be sure that my singleton node is always there?

**Comment by Ni55aN** [comment]
Do you mean that the node must be in the scene always? You can check `editor.nodes` when necessary

**Comment by flobiber** [comment]
Yes that i mean... okay i have to implement that manually?

**Comment by Ni55aN** [comment]
Yes, you should manage it as you need, as there are many options:

- add `Entry`/`End` nodes to initial scheme and disallow removing (prevent `noderemove`)
- show alert on verifying scheme on save/change

**Comment by flobiber** [comment]
It's working thank you!
