### ISSUE TITLE
Name clash when extending Component in TypeScript

### ISSUE THREAD

**Issue by pszalanski** [retejs/rete#309]
We have a custom component, similar to this one:
```typescript
export class SomeNode extends Component {

  public static nodeName = 'TheNode';

  constructor() {
    super(SomeNode.nodeName);
  }

  async builder(node: Node) {
    return node;
  }

  worker(node: Node, inputs: IOs, outputs: IOs, ...args: any): any {
  }
}
```

Now our compiler gets massive problems parsing which type `Node` is which. The type in `worker` is not the same as the one in `builder`. The easiest fix would be if you named your classes with different names and not have multiple classes with the name `Component` or `Node`.

Btw, it would be easie to subclass based on my needs if I could extend `worker` optionally. In our project, we only need the designing features, but no tasks or workers at all.

Or do you have an easy solution for me, which does not involve aliasing all the imports?

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/blob/master/src/engine/component.ts#L2

`worker`'s node and `builder`'s node are not the same

**Comment by pszalanski** [comment]
Yes, I understand. But they should not have the same name. It's bad for the typescript compiler. I don't want to be forced to alias the imports.

**Comment by Ni55aN** [comment]
Whats problem?

```js
import { Node } from 'rete';
import { Node as NodeData, Inputs, Outputs } from 'rete/types/core/data';

export class SomeNode extends Component {

  public static nodeName = 'TheNode';

  constructor() {
    super(SomeNode.nodeName);
  }

  async builder(node: Node) {
    return node;
  }

  worker(node: NodeData, inputs: Inputs, outputs: Outputs, ...args: any): any {
  }
}
```

**Comment by pszalanski** [comment]
Quite eas: As soon as I have to type `Something as SomethingElse` it means that there is a name clash. And this should *never* happen in the same library. IDEs and code editors usually cannot handle this, because the alias is a custom name invented by me, the programmer. Simply rename the class in your library and automatically importing needed classes works automatically.

**Comment by Ni55aN** [comment]
I haven't see problems with VS Code

**Comment by Ni55aN** [comment]
Please check the `v1.3.1-rc.1`

**Comment by pszalanski** [comment]
It works! Thank you very much, for changing this so quickly!
