### ISSUE TITLE
Unselect node, if clicked on editor

### ISSUE THREAD

**Issue by flobiber** [retejs/rete#311]
Is it possible to unselect a node if i like on the editor where no other node is places?

**Comment by Ni55aN** [comment]
On the user side, no. In which case do you need it?

**Comment by flobiber** [comment]
Our UX-Requirements specify that behavior.

**Comment by Ni55aN** [comment]
For example:
```js
editor.on('click', () => {
    editor.selected.clear();
    editor.nodes.map(n => n.update())
});
```

**Comment by flobiber** [comment]
Works like a charm!

**Comment by sushibear** [comment]
Does not work for me but I need this behaviour as well.
