### ISSUE TITLE
Validate: All in/outputs should be set

### ISSUE THREAD

**Issue by flobiber** [retejs/rete#312]
Is there a possibility to check if all inputs / outputs are set? 
I want to check if all sockets have a connection.

**Comment by Ni55aN** [comment]
```js
Array.from(node.inputs).every(([key, input]) => input.connections.length > 0)
```

**Comment by flobiber** [comment]
Works! 
`  public GetAllUnconnectedNodes() {
    return this.editor.nodes.filter( node => {
      const allInputsSet = Array.from(node.inputs).every(([key, input]) => input.connections.length > 0);
      const allOutputsSet = Array.from(node.outputs).every(([key, output]) => output.connections.length > 0);
      return !(allInputsSet && allOutputsSet);
    });
  }`
