### ISSUE TITLE
Double-clicked node

### ISSUE THREAD

**Issue by flobiber** [retejs/rete#313]
Possible to attach on a node-double-clicked event?

**Comment by Ni55aN** [comment]
```js
editor.on('rendernode', ({ el }) => {
  // el.addEventListener('...
});
```

**Comment by flobiber** [comment]
Works! Thank you very much for your VERY good support!

```
    this.editor.on('rendernode', ({el, node}) => {
      el.addEventListener('dblclick', () => {
        console.log(node);
      });
    });
```

**Comment by Hatead1** [comment]
Don't work for nodes, created from JSON.

**Comment by Ni55aN** [comment]
@Hatead1 you are doing something wrong. You can check https://codepen.io/Ni55aN/pen/rpOKNb and add that code after `editor.use(TaskPlugin);`

**Comment by Hatead1** [comment]
It's work if defined before editor.toJSON(n);

**Comment by Ni55aN** [comment]
of course
