### ISSUE TITLE
How to extend event list with custom events

### ISSUE THREAD

**Issue by pszalanski** [retejs/rete#314]
Is it possible to somehow extend the map of events with custom event types? Before, it was just a string which we would need to bind. Now, I get type errors for my custom event names.

Are we even supposed to invent custom events?

**Comment by Ni55aN** [comment]
https://github.com/retejs/readonly-plugin/blob/master/src/index.ts#L3

**Comment by pszalanski** [comment]
Ah, this is simply a matter of understanding typescript features. Thank you!

**Comment by liesislukas** [comment]
seems like you don't need typescript, just bind and you can use "on" after it.

```
  editor.bind('nodeupdated');
  editor.on('nodeupdated', (data) => {
    console.log(`#202114585959280 nodeupdated:: `, data);
  });
  editor.trigger('nodeupdated', {foo: 'bar'});
```
