### ISSUE TITLE
Dynamically adding socket to node from Vue control

### ISSUE THREAD

**Issue by akshayred** [retejs/rete#317]
I have an example where we can add sockets to nodes from the component. 
http://jsfiddle.net/vmxdcLbq/27/

But is there a way to add socket from Vue control function to a node? So rather than calling the addInput in builder function of component, we can call it from one of the change event methods of control?

**Comment by Ni55aN** [comment]
You can pass the `node` instance to the control, but it can lead to tight coupling.

I think you need somethink like this:

```js
var ctrl1 = new CheckBoxControl('chips', () => /* add input to node */, () => /* remove input */)
```
