### ISSUE TITLE
customize nodes in Angular app

### ISSUE THREAD

**Issue by Githamza** [retejs/rete#318]
I would change Components/nodes colors, borders ect

I have tried to use examples given [here](https://github.com/retejs/rete/issues/213#issuecomment-498839903) 

I'm not able to integrate them to my [angular app example 
](https://stackblitz.com/edit/github-rete)

**Comment by Ni55aN** [comment]
Rendering plugins require a compiled Vue component with a render function. It can be obtained from a single Vue file component (vue-loader is required, but adding Webpack rules to Angular is tricky, as I know) or components compiled in runtime using `vue.esm.js`

```js
import Vue from 'vue/dist/vue.esm';

const vueComponent = Vue.component('num', {
  template: '...
```

**Comment by Ni55aN** [comment]
The same way as component for controls https://github.com/retejs/examples/blob/master/Angular/src/app/rete/controls/number-control.ts#L4

**Comment by Ni55aN** [comment]
https://stackblitz.com/edit/github-rete-vctacd?file=src/app/rete/custom-node.ts

P.S. I cant save last changes with styles on stackblitz, it hangs
