### ISSUE TITLE
Prevent node movement on drag in React 

### ISSUE THREAD

**Issue by JStein92** [retejs/rete#320]
I am rendering a `<textarea>` element inside a node, and would like drag-select the text without moving the node.

I have tried `stopPropagation()` on the element, but it has no effect.

``` jsx
<textarea
     className={classes.text}
     onChange={onChange}
     onMouseDown={e => e.stopPropagation()}
/>
```

I have also tried targeting the nativeEvent via `nativeEvent.stopPropagation()`, to no effect.

``` jsx
<textarea
     className={classes.text}
     onChange={onChange}
     onMouseDown={e => e.nativeEvent.stopPropagation()}
 />
```

Browser: `Chrome Version 75.0.3770.80 (Official Build) (64-bit)`

Thank you!

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/253#issuecomment-462716901

The same for React, since this event listening by rete core

Try this:
```js
<textarea
     className={classes.text}
     onChange={onChange}
     onPointerMove={e => e.stopPropagation()}
/>
```

**Comment by Ni55aN** [comment]
Yep, [its working](https://codesandbox.io/s/retejs-react-render-t899c)

**Comment by JStein92** [comment]
Fantastic, thank you! It's working for me as well. You rock.
