### ISSUE TITLE
Getting started guide doesnt work

### ISSUE THREAD

**Issue by spokzers** [retejs/rete#322]
Hi

I am following the [getting started guide](https://rete.js.org/#/docs) but am unable to make it work.
Created a new Vue project using `vue-cli`, followed the guide to include the code but when I visit the page, I see a blank white screen

Created a sandbox and seeing the same behaviour
https://codesandbox.io/s/x3npl

Am I missing something?

TIA

**Comment by Ni55aN** [comment]
Your editor container doesn't have height and scene doesn't contains any nodes (at least fromJSON missed)

**Comment by Ni55aN** [comment]
https://codepen.io/Ni55aN/pen/xzgQYq

**Comment by spokzers** [comment]
adding height doesnt really change anything
if I have no nodes, does that mean I cant have an empty scene ?
What I want to achieve is an empty scene with a dock containing all the nodes.

**Comment by Ni55aN** [comment]
@spokzers parent element should has height.

> if I have no nodes, does that mean I cant have an empty scene

You'll have an empty scene

> What I want to achieve is an empty scene with a dock containing all the nodes.

You must to install https://www.npmjs.com/package/rete-dock-plugin

**Comment by spokzers** [comment]
ok I'll try

**Comment by spokzers** [comment]
Update: I added the node onto the scene and used the Dock plugin. The Dock Plugin is working fine but I still cant see anything in the scene

https://codesandbox.io/s/vue-template-f11st

**Comment by Ni55aN** [comment]
Your #app has a zzero height

**Comment by spokzers** [comment]
giving a height to the `#app` does nothing. Do I need anything else ?

**Comment by Ni55aN** [comment]
height: 100%; doesn't help when parent elements have computed height equal to zero (body and html)

**Comment by spokzers** [comment]
adding a `height: 100vh` to the html and body and adding `height: 100%` to the `#app` seems to work.

It should be added to the documentation that the parent for the `rete` needs to have definite height for it to be visible.

**Comment by Ni55aN** [comment]
> It should be added to the documentation that the parent for the rete needs to have definite height for it to be visible.

Maybe, its defined in examples on codepen

**Comment by Ni55aN** [comment]
[The parent element must have its width and height, according to them this element will be adjusted](https://rete.js.org/#/docs#lang=en&tosearch=The%20parent%20element%20must%20have%20its%20width%20and%20height%2C%20according%20to%20them%20this%20element%20will%20be%20adjusted)
