### ISSUE TITLE
Rete.js in Safari

### ISSUE THREAD

**Issue by pkhruasu-ui** [retejs/rete#324]
Hi,

I was testing this awesome library on Safari and found out that some issues are there (mainly cannot drag component, new component does not spawn at mouse location, clicking on dropdown in a component makes the component stick to the mouse). 

ex.
https://rete.js.org/#/examples/basic#lang=en&tosearch=Number%0ANumber%0A%0ANumber%0ANumber%0A%0AAdd%0ANumber%0A%0ANumber%0ANumber

Is there any way to remedy this?

**Comment by Ni55aN** [comment]
What version of Safari? The core and few plugins using Pointer events which doesn't supported in previous versions of Safary. https://github.com/retejs/rete/issues/299#issuecomment-500249946

**Comment by pkhruasu-ui** [comment]
Version 12.1.1 (14607.2.6.1.1)

A lot of people in our company is still using the current version so there is no way we can ask them to use new version.

The impact number is very small though. 
If there is a fix now, great! if not, I will wait until TP rolls in.

**Comment by Ni55aN** [comment]
The issue 299 has comments with links to polyfill. It may suit you.
