### ISSUE TITLE
Using vue render plugin 

### ISSUE THREAD

**Issue by emanuelperpetuo** [retejs/rete#325]
How I use vue render plugin , template for component,  in pure javascript  without typescript etc...?

**Comment by Ni55aN** [comment]
vue render plugin doesnt require TypeScript. For using Vue components in pure JS you need `vue.esm.js` to comple templates in runtime (`Vue.component(name, { ... })`, https://github.com/retejs/rete/issues/318#issuecomment-499381499) or vue loader

**Comment by Ni55aN** [comment]
vue render plugin doesnt require TypeScript. For using Vue components in pure JS you need `vue.esm.js` to comple templates in runtime (`Vue.component(name, { ... })`, https://github.com/retejs/rete/issues/318#issuecomment-499381499) or vue loader

**Comment by Ni55aN** [comment]
vue render plugin doesnt require TypeScript. For using Vue components in pure JS you need `vue.esm.js` to comple templates in runtime (`Vue.component(name, { ... })`, https://github.com/retejs/rete/issues/318#issuecomment-499381499) or vue loader

**Comment by Ni55aN** [comment]
vue render plugin doesnt require TypeScript. For using Vue components in pure JS you need `vue.esm.js` to comple templates in runtime (`Vue.component(name, { ... })`)  https://github.com/retejs/rete/issues/318#issuecomment-499381499 or vue loader

**Comment by Ni55aN** [comment]
vue render plugin doesnt require TypeScript. For using Vue components in pure JS you need `vue.esm.js` to comple templates in runtime (`Vue.component(name, { ... })`)  or vue loader

**Comment by Ni55aN** [comment]
test
