### ISSUE TITLE
Drag handler performance leak

### ISSUE THREAD

**Issue by pszalanski** [retejs/rete#326]
It looks like the drag handler (src/view/drag.js) is instantiated for the editor view and each node that is created. This leads to a big performance issue in our app. For example, if you instantiate 100 nodes, the drag handler is running **101 times** on each and every `pointermove` event.

Furthermore, no reference is kept to the Drag object. In our SPA it is possible to navigate to a list of files and back to the editor. The Drag objects keep stacking up and handling `pointermove`  events.

In addition to that, our app is implemented in Angular and the framework tries to determine if any changes happened based on this event. As soon as we commented out the creation of the Drag objects, our performance went back to normal for all scenarios.

If you add up both of these problems, then our app becomes unusable really quickly.

Suggestion: Refactor drag handling so there is **only one** class which handles mousemove and conditionally, drag events when a mousebutton is down.

P.S.: Would it help if we prepared a PR? 😉

**Comment by Ni55aN** [comment]
Drag handlers working fine in my Vue projects or on Codepen

> implemented in Angular and the framework tries to determine if any changes happened based on this event.

Zone.js interferes in all events, so you need to create editor in `this.zone.runOutsideAngular(() => { });`

**Comment by pszalanski** [comment]
Well just because it runs fast enough in your use cases does not mean that there is no performance problem 😄 

Still, the drag handler is instantiated unnecessarily often **and** there is no cleanup happening. 

The offer to prepare a PR still stands.

**Comment by Ni55aN** [comment]
Send me the profiler report

**Comment by Ni55aN** [comment]
> The offer to prepare a PR still stands.

What is the changes?

**Comment by Ni55aN** [comment]
There is one problem with missed `removeEventListener` for window, but I cant figure out how it will affect your performance

**Comment by Ni55aN** [comment]
Try v1.4.0

**Comment by pszalanski** [comment]
Thanks for the update!

We could resolve the massive performance drop. This was actually a problem in our implementation, after all. We use a Factory to create Angular components dynamically and we completely oversaw that we need to destroy those components as well. 

However, in our opinion you should always have only **one** handler for drag and drop and not have it scale up with each and every component that is listening to `pointermove` events. But this is completely up to you, as this is not causing any immediate problems for us. We will, however, do some further testing if this still affects performance.

Thank you for your help!

**Comment by Ni55aN** [comment]
> We will, however, do some further testing if this still affects performance.

Do you call `editor.trigger('destroy')` before destroying a component?

**Comment by pszalanski** [comment]
Yes, but that is not what I am talking about. The cleanup is fine.

But if you create a `NodeEditor` with 1000 nodes, you will have 1000 pointermove handlers, which is inefficient. You only need one handler to check for drag events, at least in the graphical editors that I have coded so far. What I'm saying is, that we ourselves see this as a problem, but we don't have an immediate problem _right now_. We'll simply tell you using a Github issue, if we have any useful info 😉

**Comment by Ni55aN** [comment]
> which is inefficient

I think It takes less time than rendering or other computations

> You only need one handler to check for drag events,

Each node is independent from each other. By the way, 1000 nodes is a bad practice just like a couple of thousand code lines
