### ISSUE TITLE
onmouseup a node

### ISSUE THREAD

**Issue by Githamza** [retejs/rete#327]
I would show node details when I select a node on a popup.

For that I'm using `nodeselect` event to trigger the popup and passe the selected node.

The problem is now when I try to move a node the popup shows ( because it triggers the `nodeselect` event.

I would like to know if there is an event to be triggered only when user release mouse click ( onmouseup ) ?

Thanks

**Comment by Githamza** [comment]
I have found the solution : use `nodedraged` event .. issue could be deleted or closed

**Comment by Githamza** [comment]
I have an issue 
actually `nodedraged` resolved my issue which is : on mouseup trigger an action ( show node details popup )

The problem is now when I drag a node, when i release mouse click I get the popup, it's not my expected behaviour.

What I would is : 
When I click on a node without dragging it, on mouse up , show popup .

When I drag a node don't show the popup on when I drop the selected node.

So what I look for is `selectednode` event but on mouseup

**Comment by Ni55aN** [comment]
Maybe you will just add your event listener on Node element

```js
editor.on('rendernode', ({ el, node }) => {
    el.addEventListener('click', /* show popup */);
});
```
