### ISSUE TITLE
Editor saves data about changed control, but in node control doesnt change.

### ISSUE THREAD

**Issue by mttv** [retejs/rete#328]
Hi everyone, so I've made this data type switcher that is working with inputs, controls and outputs.
I've bumped into issue that when I'm switching for exmaple from number data type to string type sockets are changing, but controls not.
Before changes:
![image](https://user-images.githubusercontent.com/46907387/60003967-66686080-9674-11e9-8fd4-4b50231e8b2b.png)

![image](https://user-images.githubusercontent.com/46907387/60003899-42a51a80-9674-11e9-9744-d9d960e7d3ca.png)

After:
![image](https://user-images.githubusercontent.com/46907387/60004206-d70f7d00-9674-11e9-9c03-1f8f11fc46ed.png)

![image](https://user-images.githubusercontent.com/46907387/60004142-be06cc00-9674-11e9-829e-b558974f35d8.png)

I'm fully removing old input and replacing it with a new one with a new control. Also after changing data type and starting typing in a new control I'm getting this error:
![image](https://user-images.githubusercontent.com/46907387/60006579-69b21b00-9679-11e9-946f-26a23582b202.png)

**Comment by Ni55aN** [comment]
Do you use `vue-render-plugin`? If key of old and new input/output are equal, it doesn't remount the control. 
Solution (unchanged key):
```js
// delete Number input with control
await node.update();
// add String input with control
await node.update();
```

**Comment by mttv** [comment]
@Ni55aN Thanks! That was an issue. I was calling await node.update() only once. P.S Im using `rete-react-render-plugin`
https://github.com/retejs/rete/issues/328#issuecomment-505164863

**Comment by mttv** [comment]
@Ni55aN I also have problem when disconnecting multiple inputs from output.
![image](https://user-images.githubusercontent.com/46907387/60085842-b4e43080-9742-11e9-9efc-1438bcf30c45.png)
Some of connections just are not removing fully:
![image](https://user-images.githubusercontent.com/46907387/60085922-df35ee00-9742-11e9-8de1-4501e64e830f.png)
![image](https://user-images.githubusercontent.com/46907387/60085999-fc6abc80-9742-11e9-8ac6-cf29574d4deb.png)
Code: `const removeSocket = async(emitter, node, key, socketType) => {
    console.log(node, key, socketType)
    switch (socketType) {
        case "input":
                const getInput = emitter.nodes.find(n => n.id === node.id).inputs.get(key)
                //If sockets are connected we need to remove connection, because of new socket type
                if (getInput.connections.length !== 0) {
                    getInput.connections.map(conn => {
                        emitter.removeConnection(conn)
                    })
                }
                node.removeInput(getInput)
                await node.update()
            break
        case "output":
                const  getOutput = emitter.nodes.find(n => n.id === node.id).outputs.get(key)
                if (getOutput.connections.length !== 0) {
                    getOutput.connections.map(conn => {
                        emitter.removeConnection(conn)
                    })
                }
                node.removeOutput(getOutput)
                await node.update()
            break
        default:
            break
    }
}

export default removeSocket`

**Comment by Ni55aN** [comment]
@mttv this is a common problem when working with arrays.
`array.map()` will traverse each index in the array, at that time `removeConnection` will remove element in current array by the index, so `map()` for first element will remove first element, then second element in array will be at first place and `map()` will skip it.

Solution: copy array

```js
[...getInput.connections].map(conn => {
// or
getInput.connections.slice().map(conn => {
```

**Comment by mttv** [comment]
@Ni55aN thanks once again.
