### ISSUE TITLE
Auto positioning?

### ISSUE THREAD

**Issue by seagullmouse** [retejs/rete#329]
Is there an easy way to have nodes automatically optimally positioned (rather than manually supplying y and x properties)

e.g. 
- define nodes
- add to editor
- `editor.autoPositionNodes()`

**Comment by Ni55aN** [comment]
There is [auto-arrange-plugin](https://github.com/retejs/auto-arrange-plugin), but it has a simple implementation and may not work in some cases

**Comment by seagullmouse** [comment]
Thanks for sending this. Yes it's probably too simple for my use case.

I think the plugin would work better if it tried to rearrange all the nodes at once.

**Comment by Ni55aN** [comment]
what do you mean? It will arrange all nodes relative to some node

**Comment by seagullmouse** [comment]
I was misunderstanding how to use it. Thanks!
