### ISSUE TITLE
Not understanding how Modules work

### ISSUE THREAD

**Issue by ctrl-zen** [retejs/rete#330]
I've analyzed the Module demo a dozen times and I cannot figure out where the logic to multiply input values by 2 is defined.

```js
class ModuleComponent extends Rete.Component {

    constructor() {
        super("Module");
        this.module = {
            nodeType: 'module'
        }
    }

    builder(node) {
        var ctrl = new TextControl(this.editor, 'module');
        ctrl.onChange = () => {
            console.log(this)
            this.updateModuleSockets(node);
            node._alight.scan();
        }
        return node.addControl(ctrl);
    }

    change(node, item) {
        node.data.module = item;
        this.editor.trigger('process');
    }
}
```

What am I missing? Is it just magic?

**Comment by Ni55aN** [comment]
> where the logic to multiply input values by 2 is defined

that login described in Node editor module's scheme

![Opera Снимок_2019-06-26_203323_codepen io](https://user-images.githubusercontent.com/8259641/60201875-13e49b00-9852-11e9-99a1-1d5cb2d7ef5d.png)
![Opera Снимок_2019-06-26_203510_codepen io](https://user-images.githubusercontent.com/8259641/60201878-1646f500-9852-11e9-9214-6e3e802de92c.png)

**Comment by ctrl-zen** [comment]
> that login described in Node editor module's scheme

are you saying the schema is the bottom pic is what's going on under the hood of the Module node in the top pic? where is the definition for this in the code? for example there is a hardcoded '2' in the bottom socket of the Module node. what if I want it to be 3?

**Comment by Ni55aN** [comment]
> are you saying the schema in the bottom pic is what's going on under the hood of the Module node in the top pic?

exactly

> hardcoded '2' 

its just a label. Schemes for modules placed in https://rawgit.com/retejs/examples/master/Module/data.js

>  is this coming from the Output none

Output socket of the Module node will return value from the "Output" node of this module

**Comment by ctrl-zen** [comment]
Got it. Thanks!
