### ISSUE TITLE
auto connect new node to the refference node 

### ISSUE THREAD

**Issue by jadhavsuraj2207** [retejs/rete#333]
Hi,
I looking for very specific requirement and working in angular 7.
![rete](https://user-images.githubusercontent.com/52485353/60810791-871fd280-a1ab-11e9-8573-86d85747fb48.png)
Requirement 1  =
Supose , 
I hover or right click on any node and add new node ,
then the newly created node will be auto connected to the reference node and position accordingly.
Example from above image :
Suppose I right click on 'select file' node and open my custom option to add other node,
the newly created 'select number' will be automatically connect to that 'select file' node on which  
I right clicked.
Requirement 2  = 
How to create new node .
eg. Suppose i have one button add 'select file' . when i click on that button the new 'select file' component will create and will position accordingly .
Please let me know how to do it.
Thanks .

**Comment by Ni55aN** [comment]
There is similar feature, but with reverse flow (create node by picked connection) https://github.com/retejs/connection-mastery-plugin/blob/master/src/features/create-and-connect.ts

**Comment by jadhavsuraj2207** [comment]
Hi,
I have created and connect the new node with reference to the node where i have right clicked.
My code is as follows  -
1. when right click on the node -
` this.editor.on('contextmenu', ({ e, view, node }) => {
      if(node !== undefined){
        this.rootnode = node;
        let connectionCount = this.rootnode.outputs.get('num').connections.length ;
        // to set position of newly cretaed node 
        this.test = [node.position[0] + (200+ (50* connectionCount)), node.position[1] + (200+ (50* connectionCount))];
      }
    });`
On node Create - 
`this.editor.on('nodecreate', node => {
      if(this.checkClick &&  this.test.length >0){
        console.log( this.test)
        node.position = this.test;
      }
      this.checkClick = false ;
      return node ;
     
    })
`
that worked for me !!

**Comment by jadhavsuraj2207** [comment]
Hi, 
Thanks for quick reply. you are doing such fantastic work & giving great support.
 I did above mentioned functionality by - 
1. created node by using createdNode()
2.using editor.connect() to connect reference and new node.
I am facing the node position problem.
![ivr1](https://user-images.githubusercontent.com/52485353/60886839-93219800-a270-11e9-8a59-e877dd28d5d6.png)
![ivr2](https://user-images.githubusercontent.com/52485353/60886837-93219800-a270-11e9-9521-d779bbc78d28.png)

Now, If i want to update the position of all the connected node.
eg. in image1 - if one node is connected it will position below the parent node (that i have done by setting newly created node using node.position).
If i connect another node to it the first child node will shift and changes its position like in image 2. 
hence i want to update the node position of related node .
Is there any way to do it ?  
Please let me know how to do it.
Thanks.

**Comment by Ni55aN** [comment]
Manually:
```js
node.position = [x, y];
await node.update();
```

Also you can use the auto arrange plugin, but it doesn't support versical and complex schemes
