### ISSUE TITLE
How to update data values in the node based on websocket values

### ISSUE THREAD

**Issue by mohandass-pat** [retejs/rete#334]
I want to update data values in the node based on websocket values. If I try using editor.fromJson it creates new graph. How to update the value. Can anyone help me on that. Thanks in advance :)

**Comment by Ni55aN** [comment]
It depends on phase of updating:

- before fromJSON - edit JSON
- while creating node - inside Component's builder write to `node.data.key = value`
- at runtime - usually inside Control, call  `control.putData(key, value)`
