### ISSUE TITLE
update view

### ISSUE THREAD

**Issue by mohandass-pat** [retejs/rete#335]

**Comment by mohandass-pat** [comment]
Hi. Actually this is a great tool. Really thanks for this. I have a small doubt. How to update the view after dynamically changing node data?

I referred this https://jsfiddle.net/Ni55aN/8pfqb9yy/22/.

where I tried this one ,
editor.nodes.find(n => n.id == id).data._done = true
  editor.view.update()

but update function is returning error. Actually I using the react component

**Comment by Ni55aN** [comment]
`editor.view` doesn't have `update()` function. 

```js
const node = editor.nodes.find(n => n.id == id);
node.data._done = true
await node.update();
```

**Comment by mohandass-pat** [comment]
Yeah It works. Thanks a lot.
