### ISSUE TITLE
Trigger a function while socket type miss match

### ISSUE THREAD

**Issue by mohandass-pat** [retejs/rete#338]
Hi. I want trigger a function while mismatching the node connections due to socket type error. So I can able to show users that they giving the wrong input. Thanks in advance

Error: Sockets not compatible  - For this error I need to trigger a function

**Comment by Ni55aN** [comment]
```js
editor.on('warn', e => alert(e.message))
```

**Comment by mohandass-pat** [comment]
It works. Thanks
