### ISSUE TITLE
setting default zoom at load 

### ISSUE THREAD

**Issue by jadhavsuraj2207** [retejs/rete#339]
Hi, 
I want to set the zoom level on load of the page which is 1 by default.how i can do it ?
![1](https://user-images.githubusercontent.com/52485353/60889413-91f36980-a276-11e9-90e7-361d93b9d63e.png)

1. I have tried #110  by using editor.view.scale(0.6). but it is giving me - 'editor.view.scale is not a function ' this error.
2. where i should set the default value and update the view .
   I got value of scale in editor.view.area.transform.k which is 1 by default.
   is there any way i can change the value and update the view.
Thanks.

**Comment by Ni55aN** [comment]
1. This is old method for 0.*.* version
2. Example: https://github.com/retejs/area-plugin/blob/master/src/zoom-at.js

```js
const { area } = editor.view;

area.zoom(k, 0, 0);
```

**Comment by jadhavsuraj2207** [comment]
Hi, 
Great solution!! that worked !!
Thanks .

**Comment by ayazmu** [comment]
> ```js
> const { area } = editor.view;
> 
> area.zoom(k, 0, 0);
> ```

ho can i dervice the value of k ?

**Comment by Ni55aN** [comment]
@ayazmu 
```js
area.transform.k
```

**Comment by ayazmu** [comment]
Thank you so much for your help.

Can you help me with the below issue i am facing although not related with this thread.

When i click on any node ".selected" css class gets applied to it and the node is highlighted with a default color.
I want to unselect this node whenever the user clicks outside of the node.
I am using the click event to detect outside click but i could'nt think of the logic to unselect the node on the editor. A simple solution would be to simply remove the selected class from the node but i wanted to run it through you first.
Please see below. 

//  this.editor.on('click', (e) => {
      console.log(e); // gives me the mouse event
      // logic to unselect node
    });

**Comment by Ni55aN** [comment]
@ayazmu 

```js

  editor.on('click', () => {
    const selectedNodes = [...editor.selected.list];
    editor.selected.clear();
    selectedNodes.forEach(n => n.update())
  })
```

**Comment by ayazmu** [comment]
@Ni55aN Thank You So Much!
