### ISSUE TITLE
Suggest some backend runtime

### ISSUE THREAD

**Issue by mohandass-pat** [retejs/rete#340]
Hi. I have successfully implemented the rete.js for front-end. And my requirement is I need to run the definition in backend with some python code. Is there any runtime available for this. primarily my choice is noFlo and node-red. but the output from rete.js is not compatible with noFlo runtime graph . Is there any way to convert it in .fbp format. Or any other suggestions on my requirement?. Thanks in advance

**Comment by Ni55aN** [comment]
Rete's Engine (for front- and back-end) supports only JS.
You can try the code-plugin for generating Python code, but its unstable.

I think the most preferable solution - create `worker()`'s on JS and run in Node.js

**Comment by mohandass-pat** [comment]
Thanks. this information is helpful to us
