### ISSUE TITLE
Remove all the connected node when root is remove 

### ISSUE THREAD

**Issue by jadhavsuraj2207** [retejs/rete#341]
Hi,
I want to remove the node , all the node connected to it and the nodes in its hierarchy should be removed .
Eg. 
![IVR3](https://user-images.githubusercontent.com/52485353/60972368-c719bd80-a343-11e9-8477-ce7d3b888938.png)
Here , if i remove the select file node (below start call at left) then ,
All the 'select number' node and 'select file' connected to each 'select number' will be removed .
How i can achieve this ?
Please let me know .
Thanks .

**Comment by Ni55aN** [comment]
I sketched the code, but did not check it.

```js
function removeOutputNodes(node) {
  node.outputs.values().forEach(output => {
    output.connections.forEach(connection => {
      removeOutputNodes(connection.input.node);
    })
  });
  editor.removeNode(node);
}
```

**Comment by jadhavsuraj2207** [comment]
Hi,
node.outputs.values() is giving me an follwoing error -
![error](https://user-images.githubusercontent.com/52485353/61024391-1525d400-a3cb-11e9-82f1-8d0cb00a18c2.png)
please check my node object -
![object](https://user-images.githubusercontent.com/52485353/61024416-27077700-a3cb-11e9-8519-f7257f7ebf4a.png)
here is my node.outputs.values() =
`MapIterator {Output}
__proto__: Map Iterator
[[IteratorHasMore]]: true
[[IteratorIndex]]: 0
[[IteratorKind]]: "values"
[[Entries]]: Array(1)
0: Output
value: Output {node: Node, multipleConnections: true, connections: Array(1), key: "num", name: "", …}
length: 1`

please let me know the issue.
Thanks.

**Comment by Ni55aN** [comment]
Oh, yeah, Map.values() returns MapIterator. values() should be wrapped with Array.from() or forEach replaced with for loop

```js
function removeOutputNodes(node) {
  for(let output of node.outputs.values()) {
    for(let connection of output.connections) {
      removeOutputNodes(connection.input.node);
    }
  }
  editor.removeNode(node);
}
```

**Comment by jadhavsuraj2207** [comment]
> Oh, yeah, Map.values() returns MapIterator. values() should be wrapped with Array.from() or forEach replaced with for loop
> 
> ```js
> function removeOutputNodes(node) {
>   for(let output of node.outputs.values()) {
>     for(let connection of output.connections) {
>       removeOutputNodes(connection.input.node);
>     }
>   }
>   editor.removeNode(node);
> }
> ```
