### ISSUE TITLE
Multi node selection/dragging key binding

### ISSUE THREAD

**Issue by renjfk** [retejs/rete#343]
You think it would be possible to make multi select/dragging key binding platform dependent (changing it to command rather than control on MacOS for example as control + click serves as right click purpose) or customizable somehow?

**Comment by Ni55aN** [comment]
v1.4.1-rc.1

```js
editor.on('multiselectnode', args => {
     // args.e - MouseEvent
    args.accumulate = args.e.button === 1; // for middle mouse button
    // orТ
    args.accumulate = someKeyPressed;
});
```

In this way you can define your behavior to accumulate a selected nodes.

**Comment by renjfk** [comment]
Cool, works perfectly fine. Thanks. Here's snippet who wants to make it cross platform:

```typescript
editor.on("multiselectnode", (args) => args.accumulate = args.e.ctrlKey || args.e.metaKey);
```
