### ISSUE TITLE
Zoom with buttons

### ISSUE THREAD

**Issue by Prtkpwr** [retejs/rete#344]
I want to implement the zoom functionality with buttons just like in google maps.
I am able to zoom in and zoom-out on button clicks but I want it to happen like it is in google maps, it should zoom-in at the middle of editor and zoom-out at middle of editor.

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/342#issuecomment-510898114

**Comment by Prtkpwr** [comment]
> [#342 (comment)](https://github.com/retejs/rete/issues/342#issuecomment-510898114)

Thank you for the fast response, you are really doing good man :)
