### ISSUE TITLE
Z-index

### ISSUE THREAD

**Issue by dariuszdawidowski** [retejs/rete#346]
I need custom z-sorting of elements.

Actually there are two issues causing problem:

1. every node is wrapped with almost empty div, which has only transform and no class, so I can't sort it by class

2. links are hardcoded to z-index -1, i need them above some of other elements

**Comment by Ni55aN** [comment]
```js  
// triggered when HTMLelement created for connections/nodes
editor.on('renderconnection', ({ el, connection }) => el.style.zIndex = 10) // z index of connections
editor.on('rendernode', ({ el, node }) => {
  el.style.zIndex = someCondition ? /* above */ 15 : /* below  */ 5;
});
```

**Comment by savanthvinay** [comment]
Hi
I have a problem, I have used Accordion in the node the node will expand when it clicked ,But its expand behind the other node. When the node is selected / clicked/ focus need to be  expand on top of all other nodes.
Please help me out how this can be achieved using angular15(primeNg) 
![node open](https://user-images.githubusercontent.com/80236453/235122437-0e9f95db-d712-47da-b04c-a8e9dae8bd74.png)

**Comment by Ni55aN** [comment]
@savanthvinay are you using the v1?

**Comment by Ni55aN** [comment]
@savanthvinay this is not supported by default, but you can try an unofficial plugin: https://github.com/sebbert/rete-reorder-nodes-plugin

**Comment by savanthvinay** [comment]
ok thank you..

**Comment by savanthvinay** [comment]
@Ni55aN I have used plugin: https://github.com/sebbert/rete-reorder-nodes-plugin ,Reorder is working but node (accordion) is not working / opening.
