### ISSUE TITLE
Check any node position is out of editor

### ISSUE THREAD

**Issue by jadhavsuraj2207** [retejs/rete#347]
Hi,
I want to check if any node is out of editor area.
I used ScrollWidth and scrollHeight to identify this but it seems like if my node is out of area at left side the scrollWidth and scrollHeight is not changing .
Any solution ?
Thanks.

**Comment by Ni55aN** [comment]
[getBoundingClientRect](https://developer.mozilla.org/ru/docs/Web/API/Element/getBoundingClientRect)
