### ISSUE TITLE
Implementing node machines

### ISSUE THREAD

**Issue by kethan** [retejs/rete#348]
Hi,
I am thinking of implementing node machines with retejs. (http://node-machine.org/) I am confused about how to start can anyone give me a possible simple example using node machines.

Thanks.

**Comment by Ni55aN** [comment]
I have never heard of node machines. Currently I can’t immediately figure out how it works. I'll try it on the weekend

**Comment by Ni55aN** [comment]
What exactly do you want to implement? 

Honestly, I didn't understand what is the advantage of node machine. It looks like a npm packages collection for different purposes. 

As any function for processing, you can put it in worker()

**Comment by kethan** [comment]
I wanted custom machines to integrate with rete input output controls to run microservices.

**Comment by kethan** [comment]
Anyway I understood how it works in rete
