### ISSUE TITLE
remove connection does not render

### ISSUE THREAD

**Issue by Githamza** [retejs/rete#350]
I'm trying to delete connection programmatically .

Here my code
```
      editor.nodes[0].outputs.forEach(elm => {
        elm.connections.map(connection => elm.removeConnection(connection))
      })
      console.log(node)
    })
```
in my node output variable object connection is get removed. but in UI connection is still there.

Should I trigger a function in engine or editor to make the editor applying delete to UI ?

**Comment by Ni55aN** [comment]
You should to remove a connections using NodeEditor as it works with the view layer (Node instance, Output/Input dont have access to view layer)

```js
node.outputs.forEach(output => {
    output.connections.map(connection => editor.removeConnection(connection))
})
```

**Comment by Githamza** [comment]
Nice that's working. I would like to know how to use removeConnections? ( all connections of a node )

**Comment by Ni55aN** [comment]
@Githamza it doesn't work combined with the view

**Comment by lomtesaurabh** [comment]
My question is, If the user removes any connection in the code how to know which connection is removed? so I can update connections.

**Comment by Ni55aN** [comment]
@lomtesaurabh v1 or v2?
