### ISSUE TITLE
Scrollable Background grid?

### ISSUE THREAD

**Issue by iyobo** [retejs/rete#353]
Is it possible to have a scrollable background grid?
Any idea on how that could be implemented?

**Comment by Ni55aN** [comment]
How should it look like?

**Comment by iyobo** [comment]
Like the unreal engine bscrollabel background grid: 

Watch this quick video.
 https://youtu.be/0kQDssI8fkI

**Comment by iyobo** [comment]
@Ni55aN back when I used other node graph libraries, I believe they achieved this by specifying major and minor grid lines, each with separate color and thickness settings, so users can determine how they want their gridded background to be.

I love the way rete looks and the UX is top notch!

**Comment by Ni55aN** [comment]
@iyobo I don't understand completely  where is the scrollable effect. The background looks fixed relative a nodes.
Example: https://rete.js.org/#/examples/customization

**Comment by iyobo** [comment]
@Ni55aN Oh wow, thanks for that link. 
That is exactly what I want.

**Comment by Ni55aN** [comment]
@iyobo 

https://github.com/retejs/rete.js.org/blob/master/src/components/Examples/list/customization/index.js#L47
https://github.com/retejs/rete.js.org/blob/master/src/components/Examples/list/customization/style.sass#L15
