### ISSUE TITLE
Support for svelteJs

### ISSUE THREAD

**Issue by mohandass-pat** [retejs/rete#357]
We implemented the rete in react. Now we are planning to change it in svelte. Is there any support for that? Thanks in advance :)

**Comment by Ni55aN** [comment]
No, there is no render plugin for svelte and not currently planned (Angular renderer in the queue)

**Comment by mohandass-pat** [comment]
Ok Thanks

**Comment by sheikalthaf** [comment]
@Ni55aN just checked this plugin and it looks great. but i'm using angular so the vue renderer is too heavy for angular applications.
May i know when the angular renderer will be released?

**Comment by Ni55aN** [comment]
> May i know when the angular renderer will be released?

Soon. I started working on it

**Comment by Immortalin** [comment]
@Ni55aN will you be willing to reconsider Svelte? The code generated by Svelte is a lot faster and more efficient than React. It's also simpler to use too. Efficiency will become important when the number of nodes scale up.

**Comment by Ni55aN** [comment]
> will you be willing to reconsider Svelte? 

Maybe in a month

**Comment by c0bra** [comment]
I needed a Svelte rendering plugin so I wrote this: https://github.com/c0bra/rete-svelte-render-plugin

It works for the needs I have. There's no docs currently as I needed it quickly for a work project.

**Comment by elikoga** [comment]
@c0bra is your rendering plugin still usable? I'm using the vue renderer in my svelte application currently

**Comment by Ni55aN** [comment]
An official Svelte plugin for v2 just [has been released](https://twitter.com/rete_js/status/1675577935233703939)
