### ISSUE TITLE
Custom style components not working

### ISSUE THREAD

**Issue by mohandass-pat** [retejs/rete#359]
Hi I'm using react component. I tried to use some components like toggle from semantic-ui-read. But only html is applying. Styles are not reflecting. even some other style components also not reflecting. Any help on this would be helpful. Thanks in advance :)

**Comment by Ni55aN** [comment]
What a render plugin are you using?

**Comment by mohandass-pat** [comment]
Thanks for the reply. I'm using React-render-plugin

**Comment by Ni55aN** [comment]
Check the selectors in devtools and selectors in your styles. Perhaps they are not displayed due to the specificity of the selectors
