### ISSUE TITLE
multiple node dragging without holding the accumulate button

### ISSUE THREAD

**Issue by blauwepiet** [retejs/rete#361]
Now when you select multiple nodes with CTRL and then want to drag them, you still have to press CTRL otherwise all of them get de-selected and you only drag the on under you mouse. This is not standard behavior, for example in the Blender 3d program node based interface when you selected multiple you can initiate dragging on all of the selected nodes.

I believe this can be solved by differentiating between dragging and clicking and by checking if the node is already in the selected list in the editor class before adding it to the selected array. The only thing you then need to check for is if you click without dragging to single select a node otherwise single selecting a node wouldn't work anymore. 

Maybe use the standard html drag, dragstart and dragend events?

**Comment by blauwepiet** [comment]
Also the context menu right click removes the multi selection. This is also not favorable when you want to have a context menu option for the selected nodes.

**Comment by Ni55aN** [comment]
> Also the context menu right click removes the multi selection

It doesn't remove selection when clicking on empty area

**Comment by Ni55aN** [comment]
> This is not standard behavior

Is there standard behaviour?

**Comment by Ni55aN** [comment]
>  you selected multiple you can initiate dragging on all of the selected nodes.

Yes, when pressing Ctrl (or different) key
```js
editor.on('multiselectnode', args => {
    args.accumulate = shouldAccumulate; // alternative for CTRL
});
```

**Comment by blauwepiet** [comment]
> Do you want to drag nodes without pressing the Ctrl key?

Yes, most node based software behaves like that. For example the Shader or composite editor from Blender or the Blueprint editor in Unreal engine.

> Is there standard behaviour?

No, not really, just mostly used in different software.

> It doesn't remove selection when clicking on empty area

That is true, but that is not what I want. I want the context menu to be able to have functions for a multi node selection. For example deletion, duplication, commenting, grouping, exectution, you name it on multiple nodes. I am using Rete now extensively in a innovation project and there are a lot of feature requests which include a multinode context menu.

**Comment by Ni55aN** [comment]
@blauwepiet https://github.com/retejs/rete/issues/363#issuecomment-527611356

**Comment by Ni55aN** [comment]
> I want the context menu to be able to have functions for a multi node selection. For example deletion, duplication, commenting, grouping, exectution

Ok. I'll investigate this later

**Comment by glebov-andrey** [comment]
I came across the same issue, and to work around it, I intercepted the `nodeselect` event and canceled it, if the node being selected was already selected:
``` ts
editor.on('nodeselect', node => !editor.selected.contains(node))
```
It would be nice for this to be the default behavior though)
