### ISSUE TITLE
prevent dragging nodes beyond editor wrapper

### ISSUE THREAD

**Issue by jadhavsuraj2207** [retejs/rete#365]
Hi,
This library is great !!
I want to restrict the dragging of nodes beyond the editor wrapper dimenssion. how I can do this? 
Any solution ??
Thanks in advance.

**Comment by Ni55aN** [comment]
https://github.com/retejs/area-plugin

```js
editor.use(AreaPlugin, { translateExtent: { width: 5000, height: 4000 } });
```

It will restrict the drag area, but without linking to the visible area

---

Or you can restrict it in another way as in the example

https://github.com/retejs/area-plugin/blob/master/src/restrictor.js#L10

**Comment by jadhavsuraj2207** [comment]
Thanks for the quick reply.
But i want to restrict the dragging of nodes. when i select any node  and drag then the '**nodetranslate**' event fire.on this event i get {node,x,y}. i want to restrict the node dragging out of the wrapper.

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/367
