### ISSUE TITLE
node position update not triggering

### ISSUE THREAD

**Issue by jadhavsuraj2207** [retejs/rete#366]
Hi, 
I am trying to update the node position on "nodetranslated". But its not getting updated in the UI.
Is there anything with which I can refresh the UI or trigger the change

**Comment by Bulbousonions13** [comment]
I was having similar problems but then realized that there are two parts to accessing the Node. One is this.editor.nodes[some Node Key] ... this will let you access all the node properties, but not necessarily the nodes View properties. 

However, "this.editor.view.nodes.get(node).translate(newX,newY);" you can update the view property.

I did this to update node.position and then the view ... 

let node:Node = new Node(); (Of whatever type you're custom Rete Component is)
node.postion = [newX,newY];
"this.editor.view.nodes.get(node).translate(newX,newY);"

it worked for me.

**Comment by jadhavsuraj2207** [comment]
Thanks a lot @Bulbousonions13 !! that worked for me also.

**Comment by Bigstep22** [comment]
I've been doing some more digging in this exact thing and I've found the following:
1. If you want to trigger the 'nodetranslate' and 'nodetranslated' triggers then you should do solely:
 "this.editor.view.nodes.get(node).translate(newX,newY);"
And this will also update the node.position in the background through the library.
2. If, like in the project I'm working on, you'd like to move the node without activating any triggers you should do the following:
"node.postion = [newX,newY];
this.editor.view.nodes.get(node).update();"
Note the use of the update() function in the second line.
You can double check these facts in the /src/view/node.ts file.
