### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by cristianfrpt1** [retejs/rete#368]
Hi, i'm trying to install the Rete but i cant install by NPM so i have downloaded Rete by GitHub, but when I try to run an example, my example can't import the Rete.

Have I missed to install something ?

![image](https://user-images.githubusercontent.com/54375249/64459501-66ea9200-d0ce-11e9-91f1-e70e9c3ef3a0.png)

**Comment by cristianfrpt1** [comment]
![image](https://user-images.githubusercontent.com/54375249/64459575-99948a80-d0ce-11e9-828d-9722995996c0.png)

**Comment by Ni55aN** [comment]
> but i cant install by NPM

why?

**Comment by Ni55aN** [comment]
and how are you going to build your project (webpack, html+pure js, etc.)?

**Comment by cristianfrpt1** [comment]
Sorry for the delay in replying.
I downloaded the Rete as a zip by the github

![image](https://user-images.githubusercontent.com/54375249/64557353-c5568100-d317-11e9-881c-137b128461e3.png)

and i extracted the files on a folder, then i opened the folder on VSCode (I also tried on Atom), created three new files (index.html+ main.js + styless.css), copyed the content of this example ( https://codepen.io/Ni55aN/pen/MOYPEz ) and lastly i opened the html in chrome.

I did this because i could not finish the "Getting Started" installing the Rete by the npm.
I think that Im missed to link the rete on my html but I dont know how i do this. 
I recently learned some Javascript and would like to learn Rete

**Comment by Ni55aN** [comment]
You shouldn't to download source code for your purpose. You need to install from NPM or include to page from CDN. 

If you install from NPM, then you need to use some kind of bundler (webpack, parcel, etc.)
The easiest way for a beginner is to include js to html (take links from Pen Settings -> JavaScript)

**Comment by cristianfrpt1** [comment]
(I apologize for my bad english) 
Hi NI55AN, i'll reformulate my question because i think that this way you can understand me and help me better, I was close to giving up but I need to do a report for my search group.

First of all I will introduce myself, my name is Cristian, I am 19 years old and for two months I was part of a research of my college, I am leaving the research now because I got a job in the company that I am interested. So I will leave a research report for those who enter my place and I have the objective of run the Rete.

Here's the question
If i never used any JavaScript application, what do i will need install to run Rete and how i can take these Pen Settings links ?

Thank you for your time

**Comment by unhott** [comment]
https://codepen.io/Ni55aN/pen/MOYPEz

Click the JavaScript tab. Then click settings (gear wheel icon).
You should see several links in there. These are JavaScript libraries that execute before JavaScript written inside the codepen. These enable rete to work.

**Comment by cristianfrpt1** [comment]
wow. Ok, thanks friend.

**Comment by Ni55aN** [comment]
Is the problem solved?
