### ISSUE TITLE
How to - Node implementation

### ISSUE THREAD

**Issue by fedeMarcantognini** [retejs/rete#369]
Hi,
Rete.js is great, thank you for sharing that. I am looking to creating a custom node with some functionalities to include basic calculations and distributed output to multiple links. 
As a starter with Rete.js, what do you recommend? extending the core with plugins or/and use Vue.js?
My goal is briefly explained in the image below.
![image](https://user-images.githubusercontent.com/19288193/64744111-d7b60200-d545-11e9-95f1-d01f584f5a08.png)

Thank you very much

**Comment by Ni55aN** [comment]
Definitely you need to create a custom node.

For example, you can associate Controls with extended Rete.Input/Rete.Output.

```js
class AdvancedOutput extends Rete.Output {
  control = /*...*/
}
```
```js
.. extends Rete.Component {

builder(node) {
    var output = new AdvancedOutput(/*...*/, control);
}
```


[source](https://github.com/retejs/vue-render-plugin/blob/master/src/Node.vue#L6)

```pug
.output(v-for='output in outputs()' :key="output.key")
    .output-title {{output.name}}
    .control(v-control="output.control")
    Socket(v-socket:output="output", type="output", :socket="output.socket")
```

**Comment by TheElk205** [comment]
Hello,
I think with the current master this is not possible anymore, as the `control` line is not in any more.
Is there any other way to achieve this? OVerwriting CSS and mapping them is my only solution for now.

**Comment by Ni55aN** [comment]
@TheElk205 `control` is defined in Rete.Output https://github.com/retejs/rete/blob/master/src/input.ts#L9
