### ISSUE TITLE
Перемещение блоков в Safari

### ISSUE THREAD

**Issue by shift-reality** [retejs/rete#372]
Здравствуйте!
Попробуйте поместить рабочую область rete в iframe, получается такой баг, что редактор перестает слушаться курсор и блоки перестают передвигаться. Такой же баг, если разместить блок position absolute над рабочей областью.
То есть, действия, которые повторяют ошибку:
0) начинаем двигать блок или перемещаться по рабочей зоне мышкой (ЛКМ)
1) отпустить нужно где-то на блокe position absolute или за iframe
2) редактор перестает отвечать на дальнейшее взаимодействие ЛКМ
Помогите, плиз

**Comment by shift-reality** [comment]
ошибок в консоли нет

**Comment by Ni55aN** [comment]
В каком окружении отображается редактор? (Angular, чистый html, и т.д.)

**Comment by shift-reality** [comment]
1) не знаю, просто index.html в ней вебпак все скрипты конкатезировал в 1 <script>
2) VUE js

**Comment by Ni55aN** [comment]
в простом HTML не могу воспроизвести баг. Перемещаю узел за область iframe, бросаю = все дальнейшие перемещения работают

**Comment by shift-reality** [comment]
Ладно, тогда проверю на дебиане, возможно проблема присутствует только в макос хроме
Позже отпишу

**Comment by shift-reality** [comment]
Извините, но мне не удалось повторить баг в файрфоксе и хроме (стабл и бете) в дебиан 9
Видимо это затрагивает только мак ос, сафари вообще не двигаются блоки и не работает удаление связей по щелчку ПКМ
Как можно разобраться почему не работает?

**Comment by Ni55aN** [comment]
@shift-reality на эту тему уже были issue, а именно дело в поддержке pointer events в ~~относительно~~ старых версиях Safari. Может помогут полифилы, иначе заставлять юзера обновить браузер. По поводу других браузеров под Мак мне неизвестно

https://github.com/retejs/rete/issues/299
https://github.com/retejs/rete/issues/324

**Comment by shift-reality** [comment]
а не только в сафари глючит, последняя версия хрома 77 под мак ос тоже глючит аналогично, но в ней блоки еще хоть как то двигались..
Попробую полифилы поставить, отпишусь
