### ISSUE TITLE
Add node programmatically

### ISSUE THREAD

**Issue by Githamza** [retejs/rete#378]
I would add node from JS file not from UI. 
I can't find how to do it without using the graph interface

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/blob/a5f3a09a80529309f2e4748e135afde4f7eff4e2/test/editor.ts#L68-L72

**Comment by Githamza** [comment]
Should I register before the new components on engine ?

**Comment by Ni55aN** [comment]
yes
