### ISSUE TITLE
Error: Socket not fount for <input name> with key next

### ISSUE THREAD

**Issue by saalaus** [retejs/rete#381]
Hello! I want to change input name, i try delete input, then added new, but connection resets, i try get connection before delete input, then added connection via editor.connect, but i get error: 
code:
```
const selected = editor.selected.list[0];
const input = selected.getConnections()[0].input.node

editor.removeConnection(selected.getConnections()[0])
selected.outputs.clear();

var output = new Rete.Output('next', 'tests', anyType, false)
selected.addOutput(output);

editor.connect(output, input.inputs.get('prev'))
selected._alight.scan();
```
error:
![image](https://user-images.githubusercontent.com/37474917/66680170-51e2bf00-ec89-11e9-9652-fc1fde4d6d74.png)

**Comment by Ni55aN** [comment]
`alight-render-plugin` is deprecated. Please use another render plugin (React, Vue).
