### ISSUE TITLE
Creating outputs dynamically

### ISSUE THREAD

**Issue by jtwnel** [retejs/rete#383]
Hi Vitaly, I'm creating outputs dynamically in the nodes and everything seems ok, the outputs are added and I can make connections between nodes. The issue appears when I save the current editor to JSON and later I want to restore it. The outputs disappear and instead there's the default one created by the component. 

I already checked in the builder method if I receive the created outputs but it didn't work.

Is there a way to do this?

**Comment by janhaa** [comment]
Hi, the outputs need to be created in the builder method every time. I had the same use-case recently so you need some way to track what outputs you need in the data of each node.

For example I am creating outputs/inputs based on the selection of a control. I store the id of the corresponding object in the data field and on building the node (in the `builder` method) I read the id and create the outputs/inputs based on that.

**Comment by jtwnel** [comment]
Thanks for your answer! What you confirmed its really important, now its pretty clear how to handle this.
