### ISSUE TITLE
i have problem on create conntection.

### ISSUE THREAD

**Issue by blablasw** [retejs/rete#385]
![123](https://user-images.githubusercontent.com/56448399/67352865-d2db6980-f559-11e9-97e8-707e0efaa102.JPG)

**Comment by blablasw** [comment]
![1SharedScreenshot](https://user-images.githubusercontent.com/56448399/67440214-43899100-f601-11e9-9d08-75f4329763df.jpg)

**Comment by Ni55aN** [comment]
Какая версия ноды?

**Comment by blablasw** [comment]
9.11.2

**Comment by Ni55aN** [comment]
нет, здесь в чем-то другом проблема.
Что выдает, если просто из командной строки вызвать node и в ней `Object.keys({}).reduce`?

**Comment by blablasw** [comment]
> Object.keys({}).reduce
[Function: reduce]

**Comment by Ni55aN** [comment]
Скиньте код на codepen или сюда

**Comment by blablasw** [comment]
var Rete = require('rete');
var numSocket = new Rete.Socket('Number value');

class AddComponent extends Rete.Component {
    constructor(){
        super('Add');
    }

    builder(node) {
        var inp1 = new Rete.Input('num','Number', numSocket);
        var inp2 = new Rete.Input('num2', 'Number2', numSocket);
        var out = new Rete.Output('num3', 'Number', numSocket);

        return node
            .addInput(inp1)
            .addInput(inp2)
            .addOutput(out);
    }

    worker(node, inputs, outputs) {
		console.log('work'); 
    }
}
var engine = new Rete.Engine('demo@0.1.0'); 
var texts = 	'{"id":"demo@0.1.0","nodes":{"1":{"id":1,"data":{},"inputs":{"num":{"connections":[]},"num2":{"connections":[]}},"outputs":{"num":{"connections":[{"node":2,"input":"num","data":{}}]}},"position":[-454,-36.5],"name":"Add"},"2":{"id":2,"data":{},"inputs":{"num":{"connections":[{"node":1,"output":"num","data":{}}]},"num2":{"connections":[]}},"outputs":{"num":{"connections":[]}},"position":[-135,-52.5],"name":"Add"}},"comments":[]}';
engine.register(new AddComponent());
var data =  JSON.parse(texts);
engine.process(
data
).then(console.log)

**Comment by Ni55aN** [comment]
Проверил, работает, только с одним нюансом - нужен полифилл для runtimeRegenerator. У вас, я подозреваю, что что-то кроме 'rete' пакета подключено через require, из-за этого и некорректно работает Object.keys

**Comment by blablasw** [comment]
не понял

**Comment by blablasw** [comment]
Проблема решена
