### ISSUE TITLE
Incorrect resize behaviour in flex containers

### ISSUE THREAD

**Issue by gorunovanton** [retejs/rete#386]
Hello.
EditorView is resizing as a response to the resize event of window.
https://github.com/retejs/rete/blob/1d88f87ff7032f801ce8cfa3d3a1c7e617741429/src/view/index.ts#L29

This results in incorrect behaviour in flex containers because it sets a fixed width and height and the view stops being flexible.

I think it would be better to have an option to disable this behaviour to improve integration with flex containers.

**Comment by Ni55aN** [comment]
> and the view stops being flexible.

The container should have `overflow: hidden`
