### ISSUE TITLE
Импорт сокетов вывода

### ISSUE THREAD

**Issue by EpicMan2** [retejs/rete#387]
Есть проблема с тем, что при импорте по какой-то причине не создаются выводы у ноды при импорте из JSON. Эти выводы не прописаны заранее в компоненте, а добавляются в реальном времени.

Предоставлю ниже пример. (выводы 1556999362 и 2175023083 у ноды с id 1 были созданы в процессе работы с нодой уже после её создания через node.addOutput)

```
{"id":"floweditor@0.1.0","nodes":{"1":{"id":1,"data":{"displayname":"Шаг 1","cardarea":{"images":[],"texts":[],"files":[],"questions":[{"id":"","position":0,"questions":["123","321"]}],"videos":[]}},"inputs":{"num1":{"connections":[]}},"outputs":{"1556999362":{"connections":[{"node":2,"input":"num1","data":{}}]},"2175023083":{"connections":[{"node":3,"input":"num1","data":{}}]},"num":{"connections":[{"node":4,"input":"num1","data":{}}]}},"position":[-132.71299918112794,237.67642088023746],"name":"Сообщение"},"2":{"id":2,"data":{"displayname":"Задержка 2","cardarea":{"delays":[{"count":"","type":""}]}},"inputs":{"num1":{"connections":[{"node":1,"output":1556999362,"data":{}}]}},"outputs":{"num":{"connections":[]}},"position":[595.9457344347445,559.3659451088267],"name":"Задержка"},"3":{"id":3,"data":{"displayname":"Задержка 3","cardarea":{"delays":[{"count":"","type":""}]}},"inputs":{"num1":{"connections":[{"node":1,"output":2175023083,"data":{}}]}},"outputs":{"num":{"connections":[]}},"position":[593,265],"name":"Задержка"},"4":{"id":4,"data":{"displayname":"Задержка 4","cardarea":{"delays":[{"count":"","type":""}]}},"inputs":{"num1":{"connections":[{"node":1,"output":"num","data":{}}]}},"outputs":{"num":{"connections":[]}},"position":[591.5241578885799,-27.669105220059365],"name":"Задержка"}}}
```

Далее экспортирую пример при помощи
`var data = editor.toJSON();
data = JSON.stringify(data);`
`editor.fromJSON(data);`

По какой-то причине добавляются только "num" вывод. Остальные не появляются.

Никак не могу понять в чём проблема импорта сокетов вывода. Мне нужно как-то вручную их добавлять и создавать соединение, если выводы были созданы динамически?

**Comment by Ni55aN** [comment]
Вводы/выводы и другие элементы узла в NodeEditor должны добавляться внутри builder(), и наличие соединений в данных (toJSON()) никак не влияет на добавление входов/выходов. Если они динамические, можно сохранять информацию о них в `node.meta` и добавлять их на основе

**Comment by EpicMan2** [comment]
Спасибо за крайне ценную наводку. Решил проблему именно таким образом, пересоздавая соединения при импорте из JSON, сохранив их заранее.
