### ISSUE TITLE
Socket compatibility

### ISSUE THREAD

**Issue by WieFel** [retejs/rete#389]
As of now, only Sockets that correspond one single object are compatible. For example, one defines a `numberSocket = new Socket("number")` and uses it in all his nodes. All the `numberSocket`s can be connected with each other.
However, I need to store information inside sockets using the `data` property and thus need to create various socket objects. For example, I have:
```
socket1 = new Socket("number", new ExampleData1());
socket2 = new Socket("number", new ExampleData2());
```
Is it possible to override the socket compatibility check mechanism and define an own socket policy for compatibility?
In my case I would like sockets with the same `name` to be compatible, regardless of their actual object reference.

**Comment by Ni55aN** [comment]
> Is it possible to override the socket compatibility check mechanism

Yes, you can extend the Socket class. Checking is [as follows](https://github.com/retejs/rete/blob/c137e858e449f49a412572227981bb4a268c078f/src/output.ts#L18)

Or predefined collection of sockets with `combineWith` will solve your problem

**Comment by WieFel** [comment]
Thank you @Ni55aN!
