### ISSUE TITLE
RenderControl issue

### ISSUE THREAD

**Issue by Hatead1** [retejs/rete#390]
https://codepen.io/hatead1/pen/GaZYaq - что-то я заработался, не могу понять, в чем проблема.

Если нажать плюсик, добавится output и control, но установить сразу значение control-a не получается, пишет Cannot set property 'value' of undefined (т.к. у контроля еще нет vueContext). 

Если двинуть ноду или еще раз нажать на +, значение контролу присваивается, но начинает дурить следующий добавленный. В callback всё асинхронно, вызывается node.update(), почему контрол не полностью инициализируется, что ему не хватает?

Если добавить в .on обработку события rendercontol, то визуально всё начинает "работать", но warning всё равно остается.

**Comment by Ni55aN** [comment]
Лучше в этом случае передавать начальное значение, а еще лучше в setValue менять this.props, не обращаясь к vueContext

**Comment by Hatead1** [comment]
Т.е. конкретно в моем случае решения нет?

**Comment by Ni55aN** [comment]
Есть решение, выше написал.

**Comment by Hatead1** [comment]
Это не решение существующей проблемы, это совсем другой путь. А мне хотелось узнать, можно ли это решить в лоб, а не переписывая кучу кода.

**Comment by Hatead1** [comment]
Сегодняшних 5-и баксов на партеоне недостаточно для получения нормального ответа?

**Comment by Ni55aN** [comment]
> Это не решение существующей проблемы, это совсем другой путь. А мне хотелось узнать, можно ли это решить в лоб, а не переписывая кучу кода.

Проблема в асинхронном получении vueContext, я предложил решение. Переписывать кучу кода за Вас я точно не буду

> Сегодняшних 5-и баксов на партеоне недостаточно для получения нормального ответа?

Мой рейт значительно выше, и вкладом в open source я преследую не финансовую выгоду (ее по определению нет, поэтому у меня в приоритете могут быть другие задачи)

**Comment by Hatead1** [comment]
То, что происходит, называется багом, т.к. это не мое творчество, а код в рамках вашей библиотеки. Если я применяю функции неправильно - скажите, где ошибка и указание на такое ограничение в документации. Зачем мне какие-то обходные пути и переписывание кучи компонентов, если это банальная функция создания контрола??

**Comment by Ni55aN** [comment]
Реализация `NumControl` Ваша, а не в рамках библиотеки. Rete.js предоставляет только HTMLElement, в который в свою очередь *-render-plugin вставляет компонент для контрола, который он не реализует. В простых примерах было сделано через vueContext, что для тех кейсов вполне подходит, в этом же я предложил решение
