### ISSUE TITLE
AreaPlugin zoomAt not centering on screen

### ISSUE THREAD

**Issue by Githamza** [retejs/rete#393]
I'm trying to use the AreaPlugin to center nodes, I get a weird behaviour.

I'm regenerating all graph  when I get update from an observable

```
  async ngAfterViewInit() {
   this.dataflow$.subscribe(async data => {
      this.dataFlowService.dataflowModified.next(data)
      if (this.container) {
        while (this.container.firstChild) {
          this.container.removeChild(this.container.firstChild)
        }
      }
      this.container = this.el.nativeElement

      const reteFormat = await this.reteComponentService.convertToReteFormat(
        _.cloneDeep(data)
      )
      let reteFormatJson = Object.create(reteFormat)
      const components: any[] = []
      for (const obj in data) {
        components.push(new NumComponent(data[obj].name, data))
      }
      this.engine = new Engine('demo@0.2.0')
      this.editor = new NodeEditor('demo@0.2.0', this.container)
      this.editor.clear()
      this.editor.use(ConnectionPlugin)
      this.editor.use(ContextMenuPlugin, {
        searchBar: false,
        delay: 600000,
      })
      this.editor.use(AutoArrangePlugin, { margin: { x: 50, y: 50 }, depth: 0 })
      this.editor.use(AngularRenderPlugin, { component: MyNodeComponent })

      components.map(c => {
        this.editor.register(c)
        this.engine.register(c)
      })

      await this.editor.fromJSON(Object.create(reteFormatJson))
      await this.editor.nodes.map(elm => {
        this.editor.trigger('arrange' as any, { elm })
      })
      AreaPlugin.zoomAt(this.editor)
}
```

The first time when observable gets it's first data the editor is not centered on screen 

![Capture d’écran 2019-11-29 à 00 56 27](https://user-images.githubusercontent.com/11578288/69835601-2751c300-1243-11ea-9782-4e214551135c.png)

But the weird part is when a new value of data is triggered the editor gets centered.
![Capture d’écran 2019-11-29 à 01 00 18](https://user-images.githubusercontent.com/11578288/69835679-ae9f3680-1243-11ea-8e7d-e2e3e085454b.png)

Any idea of why this is happening only on initial `data`  value ?

**Comment by Ni55aN** [comment]
It seems that Angular didn't render a nodes when `AreaPlugin.zoomAt` was called. Try to check it using breakpoint in devtools or requestAnimationFrame
