### ISSUE TITLE
Navigation of all nodes in rete 

### ISSUE THREAD

**Issue by ayazmu** [retejs/rete#394]
Hi @Ni55aN 
I want to achieve navigation of the nodes left to right, right to left, top to bottom and bottom to top with four arrows buttons respectively just like when we drag the nodes on the editor with the help of a cursor .
Is it possible to achieve this behavior in rete?
How would we do that ?

something like below : 
https://www.iconfinder.com/icons/5272630/fire_frame_midpoint_reticle_ross_icon

**Comment by ayazmu** [comment]
Hi @Ni55aN ,
After digging into the issue more, i realized changing the values of this.transform.x and this transform.y i can move the nodes. I just need to know the formula to increment the values of x and y so that i can move them in an order on clicking the arrow buttons.

**Comment by Ni55aN** [comment]
```js
editor.view.area.translate(x, y); // new position in pixels
```

Example:
```js
function moveArea(dx, dy) {
  const { area } = editor.view;
  area.translate(area.transform.x + dx, area.transform.y + dy);
}
```

```html
<button click="moveArea(0, -100)">Up</button>
<button click="moveArea(0, 100)">Down</button>
<button click="moveArea(-100, 0)">Left</button>
<button click="moveArea(100, 0)">Right</button>
```

**Comment by ayazmu** [comment]
Thanks Man! :)
