### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Dan-Gamin** [retejs/rete#395]
### Help! with this error

hello i'm new to Rete and Github so yeah.
the line the **error** was in : `import Rete from "rete";`
that's it i don't know a thing about this **error**

**Comment by Ni55aN** [comment]
What is your runtime envirinments? browser/node.js?

**Comment by ToxesFoxes** [comment]
I also encountered such a problem, I use node js.

**Comment by Ni55aN** [comment]
@ToxesFoxes Node.js doesn't support ES modules by default

**Comment by Dan-Gamin** [comment]
my development environment is browser.

**Comment by Ni55aN** [comment]
This problem is not related to Rete.js. You should verify the correct use of ES modules in your environment.

**Comment by LRagji** [comment]
@Ni55aN  Hi this may be slightly off-topic; but request you to have an examples folder here with complete implementation in one html file it will help a lot for first time adopters...

**Comment by Ni55aN** [comment]
@LRagji there are [examples](https://codepen.io/collection/nqpELR) on Codepen

You can download any of them

![image](https://user-images.githubusercontent.com/8259641/82727685-b1f81400-9cf4-11ea-893c-6958fb674272.png)
