### ISSUE TITLE
Connection create and connect

### ISSUE THREAD

**Issue by serdiuk-oleksandr** [retejs/rete#396]
Hello!

Faced the following problem, need to create a connection from one node to a new one via connection drop and context menu (after drop on editor area, context menu will appear, **connection should not disappear and keep same position that was defined before click on area without holding any keys**, just click on an editor area). Issue: After clicking on the editor area, the connection disappears, but I need to leave it next to the context menu.

<img width="763" alt="Screenshot 2019-12-11 at 00 46 41" src="https://user-images.githubusercontent.com/31037001/70575689-b51c9f00-1baf-11ea-8ffd-a06d5f3906b2.png">

I tried different things:
1. Strange, but it doesn’t work at all https://github.com/retejs/connection-mastery-plugin (at least, requirement to hold any keys is not suitable)

2. I tried the following (also did not help) to prevent:

`editor.on ('connectiondrop', connection => false). `

3. Tried and this:

```
editor.view.container.addEventListener ('mousedown', e => {
         event.preventDefault ();
         event.stopPropagation ();
});
```

and block other events in order to prevent connection disappear - not successful.

I searched for similar issues but found nothing. Tell me, can this be done as in the video that is specified in connection-mastery-plugin (https://youtu.be/8ew12FLgaMs?t=98)?

**Comment by DaryeDev** [comment]
Did you find a solution? I am interested on implementing such a system.

**Comment by Ni55aN** [comment]
@DaryeDev do you need it for v2?

**Comment by DaryeDev** [comment]
> @DaryeDev do you need it for v2?

Would be cool to not remove the connection on connectiondrop until context is returned, or dont remove it given a falsy return, and some way to remove it afterwards (calling that after clicking on the editor, in my case)

**Comment by serdiuk-oleksandr** [comment]
Issue closed

**Comment by Ni55aN** [comment]
> to not remove the connection on connectiondrop

the pseudo-connection is deleted inside the pick method if the target socket isn't found https://github.com/retejs/connection-plugin/blob/343ee308f26694b5f48083ce81201e72b4ecb4f9/src/index.ts#L106

You casn extend this plugin and change this behavior to keed pseudoconnection on the canvas.

Then you can trigger context menu https://discord.com/channels/1081223198055604244/1088598977735299142/1299483226716373013

and remove pseudoconnection as soon as new node is added
