### ISSUE TITLE
Something wrong with webpack

### ISSUE THREAD

**Issue by dev-yarolsav** [retejs/rete#397]
I have got strange error, pls help

ERROR in app.js from UglifyJs
Unexpected token: keyword «const» [./node_modules/rete-vue-render-plugin/build/vue-render-plugin.esm.js:283,0][app.js:20332,0]

**Comment by Ni55aN** [comment]
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/362#issuecomment-425849160
