### ISSUE TITLE
showcontextmenu & hidecontextmenu events

### ISSUE THREAD

**Issue by AdrienCulem** [retejs/rete#398]
Hey there,

Shouldn't the hidecontextmenu & showcontextmenu be added to the `events.d.ts` ?

Thanks !

**Comment by Ni55aN** [comment]
`rete-context-menu`-plugin` doesn't have TS type definitions, so TS analyzer doesn't know anything about these types of parameter.
You can add your own

```ts
import { Node } from 'rete';

declare module 'rete/types/events' {
    interface EventsTypes {
        hidecontextmenu:  { e: MouseEvent; node: Node },
        showcontextmenu: { e: MouseEvent; node: Node }
    }
}
```
