### ISSUE TITLE
Get data of connected node using node.data[key] in worker() - Angular 8

### ISSUE THREAD

**Issue by WieFel** [retejs/rete#412]
I am having a problem when trying to get the `node.data[key]` in the worker() function of a Component:

I use simple `NumberComponent`s as it is done in the [Angular 8 example](https://github.com/retejs/examples/tree/master/Angular8). When a NumberComponent is connected to an arbitrary node, the worker of that node is called and the `node.data` object contains the associated data, e.g. using `node.data.num`.

When I use a custom `ArrayComponent` which uses my customly made `ArrayControl` (an array of number inputs, see [my gist](https://gist.github.com/WieFel/d3aaf91723cc2e8d54064e10bb07c40a)) and connect it to an arbitrary node, the worker's `node.data` does **not** contain the array data that I am setting within the `ArrayControl`.

Therefore, I wonder where exactly the `node.data[key]` is being set prior to connecting a node with another?

**Comment by Ni55aN** [comment]
I assume the `putData` method is not called in your ArrayControl. Therefore, no data was written to the node

**Comment by WieFel** [comment]
I stepped through the code using the debugger and `putData` is called correctly. After being called, the array-node's data contains the required data, just as expected.

However, the data doesn't arrive at the other end of the connection like it does with the normal `NumberControl` and `NumberComponent`. When checking the worker() of the "receiving node", the `node.data` doesn't contain the required property anymore.

I feel like I am missing a step that moves the `node.data` from the "outputting node" to the "receiving node". Any hints?

**Comment by WieFel** [comment]
I just found out the problem.

The reason was that I was not calling `editor.process()` and thus the data was not forwarded to the "next" node.
