### ISSUE TITLE
Dynamically change a node's structure based on its input

### ISSUE THREAD

**Issue by WieFel** [retejs/rete#416]
I want to change the structure of a node based on its connected input. At the beginning, the node should be connectable to any component (see the node **Alteration** below):
![no_connection](https://user-images.githubusercontent.com/8345062/74372516-0f69f400-4ddb-11ea-9548-a973ce340454.png)

When having received a connection, the node's internal structure (controls+outputs) should be changed depending on the input, just like in the picture below:
![alt_position](https://user-images.githubusercontent.com/8345062/74372851-af278200-4ddb-11ea-9516-12eeadb84bb9.png)

As of now, when the `"connectioncreate"` event is triggered by the editor I am removing the "empty" **Alteration** node and adding a new  "filled" node at the same position. However, using this approach, the connection mechanism between the nodes doesn't work properly and has some lags.

Is there any better option for manipulating a node's controls/outputs dynamically, e.g. whithin the `worker()`?

**Comment by Ni55aN** [comment]
> Is there any better option for manipulating a node's controls/outputs dynamically, e.g. whithin the worker()?

The scheme shouldn't be modified in a `worker()`, since this changes will not affect current processing. Only some side effects are possible (for example, print log in node's control) that do not affect processing.

There are no problems with dynamic adding controls. As usual, `node.addControl`, and after that call `await node.update();`

**Comment by ilomon10** [comment]
> There are no problems with dynamic adding controls. As usual, `node.addControl`, and after that call `await node.update();`

Not working, control not updating.
On the node class the changes but those changes are not rendered.

**Comment by VitaliyDemchuk** [comment]
> > There are no problems with dynamic adding controls. As usual, `node.addControl`, and after that call `await node.update();`
> 
> Not working, control not updating.
> On the node class the changes but those changes are not rendered.

+1, not working

**Comment by VitaliyDemchuk** [comment]
how call `builder()` and redraw node, after `data` object change?

**Comment by kvnbra** [comment]
I don't know for other render plugins, but with Vue.js I had to call `this.$forceUpdate()` on the node vue component to see the result.

**Comment by montasIET** [comment]
same problem
