### ISSUE TITLE
Updating connections after dynamically changing a node

### ISSUE THREAD

**Issue by verloka** [retejs/rete#417]
Hi.

When I change the contents of a node, the connection is displayed incorrectly. To fix this, you need to distort the node by moving it. I've call node.update() it does not help. I am using Vue Render.

![presentation](https://user-images.githubusercontent.com/5623092/74522995-f0777900-4f24-11ea-8f8c-2ff64a13106a.gif)

**Comment by vamidi** [comment]
Same issue!

**Comment by verloka** [comment]
> example code in my case

this is not an elegant solution. I hope there is an internal method that can solve this problem, or another solution should be invented

**Comment by Ni55aN** [comment]
```js
await node.update();
this.editor.view.updateConnections({ node })
```

**Comment by verloka** [comment]
> ```js
> await node.update();
> this.editor.view.updateConnections({ node })
> ```

Yes it helps, thanks.

**Comment by VitaliyDemchuk** [comment]
> ```js
> await node.update();
> this.editor.view.updateConnections({ node })
> ```

work only if use next code: 
```js
async builder(node) {
  // Load data from API and call addInput(), addOutput() functions
  // ...
  
  await node.update();
  setTimeout(() => {
    this.editor.view.updateConnections({ node });
  }, 100);
}
```
why doesn't it work without `setTimeout`?

**Comment by savanthvinay** [comment]
@Ni55aN  Yes

**Comment by Ni55aN** [comment]
@savanthvinay this should work for you https://github.com/retejs/rete/issues/417#issuecomment-752506526

**Comment by stallboy** [comment]
how to do this on rete": "^2.0.2"， on react，it has not editor.view api。
i tried area.update('node', nodeid), it worked on node update
but area.update('connection', connectionid) does not work

**Comment by Ni55aN** [comment]
@stallboy `rea.update('connection', connectionid)` is supposed to work. Does it have correct `connectionid`?

**Comment by stallboy** [comment]
@Ni55aN it will begin update connection only after a mouse click on area.

`area.update('connection', connectionid)` does not work!
I also tried removeConnection then addConnection, then update,  even setTimeout... still does not work.

```typescript
setTimeout(() => {
    const connections = editor.getConnections();
    const incomingConnections = connections.filter(connection => connection.target === node.id);
    for (let ic of incomingConnections) {
        editor.removeConnection(ic.id);
        let fromNode = editor.getNode(ic.source);
        let toNode = editor.getNode(ic.target);
        let conn = new EntityConnection(fromNode, ic.sourceOutput, toNode, ic.targetInput);
        conn.connectionType = ic.connectionType ?? EntityConnectionType.Normal;
        editor.addConnection(conn);
        area.update('connection', conn.id);
    }
}, 100);
```

**Comment by Ni55aN** [comment]
@stallboy according to the screnshots, you have a problem with updating socket positions (not connections UI component directly)

https://github.com/retejs/render-utils/blob/6ba258e88eb59eeb42d2a65df3c3d11d30b36303/src/sockets-position/base-socket-position.ts#L76

How to launch it?

**Comment by stallboy** [comment]
@Ni55aN Give me 30 minutes.  I will write a English README.md soon

**Comment by Ni55aN** [comment]
@stallboy np, I'll be able to check it in a few hours or tomorrow

**Comment by Ni55aN** [comment]
@stallboy np, anyway I'll be able to check it in a few hours or tomorrow

**Comment by stallboy** [comment]
@Ni55aN  english readme done

## build backend server

### Prerequisites

* jdk21
* gradle

### build, generate cfggen.jar.

```bash
genjar.bat
```

## run backend server

```bash
cd cfgeditor
java -jar ../cfggen.jar -datadir ../example/config  -gen server
```

## run cfgeditor front server

```bash
pnpm run dev
```

## browser 
http://localhost:5173/

![image](https://github.com/retejs/rete/assets/559049/bab0d36f-7580-4d90-bd9a-5bd7a2e09c7b)

**Comment by stallboy** [comment]
> @stallboy according to the screnshots, you have a problem with updating socket positions (not connections UI component directly). It can be updated on socket update or `noderesized` event
>

**Comment by Ni55aN** [comment]
@stallboy the problem is that the node has a transition, so the socket positions are recalculated only once 
at the beginning of the animation. 

But.. this is half the problem 🙄 The second part is that there is a bug in two packages, which specifically concerns updating the positions of input sockets during a restart

I'll fix this as soon as I have time

At the moment a workaround is:
```ts
await area.update('node', node.id);
setTimeout(async () => {
  await area.update('node', node.id);
}, 200)
```
You can replace `setTimeout` with animation ticker if it's ok for you in terms of performance. After the fix this will be replaced by the faster method `area.resize`

**Comment by stallboy** [comment]
that's great. thanks a lot. I didn't expect antd animation.

**Comment by stallboy** [comment]
@Ni55aN https://github.com/retejs/react-plugin/blob/main/src/presets/classic/components/Node.tsx
the order of inputs, outputs, controls is fixed。ouputs first，then controls，inputs。

if i can give some order option，that will help.

**Comment by stallboy** [comment]
in fact, my real problem is    "automatically set node width/height by custom control  change and update related connection"  .
maybe it can be done on the retejs side.
