### ISSUE TITLE
addControl: Item has already been added to some node

### ISSUE THREAD

**Issue by fogine** [retejs/rete#419]
I believe there is a bug in code here, causing exception when calling `node.addControl`
https://github.com/retejs/rete/blob/76605fda249796667a05d9a687b3c852f70b54a6/src/node.ts#L28-L29

as when not using typescript, `Control` instance has `parent` property qual to `undefined`.

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/blob/76605fda249796667a05d9a687b3c852f70b54a6/src/control.ts#L8

It's not a bug. Initially `Control` has `parent = null`. It seems that this control has already been added to some node, so you cannot add it again

**Comment by CosasDePuma** [comment]
There is no error. I got the same exception and my mistake was extending the class using

```js
class CustomControl extends Rete.Component
```
instead of 

```js
class CustomControl extends Rete.Control
```

That's probably why you don't have the `parent` property defined.
