### ISSUE TITLE
Clone with Connections 

### ISSUE THREAD

**Issue by kaiqmo** [retejs/rete#426]
Hi there,

Is it possible to make a second clone function where it clones everything while making a new component id ?
Example uses:
Clone with Connections : Clones a component and its current values and connections.
![image](https://user-images.githubusercontent.com/22498356/77358958-9e96ef80-6d29-11ea-852e-9040c67650c4.png)

Thanks!

**Comment by Ni55aN** [comment]
https://github.com/retejs/context-menu-plugin/blob/master/src/node-menu.js#L13-L17
and call `editor.connect` for every connection from old node and relative input/output from cloned node

**Comment by CodoMg** [comment]
For me worked like this:
```javascript
const {name, position: [x, y], ...params} = node;
const component = editor.components.get(name);
const newNode = await createNode(component, {...params, x: x + 20, y: y + 20});

this.editor.addNode(newNode);

let connections = await node.getConnections();
connections.forEach(connection => {
  if (connection.input.node === node) {
    this.editor.connect(connection.output, newNode.inputs.get(connection.input.key), connection.data);
  }

  if (connection.output.node === node) {
    this.editor.connect(newNode.outputs.get(connection.output.key), connection.input, connection.data);
  }
});
```
