### ISSUE TITLE
Process node worker on input change

### ISSUE THREAD

**Issue by defcon8** [retejs/rete#429]
Hi Guys,

First of all, ReteJS great project. But I need some help, I already did some research myself but can't figure this one out.

I have a basic flow of 3 components:

- **OnSlide component:** which triggers an action (event) when the user slides a GUI component, it also exposes a value between 0 and 100 which is the the sliders position.
- **ColorRamp component:** it converts a value to an index of a color gradient. So for example i have a gradient running from green to red. An input value of 50 would result in a yellow color output (hex color).
- **SetColor component:** Which takes an action, and color.. and sets the background color of the UI component to the given color.

<img width="879" alt="Schermafbeelding 2020-04-01 om 20 56 52" src="https://user-images.githubusercontent.com/3636349/78175563-61cea500-745b-11ea-8e66-d16cfc2378fb.png">

Everything is working except the color that the ColorRamp component gives is always the same. I noticed that the worker() function in the ColorRamp component is only called the first time.

What I want to accomplish is that the Color Ramp plugin always gives the correct color, so whenever the input "value" changes.. it recalculates the correct color output.

**The strange thing is that everything works flawless but only the first time onSlide triggers an event**. In that scenario the worker() functions of all components are called. But after the first time.. only the worker() function of the onSlide component gets called...

I've been debugging all night.. can't figure it out... it looks to me like the "thread" somewhere get's lost in _asyncToGenerator_.

Thank you very much!
Kind regards,
Bastiaan

Components source code, in order of the signal flow:

**OnSlide component (event generator):**
```Javascript
import Rete from "rete";
import Sockets from "../sockets";

class OnSlideComponent extends Rete.Component {
    constructor(item){
      super('On Slide');
      this.task = {
        outputs: {act: 'option', currentValue: 'output'},
        init(task){
           item.shape.on('sliding', function(slideEventData) {
                task.run(slideEventData.value);
                task.reset();
            });
        }
      }
    }
    
    builder(node) {
      node.addOutput(new Rete.Output('act', 'Action', Sockets.actionSocket));
      node.addOutput(new Rete.Output('currentValue', 'Value', Sockets.numberSocket));
    }
    
    worker(node, inputs, sliderValue) {  
      return {
          currentValue: sliderValue
      }
    }
}

export default OnSlideComponent;
```

**ColorRamp component (value to color):**
```Javascript
import Rete from "rete";
import Sockets from "../sockets";
import NumberControl from "../controls/numbercontrol";
import Rainbow from "rainbowvis.js";

class ColorRampComponent extends Rete.Component {
  
    constructor() {
      super('Color ramp');
      this.rainbow = new Rainbow();
      this.task = {
        outputs: {
            actout: "option",
            color: "output"
        }
      }
    }
  
    builder(node) {
      var rangeMinInput = new Rete.Input('rangemin', 'Min.', Sockets.numberSocket);
      rangeMinInput.addControl(new NumberControl("rangemin", node.data.midiChannel));

      var rangeMaxInput = new Rete.Input('rangemax', 'Max.', Sockets.numberSocket);
      rangeMaxInput.addControl(new NumberControl("rangemax", node.data.midiChannel));

      var valueInput = new Rete.Input('value', 'Value', Sockets.numberSocket);
      valueInput.addControl(new NumberControl("value", node.data.midiValue));

      var colorOutput = new Rete.Output('color', 'Color', Sockets.colorSocket);

      node
        .addInput(new Rete.Input('act', 'Action', Sockets.actionSocket))
        .addInput(rangeMinInput)
        .addInput(rangeMaxInput)
        .addInput(valueInput)
        .addOutput(colorOutput)
        .addOutput(new Rete.Output('actout', 'Action', Sockets.actionSocket));
    }
  
     worker(node, inputs, outputs) {
        var value = inputs["value"] ? inputs["value"][0] : node.data.value;
        var calculatedColor = "#" + this.component.rainbow.colourAt(value);
        return {color: calculatedColor};
     }
  }

export default ColorRampComponent;
```

**SetColorComponent (updates UI component):**
```Javascript
import Rete from "rete";
import Sockets from "../sockets";
import Spectrum from "spectrum-colorpicker";
import "../../../node_modules/spectrum-colorpicker/spectrum.css";

import ColorPickerControl from "../controls/colorpickercontrol";

class SetColorComponent extends Rete.Component {
  
    constructor(item) {
      super('Set Color');
      this.task = {
        item: item, /* BW: There might be an easier way to pass objects to the worker function, but I don;t know it yet */
        outputs: {}
      }
    }
  
    builder(node) {
      var ctrl = new ColorPickerControl("color", node.data.color);
      
      var colorInput = new Rete.Input('color', 'Color', Sockets.colorSocket);
      colorInput.addControl(ctrl);

      node
        .addInput(colorInput)
        .addInput(new Rete.Input('act', 'Action', Sockets.actionSocket));
    }
  
    worker(node, inputs) {
        var color = inputs["color"] ? inputs["color"][0] : node.data.color;
        this.component.task.item.setColor(color);
   }
  }

  export default SetColorComponent;
```

**Modules versions:**
    "rete": "^1.4.3-rc.1",
    "rete-connection-plugin": "^0.9.0",
    "rete-context-menu-plugin": "^0.5.2",
    "rete-keyboard-plugin": "^0.1.2",
    "rete-task-plugin": "^0.3.0",
    "rete-vue-render-plugin": "^0.5.0",

**Comment by Ni55aN** [comment]
How do you call `task.run()`? 
Every node caches their output data. By default it will reset output data after the tasks chain will be completed

https://github.com/retejs/task-plugin/blob/47d6ca139ef42785869ebf2ea4b74800302ba9ce/src/task.js#L28

>  item: item, /* BW: There might be an easier way to pass objects to the worker function, but I don;t know it yet */

```js
task.run(data);
///
worker(node, inputs, data) { // <--

}
```

**Comment by defcon8** [comment]
Hi @Ni55aN ,

Thank you for your help. I had an extensive look at the run() function, and I think I start to understand the design. I try to debug/step thru the run function when its getting called by the first component. But it seems to be completely rewritten by a library called "renegerator-runtime". Do you have any idea if I can disable this "renegerator-runtime", for as far as I understand this library is required by Rete?

Right before I step into run():
<img width="664" alt="Schermafbeelding 2020-04-01 om 22 17 21" src="https://user-images.githubusercontent.com/3636349/78182773-191ce900-7467-11ea-8436-9d2f5227fca5.png">

And then it's getting really obfuscated:
<img width="672" alt="Schermafbeelding 2020-04-01 om 22 17 45" src="https://user-images.githubusercontent.com/3636349/78182813-2508ab00-7467-11ea-8d42-7de1df721e46.png">

Thanks,
Bastiaan

**Comment by defcon8** [comment]
Ok breakthrough, after lots of debugging and headaches I found a solution. When I ported the components from the codepen example (above) directly into my "production" code it still would not work.

The problem is in the rete-task-plugin. The codepen (which is one of the official Rete examples which I forked) includes rete-task-plugin version 0.1.7. When I use this plugin version everything works as expected. But everything above 0.1.7, so for example 0.2.0 it breaks.

It will only fire the first event and not update the other workers.

**Comment by Hatead1** [comment]
Nice :) (i'm about https://codepen.io/defcon8/pen/dyoLzRO)
1. remove all nodes.
2. Enjoy background changes.
How it's work??

**Comment by defcon8** [comment]
@Hatead1 ,

Sorry I don't quite understand what you mean. Can you please elaborate on your comment? :-)

Kind regards,

Bastiaan

**Comment by Hatead1** [comment]
Bastiaan,

Background color keeps changing, even if all nods are removed.

**Comment by Ni55aN** [comment]
@defcon8 v0.2.0 caches data, thats why the `Render` node gets old data from" Value to Color "

**Comment by stevesch** [comment]
This still appears to be a problem in rete-task-plugin 0.3.0.
It appears that nodes using this pattern of output ports that are "action + some data" don't have a good way to reset the node, at least as far as I see.

task.run has a second parameter, "needReset," which can be set to "true", or you can call task.reset manually as you have done above.  The problem in both cases is that it only resets the node initiating the action.  Dependent nodes, like the Color Ramp node in the example above, do not get reset.  The "needReset" flag is always passed in as "false" to dependent nodes (those hooked to the source of the action via connections).
I don't see an easy way around this other than to manually propagate the reset through the connections, which is also not easy (and would probably be pretty wasteful).

Unless reset can be called from the workers or something?  I don't think this would work though because the output data gets cleared before it's used.

The "needReset" flag seems like the right approach-- it resets the node after all processing is complete.  The workaround that I've found is to override the Task run() function within the init function of the nodes' task so that they call the original run() function with the "needReset" flag always "true."  Seems like it works, but is a bit odd and clunky.

Anyone else run into this?
