### ISSUE TITLE
Possible to Wrap the Editor in a React Component?

### ISSUE THREAD

**Issue by JUSTINMKAUFMAN** [retejs/rete#433]
I’m hoping to put the editor inside a react component that can be added to the DOM the React way. Is this possible?

**Comment by Ni55aN** [comment]
yes, you need a reference to HTML element with fixed sizes

**Comment by Ni55aN** [comment]
https://en.reactjs.org/docs/refs-and-the-dom.html

```js
  componentDidMount() {
    createEditor(this.ref); // create `createEditor` method that accepts a container for editor 
  }
```
