### ISSUE TITLE
Lock nodes

### ISSUE THREAD

**Issue by dotesfera** [retejs/rete#434]
Hi,

Is there a way to lock a specific node on the editor (prevent drag)?

Also, is there a way to resize the nodes with the editor drag disabled? How to disable editor drag with a specific event?

Best regards

**Comment by Ni55aN** [comment]
```js
editor.on('nodetranslate', ({ node }) => {
  if (node.id === <id>) return false; 
});
```

**Comment by dotesfera** [comment]
Is there a way to do this on lifecycle event plugin also? Can you liberate every node related event on that plugi? That lacks some good events that should be used on node component lifecycle.

**Comment by Ni55aN** [comment]
> lifecycle event plugin also?

no, `nodetranslate` event isn't supported by lifecycle plugin. You can try to modify it and make PR
