### ISSUE TITLE
Determine if a node is upstream or downstream another node

### ISSUE THREAD

**Issue by pwichmann** [retejs/rete#436]
As the title says, is it possible to determine if a node is **upstream or downstream** another node?

If so, how could this be achieved? Let's assume I have the ID of both nodes.
Somehow Rete.js must know this since the calculations flow in the designated directions.

**Comment by pwichmann** [comment]
I wrote a clunky recursive function that can iterate over all nodes and find nodes upstream.

**Comment by Ni55aN** [comment]
I see the follow alghorithm:
1. get bounding rects of nodes (`editor.view.nodes.get(node).el.getBoundingClientRect()`
2. compare nodes intersection (check `top`/`bottom` and `left`/`right` properties of rect)
3. check nodes order of intersecting nodes (`editor.view.area.el.children`)

no recursion required 💡

**Comment by pwichmann** [comment]
I use the modules plugin and so determining if a node is a predecessor or successor is much harder and cannot rely on the editor alone (which only shows the currently active module). That's my impression at least.

**Comment by Ni55aN** [comment]
The [`recursion.ts`](https://github.com/retejs/rete/blob/master/src/engine/recursion.ts) has a similar algorithm.

Or you can find other implementations in external libraries (for example, https://www.npmjs.com/package/js-graph-algorithms)
