### ISSUE TITLE
Dynamic outputs doesn't render

### ISSUE THREAD

**Issue by CRGavrila** [retejs/rete#443]
Dynamic outputs doesn't register in rete component when this will first mount. 

You can reproduce this at: https://codepen.io/hatead1/pen/GaZYaq
Steps:
1. go to codepen
2. replace: `let nodes = {"id":"demo@0.1.0","nodes":{"1":{"id":1,"data":{},"inputs":{},"outputs":{"a":{"connections":[]},"b":{"connections":[]},"c":{"connections":[]},"d":{"connections":[]}},"position":[479.0970052722768,130.678304684546],"name":"AddOutput"}}};` at line 128
3. run the pen

result:
there is no output based on node json
Expected:
should have 4 outputs

**Comment by kvnbra** [comment]
Seems similar to this closed issue : #439 
Does it resolve your problem ?

**Comment by CRGavrila** [comment]
@kvnbra I thought on that solution to also store in data, but this means repeat ourself and to store same thin 2 different places, in "data" and "outputs". If this is not a workaround and is the expected flow, the @Ni55aN should mention, and maybe i could make a pull request for docs.
