### ISSUE TITLE
preventing zoom on double click

### ISSUE THREAD

**Issue by imding** [retejs/rete#444]
hi, just curious how we can prevent the editor from zooming in when double clicking?

**Comment by Hatead1** [comment]
editor.on('zoom', ({ source }) => {
        return source !== 'dblclick';
    });

**Comment by imding** [comment]
> ```
> editor.on('zoom', ({ source }) => {
>     return source !== 'dblclick';
> });
> ```

this works, thanks alot!

**Comment by emadurandal** [comment]
FYI, In Rete.js v2, the following code works

```typescript
  area.addPipe(async context => {
    // prevent zooming with double click
    if (context.type === 'zoom') {
      if (context.data.source === 'dblclick') {
        return;
      }
    }
    return context;
  });
```
