### ISSUE TITLE
zoom goes wild on examples

### ISSUE THREAD

**Issue by vmalloc** [retejs/rete#445]
Trying to fiddle with the scroll wheel in FF when visiting one of the examples zooms way to quickly and way too much, losing the graph almost immediately. It is unclear how to recover from such a situation without reloading the page, and sometimes the attempts even yield strange results (like flipped graph image for example)

**Comment by fat4lix** [comment]
+1 I've got the same issue on Chrome 
But I think AreaPlugin https://rete.js.org/#/examples/area it's the way to prevent this issue
