### ISSUE TITLE
Editor display flips upside down sometimes when zooming in and out

### ISSUE THREAD

**Issue by iskandarreza** [retejs/rete#446]
Background: When I'm double-clicking on a node, the editor zooms in really close to the node. So I zoom out and sometimes it zooms out really fast and really far out. Then when I try to zoom back in/out quickly the whole editor flips upside down. 

![](https://i.imgur.com/1QIupmS.png)

**Comment by tombasche** [comment]
I can confirm this also happens when just zooming out really quickly with the mousewheel. Has there been any traction on this? Happy to take a look if there's been no movement. 

I *suspect* something is negated in the viewport without being handled correctly

**Comment by HeyImNoxz** [comment]
got the same problem any news ?

**Comment by tombasche** [comment]
> got the same problem any news ?

I get the feeling this repository is somewhat abandoned; last commit was 6 months ago...

**Comment by HeyImNoxz** [comment]
yeah got the same feeling

this patch fixes the problem:

```javascript

const fs = require('fs');
const path = require('path');

const loadRetePath = path.resolve(__dirname, '../node_modules/rete/build/rete.esm.js');

fs.writeFileSync(
  loadRetePath,
  fs
    .readFileSync(loadRetePath, 'utf8')
    .replace(
      'var delta = (wheelDelta ? wheelDelta / 120 : -e.deltaY / 3) * this.intensity;',
      'var delta = (wheelDelta ? wheelDelta / 120 : -e.deltaY / 50) * this.intensity;',
    ),
);

```

**Comment by becausemirbek** [comment]
> yeah got the same feeling
> 
> this patch fixes the problem:
> 
> ```js
> const fs = require('fs');
> const path = require('path');
> 
> const loadRetePath = path.resolve(__dirname, '../node_modules/rete/build/rete.esm.js');
> 
> fs.writeFileSync(
>   loadRetePath,
>   fs
>     .readFileSync(loadRetePath, 'utf8')
>     .replace(
>       'var delta = (wheelDelta ? wheelDelta / 120 : -e.deltaY / 3) * this.intensity;',
>       'var delta = (wheelDelta ? wheelDelta / 120 : -e.deltaY / 50) * this.intensity;',
>     ),
> );
> ```

where should i write this code?

**Comment by HeyImNoxz** [comment]
its a postinstall patch 
so you have to run it after npm install

example (package.json): 

```json
"scripts": {
    "postinstall": "node ./scripts/rete-patch.js"
  },
```

**Comment by becausemirbek** [comment]
> its a postinstall patch
> so you have to run it after npm install
> 
> example (package.json):
> 
> ```json
> "scripts": {
>     "postinstall": "node ./scripts/rete-patch.js"
>   },
> ```

Thanks!
