### ISSUE TITLE
Adding File control to retejs using Angularplugin

### ISSUE THREAD

**Issue by Ibrahimvse** [retejs/rete#447]
Hi  @Ni55aN , 
Thenks for this Rete great project, I am new to rete and I have angular project in which I am using rete.I need help to add file input control to my controls can you help in how I can do that?
Thanks

**Comment by kvnbra** [comment]
Hi,

What is blocking you ? How to add a custom control ? How to make a template for this control with angular ? How to use a file input in rete ?

I'm using Vue, but what I did, and understand, from the [doc](https://rete.js.org/#/docs/controls) is :
- Create a custom class extending `Rete.Control`
- Create a Vue component to add template and logic for this control
- Add the custom control to one of your `Rete.Component` subclass class, via `node.addControl(control)` in the `builder(node)` function

**Comment by Ibrahimvse** [comment]
Hi @kvnbra , Thank you for fast response. I am struggling in how to get the selected file from the file control as file in the component template, how the change method should be implemented. And how to use its value inside node worker

**Comment by Ibrahimvse** [comment]
I could create TextControl :`
import { Component, Input, Type, ANALYZE_FOR_ENTRY_COMPONENTS } from '@angular/core';
import { Control } from 'rete';
import { AngularControl } from 'rete-angular-render-plugin';
import { ReteComponent } from '../rete.component';


@Component({
  template: `<input [type]="type" [value]="value" [readonly]="readonly"  (change)="change($event.target.value)">`,
  styles: [`
    input {
      border-radius: 30px;
      background-color: white;
      padding: 2px 6px;
      border: 1px solid #999;
      font-size: 110%;
      width: 140px;
      box-sizing: border-box;
    }
  `]
})
export class TextComponent {
    @Input() type:string;
    @Input() value!: string;
    @Input() readonly!: boolean;
    @Input() change!: Function;
    @Input() mounted!: Function;

  ngOnInit() {
    this.mounted();
  }
}

export class TextControl extends Control implements AngularControl {
  component: Type<TextComponent>
  props:{
      [key:string]:unknown;
  }

  constructor(public emitter, public key,type='text', readonly = false){
      super(key);
      this.component=TextComponent;
      this.props={
          readonly,
          type,
          value:'',
          change:v=>this.onChange(v),
          mounted:()=>{
              this.setValue((this.getData(key)as any)||(this.props.type==='number'?0:''))
          }
      }
  }



  onChange(val: any) {
    this.setValue(val);
    //this.emitter.trigger('process');
  }

  setValue(val: string) {
    console.log(val)
    this.props.value=this.props.type==='number'?+val:val;
    this.putData(this.key, this.props.value)
  }
}

`
My Question what changes need to be made to make it work for file?

**Comment by kvnbra** [comment]
Happy to help :-)

To answer your question: It depend on what you want to do with the selected file.

But first you have to, obviously, use an input with `[type]="file"` and bind the change event with onChange `(change)="change($event.target.value)"` but you will need to have access to the input HTMLElement so we need to do it like that: `(change)="change($event.target)"`

And then you can use `onChange(input) {` to either upload the file via Ajax and use the file resulting URL as the `val` in `this.setValue(val);` or read the file content locally in JS with a `FileReader` and use the content as value (ie `val`).

If you want to know more about file access in JS: https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications
