### ISSUE TITLE
connection lines anchoring on top left of nodes

### ISSUE THREAD

**Issue by cslotterback** [retejs/rete#450]
![image](https://user-images.githubusercontent.com/5041423/84109233-31bdf800-a9f0-11ea-86dc-f0f565f0079b.png)

for some reason my connections started auto anchoring themselves on the top left of my nodes instead of on the sockets

**Comment by kvnbra** [comment]
Did you change the node style or layout (css/Vue) ? Or use a custom render function for the connection paths ?

**Comment by cslotterback** [comment]
ah, I hadn't even noticed I had both the VueRenderPlugin and the AlightRenderPlugin being loaded into the editor, once I removed AlightRenderPlugin they line back up. Thanks for the help!

**Comment by WellerQu** [comment]
Hi @cslotterback , I have meet the same question. Could you tell me that how to resolve this question? or the reason?

**Comment by WellerQu** [comment]
Well, I get the reason. We can NOT move the DOM of socket container. Just we can move the DOM of socket only. Thanks a lot.

**Comment by cslotterback** [comment]
I don't mess with the sockets directly, I used the plugins provided to handle the dom elements. My issue was that I had 2 differing plugins loaded into the editor and there was probably a collision that prevented either of them from working.
