### ISSUE TITLE
How to use with angular 9, any tutorial?

### ISSUE THREAD

**Issue by CosmicSnow** [retejs/rete#455]
Hi, I am trying to use rete on angular 9, I downloaded the example for this version, but, only running

`npm i rete rege-angular-render-plugin rete-connection-plugin rete-context-menu-plugin --save`
won't make it possible to import.

So I copied the folder rete from the example too, to be able to import it inside my project. but now I am having the following problem 

`ReferenceError: regeneratorRuntime is not defined`

So, the question is, is there any tutorial or something like that to follow? The doc inside this project looks like is related to vue only.

**Comment by CosmicSnow** [comment]
Ok, I got it to work,
I had to install babilon polyfill and import it on angular.json

**Comment by creadicted** [comment]
In examples https://github.com/retejs/examples/tree/master/angular9 is an Angular 9 demo. 
I updated the 8 version directly to 10 without problems.

**Comment by CosmicSnow** [comment]
> 
> 
> In examples https://github.com/retejs/examples/tree/master/angular9 is an Angular 9 demo.
> I updated the 8 version directly to 10 without problems.

thanks, I think I can proceed with this example.

I'll close this issue, since I got it to work too.
