### ISSUE TITLE
Doesn't work with Angular 10

### ISSUE THREAD

**Issue by dragonadmin** [retejs/rete#456]
Any plans for Angular 10 support?

**Comment by CosmicSnow** [comment]
hi @dragonadmin, what are the errors?

**Comment by creadicted** [comment]
updated without errors. What did not work?

**Comment by creadicted** [comment]
@dragonadmin I added a PR to the examples for an updated Angular 10 Version
https://github.com/retejs/examples/pull/31

**Comment by dragonadmin** [comment]
Sorry fort he delay.
We upgraded both Angular and rete to the newest version and the problem doesn't occur anymore, so most probably it was due to some early release or compilation issues, but we cannot reproduce it anymore.
Thanks for your quick reaction.
