### ISSUE TITLE
Doubts on the Zoom in/out and Minimap implementation

### ISSUE THREAD

**Issue by agrawal-rohit** [retejs/rete#468]
Hey man, I really enjoyed using your library with React. Unfortunately, I had to switch to Svelte and make it from scratch for more flexibility, and it has been pretty successful. I would like to add some extra functionality like zooming in and out of the Editor div and possibly adding a minimap. 

Do you have any suggestions for how you achieved that? I have tried encapsulating all the nodes in a div and scaling them, but that causes issues with dragging the nodes (It's too fast when zoomed in, and too slow when zoomed out), and most of all, the svg paths go really haywire and all over the place.

Any help here would be really appreciated :))

**Comment by creadicted** [comment]
Hey @agrawal-rohit 
It's nice that you build a svelte implementation. There are other people asking for that. Mind to share?

For the minimap. Have you looked in to the minimap pluin? https://github.com/retejs/minimap-plugin
You could either use this - which is using vue to create the rendering. Or you can use this as an inspiration.

**Comment by agrawal-rohit** [comment]
I haven't used the rete js library for the entire implementation. I used it mostly as an inspiration for how the functionality should be. So I don't think I would be able to use the minimap plugin for that purpose. Any tips on how to go about creating one?

PS - I am building this for a commercial project, so I won't be able to release the code for a while

**Comment by creadicted** [comment]
>  Any tips on how to go about creating one?
Best would be to take a look in to the one that is created and works. 

> PS - I am building this for a commercial project, so I won't be able to release the code for a while
Just a super simplified JSFiddle would be nice anyway :)
