### ISSUE TITLE
Can a socket be a "link"?

### ISSUE THREAD

**Issue by ziga-miklic** [retejs/rete#469]
Hello,

is there a way to create a socket that acts as a link, meaning it does not care if the connected socket is an input or output?

Example: linking switches together by ports. In this case no port is just the input or output, but they are all both.

Thank you,
Žiga

**Comment by creadicted** [comment]
@ziga-miklic if I have the API correct in mind you need to write an extension to allow this.

**Comment by ziga-miklic** [comment]
@creadicted I've searched around but did not find any good examples. Do you maybe know some that might help me in creating the extension? Thank you!
