### ISSUE TITLE
FromJson() not working as expected

### ISSUE THREAD

**Issue by cyango** [retejs/rete#472]
Hi, I'm struggling with exporting/importing the node editor "state" of all nodes including connections and controls.
When I do `await editor.fromJson()` it restores the nodes and node.data but **it does not restore the connections nor the control state** of the previously saved editor.

I'm using React.  Can anybody help me?

**Comment by imding** [comment]
do you have an example?

**Comment by Ankita-TechVariable** [comment]
Does it have a workaround?

**Comment by granttebeau** [comment]
Has this been solved or looked at?

**Comment by imding** [comment]
I'm using Rete and React with TypeScript on a live project with no `fromJson` issue, if someone can provide an example I can help look into it :)
