### ISSUE TITLE
Invisible Div

### ISSUE THREAD

**Issue by guianderson** [retejs/rete#479]
Every time a line is connected between components, an invisible div is created

![Screenshot_55](https://user-images.githubusercontent.com/47038612/91471251-2f8b6d00-e86c-11ea-9645-4ffc3a2b6997.png)

**Comment by EnzoPG** [comment]
Same thing here.. Actually there is a HTML element that contain all the connections:

![Screenshot_56](https://user-images.githubusercontent.com/37943178/91983405-ff2b4f00-ed01-11ea-924a-857f4a7f7c67.png)

**Comment by Hatead1** [comment]
Every div contain only one connection and used for access/modify svg path.
Why "issue"?

**Comment by EnzoPG** [comment]
> Every div contain only one connection and used for access/modify svg path.
> Why "issue"?

When we have only 2 components that's not a problem.. But when we have 250 components, these DIVs overwrite the componentsc connections than we can't do then appositely.
