### ISSUE TITLE
Incorrect rendering with bootstrap

### ISSUE THREAD

**Issue by PavlMais** [retejs/rete#484]
### HI
**I found incorrect rendering when using bootstrap grid**

**Versions:**
```
rete: 1.4.4
rete-vue-render-plugin: 0.5.0
bootstrap: 4.5.2
vue: 2.6.10
```

Source: https://codepen.io/pavlmais/pen/gOroNPx

![Screenshot_1](https://user-images.githubusercontent.com/29174836/92404455-4b302680-f13c-11ea-97f1-f30084ebe3c0.png)

It starts to work correctly when disabling position: relative in col bootstrap style

![Screenshot_2](https://user-images.githubusercontent.com/29174836/92404601-a2ce9200-f13c-11ea-8906-78734a340940.png)
Overloading the col style does not help

**Comment by creadicted** [comment]
you can overwrite the default node and change the style name.
