### ISSUE TITLE
Connector UI issue with angular in Chrome

### ISSUE THREAD

**Issue by ManuAT** [retejs/rete#485]
Connector UI issue with angular in Chrome
it's Working Fine with local development in chrome after deployment connector UI move apart from nodes,
its changes with page zoom.
it's working fine with the edge(Not chromium ver)

npm Packages used
"vue": "2.6.8",
"rete": "1.2.0-rc.4",
"rete-connection-plugin": "0.4.3",
"rete-vue-render-plugin": "0.3.2",
"rete-context-menu-plugin": "0.3.6",
"babel-polyfill": "6.26.0"
@babel/polyfill

Angular 8

![image](https://user-images.githubusercontent.com/38802051/93116444-e2682180-f6da-11ea-9c98-7f16e0950504.png)

**Comment by quicksilver32** [comment]
Hello! Try to use 0.3.0 version of rete-vue-render-plugin

**Comment by praneetloke** [comment]
Shouldn't you use the Angular plugin? The issue title/description suggests that you are trying this in Angular, but you installed the `rete-vue-render-plugin` instead of the Angular one. I am not sure how it renders anything at all with the wrong plugin installed.
