### ISSUE TITLE
Update connections

### ISSUE THREAD

**Issue by quicksilver32** [retejs/rete#488]
I have this:
![image](https://user-images.githubusercontent.com/45488195/93668542-87954800-fa95-11ea-8bfd-5cc6af6089a7.png)
This doesn't work
```
        node.update(); 
        this.editor.view.updateConnections({ node: node })
```
![image](https://im3.ezgif.com/tmp/ezgif-3-465b78d7761d.gif)

**Comment by Hatead1** [comment]
```
                    node.update(); 
                    setTimeout(() => { this.emitter.view.updateConnections({ node }); }, 10); // or this.editor
```
try it

**Comment by quicksilver32** [comment]
@Hatead1 Thank you! It works!

**Comment by xakslim** [comment]
Привет. У меня ругается что нет метода updateConnections. в чем может быть проблема?
