### ISSUE TITLE
Disable context menu on input controls

### ISSUE THREAD

**Issue by quicksilver32** [retejs/rete#491]
Hello, how i can disable context menu by clicking rigth click on input controls to use context menu of text field, like copying and inserting text, or highlithing

**Comment by Hatead1** [comment]
<input type="text" ...... **@contextmenu.stop=""** />

**Comment by quicksilver32** [comment]
@Hatead1 thanks!!!

**Comment by quicksilver32** [comment]
And know anybody, how to highlight text instead of dragging node?

**Comment by Hatead1** [comment]
... @pointerdown.stop="" @pointermove.stop="" ...

**Comment by quicksilver32** [comment]
@Hatead1 big thank you!!
