### ISSUE TITLE
fromJSON loads ~350 nodes for about 40 seconds

### ISSUE THREAD

**Issue by dalduba** [retejs/rete#493]
Here is my profile recorded on firefox:
https://drive.google.com/file/d/1-4qGKk4H5toJ0xZvogZ_owoDd5ZyyvbU/view?usp=sharing
![image](https://user-images.githubusercontent.com/6851195/97759834-de6d5300-1b12-11eb-8cf1-6d1af2032115.png)

Could you point me how to resolve this issue?

**Comment by imding** [comment]
you could implement a "group" node that contains child nodes, which don't render at the parent level.

it's not a technical solution to the "many nodes impacting performance" issue but you could maintain a reasonable performance this way.

also, grouping nodes together is a common workflow in node editors, it makes building the network more manageable.

you may have valid reasons for wanting to keep the network "flat", in which case I am also interested to see what others suggest.
