### ISSUE TITLE
Couldn't create node at mouse position on drop

### ISSUE THREAD

**Issue by unclexo** [retejs/rete#495]
First of all, tons of thanks for creating such a great tool.

I'm having a problem while creating node on drop. What I want to do is create node exactly where my cursor is at on the editor while dropping. But it is not being created at the mouse position. I'm using the following code snippet: 

```javascript
const { x, y } = editor.view.area.mouse

const component = new SomeComponent();
const textNode = await component.createNode()
textNode.position = [x, y]
editor.addNode(textNode)
```

**Comment by Ibrahimvse** [comment]
`            // force update the mouse position
            editor.view.area.pointermove(e as any as PointerEvent);
const { x, y } = editor.view.area.mouse
`

**Comment by unclexo** [comment]
@Ibrahimvse it works! Thanks a lot!
