### ISSUE TITLE
How do I update the name of the node in React?

### ISSUE THREAD

**Issue by enigma6174** [retejs/rete#502]
I want to update the name of the node dynamically after the node has been added to the editor. Basically, once the node is added to the editor, the user is presented with a form and once the user submits that form, the date from that submitted form should reflect on the node (which includes changing the name of the node also). But so far I have not been able to implement that. The issue I am facing is that once the user submits the form, those details are not reflected in already added nodes but they reflect on nodes that are added after submitting the form. And if I update the form again, the nodes added after this update will reflect those changes.  

Also, **every node has the same data** that is submitted through the form. I want the data updated through the form unique to every node in the editor and the changes should reflect immediately after submission of form.  

I am working on the project in React and so far I have not been able to find a solution to my problems.

Here are two files - rete_original.jpg and rete_modified.jpg which explain how the screen looks before and after renaming.
![rete_original](https://user-images.githubusercontent.com/48469402/103857961-7b350980-50dd-11eb-9f80-a32fd72a1dc1.JPG)
![rete_modified](https://user-images.githubusercontent.com/48469402/103857971-7ec89080-50dd-11eb-8c3c-f0c0296ff4a6.jpg)

**Comment by creadicted** [comment]
The node name that is rendered is more the nodes type name then a name of a individual one. But since you can overwrite the renderer you can replace that.

You can use a string in the nodes data section to define your custom node instance name and use that in your template instead.
