### ISSUE TITLE
Connection paths won't update on using rotate css on custom node!

### ISSUE THREAD

**Issue by unvired2018** [retejs/rete#504]
@Ni55aN to make diamond if I rotate div container to 45deg using transform the node rotates but the connections stays where they were previously!

![Screenshot 2021-01-13 at 4 51 41 PM](https://user-images.githubusercontent.com/46041704/104446369-5995bf80-55c0-11eb-961a-76768d979649.png)

**Comment by Hatead1** [comment]
The socket position recounts relative to the node container, not absolutely. Rete knows nothing about you rotate div.

**Comment by unvired2018** [comment]
The Sockets position before rotation is as expected!
![Screenshot 2021-01-13 at 6 52 05 PM](https://user-images.githubusercontent.com/46041704/104878462-046ffa00-5982-11eb-88aa-8a209bcb8702.png)

**Comment by Hatead1** [comment]
> The Sockets position before rotation is as expected!

Yep. But after rotation div offset* information does not change. 
https://github.com/retejs/rete/blob/6bdec4f575e7ba5690fe673a6547270863b5013a/src/view/socket.ts#L27

**Comment by unvired2018** [comment]
I don't think it's socket that's an issue! The renderData() function calculation of connection path isn't updating! On inspect the socket is present at rotated position So, what's the solution? Is it a css thing?

**Comment by Hatead1** [comment]
Socket coords for connection path returns by function getPosition() (link above).

**Comment by unvired2018** [comment]
I've tried almost everything nothing works!
Even tried to bindSocket individually with their div but the connection lines won't change! The offsetLeft and offsetWidth properties  are get only.
