### ISSUE TITLE
Naming Conflicts

### ISSUE THREAD

**Issue by unclexo** [retejs/rete#505]
Again tons of thanks @Ni55aN for making such a great lib!

I'm having a problem while creating a node with a specific name. 

I've a node with the name of **Carousel Item**. I've made an interface so that I can create node on dragging and dropping. So when I try to create a node named with **Carousel Item** it does not show up on the editor but I can see it has been created when I console log `editor.toJSON()`

**But when I use any different name other than _Carousel Item_ it works.**

Here is the code that can help you understand the way I'm doing it. The following code is used to name all the components I have:

```javascript
export default {
  // other properties
  CAROUSEL: 'Carousel',
  CAROUSEL_ITEM: 'Carousel Item',
  // other properties
}
```
Here is the component that does not show up on the editor when I create it on dragging and dropping:

```javascript
import Const from '../../const/component'
export class CarouselItemComponent extends Rete.Component {
  constructor() {
    super(Const.CAROUSEL_ITEM) // The name "Carousel Item" is being used here
  }
  // other code goes here
}
```
And here is code that is used to create any component when I drag and drop:

```javascript
export const createComponent = async (event, ui) => {
  // other code
  switch(draggedElementType) {
    case Const.CAROUSEL:
      return await createCarouselNode(new CarouselComponent(), event, ui)
    case Const.CAROUSEL_ITEM:
      return await createNode(new CarouselItemComponent(), event, ui)
    // other cases
    default:
      return
  }
}
```

**Comment by Hatead1** [comment]
> **But when I use any different name other than _Carousel Item_ it works.**

Try _Xxxxxxxx Yyyy_, works?
