### ISSUE TITLE
How to create a wrapper control?

### ISSUE THREAD

**Issue by VitaliyDemchuk** [retejs/rete#509]
In `data` exist array of object `[{id:1,name:'test'}, {id:2, name:'test2']`. I want to create a component wrapper with a delete button for each array object and an add button for the whole block. In the wrapper block itself, 2 controls for the ID and name should be displayed. What is the best way to do it?

**Comment by VitaliyDemchuk** [comment]
@Ni55aN maybe you know how to better organize the architecture of nested controls?

**Comment by Hatead1** [comment]
Создать контрол, назначить ему колбэк в родительском компоненте и менять свои данные как угодно.

**Comment by VitaliyDemchuk** [comment]
> Создать контрол, назначить ему колбэк в родительском компоненте и менять свои данные как угодно.

+, спасибо. Попробую меня данные в родителе через метод `putData`.
