### ISSUE TITLE
Unselecting node

### ISSUE THREAD

**Issue by magallardo** [retejs/rete#511]
Hello,

What is the best way to unselect a node without having to select another node?

I would like to click on the canvas and unselect the last selected node.  Currently, you can only unselect a node by selecting another node. Thus, you can never have all nodes unselected after one is selected.

Thanks,
Marcelo

**Comment by gilengel** [comment]
You can register a click event ([Documentation](https://rete.js.org/#/docs/events#lang=en)) on the editor and clear the list of selected nodes within it like so

`    editor.on(["click"], () => {      
      editor.selected.list = []
    });`

Not sure if there is a better way to do it but this works for me.
