### ISSUE TITLE
npm package not working in Vue 3

### ISSUE THREAD

**Issue by isjeffcom** [retejs/rete#513]
I don't think rete.js can be used within a Vue 3 project directly (namespace conflict), due to the filters are removed from Vue 3.0 officially . Any plan to fix it? Anyway, thank you~

**Comment by carl-jin** [comment]
same here

**Comment by carl-jin** [comment]
i did a PR for support vue3 https://github.com/retejs/vue-render-plugin/pull/35

**Comment by amirfel4** [comment]
when this will be fixed? any ETA?

**Comment by T0miii** [comment]
do we have a status when the PR will be merged?

**Comment by carl-jin** [comment]
We can fork or create new project from rete,cuz there have some rete plugins they are binding together.

**Comment by T0miii** [comment]
I understand thx for the update, made it work with the Stage0 renderer for now.

**Comment by rebbort** [comment]
How can you build a plugin? I cloned PR and am trying to build with npm run build but get various errors. Is there any way to get an already assembled plugin?

**Comment by Ni55aN** [comment]
I have managed to build the plugin with changes https://github.com/retejs/vue-render-plugin/pull/35 (and some fixes):
https://github.com/retejs/vue-render-plugin/tree/vue3

Also prepared an example: https://github.com/retejs/examples/tree/master/Vue3

But it has an issue - controls aren't visible
![image](https://user-images.githubusercontent.com/8259641/128248350-60063d56-8bf7-4e0e-89c1-7df4af11b3a9.png)

**Comment by Ni55aN** [comment]
the discussion moved to the thread https://github.com/retejs/vue-render-plugin/issues/39 where you can find more information
