### ISSUE TITLE
editor.toJSON gives not JSON, but JS object. editor.fromJSON is consuming actually not JSON but JS object ☠️

### ISSUE THREAD

**Issue by liesislukas** [retejs/rete#529]
this naming is confusing. 

`await editor.fromJSON(editorState);`

if editorState is JSON string - won't work.

The name says "to JSON", one may assume it will provide JSON sting, but nope. It is actually providing JS object.
`editor.toJSON();`

**Comment by Hatead1** [comment]
Yep, "editor.load" and "editor.save" would be more logical
