### ISSUE TITLE
css transform: translate and scale not working in firefox

### ISSUE THREAD

**Issue by unclexo** [retejs/rete#532]
Hi there!

Probably you may have noticed that CSS transform attribute's values: translate and scale are not working in Firefox but it's working on Chrome. I googled for the solution but I didn't get any. That's why I'm here. Please check out the following GIF. When I move the nodes then it's OK. But it goes crazy when I try zooming in or out.

**Firefox version: 88**
**OS: ubuntu (16.04, 18.04)**

Is there any workaround of this problem? Any help would be appreciated. Thanks in advanced. 

![css transform: translate and scale not working in firefox](https://user-images.githubusercontent.com/29373179/121133537-4aa3f800-c854-11eb-83c9-62d03146c26f.gif)

**Comment by Ni55aN** [comment]
Which version of Firefox are you using?

I checked in version 79 and it works fine

**Comment by unclexo** [comment]
Thank you very much for the reply!

**Firefox version: 88**
**OS: ubuntu (16.04, 18.04)**

**Comment by martin31821** [comment]
Same problem here, Firefox 90 and Arch Linux.

I tracked it down to mouse scroll events returning a negative/inverted value (?) on firefox, I can try to prepare a PR.
