### ISSUE TITLE
Routing without tasks

### ISSUE THREAD

**Issue by michaelsharpe** [retejs/rete#533]
I love this library, it has so far proved very effective!  However, I have come up against a wall and am hoping to find a solution.  I am looking to implement boolean logic gates to pass flow along different channels without triggering the other connections, which all run expensive network requests.  I am hoping to do this without using tasks, which has the concept of 'closed' sockets.  

Is this possible?

**Comment by lancety** [comment]
+1 wondering if can make node trigger and send ouput value to next node as default behavior without requiring make and connect "action" socket (if the output action socket never need to be "closed")

**Comment by michaelsharpe** [comment]
@lancety i have been wondering the same thing. Basically bake together task outputs and options into one thing. 

Sadly it seems like Rete is not maintained by the original creator any more. None of the issues get responded to and it has been months since any kind of an update. 

I have contemplated forking it officially and making heavier modifications and hopefully having others contribute as well.

**Comment by creadicted** [comment]
@michaelsharpe 

> I have contemplated forking it officially and making heavier modifications and hopefully having others contribute as well.

@Ni55aN  is still accepting pull requests and answers to question. So if you have suggestions, open up an issue or a pull request.  Especially if you are working with sections that did not become a lot of updates recently. Like the tasks plugin.
