### ISSUE TITLE
[BUG] if I set background color to the area plugin, draging a connection will be in a div under the background div, so invisible

### ISSUE THREAD

**Issue by lancety** [retejs/rete#540]
![image](https://user-images.githubusercontent.com/5547558/126640522-7ee8ff29-7664-4580-ad3c-f339b9ae2d2b.png)
as shown in the image, when draging connection line from a socket, it is in a div container under the background

**Comment by lancety** [comment]
"react": "16.8.6",
    "react-dom": "16.8.6",
    "react-scripts": "3.0.1",
    "rete": "1.3.1-rc.3",
    "rete-area-plugin": "0.2.1",
    "rete-connection-plugin": "0.7.2",
    "rete-context-menu-plugin": "^0.6.0-rc.1",
    "rete-module-plugin": "^0.4.1",
    "rete-react-render-plugin": "0.2.0"

**Comment by Ni55aN** [comment]
Did you check [this example](https://rete.js.org/#/examples/customization#lang=en&tosearch=Number%0A%0ANumber)?
Perhaps you need a negative `z-index` for your background

**Comment by lancety** [comment]
thanks~~~
