### ISSUE TITLE
[Question] is the group feature depreciated? wondering what 's the best solution to manage group of nodes

### ISSUE THREAD

**Issue by lancety** [retejs/rete#543]
manage group of nodes
- move nodes: click each nodes and ctrl + drag move is not convinent for large amount of nodes. 
- group nodes: make node groups, move group contaienr in order to move nodes will be a nice to have feature 

Please share some ideas how these are addressed, anyone? Cheers~

**Comment by creadicted** [comment]
There is the "comment" plugin that allows the creation of "frames". 
All the nodes inside are moved when the frame moves. 
> https://github.com/retejs/comment-plugin
