### ISSUE TITLE
Inherit output socket type from input socket type

### ISSUE THREAD

**Issue by jplatte** [retejs/rete#545]
In an app we're building, there are a few nodes that mostly pass through data, not affecting its type. The [Socket docs](https://rete.js.org/#/docs/sockets) are rather sparse and don't touch on use cases like that – is this at all possible?

**Comment by creadicted** [comment]
Can you be a bit more precise with your problem? 
You can just traverse the information from an input to the output.

**Comment by jplatte** [comment]
Not sure whether this is what you mean, but we ended up creating a plugin that listens to `connectioncreated` events and updates the node accordingly.
