### ISSUE TITLE
How to use Rete with node?

### ISSUE THREAD

**Issue by KICKGodz** [retejs/rete#549]
I've tried reading the docs for using node but it's very confusing to me. Could someone show me all of their files so I can understand the basics of how to make a basic Rete Node project? Thanks.

**Comment by unhott** [comment]
I believe this only runs in the front end, regardless of the backend.

**Comment by KICKGodz** [comment]
Oh I see, well then do you have a code example that you could show me of the page?

**Comment by unhott** [comment]
The readme links to various examples.

**Comment by KICKGodz** [comment]
Oh whoops, that flew past me. Thank you for the help!
