### ISSUE TITLE
Create bidirectional io/socket

### ISSUE THREAD

**Issue by AmannHolen** [retejs/rete#550]
Is there a way to create an bidirectional i/socket? For example, I want to connect input to another input  or output to another output. Can I use controls to do that or is it better way to do it ?

**Comment by creadicted** [comment]
When I remember the code is something not intended. The directional approach is needed for the worker. Maybe you can elaborate your problem with a sample to see if there are other ways around it.

**Comment by AmannHolen** [comment]
Here a sample : https://codesandbox.io/s/blueprints-test-forked-cfkv1


To resolve my case we can thought of 2 ideas:
- Check the ReteStart.vue file. There is an attributes devices (this is the main object I want to render in the rete graph).I want to have 3 types of elements : Input, output (that can be create with node.addInput or node.addOutput methods) and bidirectional . This new element must be an input and an output but not already exist.
- Input can be linked to another input and output can be linked to another output.
