### ISSUE TITLE
Prevent Drag based on class name

### ISSUE THREAD

**Issue by Dus1988** [retejs/rete#552]
Using Rete in Angular, I have some nodes that have pseudo sub-nodes for ordering. I want those sub nodes to use a standard drag and drop library for ordering. 

I have been able to properly stopPropagation so that trying to drag the sub node no longer drags the "group node", but unfortunately this also stops the `pointerDown` event from propagating to the drag and drop library. 

It would be great if in the drag object, the down function had the ability to check the config for an array of classes to ignore. I can fork this if needed, but Id like to keep using npm for this package instead of bringing into the app manually.

**Comment by creadicted** [comment]
Can you provide a sample?
