### ISSUE TITLE
Rete React Example broken

### ISSUE THREAD

**Issue by utzy** [retejs/rete#553]
I have been trying to get into Rete and I am amazed by the capabilities.
Unfortunately I cannot seem to find many good working examples using React.

The official documentation links to this CodeSandBox for a react example:
https://codesandbox.io/s/retejs-react-render-t899c

It works, but connection lines are drawn with an offset. (Tested on Win Firefox and Android Chrome)
![image](https://user-images.githubusercontent.com/28709767/134201937-070d4b57-07e0-42e3-b629-32bd7e077eda.png)

Is there a fix for this?
If not, where should one start to investigate this issue?

**Comment by utzy** [comment]
ok, seems this bug is solved by updating all rete plugins to the latest version in package.json:
`"rete": "^1.4.5",
"rete-area-plugin": "0.2.1",
"rete-connection-plugin": "^0.9.0",
"rete-react-render-plugin": "0.2.0"`

Since this CodeSandbox is linked in the official documentation, maybe someone should update this? @Ni55aN

**Comment by Ni55aN** [comment]
This is not reproduced on my latest Firefox (Win), but I updated the dependencies anyway. Please check again

**Comment by utzy** [comment]
yes, it is working now!
Thanks :)
