### ISSUE TITLE
Panning with middle mouse

### ISSUE THREAD

**Issue by AlanGreyjoy** [retejs/rete#554]
Is there a way to only pan with the middle mouse? Left click is far to conflicting. Thanks!

**Comment by Ni55aN** [comment]
customization of this feature will be available in v2

**Comment by Ni55aN** [comment]
https://retejs.org/docs/faq/#scroll-prevented

**Comment by Ni55aN** [comment]
https://retejs.org/docs/faq/#pan-middle-mouse-button
