### ISSUE TITLE
App crashes when emitting nodeselect event

### ISSUE THREAD

**Issue by jtwnel** [retejs/rete#556]
Hi,

I tried to trigger the "nodeselect" event on the "nodecreated" event handler but it crashes saying the following error 
`Unhandled Rejection (Error): Node not exist in list`. How is this possible? if the node is already visible it does not make sense to get this error.

this is a snippet of what i'm trying to do

`editor.current.on('nodecreated', (node) => {
        function_calls...
        editor.current.trigger('selectnode', node);
      });`

Thanks in advance

**Comment by Ni55aN** [comment]
Definitely, the node was deleted before triggering `selectnode`, since `nodes` array doesn't have this node anymore

https://github.com/retejs/rete/blob/6bdec4f575e7ba5690fe673a6547270863b5013a/src/editor.ts#L85-L87
