### ISSUE TITLE
How to create a readonly node?

### ISSUE THREAD

**Issue by rajasegar** [retejs/rete#557]
I couldn't find any documentation on creating a read-only node which cannot be modified, cloned or deleted?

**Comment by Ni55aN** [comment]
> which cannot be modified

> or deleted

You can follow [this example](https://github.com/retejs/readonly-plugin/blob/master/src/index.ts) and implement your own handler for the listed events, and return `false` only for a specific node

> cloned

Probably we are talking about copying through the context menu. In this case you need to define custom `nodeItems` option to hide 'Clone' item
