### ISSUE TITLE
process is not defined in rete-vue-render-plugin

### ISSUE THREAD

**Issue by SArpnt** [retejs/rete#562]
i've been trying for a while now to get rete in a website using esm modules. the esm modules on jsdelivr have multiple issues (plugins try to import rete which doesn't exist, regeneratorRuntime is not defined), so i switched to using rollup.
When i import rete-vue-render-plugin i get the error `process is not defined`.

rollup.config.js
```js
import { nodeResolve } from "@rollup/plugin-node-resolve";

export default {
	input: "./rollup.mjs",
	output: {
		file: "../scripts/bundle.min.mjs", // not minifying right now to test
		format: "es",
	},
	plugins: [
		nodeResolve(),
	],
};
```
rollup.mjs
```js
import "regenerator-runtime/runtime";
import "rete-vue-render-plugin";
```

issue happens at this code
```js
const EMPTY_OBJ = (process.env.NODE_ENV !== 'production')
    ? Object.freeze({})
    : {};
const EMPTY_ARR = (process.env.NODE_ENV !== 'production') ? Object.freeze([]) : [];
const NOOP = () => { };
```
i know that the issue is because process is part of node.js, but i'm not sure how i'm supposed to fix this.

i feel like the installation section needs to be documented somewhat better, for example it said to use babel/polyfill, which has been deprecated and replaced by regenerator runtime

**Comment by Ni55aN** [comment]
https://github.com/rollup/rollup/issues/487

**Comment by jeremybradbury** [comment]
I think this was prematurely closed. 

I tried all of the things in https://github.com/rollup/rollup/issues/487 and they don't work for Svelte.

process is always undefined even when using the replace methods.

You may assume this is an old issue, but I think it's a new one without a universal workaround.
