### ISSUE TITLE
Zoom doesn't work properly on touch devices

### ISSUE THREAD

**Issue by Mkolba** [retejs/rete#564]
It's seems to be almost impossible to zoom editor on touch devices when there are a lot of nodes. Zoom goes wild if at least one of your fingers is on the node. How can I fix it?

![Chrome](https://user-images.githubusercontent.com/49096456/147401246-af42a03e-b909-4c26-b9cd-b2f14d09f5e9.gif)

**Comment by deepsniha** [comment]
How do you manage connecting nodes on touch devices? Is it user friendly, I am finding it bit difficult since we are connecting through fingers the sockets will get covered and we can't actually see the socket end point. Is there any alternative on touch devices?
