### ISSUE TITLE
Several Questions

### ISSUE THREAD

**Issue by TorinFelton** [retejs/rete#566]
After a lot of research, this seems like a really good fit for a project I'm working on. The project does not require any live functionality from 'running' the graphs or anything like that. All I need is to be able to have a way for the user to build a flow diagram and then JSON representing that diagram (including the controls in each node) can be sent off in a request to my backend.

Now, several questions, from someone who has barely touched JS (I mostly focus on Python, C#, Java, etc.etc.):
- Does this library require you to use one of these JS frameworks like Vue, React, etc.? I cannot find a way to get it to work without having to use vue rendering or etc. for the controls.
- Can I just have some raw HTML as the controls for each node, and simply include whatever it is in a JSON output for the whole diagram?

Essentially, I just want the user to be able to build a graph and have the JSON of whatever they've built, including the options selected in the control of each node, and just send that off to my back end. I cannot figure out how to do this without wading into a JS framework.

**Comment by TorinFelton** [comment]
I have decided to use a different framework for my needs.

**Comment by tangorri** [comment]
Agree this an issue in doc, and my conclusion is react as problem to be usage (breaking change from React 17+).
Doc really miss to explain if yes/no you can use plain vanilla rendering, and how ...
