### ISSUE TITLE
Tasks documentation

### ISSUE THREAD

**Issue by microspace** [retejs/rete#582]
First, thank you for great library!
My question is: what is the use of tasks?
More specifically: can I build node tree with async workers without using of taks?

**Comment by Ni55aN** [comment]
> what is the use of tasks?

https://github.com/retejs/task-plugin/issues/9#issuecomment-1222053003

> can I build node tree with async workers without using of taks?

I would recommend not to use the task plugin (since it isn't scalable well) and write your own solution (for async tasks/control flow)
