### ISSUE TITLE
Modify control inside worker

### ISSUE THREAD

**Issue by STR1KE6969** [retejs/rete#587]
How can i modify a control inside the worker function of a component?

**Comment by Hatead1** [comment]
Modify what? Control type - delete control and create new one, control value - get control (let ctrl = this.editor.nodes.find(n => n.id === node.id).controls.get('control key').getValue();) and call ctrl.setValue(val)

**Comment by STR1KE6969** [comment]
i have a control that is a dropdown and i want to dynamically add more options to it

**Comment by Hatead1** [comment]
add function (to control) like addOptions({name, value}) and add record to dropdown data array.

**Comment by STR1KE6969** [comment]
yeah but the new options don't render

**Comment by Ni55aN** [comment]
probably you need to call the `update` method of control, if you need to re-render view
