### ISSUE TITLE
component title

### ISSUE THREAD

**Issue by lexoring** [retejs/rete#593]
Hello. Please tell me how to set a second name when creating a component so that there is a different name in the editor in the header. For example, super("add1", "addition of numbers")
![test](https://user-images.githubusercontent.com/74623056/204148771-f39274ee-0c55-4c43-9a56-ccc7db00ed16.png)

**Comment by unhott** [comment]
You can simply change it to 
`super(“Addition of Numbers”);`

if you really want to keep the ‘add1’ you can try to add a multiline string. 

`super(“add1/nAddition of Numbers”);`

**Comment by lexoring** [comment]
Thanks for the answer, but I really need to save the "Add1" and separately the text of the description of the block. Because the text "Addition of Numbers" will be in another language, and I need the name of the "Add1" block in English, then to process the name of the block at json. I need to have them separately.

I tried how you suggested super(“add1/nAddition of Numbers”); does not work like that.

**Comment by Ni55aN** [comment]
In order not to change the node identifier, you can change the title through a custom node

**Comment by hedecai** [comment]
Hi.
Is there a way to change the socket show name, for example we want to internationalization the editor for users. 
Thanks.

**Comment by Ni55aN** [comment]
@hedecai there are a couple of approaches (if we are talking about dynamic update):

- custom nodes: create custom Socket component (depending on render plugin)
- change `socket.name` and call `node.update()` (may not work in vue render, then you need to manually update the vueContext's children)

or you can set `new Rete.Socket('<name>')` before loading graph

**Comment by hedecai** [comment]
> @hedecai there are a couple of approaches (if we are talking about dynamic update):
> 
> * custom nodes: create custom Socket component (depending on render plugin)
> * change `socket.name` and call `node.update()` (may not work in vue render, then you need to manually update the vueContext's children)
> 
> or you can set `new Rete.Socket('<name>')` before loading graph

@Ni55aN 
Thanks. 

We'll try it.
