### ISSUE TITLE
fuck ukraine fuck nacists

### ISSUE THREAD

**Issue by ggtoolka** [retejs/rete#595]

**Comment by Ni55aN** [comment]
🤦‍♂️
![image](https://user-images.githubusercontent.com/8259641/209640566-ea261978-52b1-4b7c-8e3e-da7008df6e47.png)

**Comment by shayneoneill** [comment]
There really needs to be a way to report these spammers. I've stumbled across posts like this, usually on repos by ukranian brothers, and it'll be an account that *just* has abusive behavior. But no report button?
