### ISSUE TITLE
How to send an event to a node

### ISSUE THREAD

**Issue by xakslim** [retejs/rete#602]
Hello. I created custom nodes with a certain number of inputs and outputs. node fields are displayed in a separate dialog box. everything works here. at the moment I need to carry out the necessary checks. for example, I should not have unconnected nodes. and it is necessary to highlight this node and display an error under it. How can I send an event to a node? using vue2? vue-render-plugin, area-plugin

**Comment by Ni55aN** [comment]
do you need to display an error inside the node block or outside?
In the first case definitely you need a custom node

**Comment by xakslim** [comment]
needed outside. The custom element already has a class and an error text. I get a list of invalid nodes, but somehow I need to pass either an event or this class to them

**Comment by Ni55aN** [comment]
> but somehow I need to pass either an event or this class to them

```js
const node = editor.nodes.find(node => ... // find particular node
node.data /// put error identifier or whatever into this object
node.update()
```
Respectively, your custom node should retrieve error info from `node.data`

**Comment by Hatead1** [comment]
Event to node - https://codepen.io/hatead1/pen/eYKpOmr
