### ISSUE TITLE
removeInput method not removing connections from both sides, Causing crash

### ISSUE THREAD

**Issue by dbriscoe511** [retejs/rete#609]
**Description:**

When using the removeInput method to remove an input from a node, the connections associated with that input are not removed properly from both sides. The connection is removed from the input side but not from the output side. This causes issues such as undefined connections and crashes when deleting the connected node.

**Steps to reproduce:**

1. Create a node-based app using Rete.js with a custom component that allows adding and removing inputs dynamically.
2. Add a new input to a node and connect it to another node.
3. Remove the new input using the removeInput method.
4. Observe that the connection is removed only on the input side and not on the output side.
5. Modify, delete or update the input node and see weird behavior

**Expected behavior:**

The removeInput method should remove the connections from both the input side and the output side, ensuring that there are no lingering connections or undefined behavior.

Workaround:

A manual workaround for this issue is to remove the connections on both sides before calling the removeInput method:

```
let inputToRemove = nodeInstance.inputs.get("key");
console.log("input to remove", inputToRemove);
            
inputToRemove.connections.forEach((connection) => {
    // Remove connection from the input side
    inputToRemove.removeConnection(connection);
    
    // Remove connection from the output side
    const outputNode = connection.output.node;
    const outputKey = connection.output.key;
    outputNode.outputs.get(outputKey).removeConnection(connection);
});

nodeInstance.removeInput(inputToRemove);
```

**Comment by Ni55aN** [comment]
`inputToRemove.removeConnection` is an internal implementation. In order to remove connection you have to use `editor.removeConnection`:

```js
let inputToRemove = add.inputs.get("key");

inputToRemove.connections.forEach((connection) => {
    editor.removeConnection(connection);
});

add.removeInput(inputToRemove);
```


P.S. if you're new to Rete.js, it's recommended to start with v2 (although it's currently in beta and there's a risk of breaking changes, but it is more powerful and intuitive)
