### ISSUE TITLE
How to update Node in rete@next

### ISSUE THREAD

**Issue by daef** [retejs/rete#612]
The node in rete v2 has no update function anymore. How can I force rete to redraw a node after dynamically changing a label? I'm using vue-render-plugin and try for example to update editor.nodes[0].inputs.test.label or simply editor.nodes[0].label, but it doesn't show. It updates as soon as I select a node thou. Is it possible to force such an update from code?

**Comment by daef** [comment]
sorry, I'm browsing the examples and the code, but I'm too stupid to RTFM

**Comment by Ni55aN** [comment]
As for me, manuals are boring 😀 I prefer to study through examples with code too. At the same time, we must not forget the search. This version of website uses DocSearch which is a pretty powerful thing
