### ISSUE TITLE
Node meta not exported with toJSON

### ISSUE THREAD

**Issue by joshuakarp** [retejs/rete#616]
I'm trying to persist some data in `Node.meta`, export the editor `toJSON`, and then have the ability to reconstruct with `fromJSON` (including each node's data in both `data` and `meta`) . I'm currently using `Node.data` as a separate collection of data, and this works well. However, it doesn't seem that `meta` is persisted in the same way and a peek into the source confirms this: https://github.com/retejs/rete/blob/dd11a09783bbe038377eb1c3cb42774f7f9b264a/src/node.ts#L106-L113

Is the only way to persist data with `Node.data`?

**Comment by joshuakarp** [comment]
I no longer require this - I'm using a workaround that doesn't require the meta to be persisted now.

**Comment by Ni55aN** [comment]
The `meta` property was intended for runtime-only data, but this concept is no longer used in v2
