### ISSUE TITLE
Deleting node while having a connection 'hanging' throws an error.

### ISSUE THREAD

**Issue by nikola-bozin-org** [retejs/rete#617]
As the title says,
'hanging' connection is a connection that's not yet created as an instance, but its connected to one of node sockets either input or output.

when I press right click on a node, and select Delete from context menu, I get error.

 in order to explain visually, here are the images:
![screenshot1](https://user-images.githubusercontent.com/112718743/234487839-89fb9b4b-68a6-46b3-9169-b98b78a1f894.png)
![screenshot2](https://user-images.githubusercontent.com/112718743/234487854-15568275-e6b3-4c40-9bc7-52d7bbcebb7c.png)

Im using:
ConnectionPlugin from "rete-connection-plugin";
ReactRenderPlugin from "rete-react-render-plugin";

**Comment by Ni55aN** [comment]
Is it reproducible on https://codepen.io/Ni55aN/pen/xzgQYq ?

When I click RMB to open context menu, the connection disappears as expected

**Comment by nikola-bozin-org** [comment]
Well, i dont think its the proper code to reproduce on, since I'm using React project, not Vue.

**Comment by Ni55aN** [comment]
The behavior of the context menu is independent of the render plugin, but anyway, there is an example based on React for v1: https://codesandbox.io/s/72mjq7y0x0

**Comment by nikola-bozin-org** [comment]
I can confirm that on your example it works.

I copied this code:

`class BaseNode extends Rete.Component {
  constructor(name) {
    super(name);
    [
      "created",
      "onconnect",
      "destroyed",
      "ondisconnect",
      "connected",
      "disconnected"
    ].forEach((element) => {
      this[element] = this[element].bind(this);
    });
  }

  async builder(node) {}

  created(node) {}

  destroyed(node) {}

  onconnect(io) {
    // input or output
  }

  ondisconnect(connection) {
    // return false; // prevent disconnect
  }

  connected(connection) {}

  disconnected(connection) {}
  async worker(node, inputs, outputs) {}
}`

in `editor.jsx`

under 
`var numSocket = new Rete.Socket("Number value");`


and than:

1. CTRL+S  -save editor.jsx
2. Right Mouse Button to create Add node.
3. Clicked on socket.

and got `Node view not found ` error.

![Screenshot from 2023-04-26 16-00-40](https://user-images.githubusercontent.com/112718743/234599845-de22e7bf-8381-49b0-9773-de411674d98c.png)

**Comment by Ni55aN** [comment]
This issue related to HMR. Specifically in this example on Codesandbox the previous editor should be destroyed correctly

**Comment by Ni55aN** [comment]
I think we should resume from initial issue you have mentioned (https://github.com/retejs/rete/issues/617#issuecomment-1523475763 is another Codesandbox-related issue).
My question is how to reproduce https://github.com/retejs/rete/issues/617#issue-1684362333 since it isn't reproducible in the example on https://codepen.io/Ni55aN/pen/xzgQYq

**Comment by nikola-bozin-org** [comment]
Im unable to reproduce the problem in [https://codesandbox.io/s/72mjq7y0x0] because every small change I make in editor, it gives the error I provided before (probably issue related to HMR).

 I can say my editor uses these plugins:
 `  editor.use(ConnectionPlugin);
  editor.use(ReactRenderPlugin, { createRoot, component: GenericNode });
  editor.use(ContextMenuPlugin);
  editor.use(AreaPlugin, {
    background: false,
    snap: true,
    scaleExtent: { min: 0.1, max: 1 },
    translateExtent: { width: 5000, height: 4000 },
    edgeScroll: true,
  });
  editor.use(ConnectionMasteryPlugin);
  editor.use(LifecyclePlugin);
  editor.use(HistoryPlugin);`
  
  and these triggers:
  `process nodecreated connectioncreate connectioncreated connectionremoved noderemoved `
  
  Nothing else that might affect the behaviour explained in the begging of this thread.

**Comment by Ni55aN** [comment]
try to disable the mastery connection plugin

**Comment by nikola-bozin-org** [comment]
The connection mastery plugin does not cause any trouble. I thought it could help fixing my problem, but it didnt.

**Comment by Ni55aN** [comment]
try to disable other minor plugins. 

In any case, there is something in our project that isn't used in the aforementioned examples where it is not produced.  Also check dependency versions.

Or even easier, upload your project to codesandbox or somewhere else with the minimum code required to reproduce the issue

**Comment by nikola-bozin-org** [comment]
Thank you for your effort, but i might come back later to this problem... There is nothing atm that i tried and that it worked.
