### ISSUE TITLE
Unregistering components

### ISSUE THREAD

**Issue by nikola-bozin-org** [retejs/rete#624]
Is there a way to unregister components during runtime that are used by the editor and engine?

```
  components.map(c => {
    editor.register(c);
    engine.register(c);
  });
  ```
  The components we register here are visible in context-menu, but is there a way that during runtime, for example in
  ```
  editor.on('process' , ....
  ```
  to unregister components that satisfy certain criteria?

**Comment by Ni55aN** [comment]
You can add this `allocate` option (as mentioned in the README)

```js
allocate(component) { return null } // exclude component from menu items
```

It looks like this is your case, since unregistering the component is not necessary (anyway this is not supported by v1)

**Comment by nikola-bozin-org** [comment]
yeah , i get it, thanks!
