### ISSUE TITLE
Pass additional props to component with custom event

### ISSUE THREAD

**Issue by JamesNeumann** [retejs/rete#625]
I'm currently using the Rete.js 2 Beta combined with the Vue Render Plugin and enjoying the new signal and pipe functionality.
Currently I'm working on implementing a plugin that allows multi user editing.
I want to change the state of a node and a control depending on the user that selected, deselected or changed the node.

Is there a way to emit a custom event in for example the area-plugin to which the renderer-plugin listens and passes the data to the props of the specific component?

Or is there a different/better approach for achieving this functionality?

**Comment by Ni55aN** [comment]
> Is there a way to emit a custom event

you probably don't need to do it unless these events are similar to 'render' event. For example, this can be done to render custom elements, but not to change the state of existing ones.

Have you considered modifying the state of the desired node/control and then calling `area.update`? In the case of a plugin, you can use custom events freely, but their scope will be limited to the plugin itself. Additionally, the plugin have access the parent AreaPlugin and its parent NodeEditor.

**Comment by JamesNeumann** [comment]
Thanks a lot, this works!

I have seen that there is a `nodepicked`-event. Is there something comparable for detecting, if a node was unselected?

**Comment by Ni55aN** [comment]
Actually `nodepicked` isn't directly associated with the selector. The selection is completely managed by `AreaExtensions.selectableNodes`: https://github.com/retejs/area-plugin/blob/next/src/extensions/selectable.ts

Regarding detecting unselected, the selector or selectableNodes has not built-in events (not sure if it should). However, detecting can be achieved in the following way:

```ts
  function trackedSelector<E extends { label: string, id: string, unselect(): void, translate(dx: number, dy: number): void }>() {
    const selector = AreaExtensions.selector();

    return {
      ...selector,
      add(entity: E, accumulate: boolean) {
        if (!accumulate) console.log('unselected', getSelectedNodes()) // they have selected = true until selector.add is called
        selector.add(entity, accumulate)h
      },
      unselectAll() {
        console.log('unselected', getSelectedNodes())
        selector.unselectAll()
      }
    }
  }
```

In general, I will evaluate the viability of having integrated tracking at the selector level without overcomplicating it.

**Comment by JamesNeumann** [comment]
Thanks a lot! That solves my problem.

**Comment by Ni55aN** [comment]
@JamesNeumann the latest rete-area-plugin has some selector improvements
https://retejs.org/docs/guides/selectable#extend-selector
