### ISSUE TITLE
Angular : Custom Node component creating performance issue

### ISSUE THREAD

**Issue by suraj-ja** [retejs/rete#628]
Hi,

I am facing issues in loading rete js canvas when I use custom node components for large structures with more than 150 nodes. while using the default renderer not causing any issues.
Can you please help ?

**Comment by Ni55aN** [comment]
can you provide steps how to reproduce it (rete-kit command, custom component source code, etc)?

**Comment by suraj-ja** [comment]
HI,

We have removed the custom component and used the rete default node as more than 150 nodes causing the issues.
Still, we are facing issues while rendering from JSON for more than 150 nodes.

Please check the below code. We are rendering rete canvas with the JSON.
`async () => {
      await this.engine.abort();
      await this.editor.fromJSON(finalData);
    }`
  
for small flows, there are no issues in loading but for larger flows, it takes more than 3000 ms - 5000 ms to load.

Can you please suggest any alternative for editor.fromJSON(finalData) method ?

Thanks for the help

**Comment by Ni55aN** [comment]
I would suggest to switch to v2

**Comment by Ni55aN** [comment]
There is a migration guide https://retejs.org/docs/migration 
Indeed there are a lot of breaking changes, but the easiest way is to with Rete Kit

**Comment by suraj-ja** [comment]
Hi,
we have replacing editor.fromJSON() to chnaging node position by updating node.position[x,y].

`this.editor.nodes.forEach(element => {
    editor.view.nodes.get(element).translate(x, y)
});` 

it takes less processing time than editor.fromJSON(),  but for large flows with more than 120-130 nodes. we are getting unusual errors occurring only after a certain amount of nodes. Please check below screenshot:


![image (4)](https://github.com/retejs/rete/assets/37801420/8607578a-70d6-48d6-a574-db01abfbd337)

can you please help and suggest any alternative for this?
Thanks for the help !!

**Comment by Ni55aN** [comment]
In order to figure out why the numbers have become NaN, inspect the stack trace by adding a breakpoint, for instance, in `renderPathData`
