### ISSUE TITLE
V2: How to detect a Vue custom event and listen to it in editor.ts

### ISSUE THREAD

**Issue by JosueGauthier** [retejs/rete#630]
Hello, 

I have not well understand how to create custom events in the v2 between the editor.ts and a vue component. 

For example I have a vue node component where a I have a method toggleClosed()

```js

toggleClosed() {
    ...
   
      this.$emit("custom-event-name", { message: "My custom message" });
    },

```

I would like when the function is run (via @click.stop="toggleClosed") detect it in my editor.ts. 

I check on the documentation and issues but without success. 

Thanks,

**Comment by Ni55aN** [comment]
The only bridge (mostly, except store/event but) between the Vue component and your editor is the `data` property that is passed to your component.
Interaction from the component to the editor is possible through the callback

https://github.com/retejs/vue-render-plugin/blob/next/src/presets/classic/components/Control.vue#L22

**Comment by JosueGauthier** [comment]
Hello and thank you again for your time, 

I try to implement the provided code : https://github.com/retejs/vue-render-plugin/blob/next/src/presets/classic/components/Control.vue#L22
But I get the error for this.data.setValue(val) : this.data.setValue is not a function 

I have another question how to create inside the editor.ts a custom event that reacts to a custom component `data` change ?  
For example if a node change of color how to catch it and do some stuff 

Thanks,

**Comment by JosueGauthier** [comment]
Hello and sorry for the late answer I had some others problems to fix, 

But, thanks a lot again !

Firstly, so I didn't quite understand how the replacement for editor.on(...) worked I thought there was only editor.addPipe but I hadn't seen area.addPipe in the documentation, so thank you :) 

So I will try to explain clearly my problem.

I have custom nodes, I extended the `ClassicPreset.Node`
These customs nodes are able to have 2 views one closed and one open.
(On the closed view I have a certain type of sockets on the open view another type of socket. On these sockets I can connect types of links to certain types of sockets)

The problem is that when I close or open my node I want to hide/show some connections related to my nodes. For this I was looking to create a custom event to manage the fact that I open or close my node. 

I have not tested yet the solution you provide because I have a problem on the custom connection data see : https://github.com/retejs/rete/issues/633 so I will try after a fix is find.

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/630#issuecomment-1604296233

```ts
class CustomNode extends ClassicPreset.Node {
  constructor(public onCustomEvent: (payload: any) => Promise<void>) {
   ....
}


const node = new CustomNode(async payload => {
  /// remove connections
  area.update('node', node.id)
  // add connections
})
```

```js
toggleClosed() {
    ...
   
      await this.data.onCustomEvent({ message: "My custom message" });
},
```

**Comment by JosueGauthier** [comment]
A big thanks to you for your help ! 
It works perfectly thank you for your explanation.
