### ISSUE TITLE
Focus on the flow when mInimap out of bonunds.

### ISSUE THREAD

**Issue by suraj-ja** [retejs/rete#638]
Hi,
This is a great library !! Really appreciate your work !!

We are facing an issue in the minimap when 'mini-viewport' yellow box is scrolled out of the minimap box. Please check the attached screenshot. but the flow is present in the minimap. the user unable to 

![screencapture-localhost-4200-2023-07-11-09_55_43](https://github.com/retejs/rete/assets/37801420/fd0fe59d-315f-417b-b461-4d5a07386ca1)

Can we focus on any specific node? programmatically so that the user does not need to scroll and flow will be visible in the viewport screen. Please let me know.

Thanks in advance !!

**Comment by Ni55aN** [comment]
https://retejs.org/docs/guides/basic/#fit-viewport

Also you can use `boundViewport` option to make mini-viewport always inside minimap

```ts
const minimap = new MinimapPlugin<Schemes>({
  boundViewport: true
});
 ```

**Comment by suraj-ja** [comment]
Thanks !! it Works !!
