### ISSUE TITLE
`Editor.getConnections` & `Editor.getNodes` should return _not_ return the internal reference

### ISSUE THREAD

**Issue by MichaelFedora** [retejs/rete#644]
Currently, because the Editor is returning a reference to the internal array, doing the following:

```typescript
for(const conn of editor.getConnections())
  await editor.removeConnection(conn.id);
```

will only remove around half of the connections. Instead, the Editor should return a _slice_ of the internal array so that:
- it is not directly modifiable (otherwise why do you have addConnection, removeConnection, etc)
- it doesn't require users to add on an additional `.slice()` every time they want to operate on the list of items such as in the given example

This affects both `.getConnections()` and `.getNodes()` in the Editor class.

**Comment by Ni55aN** [comment]
Indeed, this would  improve the UX

> otherwise why do you have addConnection, removeConnection, etc

they are needed to interact with events.

The only drawback of this approach is a slight decrease in performance. However, even with thousands of nodes, it will be insignificant.  So, I believe it's worth it.
