### ISSUE TITLE
Error: 'Cannot use 'in' operator to search for 'randomBytes' in undefined' in Node.js v14.19.3 environment

### ISSUE THREAD

**Issue by funtuan** [retejs/rete#646]
https://github.com/retejs/rete/blob/f77e5678260a64a0eee4ff4b7a84fe1b20ddd36b/src/utils.ts#L10

## Error log
```
(node:73810) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'randomBytes' in undefined
    at getUID (/xxxx/node_modules/src/utils.ts:11:20)
    at PlaybookEventStartNode.Node (/xxxx/node_modules/src/presets/classic.ts:117:15)
```

## environment
nodejs v14.19.3

The crypto Module Not Installed: The error message mentions Cannot use 'in' operator to search for 'randomBytes' in undefined. This indicates that the crypto module might not be properly installed or available in the Node.js environment. The randomBytes method is part of the crypto module, and if it is not defined or accessible, it could cause this error.

**Comment by Ni55aN** [comment]
for some reason your environment doesn't have access to the `crypto` module which is built-in. Please check your environment

```bash
node -e "console.log(require('node:crypto').randomBytes)"
```

**Comment by funtuan** [comment]
rete@2.0.0
`node_modules/rete/rete.esm.js` line 588
```
/* global globalThis*/
var crypto = globalThis.crypto;
```

The packaging seems to have overlooked the Node.js execution scenario, and the following modification enables it to run properly in Node.js.
```
/* global globalThis*/
// var crypto = globalThis.crypto;
const crypto = require('node:crypto')
```

**Comment by Ni55aN** [comment]
`globalThis.crypto` is also available in Node.js.

**Comment by funtuan** [comment]
Thank you for providing a solution, but it must be done using commonjs in order to apply the method for resolution.

Furthermore, I am verifying whether globalThis.crypto is available in Node.js. I used the following script for verification:
```
console.log('globalThis.crypto', globalThis.crypto)
```
The verification results indicate that it is not available in Node.js versions v12.20.1, v14.20.1, and v16.16.0.

**Comment by Ni55aN** [comment]
> The verification results indicate that it is not available in Node.js versions v12.20.1, v14.20.1, and v16.16.0.

I can't say for sure the cause of `globalThis.crypto` availability, but it's not a version issue, because on my side (WSL2)

```bash
nvm install 12.20.1
nvm use 12.20.1
node -v
node -e "console.log('globalThis.crypto', globalThis.crypto)"
```

prints `crypto` module. Same result on Windows 10

> it must be done using commonjs in order to apply the method for resolution. 

The challenge here is that the usage of 'require' doesn't consistently work. I can't recall the specifics, but I believe there were complications with some bundlers that reported '`require' is not defined`. 
Alternatively, utilizing ES import is not a viable solution since, in the browser context, it must be accessed from the global namespace rather than as a module dependency

**Comment by funtuan** [comment]
I have observed an intriguing phenomenon during local environment validation. When utilizing node -e, the output is successfully printed, whereas running the same command independently within Node.js results in undefined.

It appears that node -e supports certain global scopes, whereas Node.js, which employs the CommonJS module system, lacks this global scope.

**Comment by Ni55aN** [comment]
Indeed, inside commonjs it is not defined. Besides, it's available on Codesandbox, which is confusing

https://codesandbox.io/s/rete-js-v2-import-export-999y8z

For now, the workaround is to put `globalThis.crypto = require('crypto');` before `require('rete')`

**Comment by unglud** [comment]
Got into this problem too building with `esbuild` for AWS lambda.
Solved by injecting `globalThis.crypto = require('crypto');` into bundle by:
```
await esbuild.build({
  banner: {
    js: `globalThis.crypto = require('crypto');`
  }
})
```
