### ISSUE TITLE
Need Method to Track Execution Progress and Completion Status in Rete.js ControlFlowEngine

### ISSUE THREAD

**Issue by funtuan** [retejs/rete#647]
I'm glad to hear about the release of Rete.js 2! I'm looking to implement an exec flow using the ControlFlowEngine. However, I have a question that I couldn't find a solution for by reading the documentation.

My plan is to use the frontend (Vue) to edit the flow of Rete.js through an editor and save this relationship in JSON format. The backend (Node.js) will then periodically execute this flow script using the engine.execute(node.id, data) method.

However, I'm currently missing a method to track the execution progress and determine whether it has completed (perhaps using a Promise for execute?).

I would greatly appreciate any suggestions or guidance on this matter.

**Comment by Ni55aN** [comment]
`ControlFlowEngine` works on a call-and-forget basis.
When you call `forward`, it passes control synchronously to the next nodes and does not keep track of further execution in any way.

This does not require a separate method, you just need to add your code to `execute`, for example

```ts
class AsyncExecution extends ClassicPreset.Node {
  // ....
  async execute(input: "exec", forward: (output: "exec") => void) {
    this.executionStarted()
    await doSomething9)
    forward("exec");
    this.executionCompleted()
  }
}
```

**Comment by funtuan** [comment]
Thank you for the explanation of the ControlFlowEngine and the example code for the AsyncExecution class. I appreciate your help in clarifying how it works on a call-and-forget basis.

While I understand that the call-and-forget approach can be useful in certain scenarios, I believe that using Synchronous Calls might be more convenient for me to manage single-execution situations. With synchronous calls, I can have better control over the execution flow and keep track of the process more easily.

**Comment by Ni55aN** [comment]
In simple situations, that's correct. However, sooner or later, you'll find yourself needing to perform asynchronous tasks. Therefore, it will be essential to separately track the execution of nodes. For example, you may have to find leaves (if there are no loops) and track their completion
