### ISSUE TITLE
Update node controls after node is added is not rendering properly.

### ISSUE THREAD

**Issue by gripzyyy** [retejs/rete#653]
Hello!
I want to update a node controls (add or remove them) after a node is already added to the editor.
The way I do it is I use the context menu to right click on a node in the editor, then using its context calling context.addControl(), but it doesn't render the new Control, it only renders the control if I click on the node and select it. 
I also do update height of the node on .addControl(), this is not rendered also until I use arrange.layout().
Is there anyway to correctly modify controls, inputs and outputs of a node after it has already been added to the editor so they render properly?

**Comment by Ni55aN** [comment]
https://retejs.org/docs/faq/#force-update

**Comment by gripzyyy** [comment]
I am reopening this issue cause I started using:
`area.update('node', node.id)
`
to force update nodes and it seems to work, the only issue is that I may change the height and width of a node, the controls and everything added to the node state get refreshed only the height and width does not change, they only change when I do: 
`    await arrange.layout();
    AreaExtensions.zoomAt(area, editor.getNodes());`

**Comment by Ni55aN** [comment]
what rendering plugin are you using? Do you have `height`/`width` properties in your node class (that extends ClassicPreset.Node)?
