### ISSUE TITLE
Options/Checkboxes in plain javascript

### ISSUE THREAD

**Issue by gabonator** [retejs/rete#654]
Can you please point me where could I find more examples how to integrate more controls/static labels into the Rete.Component? I tried to add checkbox, which should disable one of the input control when enabled but failed and also I am fighting with radio buttons as well. I don't know whether it is more Vue-related question or if I will find some answers here.

Application is single HTML simple signal processing tool in plain javascript with VUE:

<img width="1317" alt="image" src="https://github.com/retejs/rete/assets/1020041/0e2f27b9-05da-40f3-8917-3519b6e37297">

Code:
https://gist.github.com/gabonator/634b441c0dc35fe0f34a85dc4d20b72a

**Comment by Ni55aN** [comment]
> where could I find more examples

The first version doesn't have many examples. Any control is just an html element into which content is inserted.

> which should disable one of the input control

When I click on Filter's checkbox, the worker method prints `x < 5000 true`, where `node.data.break` is `true`. It also works when I uncheck it (prints `x < 5000 false`, where `node.data.break` is `false`)

The only issue I see is `Error` label in Pairs node, but this is related to your implementation

**Comment by gabonator** [comment]
In case anyone was trying to look for some more complex examples:
live: https://rawgit.valky.eu/gabonator/Projects/master/Rete/SimpleRfDecoder/index.html
git: https://github.com/gabonator/Projects/blob/master/Rete/SimpleRfDecoder/index.html

Thank you very much for this project, it is really simple and fun to use! Which version do you recommend for production code?

**Comment by Ni55aN** [comment]
the second version, definitely

**Comment by Ni55aN** [comment]
the second version, definitely
