### ISSUE TITLE
Missing Example for using V2 with node js

### ISSUE THREAD

**Issue by RA-FKuhn** [retejs/rete#657]
Hey, first of all awesome library. I'm currently trying to export created models from the ui to json and load them inside a Node.js application. Then I want to execute them using the engine. Is there any document or example where I can see something like this, maybe I'm missing something as I only found examples for v1? Would really appreciate any kind of help.

**Comment by Ni55aN** [comment]
The core package `rete` doesn't rely on any browser-specific API and can be used on Node.js as well

https://retejs.org/docs/guides/import-export/#import-export
https://codesandbox.io/s/rete-js-v2-import-export-999y8z?file=/src/index.ts

One more thing, if your environment is commonjs, you need this workaround https://github.com/retejs/rete/issues/646
