### ISSUE TITLE
How to use the ELK radial algorithm?

### ISSUE THREAD

**Issue by boop5** [retejs/rete#658]
I'm just following the guide for angular using the autoarrange-plugin. I do want to use another arrange algorithm though. Most of them seem to work just fine (like `elk.mrtree`). But I cant get `elk.radial` working. How can I do that?

I've tried it like this 

```
const arrange = new AutoArrangePlugin<Schemes>();
// ...
area.use(arrange)
// ...
arrange.addPreset(ArrangePresets.classic.setup());
// ...
await arrange.layout({ applier, options: {
    algorithm: 'elk.radial'
}});
```

Here is a simplified stackblitz of what I've tried https://stackblitz.com/edit/stackblitz-starters-3fm3cd?file=src%2Fmain.ts

This is how it looks if I don't specify an algorithm

![image](https://github.com/retejs/rete/assets/4655466/869133c0-1a55-4677-b014-d9d93dcefdfa)

This is the same graph but with `algorithm: 'elk.radial'`

![image](https://github.com/retejs/rete/assets/4655466/d851498e-19ac-4391-b672-61bc0f69b1b0)

This is with `elk.mrtree` algorithm

![image](https://github.com/retejs/rete/assets/4655466/18a6c568-10eb-42f8-a6d4-abca11be3af9)

**Comment by Ni55aN** [comment]
the `layout` method returns a debugging information:

- URL to online ELK editor: https://rtsys.informatik.uni-kiel.de/elklive/json.html
- Resulting ELK JSON: `source` property

Based on this, it shows [the scheme](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KAkARAlgJhBcACCAnA9mgLhANOCANgIYCeaArpgPIAOmUaAdgM4KKhiQCmBA1gHRECAczQoomABYBbNoVJcUXOHk4QeAyVEVEUAY0kkAEkUYwCURsLkBJAHIBhADIBVACIBRAPoOjNp24ASh52uODcfPzKwlyBFPRWcgAKVE4Amk72HmFqQqLiUrJI6pEoRDBQQhDgAL6qEAZQBDBKjGwA2uEcarByMP0ATAAcAKwDIyN6egNcAGYAnCM5agDusFJsAMwDAAyqapJcUMKS2EgAjLv7kMQARjysSJ2cnN0vEJhcAB5nyACC1ReYBq4TAAF1rg0tM1Wh0IaD1DAYo9EO14e8aGJMCjni83j04MV+jBhmMJlMZgsRl5MShMF5LDRKMt3msYBsLiNrgcjidfucuaC1F82HshZASGwAOxioGQGjoGiKehcFH4tTMWBcOQAdQ8AGUACqAoEg03c9XQQnIYmk8aTaZzRY0rFeeJM7DcyBsjmIAVeiCHY6nNj+8UQEVIWVAiCSpCbQVyiAKtBKunaNXiyCamDa4oeP5Gk0vM0l0HotTEMiUWj0JiZmO0zAOeuYMqWbFyABiNgAGh43F4Uvri6W6l0Eb1ikQACyze6bLhL2YwWc7KVDFkQH2SLZXBFBvmh-fvO4PDpCy2fH5yABCxeB5chjRhXDaTwr3CRqrhkKbOMvcMp2QWd5y4Rdl1XGd1yGF06QZRgPRZVZ1l3TkA0PEN0PDSNEGjd440QGUAxTNMVQbJMczzZA9SLcVS04ccgUtYCIFAhclzmKCYLg+l3WZAMd1DRMY0w-kRPeXD8LUQiExIxVlQzNh1WzLU5ALOi5QYx8Xk-eRq2oOgGBYZShWTLEWxYNsiA7FEIB7ftB2HUdwiYsA3itORbnOIgBgANk2KU-POLh5iGeY9HOTYtyE+MTx5YN+Xim4iHuAgAOY8Nr1+CAHAfBi9JfFo31-BFoh-D8-yxDK8SA60IG83yAqCkKwoiqLeIQpDBNQ4SMN5LC-Qk4VRQDQjiPDUjFIq9gswgKjdQNY16KFNzXjqryfP8wLgtC8LIs2Tr+M9cNYqG-rEr6nDRvDWThvlBT0xmlT5rU-NC2WrTVqfBEq3iWtjIotQm0s5hrNs7s+wHIcqBHUEx32DzWPmc49BGBN5lmUK-JGW5blmIgYt6uL8MDAaktJs90ovTKk2yuQ3Hyn73iK2FKrK78cT0-8adqpNkdR9GRkx7HcfxohOsZATTuJ87wzEq6kyksbpWkh7U2moH3gW4paM+01VotDbihRtGMax+YcbxgmjsobqZfZNC5aTBXsKVm6kzu+SNaerWNTe5ANP1ssDd0yE-prIz61MxsLNbdtGE7YoHOh5z4dcxHJ3qqUZyGIhzluGB10uYW9FuKUicdvdSddv1kvkNKavWunvhy7JvrDhFWZK9n3nKrmqrpJv3ON5Ac7zgui6lEuIvLyXEOlpMzrDF3ycVmNldu1XvbIpSkBenWaKWh8dJLI3+ez3P88L4vxlnqVbcwe2l9llfRLXt2N49mMvcmx7yJjpRAOEAg4n20gVcOpB-pRxMvvMyIN442UTnZFOTlYYuUYpnd4rERhSk2EQHYXAC5hQIfMIgUoliQjOtsGuH866U1SueJ4gEW43mTkzTuLNoTFXfKiPS-dSoYmqrzZuMYcF4IIUQ24JCdhkIofPZ+MZl73TJpdT+klv4EW3n-H2AC4FylUrmRamlQ5nxYWI+quD8GEOIXnWR5DqRNjdHbReSjX4qNrm-DRUYVbxhUVNX2gCYyHxAR9MBHdOB6QjoZOssDZqxzpKDcGyDIaORhnDEOOl0SImRLzJG9U-JECGJsPQM49AwEircIgmxLizC3MwCg+gZq4jULaUY9oKROkca6Y6xY9KYF0DEJOqIzLsXApxFca4NwKOZOWDOE5sH1RmFKa+UpZg7HGFwEYq5oqQgaeQJpw8IBtLJA6SkzonG9OZmoAZKAhlHMattFqe12qHScVLbAczMELIJHINZG4-IzlXOjPytw-J6AIfUxpehmlmROR0x0VJH5IWuZAW59yRGQFNkLEWlsxY23eQvT5ul5miMgKxAYUolwkgmEMBYtxikwEoQifZhzMXHMGO08kiKLk9JccSyJkJ0VcGGS0yA49r5TxnmXB+hKUUku+WSzyJs-Kqp2DAW4M4xhDBnDOKlOwoUHJhUc+F3LzndPglczhNzBkiqOVYyRtjSEOJmQK8ErlwBghADUIAA)

I guess this algorithm doesn't support a ports. After removing `_port_output`/`_port_input` in `edges`, it shows this:
![image](https://github.com/retejs/rete/assets/8259641/3f1c2738-578e-42d0-a51f-181dd6834d5b)

If this is what you need, I can find solutions to achieve this using a plugin

**Comment by boop5** [comment]
Yes, this is exactly what I'm looking for!

**Comment by Ni55aN** [comment]
@boop5 фt the moment, I haven't found an elegant (or nearly) solution on how to flexibly include exclude/modify certain fields in a ELK.js scheme

If you need it badly, there is a solution, but I'll recommend to use it carefully (at least remove `^` from "rete-auto-arrange-plugin": "^2.0.0")

```ts
// @ts-ignore
class PortlessAutoArrangePlugin extends AutoArrangePlugin<Schemes> {
  nodeToLayoutChild(...args: any[]) {
    // @ts-ignore
    const data = super.nodeToLayoutChild(...args)

    return {
      ...data,
      ports: undefined
    }
  }
  getPortId(id: string) {
    return id
  }
}

const arrange = new PortlessAutoArrangePlugin();

arrange.addPreset(ArrangePresets.classic.setup());

area.use(arrange);

console.log(await arrange.layout({
  options: {
    algorithm: 'elk.radial'
  }
}))
```

As you can see `@ts-ignore` is used here, as it breaks the interface and inheritance is tricky.
