### ISSUE TITLE
How to combine different Sockets

### ISSUE THREAD

**Issue by gabrielguarisa** [retejs/rete#659]
Hello! I'm using the old version and I wanted to understand how to combine different sockets in version 2.0, since the 'combineWith' method no longer exists. 

I'm trying to do something like in the code below:

```javascript
import Rete from "rete";

const voidSocket = new Rete.Socket("Void");
const valueSocket = new Rete.Socket("Value");

valueSocket.combineWith(voidSocket);
```

**Comment by Ni55aN** [comment]
Indeed, this is not provided by v2. Instead, you can extend a `Socket` class

```ts
export class TextSocket extends ClassicPreset.Socket {
  constructor() {
    super("Text");
  }

  isCompatibleWith(socket: ClassicPreset.Socket) {
    return socket instanceof TextSocket;
  }
}
```

and perform validation when adding a connection

```ts
editor.addPipe((context) => {
  if (context.type === "connectioncreate") {
    const { data } = context;
    const { source, target } = getConnectionSockets(editor, data);

    if (!source.isCompatibleWith(target)) {
      log("Sockets are not compatible", "error");
      return;
    }
  }
  return context;
});
```

Example: https://retejs.org/examples/chatbot

Additionally, you need `canMakeConnection` to prevent the existing connection from being removed when you drop an incompatible connection onto the socket.
