### ISSUE TITLE
CSS/Javascript Selecting Certain nodes/connections?

### ISSUE THREAD

**Issue by joeybab3** [retejs/rete#661]
Is there a way to extend the node/connection class in such a way that I can control the dom node directly?

I want to add a data-id or data-node-name parameter or a special class to only certain nodes/connections.

I am using the react renderer I believe in vanilla js for the rest of it. 

Currently, I just select all nodes or connections and look for the new one, and create an associative array that way but that feels like an ugly workaround.

**Comment by Ni55aN** [comment]
```ts
area.addPipe(context => {
    if (context.type === 'render' && context.data.type === 'node') {
        context.data.element.classList.add('your-class')
    }
    return context
})
```

it works well for this specific case, but for more complex cases you need special node components.

**Comment by joeybab3** [comment]
Yes, that adds a class to all nodes, doesn't it? How would I do that to only certain types of nodes?

**Comment by Ni55aN** [comment]
@joeybab3 `context.data.payload` is a node instance

**Comment by joeybab3** [comment]
Thanks, I was able to get that to work by using 'rendered' instead of 'render', 'render' only returned sockets.

**Comment by Ni55aN** [comment]
Your `area.addPipe` is probably called after adding a node

**Comment by joeybab3** [comment]
After a little work I was able to get it working thanks to those hints, thanks!
