### ISSUE TITLE
Simple Nodes Order breaks click event handlers

### ISSUE THREAD

**Issue by PerryRylance** [retejs/rete#664]
I'm using Rete 2 and the React integration. Can provide MRE if it helps.

I could not get click handlers to fire on my node control's checkboxes, or any other element for that matter.

Commenting out the simple nodes order plugin fixes this, so we are going to have to run without that for a while.

By the way, I'm enormously grateful for this library, version 2 is absolutely smashing, huge props to the developers and community, this is an amazing library!

**Comment by Ni55aN** [comment]
Are your controls' clickable content wrapped with `onPointerDown={(e) => e.stopPropagation()}` or `<Drag.NoDrag>`?

**Comment by PerryRylance** [comment]
No I hadn't, thank you, missed that in the docs!
