### ISSUE TITLE
Define node id

### ISSUE THREAD

**Issue by mianfrigo** [retejs/rete#665]
I was wondering if there is a way to define the id of the node manually when creating the node, something like 

`const a = new ClassicPreset.Node("A", { id: '50c3a313-a8a3-4356-a132-d6d358886cc9' });`

**Comment by Ni55aN** [comment]
```ts
const a = new ClassicPreset.Node("A")

a.id = id
```

or 

```ts
class MyNode extends  ClassicPreset.Node {
  constructor() {
    this.id = genCustomId()
  }
}
```
