### ISSUE TITLE
Adding nodes dynamically - what is going on here?

### ISSUE THREAD

**Issue by michealroberts** [retejs/rete#667]
I have the following code:

```ts
sequences.forEach(async (sequence) => {
  const node = createNode(sequence.id, sequence.name, socket);
  await editor.addNode(node);
});
```

Which adds a sample of nodes from a given data array.

Then, when calling the following:

```
const sequenceNodes = editor.getNodes();
console.log(sequenceNodes) // []
```

I get an empty array.

I'm kind of confused by this behaviour, if I log inside the `forEach` loop, I see that the nodes are being added. Furthermore, the nodes are rendering correctly.

For reference, this is the createNode function:

```ts
function createNode(id: string, label: string, socket: ClassicPreset.Socket) {
  const node = new Node(id);

  node.label = label;

  node.addInput("port", new ClassicPreset.Input(socket));
  node.addOutput("port", new ClassicPreset.Output(socket));

  return node;
}
```

This for me feels like a scoping bug?

Could someone explain why this dynamic adding of nodes doesn't seem to work outside of different scopes?

**Comment by Ni55aN** [comment]
the issue here is the incorrect use of asynchrony:

```ts
const sequenceNodes = editor.getNodes() // is called before any editor.addNode in the forEach
console.log(sequenceNodes)
```

```ts
sequences.forEach(async (sequence) => {
```

to

```ts
await Promise.all(sequences.map(async (sequence) => {
```
