### ISSUE TITLE
Tablet device support

### ISSUE THREAD

**Issue by Zensar-UI-EXP** [retejs/rete#670]
Hi Team,

We are using the retejs version 1.5.1. We have created many nodes, we are trying to access the application on a tablet device. But we are not able as a right click is not supported on tablet devices, could you please help us? 

Many Thanks
Mohamed Asheik P

**Comment by Ni55aN** [comment]
>  right click is not supported on tablet devices

do you need to open context menu?

btw, did you start to use 1.5.1 recently?

**Comment by Zensar-UI-EXP** [comment]
> > right click is not supported on tablet devices
> 
> do you need to open context menu?
> 
> btw, did you start to use 1.5.1 recently?

Hi @Ni55aN, 

We have started using the version 1.5.1 from past 1 year. 

Many Thanks
Mohamed Asheik P

**Comment by Zensar-UI-EXP** [comment]
> > right click is not supported on tablet devices
> 
> do you need to open context menu?
> 
> btw, did you start to use 1.5.1 recently?

Yes, @Ni55aN. We are trying to open context menu. Could you please help us. 

Many Thanks
Mohamed Asheik P

**Comment by Ni55aN** [comment]
https://rete.js.org/#/examples/basic

long tap on the area or any node displays the context menu

**Comment by Ni55aN** [comment]
does it work in this example? https://codepen.io/Iamafro/pen/bLqyGd?editors=0010

**Comment by Zensar-UI-EXP** [comment]
> does it work in this example? https://codepen.io/Iamafro/pen/bLqyGd?editors=0010

Thanks for the quick response @Ni55aN. No, it is not working on the tablet device. Could you please help us.

Many Thanks
Mohamed Asheik P

**Comment by Ni55aN** [comment]
I don't know, seems like something wrong with the tablet/OS/browser. It works on my Android
