### ISSUE TITLE
Add socket by dropping connection on Node

### ISSUE THREAD

**Issue by lasficw** [retejs/rete#673]
Hey, i'm trying to figure out some stuff with the `connectiondrop` event. Currently when this event is called and it doesn't create a new connection (So moving the connection to a place where no node is) i am creating a node with a small dialog popping up.

 Code looks something like this:
 
```typescript
    connection.addPipe((context) => {
      if (context.type === "connectiondrop" ) {
        if (context.data.created) {
          return context;
        }
        this.showCreateDialog(context.data.initial);
      }
      return context;
    });
```

This works fine. But now i want to support a little more. When the connection is dropped on a existing node (But not a socket of that node!) i want to automatically link those two together. So the node where the connection is dropped on should create an input node which is linked to the original socket of the origin node. The problem is though that i can't seem to find a way to get the node id where i dropped the connection.

 Is that even possible with the existing events? Could i do it with a custom plugin? 

I kinda need some advice here, would appreciate it!

**Comment by Ni55aN** [comment]
> find a way to get the node id where i dropped the connection

this can be done by finding the intersection of the node with the mouse pointer

```ts
const { pointer } = area.area // pointer position
const views = area.nodeViews.entries()

for (const [id, view] of views) {
  const node = editor.getNode(id)
  const size = node // if it has predefined sizes
  // or 
  const size = // calculate the size from view.element divided by transform.k
  console.log(id, view.position, view.element)
  
  if (/* pointer intersects the node */) console.log('Found', id)
}
```

**Comment by lasficw** [comment]
Yep that did the trick, thank you!
