### ISSUE TITLE
Custom data to psuedo connection

### ISSUE THREAD

**Issue by joskuijpers-imec** [retejs/rete#674]
Hi, fantastic library!

I made two socket classes, one of which is "DataSocket". I create these with a custom parameter called 'type' (value as String.prototype, Number.prototype, etc). When checking socket compatibility I check this type as well.
When creating a Connection I grab the type from the socket and use it as connection type, which influences the connection color in the rendering component (Angular).

I am unable to do the same for a psuedo-connection as it does not get any data. I want it to have a parameter so I can set the color according to the starting socket (start of the drag).
Is there a way this can be done that I did not see? Is there a way I can influence data of a psuedo connection?

**Comment by Ni55aN** [comment]
> When creating a Connection I grab the type from the socket and use it as connection type

actually only the socket type is the source of truth, but also, are you synchronizing the connection type with the socket type?

> psuedo-connection as it does not get any data

yes, but it has `isPseudo` property

You can refer to this example https://retejs.org/examples/chatbot.

It renders connections based on socket type in realtime, so there is no need to copy data to the connection instance.

**Comment by joskuijpers-imec** [comment]
I have:

```ts
export class DataSocket extends ClassicPreset.Socket {
  readonly type: any;
.....
}

export class Connection<
  Source extends Node,
  Target extends Node
> extends ClassicPreset.Connection<Source, Target> {
  readonly type?: any = null;

  constructor(source: Source, sourceOutput: keyof Source['outputs'], target: Target, targetInput: keyof Target['inputs']) {
    super(source, sourceOutput, target, targetInput);

    // Connection type is used for rendering
    const socketSource = source.outputs[sourceOutput]?.socket;
    if (socketSource instanceof DataSocket) {
      this.type = socketSource.type;
    } else {

    }

    const socketTarget = target.inputs[targetInput]?.socket;
    if (socketTarget instanceof DataSocket) {
      this.type = socketTarget.type;
    }
  }

}
```

And fitting connection component and socket component. They both use the 'type' to determine a custom color class so my sockets have a nice color. (using `this.data.type`)
This means I can have 10s of Types without needing 20s of classes with double code.

```ts
        connection(data) {
          const { source, target } = getConnectionSockets(editor, data.payload);
          if (
            source instanceof ExecutionSocket ||
            target instanceof ExecutionSocket
          ) {
            return ExecutionConnectionComponent;
          }
          return DataConnectionComponent;
        },
        socket(data) {
          if (data.payload instanceof ExecutionSocket) {
            return ExecutionSocketComponent;
          }
          return DataSocketComponent;
        },
```

When the connection component payload has `isPsuedo` then there is no other payload data from the graph (except node ids and keys).

**Comment by Ni55aN** [comment]
> without needing 20s of classes with double code.

you don't have to have classes for each type as long as their interfaces are identical. Why does this assume twice as many classes?

> has isPsuedo then there is no other payload data from the graph

+ source or target ids/keys

**Comment by joskuijpers-imec** [comment]
I don't understand :(

Should I inject the editor into the Component constructor so I can do a lookup with the ids/keys? Because this information is not yet passed and DI has not been used before in the examples I believe.

The chatbot has this example:
```ts
        connection(data) {
          const { source, target } = getConnectionSockets(editor, data.payload);

          if (
            source instanceof ActionSocket ||
            target instanceof ActionSocket
          ) {
            return ActionConnectionComponent;
          }
          return TextConnectionComponent;
        },
```

I have the same, but I would want to specialize the TextConnectionComponent based on extra information in the source and target.

**Comment by Ni55aN** [comment]
> inject the editor into the Component constructor

the only reliable way to bridge your NodeEditor instance and the custom component is the data property (which contains the Node instance).

>  I would want to specialize the TextConnectionComponent

_editor.ts_
```ts
class Connection extends ClassicPreset.Connection {
  myCustomProperty: any
}

const c = new Connection(....)

c.myCustomProperty  = 'your data'
```

_TextConnectionComponent.component.ts_
```ts
this.data.myCustomProperty 
```

It is not recommended to pass the editor instance to the UI component, instead you can specify some minimal data that you need in your component

**Comment by Ni55aN** [comment]
https://github.com/retejs/rete/issues/630#issuecomment-1611289178
https://github.com/Ni55aN/allmatter/blob/main/src/editor/index.ts#L91

**Comment by joskuijpers-imec** [comment]
What you describe with the custom property is what I do for my Connection class.
How can I intercept the creation of the Psuedo-connection though? I never do my own `new Connection` for that one.

For Angular, I only return the class name of the component, so I do not see how I can pass variables to it like I could in Vue:

```ts
connection(data) {
          const { source, target } = getConnectionSockets(editor, data.payload);

          //data.payload is Connection<A,B>

          if (
            source instanceof ExecutionSocket ||
            target instanceof ExecutionSocket
          ) {
            return ExecutionConnectionComponent;
          }
          return DataConnectionComponent;
        },
```

**Comment by joskuijpers-imec** [comment]
I got something to work:

```ts
area.addPipe(context => {
    if (context.type === 'render') {
      // Psuedo connections are created automatically but we need a typed color
      if (context.data.type === 'connection' && (context.data.payload as any).isPseudo) {
        // Try to get payload for psuedo connections
        const payload = context.data.payload as Connection<Node, Node>;
        const source = editor.getNode(payload.source);
        const target = editor.getNode(payload.target);

        payload.type = getDataConnectionType(source, payload.sourceOutput, target, payload.targetInput);
      }
    }

    return context
  })
```
