### ISSUE TITLE
Custom Context menu

### ISSUE THREAD

**Issue by mianfrigo** [retejs/rete#675]
Is there away to create a custom context menu, i not able to find away to do it, there is nothing the doc that show it is possible, currently i need to create something like this:

![Screenshot from 2023-11-07 11-56-35](https://github.com/retejs/rete/assets/16882735/2e7d70ad-80b9-42a9-9d2b-eb6d7e6291e6)

**Comment by Ni55aN** [comment]
In this case, it would be more appropriate to implement a preset that will use your custom component for the context menu

https://retejs.org/docs/guides/context-menu#render-context-menu

```ts
// replace with your preset
// https://github.com/retejs/angular-plugin/blob/main/src/presets/context-menu/index.ts
renderPlugin.addPreset(Presets.contextMenu.setup());
```


```ts
if (context.data.type === 'contextmenu') {
  return {
    key: 'context-menu',
    component: YourComponent, // <---
    props: {
      items: context.data.items,
      delay,
      searchBar: context.data.searchBar,
      onHide: context.data.onHide,
      rendered
    }
  }
```
