### ISSUE TITLE
How to trigger event when change position of any element ( for ex. Air Heater ).

### ISSUE THREAD

**Issue by lomtesaurabh** [retejs/rete#679]
I tried onDrag, onChange, and onClick events but not trigger when changing the position of an element, but triggered when clicking outside of the element.
![ss](https://github.com/retejs/rete/assets/133188590/e1019cf4-24d3-48ce-b272-b70c3ad05d29)

**Comment by Ni55aN** [comment]
```ts
area.addPipe(context => {
  if (context.type === 'nodetranslated') ...
  return context
})
```
