### ISSUE TITLE
select multiple node using box select

### ISSUE THREAD

**Issue by maliknajjar** [retejs/rete#681]
hi everyone .. is there a way to select multiple nodes using mouse's box select?

**Comment by Ni55aN** [comment]
https://retejs.org/examples/lasso-marquee-selection

**Comment by maliknajjar** [comment]
thanks .. is there a way to run the second version of this library in vanilla js?

**Comment by Ni55aN** [comment]
https://www.reddit.com/r/retejs/comments/165a16q/comment/jzokxk8/
