### ISSUE TITLE
Custom component inside control component: 'Failed` to resolve component: custom-icon'

### ISSUE THREAD

**Issue by ArutaGerman** [retejs/rete#689]
I made a custom control. This control component has custom-button component with icon from our UI library inside custom-button:

```
<template>
  <custom-button
    ref="editBtn"
    icon="edit"
    @click="foo"
    class="control-collapse"
  />
</template>

<script setup>
import CustomButton from '@/components/CustomButton.vue';

defineOptions({
  customOptions: {
    name: 'ControlEdit',
  },
});
</script>

```

Control was been rendered and he hasn't the icon: I have the error.

Error:
```
Failed` to resolve component: custom-icon
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
```

How to resolve this problem?

p.s. I had the same with rete v1, but I solved it. And now I don't know what I have to do

upd: I found the project with rete v1 and we used a custom-button with <svg><use> inside but not custom-icon component from UI library

**Comment by Ni55aN** [comment]
`custom-icon` should be registered in Vue (globally or inside `custom-button`)

**Comment by ArutaGerman** [comment]
> `custom-icon` should be registered in Vue (globally or inside `custom-button`)

I have it in main.js:

```
import Custromlibrary;
import App from './App.vue';

const app = createApp(App);
app.use(CustomLibrary)
```

CustomLibrary include custom-icon inside. Or I have to registry custom-icon apart?

**Comment by Ni55aN** [comment]
These are two different Vue.js instances (`const app = createApp(App);` and the one that renders `custom-button`)

**Comment by Ni55aN** [comment]
I hope [this helps](https://github.com/retejs/retejs.org/blob/02ceb3e016ec0b4ac253a92d79004393aa842bcf/content/en/docs/4.guides/2.renderers/2.vue.md)

https://github.com/retejs/vue-plugin/pull/79

Unfortunately, the official documentation for configuring Vue isn't ready yet, but this feature is already available

**Comment by ArutaGerman** [comment]
Thanks, we'll see
