### ISSUE TITLE
How do I implement Redux or any package with a provider?

### ISSUE THREAD

**Issue by areSEkko** [retejs/rete#690]
Hello,

First of all great package. I'd like to know how I could use Redux or other packages that require a provider in my node components? Node components are being created outside of the provider hence I have issues calling my store.

I am getting the following error:
"could not find react-redux contect value; please ensure the component is wrapped in a Provider"

Best regards,
Ares

**Comment by Ni55aN** [comment]
Related https://discord.com/channels/1081223198055604244/1088598977735299142/1162751391824105503
