### ISSUE TITLE
question: implementing NESTED a canvas?

### ISSUE THREAD

**Issue by hchaudhary1** [retejs/rete#695]
I want to implement something like this:
https://nocode-js.com/examples/sequential-workflow-designer-pro/webpack-pro-app/public/folders.html

Where the user can drop on a "FOLDER" icon, and it can open a new sub-canvas.

Is this possible with the current framework?
How much customization would be needed?

**Comment by Ni55aN** [comment]
it looks similar to https://retejs.org/examples/modules

**Comment by hchaudhary1** [comment]
wow, this is very helpful! thanks
