### ISSUE TITLE
Unable to use AutoArrangePlugin with Angular 17 as schemes mismatch

### ISSUE THREAD

**Issue by gundupatil** [retejs/rete#696]
Is it possible to use the auto Arrange plugin for the below mentioned scheme. Auto Arrange only works when nodes have fixed height and width

```
type Schemes = GetSchemes<
  ClassicPreset.Node,
  ClassicPreset.Connection<ClassicPreset.Node, ClassicPreset.Node>
>;
```
Scheme given for AutoArrange plugin
```
class Node extends ClassicPreset.Node {
  width = 180;
  height = 120;
}

class Connection<N extends Node> extends ClassicPreset.Connection<N, N> {}
type Schemes = GetSchemes<Node, Connection<Node>>;
```

Is there a efficient way I can re arrange all the nodes having different schemes tried with zoom functionality `area.area.transform.k`  also area.area.zoom()

dragged values will not be repositioned to initial state
Help is appreciated

**Comment by Ni55aN** [comment]
what TS error do you receive?

The app generated via Rete Kit doesn't throw any error on build

```bash
npx rete-kit app -n ang17 -s angular -v 17 -f "Angular render,Order nodes,Zoom at,Auto arrange,Dataflow engine,Selectable nodes"
```

**Comment by Ni55aN** [comment]
> only works when nodes have fixed height and width?

yes, because Elk.js (the library it's based on) needs width/height to be available before rendering the graph (in most cases).

> after the autoArrange

why can't you specify/calculate width/height based on node type and content? Like this https://github.com/retejs/rete-studio/blob/abd5d890c56a748d501ef7c027671dcea3d37908/core/src/nodes.ts#L219

**Comment by Ni55aN** [comment]
>  height and width directly did not work

this works if you don't use `arrange.layout` (or call `area,resize` directly)

Otherwise, after updating these properties, you need to call resize explicitly
