### ISSUE TITLE
Implement Copy and Paste Functionalities for Nodes in Rete.js

### ISSUE THREAD

**Issue by kaleem-uet** [retejs/rete#699]
I am currently working on a project using Rete.js, a JavaScript framework for visual programming. I've encountered a challenge where I need to implement copy and paste functionalities for nodes within the Rete.js canvas. The goal is to allow users to copy a selected node and paste it elsewhere on the canvas, effectively duplicating the node with all its configurations and connections.

Questions:
Are there any recommended practices or existing solutions within the Rete.js community for implementing such copy-and-paste functionalities?

**Comment by Ni55aN** [comment]
there is an example in context menu plugin https://github.com/retejs/context-menu-plugin/blob/main/src/presets/classic/index.ts#L46C19-L46C26

Basically, it uses `Clone` approach, but for Copy & paste you can implement similar menu (using [a context menu preset](https://retejs.org/docs/guides/context-menu#custom-preset)) with items:
`Copy`: put active node into the state
`Paste`: (for root menu) clone state's node, adds to the editor and translated into `area.area.pointer` position

**Comment by terrordrone4** [comment]
hey, please, I'm still stucked with this problem.
Basically, I saw the rete-context-menu-plugin already support both 'Delete' and 'Clone' option. But for some reason, only the 'Delete' option shown up.
 How can I show the 'clone' option ? Please!
