### ISSUE TITLE
Adding an EmberJS visualisation, where to start?

### ISSUE THREAD

**Issue by BryanCrotaz** [retejs/rete#703]
I want to create EmberJS components that hook into the engine of Rete.

I've read through the docs and everything appears to be based on signals and messaging. How do I hook into that?

For example, as the most basic example, how would a NodeGraph component hook in to receive a list of nodes and their size and location to draw the node rectangles as divs?

I can't find the css files in any of the core code - does each visualisation have to create new css from scratch?

**Comment by Ni55aN** [comment]
At the moment there is no documentation on implementing integration plugin for UI frameworks (although it's planned).

I would suggest following the existing one, e.g. [Vue plugin](https://github.com/retejs/vue-plugin)


btw, you can put your updates here https://github.com/retejs/rete/discussions/635

**Comment by BryanCrotaz** [comment]
At the moment I’ve put a React renderer inside an Ember component but
that’s a lot of bloat.

Ember works with tracked values and internal signals so it should fit well.
I really couldn’t work out how to hook into the engine. Could you write a
one pager about how to hook into the required signals for displaying the
node tree? I can probably work it out from there.


You are receiving this because you authored the thread.Message ID:
***@***.***>
