### ISSUE TITLE
Configure Connections to directly go from right node to left node

### ISSUE THREAD

**Issue by rabalsaSICKAG** [retejs/rete#718]
### Description

Hi there, 

I want to create connections, that go in the opposite direction as the default (from right to left). Basically it should represent a backward connection, e.g., going from a node back to it's previous node. 
I already managed to create custom nodes with special sockets for these backward connections (and adapt their position), however, the styling is still a little bit off, as the connections normally go from the left to the right, so they start off at the right side of an input socket and enter the output socket from their left side.
![image](https://github.com/user-attachments/assets/0439047d-68b4-467f-9a02-2e049dd4e6d7)

Is there a way to configure connections or sockets to adapt the path of a connection to directly go to the left without these "swerves"?

I'm using Angular 17 and therefore the rete-angular-plugin, as well as the connection-path-plugin.

Cheers

(also sorry, if this is the wrong request, my company only allows bug and maintenance requests...)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ni55aN** [comment]
There are couple of points should be considered:
- connections start/end point
  **Solution**:  swap the coordinates using option `socketPositionWatcher` https://retejs.org/docs/guides/connections#configure-connection-start-end
  ```ts
  if (/* is connection backward */) {
      return {
        x: x + 10 * (side === 'output' ? -1 : 1),
        y: y
      }
  }
  ```

- line path
  **Solution**: use custom path transformer based on https://github.com/retejs/connection-path-plugin/blob/c87cbf0/src/transformers.ts#L29C8-L49C2
 ```ts
 const [start, end] = points // swap the points: const [end, start]
 ```

**Comment by rabalsaSICKAG** [comment]
Thanks a lot, that led me into the right direction! 
Swapping the start and end points in the custom transformer method did not work for me, as it also changed the position of the arrow head, but I simply had to invert the startOffset and endOffset so that it would point into the other direction.
```typescript
/* is connection backward */
const startOffset = vertical ? { x: 0, y: -offset } : { y: 0, x: -offset } 
const endOffset = vertical ? { x: 0, y: offset } : { y: 0, x: offset }
```

![image](https://github.com/user-attachments/assets/09276ab4-5bcc-401d-9b5f-81eefe5d8bd0)
