### ISSUE TITLE
Auto Snap & Align Nodes when Dragging

### ISSUE THREAD

**Issue by ALPEEN** [retejs/rete#90]
UX Suggestion:
Auto Snap & Align nodes when dragging would be a great enhancement to the UX.

**Comment by Ni55aN** [comment]
Okay, now I'm looking for the best architectural solution for implementing such features in the form of plugins, so as not to complicate the exist codebase

**Comment by ALPEEN** [comment]
I see, it is good to keep in mind to keep everything as simple as possible, but with the growth of this awesome lib and its features, things will start getting complicated, too naturally.
I think what it is healthy to do is to comment well the code bases: the role of each methods and parameters, the events and its triggers etc.
I suggest too to use some libs that can reduce and organize the code such RxJS, I see that a node have all the properties of an observable so maybe we can take profits from reactive programming features etc.

**Comment by Ni55aN** [comment]
https://github.com/retejs/area-plugin/commit/b5892012152537bc63835ecc69024483c765f277

```js
editor.use(AreaPlugin, {snap: {size: 64. dynamic: true}});
```
