### ISSUE TITLE
Plans to get rid of dependencies and write vanilla JS code

### ISSUE THREAD

**Issue by Ni55aN** [retejs/rete#98]
I will continue the discussions abount changing the architecture of the library taking into account the proposals on Gitter and the plugins issue .

1. The library uses only zoom and select from D3.js, so it makes sense to rewrite these parts to pure JS in order to reduce the load time of the editor (d3.
js is large enough) and increase the performance of code execution (operations on js are performed much faster).

2. The same goes for Alight, which makes development easier and reduces the amount of code, but at the same time requires to keep writing templates and directives for yourself. There have already been proposals on this subject from those, who want to render the nodes using libraries like React.js, Angular or Vue.js, rather of using several different libraries to perform the same task.
The main solution is to render the nodes in the form of a plugin so that everyone can use more convenient for him.

**Comment by ALPEEN** [comment]
Based on my little experience with this lib:
I'm using the lib within an Angular 5 app and i'm fully satisfied in all the ways: performance, developement, integration and UI.
I found it very light and very performent, i'm using it a realtime context, i didn't found any kind of trouble while integrating it with other framework.
Personally, i think we should continue in the same direction, no problem for replacing some backend parts with lighter ones.
Regarding the two points above:
1. As i said, no problem for replacing backend part with lighter ones.
2. I found the actuel implementation and alight are the best choice, light, simple and full customizable. Regarding rendering nodes, i'm using pug and its template to render nodes using input from the server side, and it do the job pefectly.
I think React or Angular are too much for such simple job and especially compared to alight.

**Comment by ALPEEN** [comment]
I'm not at all @trsh :D 
I just gived my feedback after using the lib for sometime, and of course i'd be happier with more sofisticated and lighter lib.
I didn't found the time to go deeply with the lib, but i'm planing as soon as i'll have some time, so your point of view is surely more pertinent.
So don't worry, if it will be a vote, i'd vote like you and i'll join you in the dev later.

**Comment by trsh** [comment]
@Ni55aN so if we get rid of d3, we need a new repo, right? Because this one says "d3-node-editor". I really want to contribute to next version, but then please trust me some specific task.

**Comment by Ni55aN** [comment]
> Im not mistaken that d3js is also for SVG path drawing?

Yes, it is. 
https://github.com/Ni55aN/d3-node-editor/blob/36cba0c1fb93e831fc2ab0df042fcc755a1940a8/src/utils/view.js#L28-L32

**Comment by Ni55aN** [comment]
>  we need a new repo, right? 

Most likely it's better to rename this one. But this is a another issue of "rebranding"

**Comment by Legiew** [comment]
Hey I noticed that you pull in the whole d3 package in the package.json.
Instead you can just use the specific packages you need, so you can achieve a size improvement very easily (like for example d3-selection). Would be an easy way to improve load performance.

**Comment by trsh** [comment]
@Legiew nice point! I think this can be done before next --v.

**Comment by Ni55aN** [comment]
@Legiew @trsh  yeah, but in the end d3-select will not have the best performance and will need to adjust to its style of writing code.

Nevertheless, at this stage, this functionality has been successfully replaced with vanilla JS. Please wait for the release.
I also ask for help https://github.com/Ni55aN/d3-node-editor/issues/107

**Comment by trsh** [comment]
Closed?

**Comment by Ni55aN** [comment]
yes, 'cause v1.0.0 no longer have dependencies

**Comment by trsh** [comment]
(clap)
